"""Legal and regulatory compliance monitoring for AI edtech.

Monitor AI regulatory developments, FERPA guidance, COPPA, EU AI Act
implementation, and surface anything affecting Aelu's architecture or
data practices. Built for an AI governance attorney — precision matters.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone, UTC
from enum import Enum
from typing import Optional

logger = logging.getLogger(__name__)


class RegulatoryFramework(Enum):
    EU_AI_ACT = "eu_ai_act"
    GDPR = "gdpr"
    FERPA = "ferpa"
    COPPA = "coppa"
    CPRA = "cpra"
    FTC_AI = "ftc_ai"
    STATE_AI_LAWS = "state_ai_laws"
    NIST_AI_RMF = "nist_ai_rmf"
    UNESCO_AI_ETHICS = "unesco_ai_ethics"
    OECD_AI_PRINCIPLES = "oecd_ai_principles"
    UK_AI_REGULATION = "uk_ai_regulation"


@dataclass
class ComplianceSurface:
    area: str
    description: str
    frameworks: list[RegulatoryFramework]
    risk_level: str  # low, medium, high
    current_controls: list[str]
    data_types: list[str]


@dataclass
class FeedSource:
    name: str
    url: str
    feed_type: str  # rss, api, scrape
    framework: RegulatoryFramework
    check_frequency_hours: int = 24


@dataclass
class ActionItem:
    title: str
    description: str
    framework: RegulatoryFramework
    urgency: str  # low, medium, high, critical
    deadline: str | None = None
    assigned_to: str = "owner"


@dataclass
class SurfaceAssessment:
    surface: ComplianceSurface
    status: str  # compliant, gap, unknown
    gaps: list[str] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)


@dataclass
class ComplianceReport:
    overall_status: str  # compliant, attention_needed, action_required
    surfaces: list[SurfaceAssessment] = field(default_factory=list)
    action_items: list[ActionItem] = field(default_factory=list)
    last_checked: str = ""

    def __post_init__(self):
        if not self.last_checked:
            self.last_checked = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S")


@dataclass
class ImpactAssessment:
    affects_aelu: bool
    impact_level: str  # none, low, medium, high
    affected_surfaces: list[str]
    required_changes: list[str]
    timeline: str
    confidence: float  # 0-1


# ── Aelu's compliance surfaces ────────────────────────────

_SURFACES = [
    ComplianceSurface(
        "learner_data_collection",
        "Collection of learning progress, error patterns, session history, and performance metrics",
        [RegulatoryFramework.GDPR, RegulatoryFramework.CPRA, RegulatoryFramework.FERPA],
        "medium",
        ["Privacy policy", "Data minimization", "User consent at registration",
         "Data export (GDPR Art. 20)", "Deletion endpoint (GDPR Art. 17)"],
        ["learning_progress", "error_logs", "session_history", "proficiency_estimates"],
    ),
    ComplianceSurface(
        "audio_recordings",
        "Recording and analysis of user speech for tone grading (Parselmouth F0 extraction)",
        [RegulatoryFramework.GDPR, RegulatoryFramework.CPRA, RegulatoryFramework.STATE_AI_LAWS],
        "high",
        ["Audio processed locally where possible", "Retention policy (delete after grading)",
         "Explicit consent for recording", "No biometric template storage"],
        ["audio_samples", "tone_features", "f0_contours"],
    ),
    ComplianceSurface(
        "ai_generated_content",
        "Reading passages, scenarios, and drill content generated by AI at build time",
        [RegulatoryFramework.EU_AI_ACT],
        "low",
        ["Content reviewed before publication", "No real-time AI generation",
         "Human approval queue for all generated content"],
        ["reading_passages", "dialogue_scenarios", "grammar_examples"],
    ),
    ComplianceSurface(
        "learning_analytics",
        "Profiling learner behavior to adapt scheduling, predict mastery, estimate HSK level",
        [RegulatoryFramework.EU_AI_ACT, RegulatoryFramework.GDPR],
        "medium",
        ["Deterministic algorithms (no runtime LLM)", "Transparent scheduling logic",
         "User can view all their data", "No opaque neural network decisions"],
        ["mastery_predictions", "scheduling_decisions", "proficiency_estimates"],
    ),
    ComplianceSurface(
        "institutional_data",
        "Classroom enrollment, teacher access to student progress, grade passback (LTI)",
        [RegulatoryFramework.FERPA],
        "high",
        ["Role-based access control", "Teacher sees only their students",
         "No sharing of student data between institutions", "LTI 1.3 compliance"],
        ["enrollment_records", "grade_data", "student_progress"],
    ),
    ComplianceSurface(
        "payment_processing",
        "Stripe handles payment; Aelu stores subscription tier and customer ID only",
        [RegulatoryFramework.GDPR, RegulatoryFramework.CPRA],
        "low",
        ["PCI DSS compliance delegated to Stripe", "No card numbers stored",
         "Only Stripe customer_id in database"],
        ["stripe_customer_id", "subscription_tier", "payment_events"],
    ),
    ComplianceSurface(
        "marketing_emails",
        "Weekly progress emails, onboarding sequences, feature announcements",
        [RegulatoryFramework.GDPR, RegulatoryFramework.CPRA],
        "low",
        ["Consent at registration", "Unsubscribe in every email",
         "CAN-SPAM compliant headers", "No third-party email sharing"],
        ["email_addresses", "email_preferences"],
    ),
    ComplianceSurface(
        "childrens_data",
        "Potential for users under 13 (COPPA) or under 16 (GDPR)",
        [RegulatoryFramework.COPPA, RegulatoryFramework.GDPR],
        "medium",
        ["Terms require age 13+", "No age verification mechanism currently",
         "No targeted advertising", "No social features for minors"],
        ["age_declaration", "account_data"],
    ),
    ComplianceSurface(
        "cross_border_transfer",
        "Data may be processed across jurisdictions (user location varies)",
        [RegulatoryFramework.GDPR],
        "medium",
        ["Server in US (Fly.io)", "Privacy Shield successor framework pending",
         "Standard contractual clauses in privacy policy"],
        ["all_personal_data"],
    ),
    ComplianceSurface(
        "automated_decisions",
        "Scheduling what to study, grading answers, estimating proficiency levels",
        [RegulatoryFramework.GDPR, RegulatoryFramework.EU_AI_ACT],
        "low",
        ["All decisions are deterministic (FSRS, rule-based scheduling)",
         "User can appeal grades (grade_appeal table)", "No significant legal effect",
         "Transparency: user can see why items are scheduled"],
        ["scheduling_decisions", "grade_results", "proficiency_estimates"],
    ),
]


# ── AI-specific risks (NIST AI RMF) ─────────────────────────

AI_RISK_REGISTER = [
    {
        "id": "AI-001",
        "name": "Prompt regression",
        "description": "LLM output quality degrades silently after prompt or model updates",
        "category": "ai_quality",
        "risk_level": "high",
        "likelihood": "medium",
        "impact": "high",
        "mitigations": [
            "Prompt registry with versioning (genai_layer.py PROMPT_REGISTRY)",
            "Regression detection via detect_prompt_regressions()",
            "Human review gate on AI-generated content",
        ],
        "framework": "nist_ai_rmf",
    },
    {
        "id": "AI-002",
        "name": "Data poisoning via user-generated content",
        "description": "Adversarial or low-quality user submissions corrupt training data or content pool",
        "category": "ai_security",
        "risk_level": "medium",
        "likelihood": "low",
        "impact": "high",
        "mitigations": [
            "Content review_status gate (approved/pending_review/rejected)",
            "Input length validation on all text endpoints",
            "No direct user content injection into AI prompts",
        ],
        "framework": "nist_ai_rmf",
    },
    {
        "id": "AI-003",
        "name": "Adversarial audio in tone grading",
        "description": "Crafted audio inputs exploit F0 extraction or tone classification pipeline",
        "category": "ai_security",
        "risk_level": "medium",
        "likelihood": "low",
        "impact": "medium",
        "mitigations": [
            "validate_audio_sanity() pre-grading check (silence, clipping, duration)",
            "Deterministic grading (no LLM in grading path)",
            "Audio retention policy (delete after grading)",
        ],
        "framework": "nist_ai_rmf",
    },
    {
        "id": "AI-004",
        "name": "AI content not labeled for learners",
        "description": "Learners cannot distinguish AI-generated content from human-authored content",
        "category": "ai_transparency",
        "risk_level": "low",
        "likelihood": "medium",
        "impact": "low",
        "mitigations": [
            "is_ai_generated column on content_item (provenance tracking)",
            "human_reviewed_at gate before serving AI content",
            "EU AI Act transparency requirement awareness",
        ],
        "framework": "nist_ai_rmf",
    },
]


# ── Regulatory feed sources ───────────────────────────────

_FEED_SOURCES = [
    FeedSource("EUR-Lex AI Act", "https://eur-lex.europa.eu", "rss", RegulatoryFramework.EU_AI_ACT, 168),
    FeedSource("AI Act Implementation Tracker", "https://artificialintelligenceact.eu", "scrape", RegulatoryFramework.EU_AI_ACT, 168),
    FeedSource("EU AI Office", "https://digital-strategy.ec.europa.eu/en/policies/ai-office", "scrape", RegulatoryFramework.EU_AI_ACT, 168),
    FeedSource("EDPB Guidelines", "https://edpb.europa.eu/our-work-tools/general-guidance_en", "rss", RegulatoryFramework.GDPR, 168),
    FeedSource("DPA Decisions Tracker", "https://gdprhub.eu", "rss", RegulatoryFramework.GDPR, 72),
    FeedSource("ED.gov FERPA Guidance", "https://studentprivacy.ed.gov", "scrape", RegulatoryFramework.FERPA, 336),
    FeedSource("PTAC Resources", "https://studentprivacy.ed.gov/ptac", "scrape", RegulatoryFramework.FERPA, 336),
    FeedSource("FTC AI Enforcement", "https://ftc.gov/policy/advocacy-research/tech-at-ftc/artificial-intelligence", "scrape", RegulatoryFramework.FTC_AI, 168),
    FeedSource("FTC Consent Decrees", "https://ftc.gov/legal-library/browse/cases-proceedings", "scrape", RegulatoryFramework.FTC_AI, 168),
    FeedSource("CPPA Rulemaking", "https://cppa.ca.gov/regulations", "scrape", RegulatoryFramework.CPRA, 336),
    FeedSource("NCSL AI Legislation", "https://ncsl.org/technology-and-communication/artificial-intelligence-2024-legislation", "scrape", RegulatoryFramework.STATE_AI_LAWS, 168),
    FeedSource("Colorado AI Act Updates", "https://leg.colorado.gov", "scrape", RegulatoryFramework.STATE_AI_LAWS, 336),
    FeedSource("NIST AI RMF", "https://airc.nist.gov/AI_RMF_Playbook", "scrape", RegulatoryFramework.NIST_AI_RMF, 336),
    FeedSource("IAPP Daily Dashboard", "https://iapp.org/news/daily-dashboard", "rss", RegulatoryFramework.GDPR, 24),
    FeedSource("MLex AI Coverage", "https://mlexwatch.com", "rss", RegulatoryFramework.EU_AI_ACT, 72),
    FeedSource("The AI Act Newsletter", "https://theaiact.com", "rss", RegulatoryFramework.EU_AI_ACT, 168),
    FeedSource("UNESCO AI Ethics", "https://unesco.org/en/artificial-intelligence/recommendation-ethics", "scrape", RegulatoryFramework.UNESCO_AI_ETHICS, 720),
    FeedSource("OECD AI Policy Observatory", "https://oecd.ai", "scrape", RegulatoryFramework.OECD_AI_PRINCIPLES, 336),
    FeedSource("UK DSIT AI Regulation", "https://gov.uk/government/publications/ai-regulation-a-pro-innovation-approach", "scrape", RegulatoryFramework.UK_AI_REGULATION, 336),
    FeedSource("ICO AI Guidance", "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/artificial-intelligence", "scrape", RegulatoryFramework.UK_AI_REGULATION, 336),
]


# ── Regulatory calendar ──────────────────────────────────

_REGULATORY_CALENDAR = [
    {"framework": "EU AI Act", "event": "Prohibitions effective", "date": "2025-02-02", "status": "passed"},
    {"framework": "EU AI Act", "event": "GPAI rules effective", "date": "2025-08-02", "status": "upcoming"},
    {"framework": "EU AI Act", "event": "High-risk obligations (Annex III)", "date": "2026-08-02", "status": "upcoming"},
    {"framework": "EU AI Act", "event": "Full application (all provisions)", "date": "2027-08-02", "status": "upcoming"},
    {"framework": "Colorado AI Act", "event": "Effective date", "date": "2026-02-01", "status": "upcoming"},
    {"framework": "CPRA", "event": "Automated decision-making rules (pending)", "date": "2026-06-01", "status": "pending"},
    {"framework": "NIST AI RMF", "event": "Version 2.0 expected", "date": "2026-12-01", "status": "planned"},
    {"framework": "EU AI Act", "event": "Code of Practice for GPAI due", "date": "2025-05-02", "status": "upcoming"},
]


class AeluComplianceSurface:
    """Map Aelu's regulatory surfaces."""

    def get_surfaces(self) -> list[ComplianceSurface]:
        return list(_SURFACES)

    def get_by_framework(self, framework: RegulatoryFramework) -> list[ComplianceSurface]:
        return [s for s in _SURFACES if framework in s.frameworks]

    def get_high_risk(self) -> list[ComplianceSurface]:
        return [s for s in _SURFACES if s.risk_level == "high"]


class RegulatoryFeedSource:
    """Regulatory feed source registry."""

    def get_sources(self) -> list[FeedSource]:
        return list(_FEED_SOURCES)

    def get_by_framework(self, framework: RegulatoryFramework) -> list[FeedSource]:
        return [s for s in _FEED_SOURCES if s.framework == framework]


class ComplianceChecker:
    """Check Aelu's current compliance posture."""

    def check_aelu_compliance(self) -> ComplianceReport:
        assessments = []
        action_items = []

        for surface in _SURFACES:
            assessment = self._assess_surface(surface)
            assessments.append(assessment)

            if assessment.status == "gap":
                for gap in assessment.gaps:
                    action_items.append(ActionItem(
                        title=f"Address gap: {gap}",
                        description=f"Surface: {surface.area}",
                        framework=surface.frameworks[0] if surface.frameworks else RegulatoryFramework.GDPR,
                        urgency="medium" if surface.risk_level != "high" else "high",
                    ))

        overall = "compliant"
        if any(a.status == "gap" for a in assessments):
            overall = "attention_needed"
        if any(a.status == "gap" and a.surface.risk_level == "high" for a in assessments):
            overall = "action_required"

        return ComplianceReport(
            overall_status=overall,
            surfaces=assessments,
            action_items=action_items,
        )

    def _assess_surface(self, surface: ComplianceSurface) -> SurfaceAssessment:
        gaps = []
        recommendations = []

        # Check for known gaps
        if surface.area == "childrens_data":
            if "No age verification mechanism currently" in surface.current_controls:
                gaps.append("No age verification — COPPA risk if users under 13")
                recommendations.append("Add age gate at registration or terms-only acknowledgment")

        if surface.area == "audio_recordings":
            if surface.risk_level == "high":
                recommendations.append("Review biometric data classification under IL BIPA and TX CUBI")
                recommendations.append("Ensure audio deletion is provably complete (no backup retention)")

        if surface.area == "cross_border_transfer":
            gaps.append("EU-US data transfer mechanism should be documented")
            recommendations.append("Implement Data Privacy Framework certification or update SCCs")

        if surface.area == "institutional_data":
            recommendations.append("Maintain FERPA compliance documentation for institutional sales")

        if surface.area == "ai_generated_content":
            # NIST AI RMF: check AI-specific risks
            ai_risks = [r for r in AI_RISK_REGISTER if r["risk_level"] in ("high", "medium")]
            if ai_risks:
                recommendations.append(
                    f"Monitor {len(ai_risks)} AI-specific risks in NIST AI RMF register"
                )

        status = "gap" if gaps else "compliant"
        return SurfaceAssessment(
            surface=surface, status=status,
            gaps=gaps, recommendations=recommendations,
        )


class ImpactAssessor:
    """Assess impact of regulatory changes on Aelu."""

    _KEYWORD_SURFACE_MAP = {
        "biometric": ["audio_recordings"],
        "audio": ["audio_recordings"],
        "voice": ["audio_recordings"],
        "profiling": ["learning_analytics", "automated_decisions"],
        "automated decision": ["automated_decisions", "learning_analytics"],
        "educational": ["institutional_data", "learner_data_collection"],
        "student": ["institutional_data"],
        "children": ["childrens_data"],
        "minor": ["childrens_data"],
        "transfer": ["cross_border_transfer"],
        "cross-border": ["cross_border_transfer"],
        "payment": ["payment_processing"],
        "marketing": ["marketing_emails"],
        "consent": ["learner_data_collection", "marketing_emails"],
        "deletion": ["learner_data_collection"],
        "transparency": ["ai_generated_content", "automated_decisions"],
        "high-risk ai": ["learning_analytics"],
        "generated content": ["ai_generated_content"],
    }

    def assess_regulatory_change(
        self, change_description: str, framework: RegulatoryFramework
    ) -> ImpactAssessment:
        desc_lower = change_description.lower()
        affected = set()

        for keyword, surfaces in self._KEYWORD_SURFACE_MAP.items():
            if keyword in desc_lower:
                affected.update(surfaces)

        # Framework-specific surface matching
        framework_surfaces = [s.area for s in _SURFACES if framework in s.frameworks]
        if not affected:
            # Conservative: if we can't determine specifics, flag all surfaces for this framework
            affected = set(framework_surfaces)

        affects = len(affected) > 0
        impact = "none"
        if affected:
            high_risk = [s for s in _SURFACES if s.area in affected and s.risk_level == "high"]
            if high_risk:
                impact = "high"
            elif any(s.risk_level == "medium" for s in _SURFACES if s.area in affected):
                impact = "medium"
            else:
                impact = "low"

        required_changes = []
        if "high-risk" in desc_lower and "learning_analytics" in affected:
            required_changes.append("Review if Aelu falls under Annex III educational AI classification")
        if "biometric" in desc_lower and "audio_recordings" in affected:
            required_changes.append("Review audio processing against new biometric data definition")
        if "deletion" in desc_lower or "erasure" in desc_lower:
            required_changes.append("Verify deletion endpoints meet new requirements")

        confidence = 0.8 if affected else 0.4
        if not required_changes and affects:
            required_changes.append("Flag for human review — impact unclear")
            confidence = 0.5

        return ImpactAssessment(
            affects_aelu=affects,
            impact_level=impact,
            affected_surfaces=sorted(affected),
            required_changes=required_changes,
            timeline="Review within 30 days" if impact in ("medium", "high") else "Monitor",
            confidence=confidence,
        )


class ComplianceMonitor:
    """Main interface for compliance monitoring."""

    def __init__(self):
        self.surfaces = AeluComplianceSurface()
        self.feeds = RegulatoryFeedSource()
        self.checker = ComplianceChecker()
        self.assessor = ImpactAssessor()

    def audit(self) -> ComplianceReport:
        return self.checker.check_aelu_compliance()

    def assess_change(self, description: str, framework: str) -> ImpactAssessment:
        try:
            fw = RegulatoryFramework(framework)
        except ValueError:
            # Try matching by name
            fw_map = {f.name.lower(): f for f in RegulatoryFramework}
            fw = fw_map.get(framework.lower(), RegulatoryFramework.GDPR)
        return self.assessor.assess_regulatory_change(description, fw)

    def get_action_items(self, urgency: str = "all") -> list[ActionItem]:
        report = self.audit()
        if urgency == "all":
            return report.action_items
        return [a for a in report.action_items if a.urgency == urgency]

    def get_regulatory_calendar(self) -> list[dict]:
        return list(_REGULATORY_CALENDAR)

    def format_report(self, report: ComplianceReport) -> str:
        lines = [f"Compliance Report — {report.last_checked}", ""]
        lines.append(f"Overall: {report.overall_status.upper()}")
        lines.append("")

        for assessment in report.surfaces:
            icon = "✓" if assessment.status == "compliant" else "⚠"
            lines.append(f"  {icon} {assessment.surface.area} [{assessment.surface.risk_level}]")
            for gap in assessment.gaps:
                lines.append(f"      Gap: {gap}")
            for rec in assessment.recommendations:
                lines.append(f"      Rec: {rec}")

        if report.action_items:
            lines.append("")
            lines.append("Action Items:")
            for item in report.action_items:
                lines.append(f"  [{item.urgency.upper()}] {item.title}")

        return "\n".join(lines)

    def get_ai_risks(self) -> list[dict]:
        """Return the NIST AI RMF risk register entries."""
        return list(AI_RISK_REGISTER)

    def weekly_brief(self) -> str:
        report = self.audit()
        calendar = [c for c in _REGULATORY_CALENDAR if c["status"] == "upcoming"]

        lines = ["Regulatory Brief", ""]
        lines.append(f"Compliance posture: {report.overall_status}")

        if report.action_items:
            lines.append(f"Action items: {len(report.action_items)}")
            for item in report.action_items[:3]:
                lines.append(f"  - [{item.urgency}] {item.title}")

        if calendar:
            lines.append("")
            lines.append("Upcoming deadlines:")
            for c in sorted(calendar, key=lambda x: x["date"])[:3]:
                lines.append(f"  {c['date']}: {c['framework']} — {c['event']}")

        return "\n".join(lines)
