#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Apply manually curated pinyin to passages with empty text_pinyin fields."""

import json

pinyin_map = {
    "j7_observe_011": "Zài Shànghǎi, páiduì bù zhǐ shì páiduì. Tā shì yì chǎng méiyǒu cáipàn de xīnlǐ bóyì. Wǎnghóng cāntīng ménkǒu de duìwu lǐ zhìshǎo yǒu sān zhǒng rén: zhēn de xiǎng chī de, pāi wán zhào jiù zǒu de, yǐjí gēnběn bù zhīdào zhè jiā diàn mài shénme dàn jiùshì bù xiǎng dāng nàge xiān líkāi de rén. Dì sān zhǒng rén shì zuì wēixiǎn de — tāmen huì yìzhí pái dào zuìhòu, diǎn yí fèn zuì guì de cài, pāi yì zhāng zhàopiàn fā péngyouquān, ránhòu gěi chàpíng. Gèng jīngcǎi de shì yàodiàn ménkǒu lǐng zèngpǐn jīdàn de duìwu. Tuìxiū āyí men zìfā zǔjiàn le yí tào qíngbào xìtǒng: qiánmiàn de rén fùzé huíbào \"hái shèng jǐ hé\", zhōngjiān de rén fùzé chuándì xìnxī, hòumiàn de rén fùzé juécè. Rúguǒ jīdàn kuài méi le, duìwu mòduān huì lìkè chūxiàn sāodòng — yǒurén jiǎzhuāng tuǐjiǎo bù hǎo yāoqiú chāduì, yǒurén tūrán \"rèn chū\" qiánmiàn de shúrén, yǒurén gāncuì cóng pángbiān de xiǎo xiàng rào dào duìwu qiánfāng jiǎzhuāng gāng dào. Wǒ qīnyǎn kàn dào guò liǎng ge āyí wèile yì hé jīdàn chàdiǎn dòngshǒu, zuìhòu bèi dì sān ge āyí quàn zhù le. Quàn zhù de fāngshì shì: \"Bié chǎo le, wǒ gāng kàn dào jiē duìmiàn nà jiā yě zài fā, érqiě shì shuānghuáng dàn.\" Liǎng ge rén shùnjiān héjiě, yìqǐ xiǎo pǎo guò mǎlù. Wǒ rènshi de yí wèi shèhuìxué yánjiūzhě shuō guò: \"Gàosu wǒ yí ge chéngshì zěnme páiduì, wǒ jiù néng gàosu nǐ zhège chéngshì de shèhuì xìnrèn chéngdù.\" Àn zhège biāozhǔn, Shànghǎi de shèhuì xìnrèn chéngdù dàyuē děngyú: \"Wǒ xìnrèn nǐ bú huì chāduì, chúfēi jīdàn kuài méi le.\"",

    "j7_observe_048": "Wǒ yǐqián bú huì děngdài. Páiduì jiāolǜ, děng rén fánzào, děng wàimài de shíhou měi sānshí miǎo shuāxīn yí cì jìndùtiáo. Hòulái wǒ zhùyì dào wǒ de línjū Lǎo Zhào. Lǎo Zhào shì tuìxiū mùjiang, wéiyī de àihào shì diàoyú. Yǒu yí cì wǒ kàn tā diào le yí ge xiàwǔ, yì tiáo yú dōu méi diào dào. Wǒ wèn tā jí bù jí. Tā tóu yě bù huí de shuō: \"Jí shénme? Yú yòu méiyǒu shàngbān yào chídào.\" Tā gēn wǒ jiěshì, zuò mùjiang de shíhou shuā le qī yào děng tā gān, jiāo le sǔntou yào děng tā gù, jí shì méiyǒu yòng de. Wǒ shuō wǒ lǐjiě dàoli, dàn zuò bú dào. Tā chénmò le yíhuìr shuō: \"Nǐ děng wàimài de shíhou zuò shénme?\" Wǒ shuō shuā shǒujī. Tā shuō: \"Nà nǐ bú shì zài děngdài, nǐ shì zài táobì děngdài. Zhēnzhèng de děngdài shì shénme dōu bù gàn, jiù zuò zhe.\" Wǒ shì le yí cì. Děng hóngdēng de shíhou shénme dōu bù gàn, jiù zhàn zhe. Wǒ jiānchí le dàyuē shíyī miǎo jiù ná chū le shǒujī. Dì èr cì jiānchí le shíbā miǎo. Dì sān cì wǒ rěn dào le lǜdēng liàng, gǎnjué xiàng wánchéng le yí cì mǎlāsōng. Hòulái wǒ gàosu Lǎo Zhào wǒ de jìnbù, tā zhèngzài shōushi yúgān — háishi yì tiáo méi diào dào. Tā shuō: \"Búcuò, wǒ liàn le sānshí nián cái zuò dào de shì nǐ yì zhōu jiù huì le.\" Wǒ shuō: \"Nà nín diàoyú sānshí nián diào dào guò jǐ tiáo yú?\" Tā rènzhēn xiǎng le xiǎng: \"Jiā qǐlái dehuà...... dàgài gòu chī yí dùn huǒguō.\" Tā bǎ kōng tǒng wǎng jiān shàng yì káng, zǒu le. Wǒ zhàn zài hé biān kàn zhe tā de bèiyǐng, tūrán juéde děngdài běnshēn yǐjīng shì tā de quánbù shōuhuò le. Yú zhǐ shì jièkǒu.",

    "j7_observe_049": "Wǒ mā měi cì qù càishìchǎng zhīqián dōu xiě mǎi cài dān, bú yòng shǒujī bèiwànglù, yòng yuánzhūbǐ xiě zài jiù rìlì zhǐ bèimiàn. Zì hěn xiǎo, páiliè jǐncòu, ǒu'ěr jiā kuòhào: \"rúguǒ xīnxiān dehuà\" \"kàn jiàqian\" \"gēn shàng cì nàge tān bǐ yíxià\". Yǒu yí cì wǒ zǐxì yánjiū le yì zhāng tā de mǎi cài dān, fāxiàn tā de xìnxī mìdù chāoguò dàduōshù gōngsī de xiàngmù jìhuàshū. \"Páigǔ (zhōumò dùn tāng, mǎi Lǐ túhù jiā de, búyào Zhāng jiā de, shàng cì tài féi)\" — zhè yì háng bāohán le shíjiān guīhuà, gōngyìngshāng pínggū hé zhìliàng kòngzhì. \"Jīdàn x2 dǎ (gěi lóuxià Zhāng nǎinai dài yì dǎ, tā shàng zhōu bāng wǒ shōu le kuàidì)\" — zhè shì rénqíng wǎnglái de zhàiwù qīngsuàn. \"Dòufu (nèn de, Lǎo Wáng jiā bān zǒu yǐhòu mǎi càichǎng dōngtou nà jiā de, bùrú Lǎo Wáng dàn còuhe)\" — zhè shì gōngyìngliàn zhōngduàn hòu de tìdài fāng'àn fēnxī. Zuì ràng wǒ kùnhuò de shì qīngdān mòwěi yǒngyuǎn huì chūxiàn de yì háng: \"Xiǎo Míng ài chī de nà zhǒng gāodiǎn\". Wǒ sānshíwǔ suì le. Wǒ yǐjīng shí'èr nián méiyǒu zhù zài jiālǐ le. Wǒ shàng cì chī nà zhǒng gāodiǎn kěnéng shì gāozhōng de shì. Dàn tā de qīngdān shàng, zhè yì háng cóng wèi xiāoshī guò. Yǒu yí cì wǒ rěn bú zhù gēn tā shuō: \"Mā, wǒ xiànzài bù zěnme chī gāodiǎn le.\" Tā kàn le wǒ yì yǎn, jìxù xiě dānzi: \"Nà wǒ mǎi huílái fàng zhe, wànyī nǐ huílái ne.\" Wǒ hòulái bǎ jǐ zhāng tā yòng guò de mǎi cài dān jiā jìn le yì běn shū lǐ. Qīngdān shàng yǒuxiē cài tā yǐjīng mǎi bú dào le, yǒuxiē tānwèi yǐjīng bú zài le, yǒuxiē línjū yǐjīng bān zǒu le. Dàn \"Xiǎo Míng ài chī de nà zhǒng gāodiǎn\" hái zài. Tā shì zhěng zhāng qīngdān shàng wéiyī cóng bù dǎzhé, cóng bù bǐjià, cóng bù biāozhù tìdài fāng'àn de yí xiàng.",

    "j7_observe_054": "Wǒ gēn qīzi dié yīfu de fēnqí yǐjīng chíxù le jiǔ nián. Tā de fāngfǎ: měi jiàn T xù xiān duìzhé xiùzi, zài duìzhé shēntǐ, zuìhòu zài zhé yí cì, dié chūlái dàxiǎo yì mú yíyàng, zhěngzhěngqíqí mǎ zài yīguì lǐ, xiàng MUJI de zhǎnshìguì. Wǒ de fāngfǎ: fēn chéng \"dàzhì duìzhé\" hé \"róu chéng yì tuán sāi jìnqù\" liǎng dǎng, qǔjué yú dàngtiān de xīnqíng. Wǒmen wèi cǐ chǎo guò wúshù cì. Tā rènwéi wǒ de diéfǎ shì duì bùliào de fànzuì. Wǒ rènwéi yīfu chuān zài shēn shàng méi rén néng kàn chū tā shì bèi jīngxīn dié guò háishi bèi rēng jìn guò xǐyījī ránhòu zhíjiē chuān de. Yǒu yì tiān wǒ zuò le yí ge shíyàn: wǒ jīngxīn dié le sān jiàn T xù, tóngshí róu le sān jiàn T xù, ránhòu fēnbié chuān chūmén. Wǒ wèn le liù ge tóngshì néng bu néng kàn chū qūbié. Liù ge rén dōu shuō kàn bù chūlái. Wǒ pāizhào gěi qīzi kàn, yǐwéi yíng le. Tā kàn le yì yǎn shuō: \"Wǒ dié yīfu bú shì gěi biéren kàn de.\" Ránhòu tā dié wán yì luò yīfu, zhàn zài yīguì qián kàn le hǎo jǐ miǎo. Nàge yǎnshén bú shì zài jiǎnchá zhěng bu zhěngqí. Nà shì yí ge zài shěnshì zìjǐ zuòpǐn de rén de yǎnshén. Nà yí kè wǒ hūrán míngbai le: tā de shēnghuó zài hěn duō fāngmiàn shì shīkòng de — gōngzuò yālì, háizi shēngbìng, gēn tā mā de guānxì — dàn zhège yīguì shì tā wéiyī néng wánquán zhǎngkòng de lǐngdì. Wǒ méiyǒu zài shuō shénme. Cóng nà yǐhòu wǒ ǒu'ěr yě huì rènzhēn dié yí cì. Dié de dāngrán háishi hěn chǒu. Dàn tā měi cì kàn le dōu xiào. Nà zhǒng xiào bú shì yīnwèi wǒ dié de hǎo, shì yīnwèi wǒ zhōngyú bú zài shìtú zhèngmíng tā shì cuò de le.",

    "j7_city_058": "Yèshì tānwèi de páiliè bú shì suíjī de, ér shì jǐ shí nián dìpán zhēngduó de jūnhéng tài. Shāokǎo tān zhànjù shàngfēngkǒu, yīnwèi Lǎo Chén sānshí nián qián jiù zhàn zài nàr, shéi dōu bié xiǎng dòng tā. Shuǐguǒ tān shǒu rùkǒu, lìrùnlǜ gāo kàng de zhù zuì guì de tānwèi fèi. Miàntiáo tān cáng zài zuì shēn chù — zǒu dào nàlǐ de rén tōngcháng yǐjīng è le, chéngjiāolǜ zuì gāo. Dàn yèshì zhēnzhèng de fēngjǐng bú shì zhèxiē, ér shì liǎng ge shāokǎo tān zhījiān de lěngzhàn. Lǎo Wáng hé Lǎo Liú, tānwèi jǐn āi, càidān jīhū yì mú yíyàng, èrshí nián lái cóng bù shuōhuà. Tāmen gèzì bǎi zhe xiāngtóng de kǎochuàn, xiāngtóng de píjiǔ, xiāngtóng de sùliào dèng, jiàgé yǒngyuǎn chā yì máo qián — shéi xiān jiàngjià, duìfāng bàn xiǎoshí nèi gēn shàng. Kèrén zǒu cuò tānwèi, shuāngfāng dōu jiǎzhuāng méi kànjiàn. Wǒ guānchá le yí ge yuè, cóng méi jiàn guò tāmen yǒu rènhé jiāoliú. Zhídào yǒu yì tiān wǎnshang chéngguǎn lái le. Liǎng ge rén tóngshí shōu tān, dòngzuò pèihé zhī mòqì fǎngfú páiliàn guò yì bǎi cì — xiān shōu zhāopai, zài dié zhuōzi, zuìhòu tuī chē. Chéngguǎn zǒu hòu, tāmen tóngshí bǎi huíqù, xiān tuī chē, zài zhī zhuōzi, zuìhòu guà zhāopai. Ránhòu jìxù jiǎzhuāng duìfāng bù cúnzài.",

    "j7_city_063": "Wǒ zhù shíbā lóu, měi tiān zuò diàntī hǎo jǐ cì. Diàntī shì yí ge jīngmì de shèhuìxué shíyànshì, ér wǒ shì wéiyī de yánjiūyuán. Shǒuxiān shì zhànwèi guīzé. Yí ge rén de shíhou zhàn ànniǔ pángbiān, miàn duì mén. Dì èr ge rén jìnlái, dì yí ge rén zìdòng tuì dào jiǎoluò. Dì sān, dì sì ge rén jìnlái, měi ge rén zìdòng xúnzhǎo lí suǒyǒu rén zuì yuǎn de wèizhi, xiàng tóngjí cítiě. Wǒ zài diàntī lǐ huà guò yì zhāng shìyìtú: liǎng ge rén shì duìjiǎoxiàn, sān ge rén shì děngbiān sānjiǎoxíng, sì ge rén shì zhèngfāngxíng sì jiǎo, wǔ ge rén — wǔ ge rén de shíhou shùxué móxíng jiù bēng le, yīnwèi zǒng yǒu yí ge rén bèi pò zhàn zài zhōngjiān, tā huì lìkè tāo chū shǒujī jiǎzhuāng hěn máng yǐ jiǎnqīng cúnzàigǎn. Ránhòu shì mùguāng fǎzé. Diàntī lǐ de rén bù hùxiāng kàn. Kàn shǒujī, kàn lóucéng xiǎnshì, kàn tiānhuābǎn, kàn dìmiàn, kàn zìjǐ de xiézi — jiùshì bú kàn duìmiàn de rén. Wǒ zuò guò yí ge shíyàn: zài diàntī lǐ zhíshì yí ge mòshēngrén wēixiào. Tā xiān shì lèng le yí miǎo, ránhòu dītóu kàn shǒujī, ránhòu zài xià yì céng jiù chūqù le — nà bú shì tā yào dào de lóucéng. Zuì yǒuqù de shì shēngyīn. Yí ge rén dúzì zài diàntī lǐ kěnéng hēng gē, zìyánzìyǔ, shènzhì tōutōu fàng pì. Liǎng ge rén de shíhou ānjìng. Sān ge rén yǐshàng, ānjìng dào nǐ néng tīngjiàn měi ge rén hūxī de pínlǜ. Dàn dāng diàntī tūrán huàng le yíxià, suǒyǒu rén huì tóngshí táitóu duìshì. Nà shì wéiyī de lìwài: gòngtóng de kǒngjù kěyǐ zài líng diǎn sān miǎo nèi wǎjiě suǒyǒu shèjiāo píngzhàng. Ránhòu diàntī huīfù zhèngcháng, píngzhàng chóngxīn shēng qǐ. Bǐ xiū qiáng kuài duō le.",

    "j7_city_069": "Gébì zhuāngxiū yǐjīng sì ge yuè le. Hétong shàng xiě de shì liǎng ge yuè. Wǒ xiànzài néng tōngguò shēngyīn jīngquè pànduàn tāmen zài zuò shénme: qīngcuì de dīngdīng shēng shì qiāo cízhuān, chénmèn de dōngdōng shēng shì zá qiáng, chíxù de wēngwēng shēng shì diànjù qiē mùbǎn. Wǒ shènzhì néng pànduàn gōngrén de qíngxù — huó gàn de shùn de shíhou diànzuàn shēng jiézòu píngwěn, pèng dào wèntí de shíhou huì tíng yíxià, mà yì shēng, zài jìxù. Wǒ gēn gébì yèzhǔ de quánbù jiāoliú shì tōngguò qiángbì wánchéng de. Bú shì qiāo qiáng, shì bèidòng jiāntīng. Wǒ zhīdào tāmen wèi cízhuān yánsè chǎo guò sān cì jià, nǚfāng xiǎng yào huīsè de, nánfāng juéde báisè jīngdiǎn. Zuìhòu xuǎn le huībái sè — wǒ cóng gōngrén duì zhe qiáng shuō \"zhè shì shénme yánsè, huī bù huī bái bú bái\" tuīduàn chūlái de. Wǒ zhīdào tāmen chāo yùsuàn le bǎifēnzhī sìshí, yīnwèi yǒu yì tiān wǎnshang nánfāng zài yángtái dǎ diànhuà gēn tā mā jiè qián, shēngyīn tài dà wǒ xiǎng bù tīng dōu bù xíng. Wǒ zhīdào gōngtóu xìng Liú, shǒuxià yǒu sān ge rén, qízhōng yí ge xīn lái de zǒngshì bèi mà. Wǒ shènzhì zhīdào xīn lái de nàge jiào Xiǎo Mǎ, yīnwèi \"Xiǎo Mǎ nǐ guòlái kànkan zhège jiǎo mó de xiàng shénme yàngzi\" zhè jù huà wǒ dàgài tīng le liǎng bǎi biàn. Zhuāngxiū zhōngyú zài shàng zhōu jiéshù le. Gébì ānjìng le. Wǒ yīnggāi gǎndào jiětuō. Dàn dì èr tiān zǎoshang bā diǎn bàn, wǒ tiáojiàn fǎnshè de děng diànzuàn shēng xiǎng qǐ, děng le wǔ fēnzhōng cái yìshí dào bú huì zài yǒu le. Nàge ānjìng ràng wǒ bù xíguàn. Sì ge yuè de zàoyīn yǐjīng biàn chéng le wǒ shēnghuó jiézòu de yí bùfen. Xiǎo Mǎ yě bù zhīdào hòulái qù nǎlǐ le.",

    "j7_city_070": "Wǒ jiā fùjìn yǒu ge hónglǜdēng zhuāng zài yí ge jīhū méi chē jīngguò de xiǎo lùkǒu. Tā zhōngshí de zhíxíng zhízé: hóng liùshí miǎo, lǜ liùshí miǎo, huáng sān miǎo, rìyè xúnhuán. Wǒ zài nàge lùkǒu zhàn le yí ge xiǎoshí zuò le ge tǒngjì. Jīngguò de sìshíqī ge xíngrén zhōng, zhǐyǒu bā ge děng le lǜdēng. Bā ge lǐmiàn yǒu wǔ ge shì yīnwèi pángbiān yǒu biéren cái děng de. Yě jiùshì shuō, zhēnzhèng zài méi rén kàn zhe de qíngkuàng xià hái děng lǜdēng de rén, quán shìjiè zhǐ shèng sān ge, qízhōng liǎng ge dài zhe xiǎohái. Suǒyǐ shíjìshang zhǐyǒu yí ge rén chūyú chúncuì de guīzé xìnyǎng zài děng hóngdēng. Nàge rén shì yí wèi qīshí duō suì de lǎo tàitai, tā děng de fēicháng rènzhēn, shènzhì zài lǜdēng liàng le yǐhòu hái duō děng le liǎng miǎo cái guò — dàgài shì bù xìnrèn huángdēng de hányì. Zuì yǒu yìsi de shì chuǎng hóngdēng de fāngshì yě fēn děngjí. Zuì dǐcéng shì \"kàn dōu bú kàn zhíjiē zǒu\", zhè zhǒng rén tōngcháng zài dǎ diànhuà. Zhōngjiān céng shì \"zuǒyòu kàn yì yǎn ránhòu kuài zǒu\", bǎoliú le zuì jīběn de shēngcún běnnéng. Zuì gāo céng shì \"yóuyù sān miǎo, kàn le liǎng yǎn, quèrèn méi chē, xiǎo suìbù kuài zǒu, guò le mǎlù zhīhòu huítóu kàn yì yǎn hónglǜdēng\" — zhè zhǒng rén chuǎng le hóngdēng dàn liángxīn hái zài, nàge huítóu yí kàn shì gěi guīzé de zuìhòu yìdiǎn zūnzhòng. Wǒ bǎ zhège jiào zuò \"chuǎng hóngdēng de huímóu\". Hòulái nàge lùkǒu de hónglǜdēng huài le, liǎng zhōu méi xiū. Jiéguǒ nà liǎng zhōu fǎn'ér méi rén chuǎng hóngdēng le — yīnwèi méiyǒu dēng kě chuǎng, rénmen guò mǎlù shí fǎn'ér biàn de gèng xiǎoxīn le.",

    "j7_observe_020": "Wǒ zuò guò yí liàng chūzūchē, sījī shì ge huà bù duō de zhōngnián rén. Chē lǐ fàng zhe gǔdiǎn yīnyuè. Wǒ wèn tā xǐhuan gǔdiǎn yuè ma. Tā shuō bù xǐhuan, dàn gǔdiǎn yuè méi gēcí, bú huì ràng tā xiǎng gēn zhe chàng, gēn zhe chàng jiù huì fēnxīn, fēnxīn jiù huì chū shìgù, chū shìgù jiù huì kòu fēn fákuǎn, suǒyǐ gǔdiǎn yuè běnzhìshang shì yì zhǒng jīngjì xíngwéi. Wǒ juéde zhège luójì wúxièkějī. Quánchéng wǒmen jīhū méi zài shuōhuà, zhídào kuài dào mùdìdì tā hūrán shuō: \"Wǒ kāi le èrshí nián chūzūchē, lā guò jǐ shí wàn rén. Nǐ zhīdào shénme rén ràng wǒ yìnxiàng zuì shēn?\" Wǒ cāi le jǐ ge — míngrén? Yǒuqián rén? Hē zuì de rén? Tā dōu yáotóu. \"Shì nàxiē shàng chē yǐhòu shuō 'bù jí, rào yuǎnlù yě xíng' de rén.\" Tā shuō zhè zhǒng chéngkè èrshí nián bù chāoguò shí ge. Dàn měi yí ge shuō zhè jù huà de rén, hòulái zài chē shàng dōu huì shuō yìxiē tèbié shēn de huà. Tā de lǐlùn shì: zhè zhǒng rén fàngqì le xiàolǜ, shíjiān jiù biàn shēchǐ le, zài shēchǐ de shíjiān lǐ rén róngyì dǎkāi zìjǐ. \"Nǐ zhīdào ma,\" tā shuō, \"měi ge chéngkè shàng chē dì yí jù huà bú shì 'kuài diǎn' jiùshì bào mùdìdì. Mùdìdì hé sùdù, zhè jiùshì xiàndài rén de quánbù.\" Wǒ xiǎng le xiǎng wèn tā: \"Nà rúguǒ wǒ xiànzài shuō bù jí ne?\" Tā kàn le yì yǎn jìjiàqì shuō: \"Xiànzài shuō yě xíng, dàn nǐ yǐjīng dào le. Shísì kuài wǔ.\" Wǒ fù le qián xià chē. Zǒu le liǎng bù yòu huítóu kàn — tā de chē tíng zài yuándì méi dòng, chuānghù bàn kāi, gǔdiǎn yīnyuè yǐnyuē chuán chūlái. Tā zài děng xià yí ge chéngkè. Dàgàilǜ yòu huì shì yí ge shuō \"kuài diǎn\" de rén.",

    "j7_observe_027": "Língchén sān diǎn de biànlìdiàn xiàng hēi'àn lǐ yí ge fāguāng de yúgāng, lǐmiàn de rén dōu zài màn dòngzuò yóuyǒng. Wǒ shīmián zǒu jìnqù de shíhou, zhǐyǒu liǎng ge kèrén. Shōuyíntái páng zuò zhe yí ge chuān wàimài fú de xiǎohuǒzi, miànqián yì wǎn guāndōngzhǔ, chī de jí màn — bú shì pǐnwèi, shì zài tuōyán huíqù jiē dān de shíjiān. Jiǎoluò lǐ yí ge chuān xīzhuāng de zhōngnián nánrén, lǐngdài sōng le, kào zhe zázhì jià fān yì běn diàoyú zázhì, fān de sùdù shuōmíng tā zhǐ shì xūyào yí ge dòngzuò lái zhànjù shuāngshǒu. Diànyuán miàn wú biǎoqíng de shuō le yí jù \"huānyíng guānglín\", shēngyīn dài zhe yǐjīng shuō le sān bǎi biàn de jīxièguǎn. Wǒ zài yǐnliào guì qián zhàn le hěn jiǔ. Ná qǐ yì guàn kāfēi, fàng xià. Ná qǐ yì guàn nǎichá, fàng xià. Zuìhòu xuǎn le yì guàn wēn rè de kāfēi niúnǎi — bú shì yīnwèi xiǎng hē, shì yīnwèi guànzi wò zài shǒu lǐ shì wēn de. Hē wán kāfēi, tuī mén zǒu rù yèsè. Wàimài xiǎohuǒ zhōngyú chī wán le guāndōngzhǔ, zhèngzài jì tóukuī. Tā cháo wǒ diǎn le xià tóu. Wǒ yě diǎn le xià tóu. Liǎng ge bù xiǎng huí jiā de rén zài yíngguāngdēng xià jiāohuàn le rénlèi zuì jiǎnduǎn de wènhòu.",

    "j8_observe_003": "Hòuzhěnshì shì yì zhǒng bǎ suǒyǒu rén biàn chéng tóng yì zhǒng dòngwù de kōngjiān. Jìn mén zhīqián nǐ kěnéng shì zǒngjīnglǐ, dàxué jiàoshòu huòzhě wàimài qíshǒu, zuò xiàlái yǐhòu nǐ zhǐ shì \"sānshíqī hào\". Wǒ zài hòuzhěnshì guānchá le yí ge shàngwǔ, fāxiàn rénlèi zài zhèlǐ de xíngwéi móshì yángé fēn wéi sān dǎng. Dì yī dǎng: tāo chū shǒujī shuā duǎn shìpín, yīnliàng wàifàng, wánquán bú zàihu pángbiān de rén zhèngzài jīnglì shénme jíbié de jiāolǜ. Dì èr dǎng: shuāngshǒu jiāochā fàng zài xīgài shàng, mùguāng huànsàn de dīng zhe qiáng shàng nà zhāng \"gāo xuèyā de shí dà wēihài\" xuānchuánhuà, yǐjīng dú le dì liù biàn dàn yí ge zì dōu méi jì zhù. Dì sān dǎng zuì hǎnjiàn: shénme dōu bù gàn, jiù zuò zhe kàn. Wǒ shǔyú dì sān dǎng, zhè ràng pángbiān de rén hěn bù'ān — yí ge shénme dōu bú kàn de rén zài hòuzhěnshì lǐ xiǎn de kěyí. Zuì jīngcǎi de shíkè shì jiàohào. Guǎngbō měi xiǎng yí cì, zhìshǎo yǒu sì ge rén huì tóngshí táitóu, jǐnguǎn tāmen de hàomǎ chā le èrshí duō wèi. Sānshíwǔ hào bèi jiào dào de shíhou, wǔshíbā hào de rén yě huì xiàyìshí de zhàn qǐlái bànjié zài zuò xiàqù, ránhòu jiǎzhuāng zài jì xiédài. Yǒu yí wèi dàjiě sān cì zhàn qǐlái yòu zuò xià, zuìhòu gāncuì gēn pángbiān de rén jiěshì: \"Wǒ bú shì chāduì, wǒ tuǐ má le.\" Hòuzhěnshì yě shì chéngshì lǐ shǎo yǒu de mòshēngrén huì zhǔdòng dāhuà de dìfang. Yí ge lǎo dàye gēn wǒ jiǎng le èrshí fēnzhōng tā de xuètáng zhǐbiāo biànhuà shǐ. Wǒ wánquán tīng bù dǒng, dàn wǒ diǎntóu de pínlǜ ràng tā fēicháng mǎnyì. Tā zuìhòu shuō: \"Xiǎohuǒzi, nǐ shì ge hǎo tīngzhòng.\" Wǒ shuō xièxie. Qíshí wǒ zhǐ shì zài shǔ tā shuō le duōshao cì \"wǒ gēn nǐ shuō\" — dá'àn shì sānshísì cì.",

    "j8_observe_010": "Chāoshì ménkǒu de sùliào dài jià guà zhe liǎng zhǒng: xiǎo hào sān máo, dà hào wǔ máo. Wéirào zhè liǎng máo qián de chājià, wǒ guānchá dào le yí bù wánzhěng de rénlèi xíngwéixué jìlùpiàn. Bǎifēnzhī bāshí de gùkè xuǎn dà hào, nǎpà zhǐ mǎi le yì píng jiàngyóu. Luójí hěn jiǎndān: liǎng máo qián bù zhíde jiūjié, dàn dà dàizi wànyī yào zhuāng biéde dōngxi ne — zhège \"wànyī\" zhīchēng le zhěnggè dà hào dàizi de xiāoliàng. Zhēnzhèng yǒuqù de shì nàxiē zì dài gòuwù dài de rén. Tāmen qīng yī sè shì wǔshí suì yǐshàng de nǚxìng, dàizi dié de zhěngzhěngqíqí cáng zài kuà bāo de tèdìng jiācéng lǐ. Wǒ cǎifǎng guò shí jǐ wèi, méiyǒu yí wèi tí dào huánbǎo. Tāmen de luójí shì: \"Huā qián mǎi yí ge yòng wán jiù rēng de dōngxi, nǎozi yǒu wèntí ba?\" Zhè zhǒng jiéjiǎn gēn niánqīngrén de huánbǎo xùshì shūtú tóng guī, dàn dòngjī wánquán bùtóng — yí ge shì \"wèile dìqiú\", yí ge shì \"wèile zhè liǎng máo qián wǒ gēn nǐ pīn le\". Zuì xìjùhuà de chǎngmiàn fāshēng zài shōuyíntái: yí wèi āyí fāxiàn sùliào dài zhǎng le yì máo, cóng sān máo biàn chéng le sì máo. Tā dāngchǎng zhìwèn shōuyínyuán. Shōuyínyuán shuō zhè shì gōngsī de juédìng. Āyí shuō: \"Gōngsī de juédìng? Nǐmen gōngsī zhī bù zhīdào wǒ cóng liù lóu zǒu xiàlái jiùshì wèile shěng yí kuài qián de diàntī fèi?\" Tā zuìzhōng háishi mǎi le, dàn yāoqiú shōuyínyuán bǎ dàizi chēng kāi ràng tā jiǎnchá yǒu méiyǒu pòdòng — \"sì máo qián de dōngxi, zhìliàng zǒng gāi bǐ sān máo de hǎo ba.\" Shōuyínyuán miàn wú biǎoqíng de pèihé le. Wǒ zhàn zài hòumiàn, yì shēng méi kēng.",

    "j8_observe_011": "Bānjiā shí zhěnglǐ shūzhuō chōuti, wǒ fājué chū le yí ge rénlèixué yízhǐ. Zuì shàng céng shì jìndài wénwù: jǐ zhāng kuàidì dān, yì gēn duàn le de shùjùxiàn, liǎng kē méi diàn de niǔkòu diànchí, yì bāo èr líng èr sān nián de guòqī gǎnmào yào. Wǎng xià shì zhōnggǔ céng: yì zhāng guòqī de jiànshēn kǎ — mǎi de shíhou xìnshìdàndàn měi zhōu qù sān cì, shíjì qù le qī cì jiù zài yě méi qù guò, kǎ shàng de zhàopiàn lǐ wǒ bǐ xiànzài shòu shí gōngjīn, zhè shì tā wéiyī de kǎogǔ jiàzhí. Jǐ zhī bǐ mào diūshī de yuánzhūbǐ. Yì běn zhǐ xiě le sān yè de rìjì — dì yī yè xiě zhe \"cóng jīntiān qǐ jìlù měi tiān de gǎnwù\", dì èr yè xiě zhe \"jīntiān méi shénme gǎnwù\", dì sān yè shì kòngbái de, dàibiǎo lián méi gǎnwù zhè jiàn shì yě lǎn de jì le. Chōuti zuì dǐbù shì zhēnzhèng de yuǎngǔ céng: yì fēng shí nián qián péngyou jì lái de míngxìnpiàn, yóuchuō móhu dàn zìjì qīngxī, wǒ yǐjīng sì nián méi gēn zhège péngyou liánxì le. Yì bǎ yàoshi, shǔyú nǎ shàn mén yǐjīng shì yí ge yǒngyuǎn bú huì bèi jiě kāi de mí. Yì zhāng fànhuáng de zhàopiàn, bèimiàn xiě zhe yí ge rìqī hé yí ge dìmíng, wǒ jì bù qǐ nà tiān fāshēng le shénme, dàn xiǎnrán dāngshí de wǒ rènwéi tā zhíde jì zhù. Měi yì céng dōu dàibiǎo yí duàn bèi yíwàng yòu bèi yìwài wājué de shíguāng. Ràng wǒ gǎnkǎi de bú shì zhèxiē wùpǐn běnshēn, shì tāmen bèihòu nàxiē céngjīng de dǎsuàn: jiànshēn kǎ shì xiǎng biàn jiànkāng de juéxīn, rìjì shì xiǎng jìlù shēnghuó de yuànwàng, míngxìnpiàn shì xiǎng bǎochí liánxì de chéngnuò. Chōuti shì yí ge zhuānmén shōuróng hǎo yìtú de mùdì. Bānjiā de shíhou cái huì zài jiàn dào tāmen.",

    "j8_observe_013": "Xià yǔ tiān liǎng ge rén gòngyòng yì bǎ sǎn, sǎn de qīngxié jiǎodù shì yì tái jīngmì de guānxì jiǎncè yí. Qínglǚ zhījiān, sǎn zìdòng piān xiàng ǎi de nàge, gāo de nàge xīngānqíngyuàn ràng bàn biān jiānbǎng lín shī — zhè shì àiqíng de biāozhǔn jìliàng dānwèi: \"wǒ yuànyì wèi nǐ shī diào de jiānbǎng miànjī\". Tóngshì zhījiān, sǎn bǎochí yángé de zhōngzhóuxiàn duìchèn, gè lín yí bàn, shéi yě bù duō lín yì dī — zhè shì zhíchǎng guānxì de jīngquè jǐhé: píngděng, kèzhì, jué bù yuèjiè. Zuì wéimiào de shì gāng rènshi de rén: chēng sǎn de bǎ sǎn wēiwēi piān xiàng duìfāng, zhè shì shànyì; duìfāng kào jìn yìdiǎn, shì jiēshòu; duìfāng bǎochí jùlí nìngkě lín shī, shì lǐmào de jùjué. Wǒ zài dìtiě zhàn chūkǒu guānchá le yì zhěnggè yǔ tiān, fāxiàn le yí ge yǒuqù de lìwài: yí duì míngxiǎn zài chǎojià de qínglǚ. Nán de chēng sǎn, sǎn wánquán piān xiàng le zìjǐ zhè biān, nǚ de lín zhe yǔ zǒu zài pángbiān. Zǒu le dàyuē wǔshí mǐ, nán de hūrán bǎ sǎn wǎng nǚfāng nuó le guòqù, dàn méiyǒu shuōhuà. Nǚ de yě méiyǒu kàn tā, dàn mòmò kào jìn le bàn bù. Yǔ xià dào zuìhòu, sǎn yòu huí dào le biāozhǔn de piān xiàng ǎi fāng de jiǎodù. Zhěnggè héjiě guòchéng méiyǒu yí ge zì, wánquán kào sǎn de jiǎodù biànhuà wánchéng. Zuì ràng wǒ yìnxiàng shēn de shì yí wèi fùqīn sòng nǚ'ér shàngxué. Sǎn jīhū wánquán zhào zài nǚ'ér tóu shàng, tā zhěnggè hòubèi dōu shī tòu le. Nǚ'ér wánquán méi zhùyì dào. Tā yǒngyuǎn yǐwéi jīntiān de yǔ bú dà.",

    "j8_observe_014": "Yí dùn fàn jiéshù hòu zhuō shàng shèng xià de cài shì yí fèn jīngquè de shèjiāo sǐjiǎn bàogào. Péngyou jùcān, shèngcài zuì duō — měi ge rén dōu diǎn le zìjǐ xiǎng chī de, jiéguǒ shí'èr ge cài lái le bā ge rén, zhuō shàng xiàng dǎ le yì chǎng méiyǒu yíngjiā de sècǎi zhànzhēng. Shāngwù yànqǐng de shèngcài liàng tóngyàng jùdà, dàn sǐyīn bùtóng: kèren bù gǎn chī tài duō pà xiǎn de tānlán, zhǔrén nìngkě duō diǎn jué bù néng chūxiàn kōng pán — kōng pán yìwèi zhe \"zhāodài bù zhōu\", zhè sì ge zì zài Zhōngguó shāngwù wénhuà lǐ de shāshānglì dàgài děngyú zhíjiē huǐyuē. Zuì gāoxiào de shì jiātíng rìcháng fàncài. Wǒ mā néng jīngquè jìsuàn dào měi ge rén chī jǐ wǎn fàn, shéi jīntiān wèikǒu bù hǎo, shéi jiǎnféi bù chī zhǔshí, zuò chūlái de cài qiàhǎo bèi chī wán, wùchā bù chāoguò bàn wǎn. Wǒ yánzhòng huáiyí tā qiánshì shì dàndào jìsuànyuán. Dàijì chāyì zuì míngxiǎn de huánjié shì dǎbāo. Liùshí suì yǐshàng: quán dǎbāo, nǎpà zhǐ shèng sān piàn qīngcài yèzi, nà yě shì sān piàn yǒu zūnyán de qīngcài yèzi. Sìshí suì zuǒyòu: xuǎnzéxìng dǎbāo, pínggū biāozhǔn shì \"míngtiān zhōngwǔ rè yíxià hái néng bu néng chī\". Èrshí duō suì: cóng bù dǎbāo. Wǒ wèn guò yí ge èrshísān suì de biǎodì wèishénme bù dǎbāo, tā shuō: \"Dǎbāo huíqù yě bú huì chī, fàng dào hòutiān rēng diào, hái duō làngfèi yí ge dǎbāo hé.\" Zhège luójí zài jīngjìxué shàng jūrán shì duì de, dàn zài wǒ mā kàn lái děngtóng yú fànzuì. Shàng cì jiātíng jùcān, wǒ mā bǎ suǒyǒu shèngcài dǎbāo huí jiā, bāokuò yì pán zhǐ shèng tāngzhī de shuǐzhǔ yú. Wǒ wèn tā tāngzhī zěnme chī. Tā shuō: \"Míngtiān ná lái zhǔ miàntiáo.\" Dì èr tiān nà wǎn miàn quèshí hěn hǎochī.",

    "j8_observe_019": "Bīngxiāng mén shàng de cítiě tiē shì yí ge jiātíng de fēi zhèngshì kǎogǔ xiànchǎng. Wǒ mā de bīngxiāng mén fēn sān ge qū: zuì shàngmiàn shì xíngzhèng qū, cíxìng biānqiān jiā jiā zhe guàhào dān hé jiǎofèi tíxǐng. Zhōngjiān shì wàijiāo qū, lǚyóu jìniànpǐn cítiě — Fùshìshān nàge shì èr líng yīqī nián mǎi de, tā duì Rìběn wéiyī de jìyì shì mǎtǒng gài néng jiārè. Zuì xiàmiàn shì lìshǐ bǎohù qū: wǒ wǔ suì huà de huà, yòng qī bā ge kǎtōng cítiě gùdìng zhe, zhǐ yǐjīng fànhuáng, nèiróng yísì shì yì tiáo yú dàn yě kěnéng shì yí jià fēijī. Yǒu yí cì wǒ jiànyì mā zhěnglǐ yíxià bīngxiāng mén, shízài tài yōngjǐ le. Tā shuō bù xíng, měi yí ge dōu yǒu yòngchù. Wǒ shuō nàge xiě zhe \"niúnǎi kuài guòqī\" de biānqiān kěyǐ rēng le ba, shàngmiàn de rìqī shì èr líng yījiǔ nián de. Tā kàn le yì yǎn shuō: \"Liú zhe tíxǐng wǒ yǐhòu mǎi niúnǎi yào kàn rìqī.\" Wǒ fàngqì le. Hòulái wǒ zhùyì dào: zuì xiǎnyǎn de zhōngyāng wèizhi yǒngyuǎn liú gěi zuì xīn de dōngxi, jiù de bèi jǐ dào biānyuán dàn cóng bù rēng diào. Zhǐyǒu wǒ wǔ suì huà de nà zhāng huà yìzhí zài zuì xiàmiàn de zhèng zhōngjiān, wèizhi cóng wèi biàn guò. Nà shì wéiyī yí ge bù xūyào gēn rènhé xīn cítiě jìngzhēng de wèizhi. Měi tiān zuòfàn shí tā dītóu jiù néng kàn dào. Wǒ sānshí'èr suì le, zài nà shàn bīngxiāng mén shàng yǒngyuǎn shì wǔ suì.",

    "j8_observe_020": "Wǒ zhù zài zhè dòng lóu de dì qī céng sān nián le, bú rènshi tóng céng rènhé línjū de liǎn. Dàn wǒ duì tāmen de shēngxué dàng'àn liǎorúzhǐzhǎng. Qī líng èr: měi tiān qīngchén liù diǎn nàozhōng xiǎng, shì yì shǒu gǔdiǎn gāngqín qǔ. Wǒ tuīduàn tā shì yí ge yǒu pǐnwèi de zǎoqǐ zhě, dàgài sìshí duō suì, dújū. Ránhòu yǒu yì tiān tā de mén kāi le, chūlái yí ge chuān xīhā fēnggé yīfu, dài dà jīn liànzi de èrshí suì chūtóu de xiǎohuǒzi. Wǒ zhěng tào shēngxué xiàoxiàng xìtǒng dāngchǎng bēngkuì. Qī líng sì yǎng le yì zhī māo. Māo zhuǎ zài mù dìbǎn shàng de shēngyīn gēn gǒu zhuǎ bùtóng — gèng qīng, gèng suì, gèng bù guīlǜ, xiàng yǒurén yòng shǒuzhǐ suíyì qiāo zhuōmiàn. Wǒ gěi tā qǔ míng \"Lóubǎn\", yīnwèi wǒ zhǐ tōngguò lóubǎn rènshi tā. Tā měi tiān língchén liǎng diǎn zuǒyòu kāishǐ pǎokù, cóng kètīng dào wòshì, zài cóng wòshì dào kètīng. Wǒ tǎng zài chuáng shàng tīng zhe tóudǐng de jiǎobù shēng, jiànjiàn xuéhuì le fēnbiàn tā de xīnqíng: yúnsù pǎo shì wúliáo, tūrán jiāsù shì zhuā dào le shénme, cháng shíjiān ānjìng zhīhòu de yì shēng zhòng xiǎng shì cóng gāo chù tiào xiàlái. Wǒ cóng wèi jiàn guò zhè zhī māo. Dàn rúguǒ yǒu yì tiān lóu shàng ānjìng le, wǒ xiǎng wǒ huì qiāo mén wèn yì shēng.",

    "j8_city_045": "Wǒ jiā fùjìn yǒu yì jiān kāi le èrshí nián de záhuò diàn. Guòdào zhǎi de liǎng ge rén cuò shēn yào cè zhe zǒu. Lǎobǎn xìng Sūn, chénmò guǎyán, cóng bù zhǔdòng dāhuà, dàn tā duì shāngpǐn bǎifàng yǒu yì zhǒng jìnhū piānzhí de jiǎngjiu. Tā de jīngyíng zhéxué yòng yí jù huà gàikuò jiùshì: \"Hǎo de záhuò diàn bú shì chāoshì de suōxiǎo bǎn, shì yí ge shèqū de shēnghuó suǒyǐn.\" Tā huì gēnjù jìjié diào huòjià — rù qiū bǎ qūwényè nuó dào jiǎoluò, huàn shàng nuǎnshuǐdài hé jiāngchá. Méiyǔ qián yì zhōu, chúshī hé zhǔnshí chūxiàn zài zuì xiǎnyǎn de wèizhi. Dàn zhēnzhèng ràng wǒ pèifú de shì tā de shíjiān cèlüè. Zhè tiáo jiē yǒu sān jiā zǎocān diàn, suǒyǐ tā zǎoshang bù jí zhe kāi mén. Tā de huángjīn shíduàn shì wǎnshang shí diǎn yǐhòu — fànguǎn dǎyàng, biànlìdiàn rén mǎn wéi huàn, tā de xiǎo diàn qiàhǎo tiánbǔ zhège fèngxì. \"Kāi záhuò diàn bú shì zuò shēngyi,\" tā yǒu yí cì hǎnjiàn de zhǔdòng kāikǒu, \"shì zuò fānyì. Bǎ zhè tiáo jiē shàng měi ge rén shuō bu chūkǒu de xūqiú fānyì chéng huòjià shàng de shāngpǐn.\" Tā zhǐ zhe ménkǒu yí ge bù qǐyǎn de xiǎo lánzi — lǐmiàn fàng zhe miǎnfèi de chuāngkētiē hé yícìxìng yǔyī. \"Zhuàn bù liǎo qián, dàn xià cì tāmen yào mǎi dōngxi shí huì xiǎng qǐ zhèlǐ.\" Wǒ wèn tā zěnme gēn gébì xīn kāi de liánsuǒ biànlìdiàn jìngzhēng. Tā kàn le yì yǎn nà jiā èrshísì xiǎoshí yíngyè, dēnghuǒ tōngmíng, ménkǒu bǎi zhe sān ge cùxiāo zhǎnjià de biànlìdiàn shuō: \"Tāmen mài de shì shāngpǐn. Wǒ mài de shì 'Sūn lǎobǎn jìde nǐ jiā háizi niúnǎi guòmǐn suǒyǐ cónglái bù gěi nǐ tuījiàn niúnǎi' zhè jiàn shì.\" Nà jiā biànlìdiàn hòulái kāi le bā ge yuè jiù guān le. Sūn lǎobǎn de diàn hái zài. Ménkǒu nàge lánzi lǐ de chuāngkētiē háishi miǎnfèi de.",

    "j8_city_050": "Bān jìn sānshí'èr céng gāolóu yǐhòu, wǒ chéng le yì míng diàntī chénmòxué de yèyú yánjiūzhě. Diàntī lǐ de chénmò zhìshǎo fēn sì ge pǐnzhǒng. Zuì chángjiàn de shì \"lǐmàoxìng chénmò\": jìn mén diǎntóu wēixiào, ránhòu gèzì dīng zhe lóucéng shùzì, quánchéng bù shuōhuà. Zhè shì chéngshì rénjì guānxì zhōng zuì jīngqiǎo de fāmíng — yòng líng diǎn wǔ miǎo de miànbù jīròu yùndòng tóngshí wánchéng \"wǒ kàn dào nǐ le\" hé \"wǒ bú huì dǎrǎo nǐ\" liǎng ge xìnxī de chuándì. Ránhòu shì \"gāngàxìng chénmò\", chūxiàn zài gāng chǎo guò jià de línjū zhījiān. Kōngqì zhōng de jǐnzhānggǎn kěyǐ yòng shǒu mō dào. Liǎng ge rén hèn bu de bǎ zìjǐ suō jìn diàntī de duìjiǎoxiàn liǎng duān, rúguǒ diàntī shì yuánxíng de tāmen yídìng huì zhàn dào dìqiú bèimiàn qù. Dì sān zhǒng shì \"mòqìxìng chénmò\", cúnzài yú zhù le hěn duō nián de lǎo línjū zhījiān. Bù shuōhuà bú shì yīnwèi méi huà shuō, ér shì yīnwèi bù xūyào le — yí ge yǎnshén jiù néng chuándá \"jīntiān lèi le\" huòzhě \"zuìjìn hái hǎo ba\". Yǒu yí cì tíngdiàn, diàntī kùn zhù le wǒ hé liù lóu de Chén shū. Hēi'àn lǐ wǒmen bèi pò dǎpò le duō nián de chénmò. Tā shuō tā qíshí yìzhí xiǎng gàosu wǒ, tā tǐng xǐhuan wǒ yángtái shàng zhǒng de bòhe, měi cì diàntī mén kāi de shíhou néng wén dào qīngxiāng. Wǒ shuō wǒ yě yìzhí xiǎng gàosu tā, tā měi tiān zǎoshang zài lóudào liàn tàijíquán de shēngyīn hěn hǎotīng. Diàn lái le, mén kāi le, wǒmen xiāngshì yí xiào. Ránhòu jìxù huí dào gèzì de chénmò lǐ. Dàn nàge chénmò de pèifāng yǐjīng biàn le: cóng \"bù xiǎng shuō\" biàn chéng le \"bú yòng shuō\". Zhè shì dì sì zhǒng — \"bèi wēnnuǎn tiánchōng guò de chénmò\". Zuì xīyǒu de pǐnzhǒng.",

    "j8_city_056": "Tǒngzilóu lǐ línjū zhījiān zhǐ gé yí miàn báo zhuān qiáng, géyīn xiàoguǒ yuē děngyú yòng bàozhǐ gé kāi liǎng jiān fáng. Nǐ de nàozhōng jǐ diǎn xiǎng, wǎnshang jǐ diǎn shuìjiào — gébì yì qīng èr chǔ. Zhùhù men duì cǐ fāzhǎn chū yì tiáo bù chéng wén de héxīn tiáokuǎn: nǎpà nǐ qīngqīngchǔchǔ tīngjiàn gébì fūqī chǎojià de quánbù xìjié, dì èr tiān pèngmiàn yě bìxū biǎoyǎn wánquán bù zhīqíng. Dàn gòng qiáng wàijiāo bù zhǐ shì zhuāng lóng zuò yǎ. Dōngtiān yè lǐ nǐ késou bù zhǐ, gébì huì qīng qiāo sān xià qiáng: \"Nǐ hái hǎo ma?\" Huí qiāo liǎng xià: \"Méi shì.\" Bù huíyìng dehuà, shí fēnzhōng nèi yídìng yǒurén lái qiāo mén. Zhè tào ànhào shì bān jìnlái dì yī tiān gébì Liú dàjiě jiāo wǒ de. Tā shuō: \"Zhù zài zhè zhǒng fángzi lǐ, qiáng bú shì yòng lái gé kāi rén de, shì yòng lái liánjiē rén de.\" Hòulái Liú dàjiě bān zǒu le. Xīn línjū bān jìnlái de dì yī tiān wǎnshang jiù kāi le wàifàng de duǎn shìpín, shēngyīn dà de xiàng zài wǒ chuángtóu kāi le ge diànyǐngyuàn. Wǒ yóuyù le hěn jiǔ, zuìhòu qiāo le sān xià qiáng. Duìmiàn ānjìng le. Ránhòu huí le liǎng xià. Gòng qiáng wàijiāo de xiéyì jiù zhèyàng wánchéng le jiāojiē."
}

# Apply to files
for filename, ids in [("passages_hsk7.json", [k for k in pinyin_map if k.startswith("j7_")]),
                       ("passages_hsk8.json", [k for k in pinyin_map if k.startswith("j8_")])]:
    with open(filename, "r") as f:
        data = json.load(f)

    updated = 0
    for passage in data:
        if passage["id"] in pinyin_map:
            passage["text_pinyin"] = pinyin_map[passage["id"]]
            updated += 1

    with open(filename, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"{filename}: updated {updated} passages")

print("Done.")
