#!/usr/bin/env python3
"""Compress text_en for HSK 8 passages over 280 words.
Edits text_en ONLY. Does not touch text_zh or text_pinyin.
"""

import json
import sys

INPUT = "/Users/jasongerson/mandarin/content_gen/passages_hsk8.json"
OUTPUT = INPUT  # overwrite in place

# Map of passage id -> compressed text_en
COMPRESSED = {

"j8_observe_008": (
    "This city has three used bookshops left. The one I frequent is deep in an alley, "
    "its storefront so narrow only one person can pass. The glass door is papered from "
    "inside with handwritten recommendation cards, blocking nearly all natural light. "
    "Push it open and a distinctive smell washes over you\u2014old paper, wooden shelves, "
    "the dull sweetness of rooms long underventilated. The owner, surnamed Tao, was a "
    "middle-school Chinese teacher before retirement. Fifteen years ago he spent his "
    "savings to take over this shop. He has his own system for evaluating books: he "
    "ignores the publisher and listed price, opens only to the first three pages and the "
    "last. The first three pages reveal a book\u2019s breathing rhythm; the last shows "
    "whether the author ended in haste or composure. Pricing follows its own logic\u2014he "
    "adjusts upward based on the density of pencil annotations. \u2018A book genuinely read,\u2019 "
    "he says, \u2018is worth more than a new one, because it carries an extra layer of "
    "dialogue.\u2019 I asked how he keeps going while bookstores everywhere close. He pointed "
    "to two students reading on an old sofa in the corner: \u2018As long as someone will sit "
    "here for an afternoon, this shop has a reason to stay alive.\u2019 I looked at them\u2014"
    "backpacks on the floor, cola on the armrest, completely immersed, as if they\u2019d shut "
    "the world outside the door."
),

"j8_mystery_002": (
    "When I moved into this old Western-style house, the landlord said not to bother "
    "with the attic\u2014just odds and ends, nothing to see. After half a year, I went up. "
    "It was neater than expected. Dust covered everything, but things were arranged with "
    "order: boxes of old books, a full-length mirror, a guitar missing a string. Most "
    "striking was a vintage typewriter by the window\u2014an Olivetti, probably 1960s. A "
    "sheet of paper was still loaded, half a page of English typed on it. I leaned in: "
    "\u2018Dear M, I have been trying to write this letter for three months, and every "
    "version ends up sounding like a lie.\u2019 The content broke off after a comma, as if "
    "the writer had hesitated and never returned. I didn\u2019t touch the paper or open the "
    "drawer beneath the typewriter. Some things, once opened, saddle you with the "
    "responsibility of knowing them. I just stood there: what kind of person wrote "
    "letters in this attic? Was the letter ever sent? Or are some words destined to stop "
    "at a comma? The cafe owner downstairs told me a translator once lived here, went "
    "to America in the 1980s, never came back. That typewriter and half-finished letter "
    "had waited in the attic for nearly forty years. Sometimes I go up and sit, touching "
    "nothing, just feeling the texture of interrupted time\u2014a comma can weigh forty years."
),

"j8_identity_002": (
    "Renewing my passport, I dug out all my old ones\u2014four total, age sixteen to now. "
    "Four photos, four faces, the same person. Each looks like someone else. The "
    "sixteen-year-old: wide eyes, caught between nervousness and excitement\u2014first trip "
    "abroad, a school trip to Japan. Twenty-four: much thinner cheeks, a look of "
    "determination now slightly comical. Just finished graduate school, believed I was "
    "going to change the world. Thirty-two: the most unnatural\u2014a deliberate smile, "
    "mimicking some \u2018mature professional.\u2019 I\u2019d just been promoted, playing a role I "
    "assumed others expected. Now, forty. The photographer told me to smile. I did, "
    "faintly\u2014not unhappy, but no longer needing to prove anything to a lens. I arranged "
    "the four passports on the table. They don\u2019t record which countries I visited, but "
    "how I faced a camera at different ages\u2014how I faced being seen. At sixteen, afraid, "
    "hence nervous. At twenty-four, eager, hence resolute. At thirty-two, unsure who "
    "should be seen, hence performing. At forty, accepting that the one being seen is "
    "simply who I am. Perhaps all the photos together form one true face. But that face "
    "isn\u2019t in any single passport\u2014it exists only in the gaze you bring to looking "
    "through them: a gaze tempered by time, finally gentle."
),

"j8_city_042": (
    "Downstairs from my apartment is a twenty-four-hour flower shop. The owner, Sister "
    "Mei, is in her fifties. During the day the shop is ordinary, but after midnight it "
    "gets interesting. Every late-night buyer carries a story. Nurses just off shift pick "
    "pale flowers\u2014\u2018a reward for myself.\u2019 A taxi driver comes at three a.m. for a single "
    "sunflower to stick in his steering-wheel cup holder, saying it makes the night shift "
    "less lonely. What moves Sister Mei most is an elderly gentleman who appears at one "
    "a.m. on the fifteenth of every month to buy white baby\u2019s breath. She once asked why "
    "always at that hour. The fifteenth was the anniversary of his wife\u2019s death, he said. "
    "He walks to the river on full-moon nights to set the flowers on the water. \u2018Too "
    "many people during the day. I don\u2019t want anyone to see me cry. At dawn by the river "
    "it\u2019s just me and the moon\u2014just right.\u2019 Sister Mei was silent a long time. From then "
    "on, every fifteenth she wraps a bouquet in advance and leaves it on the counter, "
    "unpriced. The old man takes it, never asking how much, only giving her a nod before "
    "leaving. This wordless understanding has lasted over three years."
),

"j8_city_044": (
    "The old pedestrian overpass in the south of the city was built in 1987. Every "
    "morning at five-thirty, sanitation workers\u2019 brooms wake it first\u2014bamboo bristles "
    "sweeping concrete steps, dry and even. After six, morning-market vendors set up "
    "beneath the bridge: the sizzle of oil pans, the rush of steam escaping a lifted "
    "steamer lid\u2014the warmest sonic layer of the overpass\u2019s day. By rush hour, car horns "
    "and scooter bells drown everything. Only standing at dead center, both feet on a "
    "warped iron plate, can you feel the structure trembling to the rhythm of traffic. "
    "Two or three in the afternoon is the quietest moment; a retiree leans on the "
    "railing, wind threading through the gaps emits a soft keening, like a whisper the "
    "city forgot. At dusk, schoolchildren bounce across, pencil cases clattering in "
    "backpacks\u2014the crispest sound of the day. Late at night, a busker strums guitar at "
    "the bridgehead, the melody echoing with the last bus\u2019s braking. If an overpass had "
    "memory, it would remember not how its appearance changed but these sounds flowing "
    "over it for thirty years\u2014they define a place\u2019s soul more than any building material."
),

"j8_city_047": (
    "My building was built in 1993. Sixty mailboxes line the lobby wall, each with a "
    "small brass unit number. Over thirty years, these mailboxes have lived a complete "
    "cycle from full operation to abandonment. In the nineties, the mailbox was a daily "
    "destination\u2014newspapers, letters from relatives, the occasional heart-racing "
    "envelope. Into the 2000s, mailboxes filled with advertising flyers and credit-card "
    "statements as paper correspondence left the stage. By the late 2010s, parcel lockers "
    "and email had replaced the mailbox entirely; most residents stopped clearing theirs, "
    "letting flyers overflow like forgotten miniature archives. But not all were "
    "abandoned. Teacher Zhang on the third floor still opens her mailbox every day, "
    "though nine times out of ten it\u2019s empty. I asked why. She said it was a habit "
    "formed thirty years ago. \u2018Just as some people must drink water first thing after "
    "waking, I must check my mailbox. Whether there\u2019s a letter doesn\u2019t matter\u2014what "
    "matters is the act makes me feel I\u2019m still expecting something. Once a person stops "
    "expecting, days become nothing but repetition.\u2019"
),

"j8_city_049": (
    "The plane trees along this road were planted in 1956; every trunk now takes two "
    "people to wrap their arms around. City records list numbers, species, planting "
    "dates, but not the human stories each tree has witnessed. At the base of tree three, "
    "a crack repaired repeatedly\u2014a nineties bicycle crash. The rider, a college student "
    "rushing to an exam, got up and checked his admission ticket before checking himself. "
    "Tree seventeen has a depression\u2014a nail hole from 2003, when community workers "
    "pinned a SARS bulletin to the trunk. The bark has nearly swallowed it, leaving a "
    "shallow dimple. What touches me most is the bench beneath tree forty-two, donated by "
    "an elderly couple. A brass plaque reads: \u2018Dedicated to the fifty years since we met "
    "under this tree.\u2019 The old gentleman has since passed. His wife still comes every "
    "evening\u2014sometimes with a book, sometimes with nothing, just watching passersby. The "
    "landscaping worker who manages this stretch told me he is extra careful pruning tree "
    "forty-two, keeping the shadow of its branches over that bench. \u2018I don\u2019t know what "
    "she\u2019s waiting for,\u2019 he said, \u2018but what I can do is make sure that shade is always "
    "there.\u2019"
),

"j8_city_051": (
    "In the park there is a wooden bench polished to a sheen from years of sitting. The "
    "groundskeeper says it was installed in 1998: seat slats replaced twice, armrests "
    "three times, leg bolts once. But its \u2018soul\u2019\u2014the cast-iron base welded into the "
    "ground\u2014has never changed. At five a.m., the first to sit are elders who\u2019ve finished "
    "morning exercises, carrying thermoses and radios, leaving tea stains on the seat. "
    "Around nine, young mothers bring children to bask in the sun, stroller wheels "
    "rolling over the same patch of dirt until two shallow ruts form. In the quietest "
    "part of the afternoon, someone naps here\u2014newspaper over the face, shoes under the "
    "seat\u2014the greatest trust one can give a public space. Evening is the bench\u2019s "
    "busiest period: couples, chess-playing elders, phone-scrolling young people take "
    "turns, like a buffet of city life. What moves me most are those who sit alone. They "
    "don\u2019t look at phones, don\u2019t read, don\u2019t talk\u2014just sit quietly, eyes gazing into "
    "the distance or at nothing. The bench\u2019s most important function is not providing a "
    "place to sit and do something, but permitting people to sit and do nothing\u2014in a "
    "society that measures everything by efficiency, the right to idleness is a luxury."
),

"j8_city_052": (
    "Looking across to the high-rise opposite late at night, every lit window is a "
    "miniature theater. I spent one winter on my balcony observing window-light changes "
    "in the building across the way, like an amateur astronomer discerning constellations "
    "of the human world. Warm yellow light is most common\u2014a ceiling lamp or table lamp, "
    "meaning someone is still up: watching TV, doing housework, or waiting for a family "
    "member late coming home. Cool white fluorescent light means someone working "
    "overtime\u2014emotionless, uniform brightness, as if forcing a shard of daytime from the "
    "night. The gentlest is a faint blue glow from a phone or tablet\u2014the occupant in "
    "bed but not yet asleep, scrolling through last messages in the dark. Occasionally "
    "a rapidly flickering colored light\u2014someone watching a movie or gaming. What "
    "fascinates me most are lights that suddenly come on at two or three a.m. They are "
    "always abrupt, making you guess: nightmare? A baby\u2019s cry? Something remembered that "
    "won\u2019t let go? These lights usually go out after ten minutes, as if the wakefulness "
    "were an extension of a dream. Every window is a star, every lamp its spectrum. You "
    "can\u2019t know the specific story on that planet, but color, brightness, and duration "
    "sketch the outline of a life."
),

"j8_city_053": (
    "In an era of delivery platforms, three repair shops survive in that southern alley\u2014"
    "Old Zhou the cobbler, Master Lin the umbrella mender, Granny He the watchmaker. "
    "They cling to a dying belief: when something breaks, fix it, don\u2019t throw it away. "
    "Old Zhou\u2019s shop is two square meters, tools covering every wall, the air thick with "
    "leather and glue. Fewer people come now; a young person\u2019s first reaction to worn "
    "shoes is opening a shopping app. \u2018It\u2019s not that they don\u2019t value things,\u2019 Old Zhou "
    "says. \u2018This era taught them new is always cheaper than repaired.\u2019 But his business "
    "has shifted. The people who come now bring emotions, not just shoes. A young woman "
    "brought canvas shoes worn beyond recognition\u2014her college boyfriend gave them to "
    "her; they\u2019d broken up but she wanted to keep the shoes. A middle-aged man brought "
    "handmade cloth shoes, the last pair his late mother made. Old Zhou took them with "
    "unusual gentleness, as if receiving porcelain. What he repairs is no longer shoes\u2014"
    "it\u2019s memories. \u2018You can buy new shoes, but you can\u2019t buy the roads stitched into "
    "the soles. I\u2019m repairing those roads.\u2019 Master Lin\u2019s umbrella shop has similar "
    "stories, Granny He\u2019s watches even more\u2014behind every old timepiece lies a private "
    "narrative about time."
),

"j8_city_054": (
    "The stray cats of this old district have formed an intricate social system whose "
    "logic resembles human governance. The orange tabby at the corner shop is the "
    "recognized \u2018district chief,\u2019 enjoying priority foraging and the best napping spot\u2014"
    "the rattan chair the shopkeeper\u2019s wife leaves by the door. Cats passing through its "
    "territory must observe unwritten transit etiquette: lower the head, slow the pace, "
    "avoid eye contact. When an outsider intrudes, the orange tabby doesn\u2019t attack but "
    "circles the newcomer slowly, completing an \u2018identity inspection\u2019 through body "
    "language. Most outsiders leave under this silent pressure; the rare few who stay "
    "must endure a days-long \u2018observation period,\u2019 confined to marginal spots at the "
    "alley\u2019s edges. What astonishes me most is the mutual-aid mechanism. A black cat "
    "with a lame leg always finds food left by the others after eating\u2014not pity, but a "
    "natural, unspoken understanding. A neighbor who feeds the strays told me cat society "
    "is far more complex than humans imagine. \u2018They have their own diplomacy, borders, "
    "welfare system,\u2019 she said. \u2018The only difference from humans is they never hold "
    "meetings.\u2019"
),

"j8_city_055": (
    "The city announced last year it would dismantle the remaining two hundred and "
    "thirty public phone booths. A grassroots \u2018Phone Booth Guardians Alliance\u2019 launched "
    "a preservation campaign, collecting over four thousand personal memories. One "
    "submission, from a middle-school Chinese teacher, has stayed with me. In college, "
    "every weekend she called her parents from the phone booth outside the school gate. "
    "Long-distance calls required magnetic cards\u2014fifty yuan bought about fifteen minutes. "
    "To fit everything in, she\u2019d outline a script beforehand: report grades, ask about "
    "the harvest, then use the last two or three minutes for small talk. \u2018That urgency "
    "made every sentence precious,\u2019 she wrote. \u2018Now you can chat on WeChat all day and "
    "say nothing. Back then you compressed all your longing into fifteen minutes; every "
    "word was chosen. That density no longer exists.\u2019 Another contributor, a taxi driver, "
    "said twenty years ago he stepped out of the train station into a strange city with "
    "a hundred yuan. He called a friend back home from the station-square phone booth; "
    "that call got him his first job. \u2018That phone booth was the starting point of my "
    "putting down roots here. Tearing it down is like tearing out the first foundation "
    "stone of my life.\u2019"
),

"j8_system_065": (
    "This district library has a well-known summer secret\u2014it is the only free "
    "air-conditioned public space in three surrounding compounds. Every July and August, "
    "the reading room\u2019s headcount triples, but only half are there to read. The rest "
    "come to escape the heat\u2014retirees with chess sets, young workers with laptops, "
    "children with snacks and comics. Director Chen never evicts these \u2018atypical "
    "readers.\u2019 She says a library\u2019s primary function is not housing books but sheltering "
    "people. \u2018A city\u2019s civilization is measured not by how many libraries it builds, but "
    "by how many kinds of people its libraries allow in.\u2019 Her only requirement: quiet. "
    "Whatever you come to do, keep the volume within a range that doesn\u2019t affect others. "
    "This rule creates a wondrous coexistence: chess-playing elders replace the sound of "
    "placing pieces with hand gestures, video-watching young people smile silently in "
    "headphones, parents communicate with children via notes. One detail moved me\u2014"
    "beside the water dispenser sits a box of free paper cups: \u2018For friends who forgot "
    "to bring a cup.\u2019 Director Chen says an elderly regular provides them, buying a pack "
    "weekly with his own money. \u2018He says when he was young and poor, on scorching days "
    "he could barely find drinking water. He doesn\u2019t want others to feel that "
    "embarrassment.\u2019"
),

"j8_system_066": (
    "Neighborhood committee director Old Fang has his own \u2018community weather "
    "forecasting\u2019 system\u2014he observes subtle signs to predict what\u2019s coming. \u2018When the "
    "square-dancing aunties change their song, it means an internal power transition,\u2019 "
    "he says. \u2018Who controls the sound equipment, who decides the playlist, how positions "
    "are arranged\u2014all politics.\u2019 His most accurate prediction: last year he noticed "
    "dog-walking in the compound had surged thirty percent, mostly middle-aged men. Not "
    "a pet trend\u2014a signal of domestic conflict. \u2018Middle-aged men can\u2019t sit still at home "
    "and look for excuses to go out. The most convenient is walking the dog. Those whose "
    "walks exceed forty minutes are hiding outside for peace.\u2019 Over the next two months, "
    "family mediation requests doubled. He also reads trash cans. \u2018When a floor\u2019s bins "
    "fill with takeout containers, someone on that floor is either working overtime or "
    "living alone and in low spirits.\u2019 His method for neighborly disputes: he never "
    "rushes to mediate but lets both sides speak fully, then finds a \u2018shared grievance\u2019 "
    "as entry point. \u2018Get the two quarreling people to curse the property management "
    "together, and they\u2019ll forget why they were arguing.\u2019 His biggest takeaway from "
    "eighteen years: \u2018Managing a community isn\u2019t managing people\u2014it\u2019s managing the "
    "invisible gaps between people. Too wide and the wind leaks; too tight and there\u2019s "
    "pressure. My job is adjusting every gap to the width that lets air circulate.\u2019"
),

"j8_system_069": (
    "Old Wu is the compound\u2019s security guard, keeping a thick logbook of every visitor. "
    "But what the logbook truly records goes beyond names and times. Beside each entry he "
    "makes pencil annotations in symbols only he can read\u2014a circle means \u2018regular,\u2019 a "
    "triangle \u2018first-time visitor,\u2019 an asterisk \u2018keep an eye on.\u2019 This system distills "
    "twenty years of guarding. \u2018I don\u2019t memorize names\u2014I memorize faces,\u2019 he says. "
    "\u2018When a person walks in, their pace, gaze, and expression tell me a great deal. "
    "Walking briskly, eyes straight ahead\u2014legitimate business, let them through. Walking "
    "slowly, looking around\u2014first time, needs directions. Walking quickly with a shifty "
    "gaze\u2014needs the most attention. They know where they\u2019re going but don\u2019t want to be "
    "noticed.\u2019 His proudest moment: his logbook helped crack a burglary. When police "
    "pulled surveillance footage, he pointed to an entry from three days prior: \u2018This "
    "person said he was visiting a friend, but his shoes were wrong\u2014brand-new sneakers "
    "with zero sole wear, suggesting he changed shoes deliberately to avoid identifiable "
    "footprints.\u2019 Police used this lead to identify the suspect. Old Wu says guarding "
    "isn\u2019t watching the gate\u2014it\u2019s reading people. \u2018Every person walking through "
    "unwittingly displays a part of themselves. My job is collecting these fragments and "
    "piecing them into a story.\u2019"
),

"j8_system_071": (
    "Before retiring I taught Chinese at this middle school for thirty years, but what I "
    "knew best was the blackboard. I watched blackboards go from cement surfaces in "
    "wooden frames to green magnetic panels to electronic whiteboards. Each replacement "
    "shifted the teaching ecology. In the cement era, chalk dust was part of the air. "
    "Teachers patted white powder off their clothes after class; veteran teachers\u2019 "
    "finger joints bore a permanent white deposit. Those boards had a distinctive feel\u2014"
    "the resistance of chalk on rough surface was just right, and characters came out "
    "with settled gravity. Magnetic green boards made writing smoother, but the \u2018weight\u2019 "
    "of characters lightened. Then electronic whiteboards\u2014writing on a smooth screen "
    "with finger or stylus, text freely resizable, erasable\u2014technically convenient, but "
    "the solemnity of \u2018once you put down a stroke, it cannot be altered\u2019 had vanished. "
    "What I miss most are the inerasable traces on traditional blackboards\u2014even after "
    "repeated wiping, characters left a faint grayish-white shadow. Those residual "
    "strokes were memory strata: today\u2019s math formulas over yesterday\u2019s Tang poetry, "
    "last week\u2019s chemistry equations beneath this week\u2019s English vocabulary. A "
    "blackboard used ten years was an archaeological site of countless lessons. "
    "Electronic whiteboards leave no trace\u2014every clearing is thorough, perfect, "
    "historyless. We traded depth for efficiency."
),

"j8_system_072": (
    "The six-story building I live in has no elevator; all residents climb stairs daily. "
    "The stairwell has become the building\u2019s most distinctive social space\u2014belonging to "
    "no household yet shaped by everyone. What first caught my attention was its "
    "acoustics. Smooth cement walls produce strong reverberation\u2014each resident\u2019s "
    "returning keys, the rustling of shoes, a closing door all travel floor by floor, "
    "like a vertical broadcasting system. Live here long enough and you identify "
    "climbers by footsteps alone. Teacher Zhang on the second floor: steady, even "
    "stride\u2014years of tai chi. The young couple on three always walk single-file, half a "
    "flight apart, wife\u2019s heels clicking ahead, husband\u2019s sneakers padding behind. The "
    "elderly woman alone on five climbs slowest, resting every few steps, breathing "
    "heavier each floor. The warmest sound comes every evening\u2014Uncle Liu on four places "
    "a small radio on the stairwell windowsill, tuned to the storytelling channel, "
    "volume just audible to neighbors on three through five. No one asked him to; no one "
    "has complained. That sound flows through the twilight stairwell, blending with the "
    "last sunset through the window and the aroma of stir-frying from below\u2014a dusk "
    "symphony belonging only to this building."
),

"j8_identity_081": (
    "My right foot turns slightly outward when I walk\u2014traceable to age fourteen, a year "
    "of financial hardship. My father bought leather shoes two sizes too large, saying "
    "bigger ones last two extra years. To keep them from slapping, I adjusted my sole "
    "angle, and over time developed a distinctive gait. Later our circumstances improved, "
    "but the habit had been carved into muscle memory. During a checkup, an orthopedic "
    "doctor noted asymmetric wear on my right knee joint and asked if I\u2019d long worn "
    "ill-fitting shoes. I told him the story. He paused, then said: \u2018The body is the "
    "most honest recorder. Your father\u2019s financial pressure, your adaptation, the "
    "unspoken consideration between father and son\u2014all written in your bones.\u2019 We "
    "assume poverty is a temporary state\u2014endure it and it\u2019s over. But its traces last "
    "longer than we imagine. It changed a child\u2019s gait, the gait changed bone structure, "
    "bone structure affected joint health. The cost of one pair of ill-fitting shoes "
    "fully manifests thirty years later. This isn\u2019t my father\u2019s fault; it\u2019s poverty\u2019s. "
    "But whenever I feel that subtle outward turn, I think of his expression in the shoe "
    "store\u2014hesitating a long time before choosing the pair two sizes too big. That "
    "expression is called: I can\u2019t give you the best, but what I can give is already "
    "everything I have."
),

"j8_identity_082": (
    "In everyone\u2019s gustatory memory there is an origin point\u2014a taste that instantly "
    "pulls you back to the childhood kitchen. For me: my grandmother\u2019s sour-pickled-"
    "cabbage fish. Not the refined restaurant version with careful plating, but the most "
    "primitive version\u2014home-pickled cabbage, well water from the courtyard, grass carp "
    "from the river that morning. Grandmother was illiterate with no recipes; her "
    "culinary knowledge lived in muscle memory. Salt she measured by pinching with three "
    "fingers, oil temperature by hovering her palm above the wok, doneness by poking the "
    "fish\u2019s belly with chopsticks. I once tried to replicate this dish. Best ingredients, "
    "countless recipes, precise gram measurements and timing. The result tasted good but "
    "was \u2018wrong\u2019\u2014like a transcribed song with every note correct but the soul missing. "
    "The reason her version was \u2018right\u2019 was not superior skill but unquantifiable "
    "variables: her pickling jar, in use thirty years, harbored a microbial community "
    "giving the cabbage a unique fermentation flavor; the well water had different "
    "minerals from tap water; even her knife rhythm affected how food fibers fractured. "
    "These variables composed an irreproducible \u2018taste fingerprint.\u2019 When I say \u2018I miss "
    "home,\u2019 what I miss is perhaps not a coordinate but that fingerprint\u2014created by a "
    "specific person, in a specific space, through a method that can never be "
    "standardized. When that person is gone, that taste disappears forever."
),

"j8_identity_085": (
    "Cleaning out an old wallet, I found a library card from fifteen years ago. The "
    "photo showed a young person I could barely recognize\u2014round face, thick eyebrows, "
    "black-rimmed glasses, expression as serious as if heading to an exam rather than "
    "borrowing a book. I tried logging into the library system with the old card. The "
    "borrowing records were still there: Kafka, Borges, Marquez, a beginner\u2019s Japanese "
    "textbook (clearly abandoned), three photography composition manuals (I now know "
    "nothing about photography), and How to Achieve Financial Freedom Before Thirty. "
    "This last title made me laugh\u2014fifteen years later, I can\u2019t even recognize the "
    "person who wanted to. What moved me most were the \u2018overdue, not returned\u2019 tags. "
    "Four books marked overdue; three eventually returned with late fees. One remains "
    "unreturned: a pocket edition of Three Hundred Tang Poems, probably lost during a "
    "move. The thought that I forever owe that book doesn\u2019t make me feel guilty. It "
    "gives me a poetic comfort\u2014as if that book is a version of myself deposited in the "
    "library, forever in its early twenties, forever reading Li Bai and Du Fu, forever "
    "unaware of what life would become."
),

"j8_identity_086": (
    "My father\u2019s hands are rough as sandpaper, nail crevices forever embedded with "
    "machine oil. Thirty-five years as a fitter in a machinery plant\u2014his hands are his "
    "resume. Every callus a medal of repeated labor, every scar evidence of a lapse in "
    "attention. After retirement, his hands gradually softened, but the calluses and "
    "scars will never disappear. My mother\u2019s hands tell a different story. Forty years "
    "as a primary school teacher left deep indentations on her right index and middle "
    "fingers from gripping chalk and pens. Her joints are slightly deformed from washing "
    "blackboards with cold water in winter, yet those hands remain nimble\u2014she crochets "
    "intricate patterns, folds paper into any shape. If someone who didn\u2019t know my "
    "parents saw only their hands, they could read more than half a life story. Hands "
    "are the body\u2019s least capable liars. You can disguise class through clothing and "
    "speech, but hands betray you. Hands that have never done heavy labor and hands "
    "soaked daily in dish soap fool no one. Once I held my father\u2019s hand to cross the "
    "road\u2014his first time out after his stroke. Hands that once bent steel bars now "
    "needed all their strength to grip my fingers. Hand holding hand\u2014this seemingly "
    "simple action may be humanity\u2019s oldest, most direct form of communication. What it "
    "transmits is not information, but existence itself."
),

"j8_food_091": (
    "Hot pot is the most democratic dining format in Chinese social life. No chef, no "
    "hierarchy of dishes, no fixed serving order\u2014all ingredients laid out at once, "
    "everyone cooking at their own pace. But beneath this egalitarian format lies a "
    "precise set of social codes. First, the soup base. \u2018Spicy or not?\u2019 often reveals "
    "subtle power dynamics. If an elder or boss doesn\u2019t eat spicy, the split pot becomes "
    "default; among friends, choosing clear oil or beef tallow becomes an open vote on "
    "taste. Second, the order of adding ingredients. Experienced diners know tripe needs "
    "seconds of blanching, potato slices need long simmering. But someone always dumps "
    "an entire plate of meat into the pot, crashing the broth temperature and blocking "
    "other ingredients from cooking. This is one of the most serious hot pot gaffes\u2014it "
    "reveals selfishness, caring only about what you want without considering shared "
    "resources. The warmest hot pot memories belong to winter. A snowy night, close "
    "friends around a steaming copper pot\u2014minus-ten-degree wind outside, boiling chili "
    "oil inside. Glasses fogged, cheeks flushed, laughter drifting toward the ceiling. "
    "That warmth doesn\u2019t come just from heat, but from people willing to cook in the "
    "same pot and share the same flavor."
),

"j8_food_092": (
    "The oldest night market here has forty years of history, stretching three hundred "
    "meters from skewer stalls east to dessert stalls west. I\u2019ve walked it countless "
    "times and built a food map more precise than any app\u2014based on smell. Eyes closed, "
    "my nose locates me: the smoky fusion of cumin and chili means the skewer entrance; "
    "then stinky tofu\u2019s fermented aroma; then clean osmanthus sweetness\u2014the old "
    "woman\u2019s tangyuan stall; finally roasted sweet potato from an iron barrel. Each "
    "stall has its optimal window. Skewers taste best before eight, when charcoal hits "
    "peak intensity. Stinky tofu peaks after nine\u2014the longer pre-frying marination "
    "deepens the flavor. Tangyuan\u2019s golden hour is after ten, when the broth has "
    "simmered three or four hours, absorbing fragments of sesame and peanut from "
    "countless tangyuan into a luxurious \u2018tangyuan stock.\u2019 Most vendors are familiar "
    "faces with complex ties of competition and cooperation. One unwritten rule: never "
    "solicit customers in front of someone else\u2019s stall. \u2018Everyone earns their living "
    "by their craft,\u2019 the skewer owner says. \u2018Stealing customers is smashing their rice "
    "bowl. We compete by making our food better, not by keeping others from selling.\u2019"
),

"j8_food_093": (
    "In Chinese social settings, tea is not a beverage but a complete communication "
    "grammar. When to pour, how full, what cup, whether to refill\u2014every detail carries "
    "information words cannot express. The basic rule: \u2018tea seven, wine eight.\u2019 Tea "
    "poured seven-tenths full leaves space for steam so the guest won\u2019t burn their "
    "hands, while implying \u2018leaving room.\u2019 Fill a cup to the brim and the other party "
    "thinks you don\u2019t know the rules, or you\u2019re hinting \u2018drink up and leave.\u2019 Refill "
    "timing is meaningful. In business settings, if the host frequently refills, the "
    "conversation can continue; if the host stops refilling or lifts the cup and says "
    "\u2018please, have some tea,\u2019 that\u2019s the signal to leave\u2014the ancient \u2018raising the cup "
    "to dismiss the guest.\u2019 Most subtle: what tea\u2019s temperature conveys. Freshly brewed "
    "hot tea signals welcome\u2014the host prepared it for your arrival. Cool tea when the "
    "guest arrives means either the host waited too long (reproaching your lateness) or "
    "made no preparation (you aren\u2019t important enough). My teacher once said: \u2018Tea is "
    "the quietest social tool the Chinese invented. It lets you entertain with silence, "
    "express attitudes through temperature, and convey the unsayable through the depth "
    "of water in a cup.\u2019"
),

"j8_food_094": (
    "Cantonese soup-making is a discipline of patience. My colleague Ah Hua spends at "
    "least four hours every Sunday on old-fire soup\u2014in modern life, practically a "
    "luxury. The essence lies not in precious ingredients but in time: bones slowly "
    "releasing collagen over gentle flame, herbal ingredients leaching into barely "
    "simmering water, all flavors finding equilibrium through long fusion. \u2018Impatience "
    "is the worst enemy of soup,\u2019 Ah Hua says. \u2018High heat makes it cloudy; only slow "
    "simmering over low heat makes it clear. Same principle as being a person.\u2019 She "
    "taught me the stages. First half hour: almost no flavor\u2014the \u2018acquaintance period,\u2019 "
    "ingredients just thrown together. After one hour: faint savoriness, flavors "
    "beginning to permeate\u2014the \u2018adjustment period.\u2019 Around two hours: suddenly rich and "
    "multidimensional\u2014the \u2018fusion period,\u2019 all ingredients releasing their essence "
    "simultaneously, creating a composite no single ingredient could produce. The final "
    "hour is the \u2018settling period\u2019: don\u2019t stir, don\u2019t add water, don\u2019t season. Let the "
    "soup quiet down on its own. Ah Hua says this last hour matters most, because \u2018good "
    "things are completed in quietness.\u2019"
),

"j8_food_096": (
    "One a.m., I stand in my kitchen cooking noodles. A ritual only those who live alone "
    "truly understand\u2014not hunger, but the need for something with a definite result. "
    "The day\u2019s work is full of uncertainty: emails unanswered, proposals rejected, words "
    "in meetings that may not have landed. But noodles are different. Boil water, add "
    "noodles, wait three minutes, add a poached egg, scatter scallions. Every step has "
    "clear cause and effect. In an uncertain world, this small certainty is comfort. "
    "Late-night kitchen sounds have a texture invisible by day. The kettle lid chattering "
    "as water boils, oil sizzling, chopsticks clicking against the bowl\u2014drowned in "
    "daytime noise, but at one a.m. each becomes clear and solemn, like a solo in the "
    "deep of night. When I cook noodles late, my movements naturally slow, my sounds "
    "soften. Not fear of disturbing neighbors, but because the atmosphere demands "
    "reverence\u2014for quiet moments, for solitary space, for a simple bowl of food. The "
    "true sign of learning to be alone is not enduring loneliness but cooking noodles "
    "at one a.m. with genuine care\u2014not perfunctory, as if this bowl were for the most "
    "important person in the world. Because in that kitchen, you are."
),

"j8_food_097": (
    "The breakfast stall downstairs has been open over twenty years. I\u2019ve never known "
    "the owner\u2019s name. He starts kneading dough at three-thirty, first dough sticks hit "
    "oil at four-thirty, opens at five sharp. The street\u2019s biological clock is "
    "calibrated by his frying. No sign\u2014just yellowed plastic tarp overhead. Ordering "
    "requires no words: you stand at the stall, he glances and knows. Not mind-reading "
    "but twenty years of observation. The suited man in a hurry wants a dough stick and "
    "soy milk to go. The backpack student will hesitate and still choose fried cake. "
    "The elderly woman back from her morning walk wants tofu pudding with extra savory "
    "sauce. I once tried to break this understanding and ordered something I\u2019d never "
    "ordered. He froze, then looked up\u2014no displeasure, only gentle puzzlement: \u2018what\u2019s "
    "with you today?\u2019 I realized that though I thought I was anonymous, in his cognitive "
    "map I was a specific person with fixed preferences. His stall is a miniature "
    "archaeological site\u2014the iron wok\u2019s bottom holds thick carbonized residue, "
    "geological strata from countless dawns of high-temperature frying. Each layer "
    "records some morning, some hungry commuter, some child who overslept. If this stall "
    "disappeared, it would take twenty years of the street\u2019s morning memory with it."
),

"j8_food_098": (
    "In my memory, making dumplings was never cooking\u2014it was family liturgy. Every New "
    "Year\u2019s Eve, Grandmother dusted the big kitchen table with flour, then placed a "
    "ball of risen dough at the center\u2014solemn as placing an offering on an altar. "
    "Division of labor formed naturally. Grandfather rolled wrappers\u2014his wrist pressure "
    "the most even, each wrapper perfectly round. Mother seasoned the filling, the step "
    "the family recognized as requiring the most judgment: how much salt, how fine the "
    "ginger, the soy-sauce-to-vinegar ratio. My cousin and I wrapped, with Grandmother "
    "inspecting beside us. She\u2019d pick up each dumpling\u2014if the pleats weren\u2019t even or "
    "the seal not tight, she\u2019d quietly unwrap and re-fold it without a word. The silence "
    "itself was the sternest review. An unwritten rule: you must chat. Grandmother said "
    "\u2018dumplings wrapped in silence have no soul.\u2019 So conversation ranged from "
    "neighborhood gossip to international affairs, whose child got into university to "
    "vegetable prices. The topics didn\u2019t matter; what mattered was the sound\u2014laughter, "
    "arguments, sighs\u2014kneaded into the filling like seasoning. Years later, making "
    "dumplings alone in a distant city, the flavor was right, the shape fine, but "
    "something was missing. What was missing were the people who should have been around "
    "that flour-dusted table, and their background noise\u2014that noisy, warm sound that "
    "belongs to \u2018home.\u2019"
),

"j8_food_099": (
    "I like strolling through vegetable markets, not from passion for cooking, but "
    "because the market is the most honest place I know. Supermarket vegetables are "
    "packaged into perfect forms\u2014uniform color, consistent size, smooth surfaces\u2014as if "
    "they came off an assembly line. Market vegetables retain their dirt, irregular "
    "shapes, insect-bite traces. These \u2018imperfections\u2019 prove authenticity\u2014they\u2019ve "
    "weathered rain and sun, competed with insects, arrived carrying the earth\u2019s "
    "temperature. The social rules are distinctive too. Transactions aren\u2019t cold QR-code "
    "payments but conversations with warmth. The vegetable auntie tells you which "
    "variety is freshest and which has gone off\u2014candor nearly unimaginable in the "
    "commercial world. Haggling isn\u2019t confrontation but gentle tug-of-war. You say \u2018a "
    "little cheaper,\u2019 she says \u2018already the lowest,\u2019 then stuffs two extra scallions "
    "in your bag\u2014both sides satisfied, because the transaction\u2019s essence isn\u2019t numbers "
    "but relationship. What I love most is the sound: hawking calls, bargaining, "
    "rustling bags, the thud of chopping on cutting boards, a radio\u2019s storytelling "
    "program drifting from some corner\u2014blending into a \u2018vegetable market symphony.\u2019 "
    "When I\u2019m low, I walk through. Seeing heaping fresh produce, hearing those calls\u2014"
    "people are still earnestly preparing for the next meal. That is comfort enough."
),

"j8_food_100": (
    "Chinese people have a special dependence on congee. It isn\u2019t a proper meal\u2014not "
    "dignified enough. It isn\u2019t a snack\u2014not casual enough. It exists in a subtle "
    "middle ground: companionship during illness, transition at dawn, solace late at "
    "night, the default choice for every moment requiring tenderness. Grandmother had "
    "an unwritten code. Water-to-rice ratio adjusted by season\u2014winter congee thicker "
    "for warmth, summer congee thinner, served with cold cucumber. Congee must simmer "
    "over low heat, no water added midway. She said \u2018good congee is waited into being, "
    "not rushed.\u2019 Once done, it must rest in the pot\u2014letting rice grains absorb "
    "moisture, release starch\u2019s viscosity, form that lustrous \u2018congee cream.\u2019 "
    "Grandmother said that cream is the essence, saved for whoever most needs "
    "nourishment. In my family\u2019s emotional dictionary, \u2018let me make you congee\u2019 is more "
    "concrete than \u2018I love you.\u2019 When you\u2019re fevered in bed, mother\u2019s plain congee\u2014"
    "light, warm, easy to digest\u2014doesn\u2019t cure the illness but promises to accompany "
    "your weakest moment. When you come home after a heartbreak, the pot of millet "
    "congee kept warm on the table asks nothing, offers no advice, simply waits for you "
    "to drink it. Congee never tries to be the protagonist. A thoroughly humble food, "
    "content to play supporting role, content to quietly provide understated warmth "
    "while everyone overlooks it."
),

"j8_food_101": (
    "My last meal before going abroad was at a small restaurant in my hometown. No "
    "refined decor, no background music\u2014menu handwritten on a whiteboard. But my "
    "father had eaten here since childhood, and our family came for every important "
    "occasion. I remember what we ordered: sweet-and-sour ribs, hot-and-sour soup, "
    "dry-fried green beans, braised fish, a small dish of peanuts. All my childhood "
    "favorites, but every dish tasted different that day\u2014not because the chef had "
    "changed, but because my taste buds were steeped in the bitterness of approaching "
    "farewell. Father spoke little. He was never talkative, but that day\u2019s silence had "
    "a different texture\u2014words stuck in his throat with no exit. He just kept serving "
    "me food, chopstick after chopstick, as if pre-storing in my stomach all the "
    "hometown flavors I wouldn\u2019t taste for years. Mother talked a great deal, but every "
    "sentence circled the same things: \u2018Is winter cold there?\u2019 \u2018Remember to eat on "
    "time.\u2019 \u2018Did you pack enough clothes?\u2019 These were her only way of expressing love, "
    "because \u2018I can\u2019t bear to see you go\u2019 was too heavy to say aloud. When it came "
    "time to pay, the restaurant owner refused. He patted father\u2019s shoulder: \u2018The "
    "child\u2019s heading far\u2014this meal\u2019s on me.\u2019 Father just nodded. I\u2019d never seen him "
    "accept kindness so easily\u2014later I understood he was afraid opening his mouth would "
    "make him cry. On the drive back, I realized: every dish was an unspoken sentence. "
    "Sweet-and-sour ribs: \u2018wishing you sweetness.\u2019 Hot-and-sour soup: \u2018life has its "
    "sour and spicy.\u2019 Dry-fried green beans: \u2018live with clean decisiveness.\u2019 Braised "
    "fish: \u2018abundance year after year.\u2019 The peanuts: \u2018safe and sound.\u2019"
),

"j8_system_057": (
    "The community archive room sits in the sub-district office basement\u2014rows of "
    "sheet-metal filing cabinets lined up like a cemetery of paper memory. Custodian "
    "Old Han has worked here twenty-three years and knows every cabinet by heart. He "
    "says cabinets aren\u2019t merely containers but a community\u2019s collective diary. The "
    "bottom cabinets hold 1960s\u201370s materials\u2014handwritten registration forms, yellowed "
    "letters of introduction, files with black-and-white photos. The pen strokes are "
    "upright and forceful, carrying the gravity of the era. Middle tiers hold the "
    "\u201980s\u201390s, where typewritten text begins replacing handwriting, though handwritten "
    "red-pen annotations still appear. The top tier: the last decade, almost entirely "
    "printed. Old Han says what he fears most isn\u2019t losing archives but digitization\u2014"
    "authorities require paper archives be scanned into the cloud. \u2018Paper has warmth,\u2019 "
    "he says. \u2018Touch a fifty-year-old document and you feel the brittleness, smell the "
    "oxidized ink, see traces of the writer\u2019s trembling hand. All that disappears in a "
    "PDF.\u2019 He pointed to a 1976 joint petition. The lower-right corner had a dark "
    "ring-shaped stain. \u2018Not a water stain\u2014a teacup ring. The person writing was "
    "drinking tea and wrote for a long time. No scanner can capture that, yet it is the "
    "most valuable part of an archive\u2014not the text, but the living person behind it.\u2019"
),

"j8_system_058": (
    "Old Zhao reads water meters for this district. From the fifth to the tenth of "
    "every month, he goes door to door. Eighteen years in, he\u2019s visited every corner of "
    "twelve hundred households. He says the job taught him not numbers but reading\u2014"
    "reading living conditions behind the meter. A sudden spike usually means one of "
    "two things: guests arrived, or a pipe is leaking. If the latter, Old Zhao knocks "
    "to alert them rather than waiting for the bill. A sudden plummet requires special "
    "attention\u2014he once called police after a solitary elderly person\u2019s usage was near "
    "zero for two months. They found the man had fallen and couldn\u2019t move. \u2018The water "
    "meter doesn\u2019t lie,\u2019 Old Zhao says. \u2018A person living normally uses at least forty "
    "or fifty liters a day. When a meter stops entirely, either the person isn\u2019t home "
    "or something has happened.\u2019 What troubles him most are households with abnormally "
    "stable usage\u2014precise to the point of mechanical. \u2018Normal usage fluctuates. Today "
    "you washed clothes, used more; tomorrow you didn\u2019t cook, used less. But some "
    "residents\u2019 daily consumption is virtually identical, meaning this person\u2019s life "
    "has been compressed into a fixed routine\u2014same time to wake, same food, same "
    "rhythm.\u2019 He paused: \u2018That precision breaks my heart. It means this person\u2019s life "
    "no longer contains any surprises\u2014not even good ones.\u2019"
),

"j8_system_059": (
    "At the far end of the subway platform sits an inconspicuous transparent plastic "
    "box: \u2018Lost and Found.\u2019 Most passengers hurry past, but attendant Xiao Chen tidies "
    "it three times daily. She says this box is her best window into human nature. "
    "Umbrellas are the most common\u2014nearly half of all lost property. \u2018People only think "
    "of umbrellas when it rains and forget the moment it stops.\u2019 Next: power banks and "
    "earbuds, the occasional wallet or keys. But what truly impresses her are the "
    "unclassifiable items\u2014a handwritten letter without a stamp, a child\u2019s drawing of a "
    "sun, a worn novel open to page 123 with a leaf as bookmark. Owners of these almost "
    "never reclaim them, but how they wait quietly in the box gives Xiao Chen a feeling "
    "of something solemn. \u2018Every lost item represents a moment when someone passed "
    "through this city. Left behind, that moment solidifies in this box.\u2019 By regulation, "
    "items unclaimed after thirty days are disposed of. But Xiao Chen has a private "
    "exception\u2014she sets aside items that clearly carry personal emotion, storing them "
    "in shoeboxes. Three full boxes now, on the top shelf of the office cabinet. \u2018Maybe "
    "no one will ever come,\u2019 she says, \u2018but I don\u2019t want someone\u2019s memories treated as "
    "garbage. In my keeping, they\u2019re lost property, not waste. The difference is "
    "whether someone is still waiting for them to come back.\u2019"
),

"j8_system_060": (
    "Auntie Zhang has been this middle school\u2019s janitor for twelve years. She never "
    "went to college, but her understanding of the school surpasses most teachers\u2019. Her "
    "schedule is the school\u2019s hidden curriculum\u2014classrooms at six a.m., cafeteria "
    "breakfast remains at seven-thirty, office wastepaper baskets at nine, exam notices "
    "blown across the sports field at four-thirty. Behind each time node lies a group "
    "and their behavioral patterns. What she reads best isn\u2019t the teaching plan but the "
    "students\u2019 emotional cycles. \u2018The week before midterms, torn draft paper in the "
    "bins triples. That means nerves. The day after exams, bathroom tissue drops "
    "sharply\u2014most students spend that day sleeping at their desks.\u2019 She\u2019s spotted "
    "another pattern: the first week of September, freshman dormitory trash is "
    "abnormally low. \u2018Not because freshmen are clean\u2019\u2014she laughs\u2014\u2018they\u2019re too "
    "embarrassed to use hallway bins, so they stash it under beds. By week two, back "
    "to normal.\u2019 Her proudest moment: noticing a senior sitting on the rooftop a long "
    "time. She swept up there and saw cigarette butts, though the student didn\u2019t smoke. "
    "She didn\u2019t approach directly but pretended to sweep nearby, drawing closer. Then "
    "told the homeroom teacher. \u2018I don\u2019t understand psychology, but when a non-smoker "
    "has a ground full of cigarette butts, he\u2019s been sitting there too long and needs "
    "someone to notice him.\u2019"
),

"j8_system_061": (
    "On the first of every month, a long queue forms outside this old post office\u2014"
    "almost entirely people over sixty. They come to send money or mail packages to "
    "children far away. Clerk Xiao Li says these elders could easily use mobile banking "
    "or courier pickup; they have no need to come in person. Yet they appear punctually, "
    "as if performing an ancient ritual. \u2018What they care about isn\u2019t the remittance,\u2019 "
    "she says. \u2018It\u2019s filling out the slip by hand. Watch their expressions\u2014when they "
    "write the recipient\u2019s name, they\u2019re especially careful, each stroke slow, as if "
    "speaking to their child.\u2019 She\u2019s noticed another detail: many don\u2019t hurry to leave "
    "but sit in the lobby chatting with other elders. This place has become their "
    "monthly social venue. One regular told Xiao Li her son works in Shenzhen, comes "
    "home once a year. \u2018He transfers money by WeChat\u2014one ding and it arrives. But that "
    "money doesn\u2019t seem like it came from him; it came from the phone. When I send him "
    "money here, it\u2019s slow, but every yuan has passed through my hands. That feeling is "
    "different.\u2019 Xiao Li told me that whenever she\u2019s tempted to rush these elderly "
    "customers, she thinks of that sentence. \u2018Efficiency is for the young. Warmth is "
    "for the old.\u2019"
),

"j8_system_062": (
    "Bus Route 23 has run since 1985\u2014forty years. It departs from the industrial "
    "district in the north, passes through the old city center, and terminates at the "
    "southern train station. Thirty-two stops, about ninety minutes. Veteran driver "
    "Master Wu has driven it for twenty years. He says Route 23 is a blood vessel of "
    "the city\u2014every stop connects to a different ecosystem. At the industrial stops, "
    "workers in overalls board; the carriage smells of diesel and metal dust. At old-"
    "district stops, passengers shift to ladies with vegetable baskets and children with "
    "backpacks; the air fills with scallion and steamed-bun scent. At the hospital stop, "
    "the carriage falls quiet\u2014somber faces, X-ray films, family members with limited "
    "mobility. Master Wu always brakes especially gently here. \u2018The people at this stop "
    "are not at peace inside. The least I can do is give them a smooth start.\u2019 At "
    "university-town stops, the carriage drops thirty years in age\u2014music from earbuds, "
    "delivery alerts, internet slang composing a different soundscape. His favorite "
    "moment: the last run before clocking off\u2014setting sun through the windshield, three "
    "or four passengers left, each gazing out a different window. \u2018Then the whole bus is "
    "like a song nearing its end, every note returning to silence.\u2019"
),

"j8_system_063": (
    "This hospital has six elevators, but what merits study is their internal ecosystem. "
    "Each carries different populations and emotions at different times. The outpatient "
    "elevator at eight a.m. is the most crowded\u2014registration slips, test reports, "
    "imaging materials shuttling through, the air blending disinfectant and anxiety. The "
    "inpatient elevator is different\u2014pace much slower, wheelchairs and crutches entering "
    "and exiting, door speed deliberately slowed by two seconds after repeated family "
    "complaints. Head Nurse Li has observed hospital elevators for fifteen years. She "
    "says interpersonal distance inside is worth studying\u2014in a shopping-mall elevator, "
    "strangers maintain at least thirty centimeters; in a hospital elevator, this "
    "shrinks to nearly zero. \u2018Illness makes people vulnerable, and vulnerability makes "
    "people accept the closeness of strangers.\u2019 Her deepest impression: a young father "
    "holding a child just out of surgery, waiting for the elevator. The child crying, "
    "the father\u2019s eyes red too. The doors opened\u2014packed\u2014but everyone stepped back in "
    "unison, carving out space. No one spoke, no one complained; they simply, silently, "
    "gave way. \u2018That one step,\u2019 Head Nurse Li said, \u2018was the quietest act of kindness "
    "I\u2019ve ever seen.\u2019"
),

"j8_system_064": (
    "A convenience store at two a.m. has a distinctive temperament\u2014the last shelter for "
    "the city\u2019s insomniacs. Clerk Xiao Wu has worked nights for three years. The "
    "daytime store and the late-night store are different species. Daytime customers "
    "have clear purposes: enter, grab, scan, leave\u2014under three minutes. Late-night "
    "customers often aren\u2019t there to buy things; they\u2019re there to \u2018exist.\u2019 Someone buys "
    "coffee and sits by the window until dawn. Someone walks the aisles three times and "
    "buys nothing. Someone stands at the magazine rack for half an hour, then leaves. "
    "Xiao Wu never hurries them. \u2018What they need isn\u2019t merchandise\u2014it\u2019s a place with "
    "lights on that won\u2019t drive you away for not spending.\u2019 His most unforgettable "
    "regular: a middle-aged woman who appears every Wednesday at dawn. She buys a rice "
    "ball and milk, sits in the window seat to finish them, then leaves quietly. Never "
    "speaks, never checks her phone. Once Xiao Wu noticed tear tracks at the corners of "
    "her eyes. He placed a packet of tissues beside her, saying nothing. She looked up, "
    "gave a slight nod, continued eating. Now every Wednesday morning he places tissues "
    "at that spot in advance. They have never exchanged a word, but Xiao Wu feels this "
    "may be the most meaningful understanding of his three-year career."
),

"j8_identity_073": (
    "Going home for Spring Festival last year, I discovered I could no longer understand "
    "my grandmother\u2019s dialect. She asked if I wanted some \u2018sanzi\u2019 and I froze three "
    "seconds before realizing she meant a deep-fried pastry. Worse, the dialect I\u2019d "
    "spoken for eighteen years was almost completely lost. My tongue turned clumsily, "
    "producing tones neither Mandarin nor authentic dialect\u2014like trying to speak two "
    "languages simultaneously and managing neither. Grandmother smiled, but with a "
    "sadness I couldn\u2019t ignore. The young people in the village all stopped speaking "
    "dialect; even three-year-olds open their mouths in Mandarin. \u2018What they hear on TV, "
    "what they learn at school\u2014it\u2019s all that language,\u2019 she said. \u2018Our language\u2014in "
    "twenty years no one will speak it.\u2019 That night I lay on the old bed listening to "
    "insects outside\u2014insects still using the same language they\u2019ve used for thousands "
    "of years, yet our dialect fractured within a generation or two. Dialect is not "
    "just a communication tool; it is a way of thinking, a system of emotional "
    "encoding, a coordinate system for understanding the world. Some emotions can only "
    "be expressed in dialect\u2014the Mandarin word for \u2018missing someone\u2019 is too refined; "
    "only the rough, nasal hometown word for \u2018missing\u2019 holds the full weight of twenty "
    "years away. When I lost my dialect, I lost an invisible umbilical cord to my "
    "hometown."
),

"j8_identity_074": (
    "Sorting through my father\u2019s belongings, I found a tin box of letters in his study. "
    "Arranged by year, 1982 to 2005\u2014the last year he and my mother used paper letters "
    "before shifting to texts, then WeChat. The earliest letter: paper yellowed and "
    "brittle, but his fountain-pen handwriting still clear\u2014upright, restrained, evenly "
    "spaced, every stroke following strict conventions, like someone trained in brush "
    "calligraphy forced to use a fountain pen. The content: his first letter to my "
    "mother upon starting a new job, reporting on conditions. But the nervousness "
    "between the lines couldn\u2019t be hidden\u2014three paragraphs on cafeteria food, half a "
    "page on dormitory bunk assignment, and only the final sentence: \u2018Awaiting your "
    "reply.\u2019 The last letter, 2005. His handwriting had changed\u2014relaxed, hasty, the "
    "young man\u2019s stiffness replaced by a middle-aged man\u2019s ease. The closing: \u2018There\u2019s "
    "pork-rib soup in the fridge\u2014just heat it up.\u2019 That sentence has no literary "
    "quality whatsoever, but I cried reading it. From \u2018awaiting your reply\u2019 to \u2018pork-"
    "rib soup in the fridge,\u2019 twenty-three years condensed in handwriting changes. "
    "A person\u2019s handwriting is the electrocardiogram of their life\u2014taut in youth, "
    "expansive in middle age, trembling in old age. When we stop writing by hand, what "
    "vanishes is not just a mode of writing but the most authentic ripples on the curve "
    "of a life."
),

"j8_identity_075": (
    "On my left wrist: a two-centimeter scar from falling out of a tree at seven. Right "
    "knee: irregular white scarring from a bicycle crash on gravel at twelve. My left "
    "big toenail will never grow evenly\u2014someone stamped on my foot during a soccer "
    "match at fifteen. These scars are a private passport, each stamped with a "
    "particular age and scene. A doctor once noticed all my scars during a checkup and "
    "asked if I worked in a high-risk profession. No\u2014these are the normal wear of "
    "growing up. Behind every scar: risk-taking, impulse, or sheer bad luck. When I "
    "show someone a scar, the other person almost always responds with one of their "
    "own\u2014a kind of symmetrical etiquette. You reveal a vulnerability; the other "
    "reciprocates with equal degree. Scars are the most honest social currency, because "
    "they cannot be forged. Every scar is undeniable proof you experienced something. "
    "As I\u2019ve grown older, new scars have become fewer\u2014not because the world is safer, "
    "but because we\u2019ve grown more cautious. Sometimes I miss that age when I had no "
    "idea of my limits and was forever tumbling into bruises. Those scars remind me I "
    "was once someone unafraid of pain. Now, the scars I fear most stay inside, grow "
    "beneath the skin, and can never be shown to anyone."
),

"j8_identity_076": (
    "Sorting through old belongings at my family home, I found a detail in my mother\u2019s "
    "diary: before I was born, my parents had three candidate names for me. The one I "
    "got was ranked third. The first, \u2018Zhiyuan,\u2019 from Zhuge Liang\u2019s \u2018Without "
    "tranquility one cannot see far.\u2019 The second, \u2018Ruoshui,\u2019 from Laozi\u2019s \u2018Supreme "
    "goodness is like water.\u2019 The reason for the final choice was prosaic\u2014on the day I "
    "was born, my grandfather was reading about plants, saw a tree name he liked, and "
    "that settled it. I sometimes wonder: if I\u2019d been called \u2018Zhiyuan\u2019 or \u2018Ruoshui,\u2019 "
    "would my life have been different? A name doesn\u2019t change destiny. But a name "
    "influences a person\u2019s imagination of themselves. Someone named \u2018Zhiyuan\u2019 might "
    "unconsciously seek grand-narrative possibilities; someone named \u2018Ruoshui\u2019 might "
    "gravitate toward gentle forces. A name is the first gift parents give a child, and "
    "the first expectation. Before the child develops a sense of self, the name has "
    "already begun shaping a latent narrative about \u2018what kind of person I should "
    "become.\u2019 Most people ultimately deviate from their parents\u2019 naming expectations. "
    "But that name, like a coordinate pin at the starting point, no matter how far you "
    "travel, still marks the direction you were first hoped to go. And those names you "
    "were almost given are parallel lives\u2014existing quietly in some diary, waiting to be "
    "happened upon."
),

"j8_identity_077": (
    "After fifteen years in Beijing, I thought my Mandarin was flawless. Then a taxi "
    "driver heard three sentences and guessed my hometown. \u2018You\u2019re from Hubei, right? "
    "You can\u2019t distinguish n from l, and your fourth tone lifts at the end.\u2019 Astonished "
    "and embarrassed\u2014those features I thought fifteen years had smoothed away were "
    "hiding in my speech\u2019s base code, like pre-installed software that can never be "
    "fully deleted. I began paying attention. The driver was right. When emotions ran "
    "high\u2014arguments, rushing, excitement\u2014the dialect substrate surfaced like reef "
    "exposed by retreating tide. Once on the phone, at an excited moment I blurted a "
    "sentence in pure hometown speech; after hanging up I sat stunned. An accent is not "
    "a linguistic habit but an identity marker\u2014more stubborn than an ID card, more "
    "honest than a household register. You can change your registered birthplace, switch "
    "cities, even change nationality, but you cannot fully change your accent. It is a "
    "watermark your birthplace etched onto your vocal cords, the earliest formatting "
    "applied to you. Some linguists say the phonetic environment before age seven "
    "permanently shapes articulatory organs. If true, then inside every throat lives a "
    "seven-year-old self, quietly issuing the sounds that give away our origins at the "
    "moments we think we\u2019ve long since grown up."
),

"j8_identity_078": (
    "I\u2019ve gotten my hair cut at the same barbershop for twelve years. The barber, Old "
    "Chen, never asks \u2018what style?\u2019\u2014for twelve years I\u2019ve gotten the same cut: short, "
    "clean, no maintenance. But Old Chen once said something I can\u2019t forget. The "
    "barbershop mirror is the cruelest mirror in the world, because within two months it "
    "shows your appearance deteriorating from \u2018freshly-cut alertness\u2019 to \u2018needs-a-"
    "haircut weariness.\u2019 Crueler still is the long-term change\u2014he watches regulars "
    "return year after year, hair going from black to gray to white, thick to thin, then "
    "gone. \u2018I cut one old gentleman\u2019s hair for twenty years. At first, jet-black, dense. "
    "Eventually only a ring of white fuzz around the back. The last time, I had nothing "
    "to cut, but he sat in the chair and let me trim slowly for twenty minutes. Leaving, "
    "he looked in the mirror and said: Old Chen, you\u2019re the person who watched me lose "
    "my hair one strand at a time.\u2019 Old Chen said that left him silent a long time. The "
    "relationship between barber and client is a special form of time-witnessing\u2014not "
    "relatives, not friends, but between you there is a mirror faithfully recording "
    "one person\u2019s transformation from youth to old age. \u2018Sometimes I feel I\u2019m not "
    "cutting hair but time. Every snip cuts away another stretch of days that have "
    "passed.\u2019"
),

"j8_identity_079": (
    "When I moved, I had to face a bookshelf accumulated over fifteen years. Clearing "
    "it became self-archaeology\u2014every book\u2019s purchase date and reading state "
    "corresponded to a life phase. The bottom layer: college-era books. Sartre\u2019s Being "
    "and Nothingness, Camus\u2019s The Stranger, half-read philosophy introductions. Pages "
    "yellowed, margins filled with annotations I\u2019d thought profound\u2014looking back, full "
    "of a twenty-year-old\u2019s earnestness and naivete. Middle tiers: ages twenty-five to "
    "thirty, with an obvious shift. Existentialism yielded to pragmatism, philosophy "
    "replaced by management textbooks. Reading traces changed too: no lengthy marginal "
    "notes, just hasty underlines and fluorescent keywords. That version of me no longer "
    "had patience to think slowly, eager to extract immediately usable information. The "
    "top tier: recent years, another turn\u2014types returning to literature and philosophy, "
    "but not Western classics. Eastern Zen, Tang poetry, Japanese aesthetics. These "
    "books bore almost no marks, because I\u2019d learned a way of reading that doesn\u2019t try "
    "to \u2018grasp\u2019 anything\u2014just let words flow past. A bookshelf is a geological "
    "cross-section of intellectual evolution. Bottom: sedimentary rock of passion and "
    "confusion. Middle: a stratum of utilitarianism and anxiety. Top: a thin layer of "
    "calm that settled after countless fractures."
),

"j8_quiet_113": (
    "Grandfather\u2019s purple clay teapot has been in use over forty years. Its body is "
    "covered with a warm patina cultivated by time; your fingers glide over it like "
    "touching solidified time. He never allowed dish soap on it\u2014\u2018Tea nourishes the pot, "
    "the pot nourishes the tea; break that relationship and the pot is just clay.\u2019 "
    "Every morning, grandfather\u2019s first act was boiling water, waiting until just below "
    "scalding, then slowly pouring it into the pot, letting the vessel gently awaken. A "
    "good teapot is like a person\u2014rouse it gently, don\u2019t blast it with boiling water. "
    "Brewing took on ritualistic solemnity in his hands. First rinse the pot\u2019s body with "
    "hot water, then gently pry open the tea canister and use a bamboo scoop for the "
    "right amount. Tea leaves falling into the pot\u2014extraordinarily faint, like dry "
    "autumn leaves on cotton cloth. The first steep was a rinse, poured away; the "
    "second the true beginning, and the pour had to be quick\u2014\u2018steep too long and it "
    "turns bitter, just like a person holding in worries.\u2019 After grandfather passed, "
    "the pot came to me. The first morning I brewed tea alone, lifting the lid, a scent "
    "washed over me\u2014aged tea fragrance and the tobacco traces embedded in grandfather\u2019s "
    "fingerprints. This pot\u2019s warmth came not merely from tea temperature, but from "
    "forty years of palms whose warmth had seeped into every pore of the purple clay."
),

"j8_quiet_114": (
    "Father only practiced calligraphy before dawn\u2014the cleanest moment of the day, all "
    "things still asleep, so the conversation between ink and paper could proceed "
    "undisturbed. Half past four on a winter morning, the world outside pitch black, "
    "his desk lamp the only light on the lane. He would first grind ink\u2014never "
    "ready-made, insisting on slowly grinding an old ink stick on an end inkstone. "
    "Grinding ink was calming the mind: \u2018the ink grinds the person, the person grinds "
    "the ink.\u2019 By the time the consistency was right, the heart had settled too. Father "
    "copied Yan Zhenqing\u2019s \u2018Draft of a Requiem to My Nephew,\u2019 \u2018the second-greatest "
    "running script under heaven.\u2019 Twenty years of copying, never once satisfied. When "
    "Yan Zhenqing wrote that draft, he was filled with grief\u2014his brush strokes carrying "
    "the anguish of a nephew killed in battle. \u2018You can copy its form but not its heart. "
    "Yet you write it again and again, and one day when you experience a similar sorrow, "
    "those dry strokes and flying whites suddenly make sense.\u2019 As a child I didn\u2019t "
    "understand why he rose alone to write while everyone slept. Only later did I grasp "
    "that those predawn hours were a territory of spirit he\u2019d reserved for himself\u2014"
    "there he was no one\u2019s husband, father, or colleague, just a person alone with "
    "brush and ink. When the first morning light entered, he\u2019d spread the characters on "
    "the floor, contemplate them briefly, then fold them away, satisfied or not. Those "
    "characters were never shown to anyone\u2014their meaning lay not in being admired, but "
    "in the quiet act of writing itself."
),

"j8_quiet_115": (
    "Grandmother\u2019s sewing box was a mooncake tin, its lid printed with a faded Chang\u2019e. "
    "Opening it fascinated my childhood self more than any treasure chest. Top layer: "
    "threads of every color, arranged dark to light\u2014a miniature rainbow. Beneath, a row "
    "of silver needles stuck into a hand-sewn cotton pad. Inside the pad: hair "
    "grandmother had saved over years. Hair oil prevents silver needles from rusting\u2014a "
    "trick her mother taught her. The bottom hid odds and ends: spare buttons, elastic, "
    "half a block of tailor\u2019s chalk, a compass missing one leg. Every item had its "
    "origin. The broken compass had been grandfather\u2019s when he did carpentry; after he "
    "died, grandmother tucked it in, though it served no purpose in needlework. Her "
    "mending was exceptional. She could patch a dark coat so seamlessly you\u2019d need a "
    "magnifying glass to detect the stitches. The highest level of mending was not "
    "\u2018making it look unpatched,\u2019 but \u2018letting people see it was patched yet feeling it "
    "looks better than before.\u2019 When my school uniform cuff wore through, she sewed on "
    "a floral edging that covered the hole and became a one-of-a-kind decoration. After "
    "grandmother passed, mother preserved the tin exactly as it was. Sometimes I open "
    "it, not looking for anything\u2014just wanting that blend of cotton thread, rust, and "
    "camphor. The scent of grandmother\u2019s hands. The scent of an entire vanished age."
),

"j8_quiet_116": (
    "The backyard bamboo grove was planted by grandfather some sixty years ago. Bamboo "
    "has an awe-inspiring vitality\u2014every culm above ground connects to an intricate root "
    "network below, all interconnected. Grandfather said bamboo best understands "
    "\u2018communal living\u2019: a single bamboo can\u2019t make a grove, but once roots take hold, "
    "dozens of shoots can emerge overnight. When wind rises, the grove produces a unique "
    "sound\u2014not the rustling of swayed trees, but something more crystalline, almost "
    "metallic. Culms touching one another make delicate \u2018ding\u2019 and \u2018dong\u2019 sounds, as "
    "if someone played an impromptu piece on a lost instrument. In gentle breezes, "
    "scattered light taps; in strong winds, the sounds converge into a dense, "
    "undulating ensemble\u2014the grove itself an enormous wind chime. My favorite thing: "
    "carrying a rattan chair to the grove\u2019s edge on summer evenings, closing my eyes, "
    "listening. As dusk deepened and cicadas faded, the bamboo sound surfaced from "
    "daytime noise, becoming the last soloist of twilight. That sound had a wondrous "
    "soothing power\u2014not uniform like white noise, but with rises and falls, pauses and "
    "surprises, yet every note gentle. It reminded you the world was still turning, wind "
    "still blowing, life still growing, but none required your participation\u2014you need "
    "only sit and listen. The first spring after grandfather\u2019s passing, an extraordinary "
    "number of new shoots emerged, crowded densely, as if the earth were commemorating "
    "the man who planted them."
),

"j8_quiet_117": (
    "After the Frost Descent solar term, strings of orange-red persimmons hang beneath "
    "every village eave, like small lanterns tied to dusty earthen walls. Drying "
    "persimmon cakes requires patience and weather\u2019s cooperation. First: selecting "
    "fruit\u2014too firm and the astringency is strong, too soft and they rot mid-drying. "
    "Grandmother went to the orchard herself, pressing each persimmon\u2019s waist between "
    "thumb and forefinger, judging ripeness through decades of touch. Selected "
    "persimmons are peeled\u2014even the peels kept, spread on bamboo trays to dry for "
    "steeping later. Persimmon-peel water has a faint sweetness and warms the stomach in "
    "winter. Peeled persimmons are tied with cotton string to bamboo poles, a dozen per "
    "pole, propped beneath the eaves. Then the waiting. They dehydrate slowly in dry "
    "autumn wind\u2014sun by day, breeze by night\u2014for roughly three weeks. Color deepens "
    "from bright orange-red, fine wrinkles appear, sugar seeps out and crystallizes into "
    "a thin white frost. Grandmother called this \u2018persimmon bloom\u2019\u2014the most precious "
    "part. It dissolves on the tongue, sweet but never cloying. The anxiety of drying "
    "persimmons is weather. Days of rain mean mold, and the season\u2019s labor is wasted. "
    "So grandmother watched forecasts closely, bringing poles inside at the first "
    "overcast sky. In those autumns, the air was suffused with the persimmon\u2019s clean "
    "sweetness, mingled with rice straw and earth. That was what autumn in one\u2019s "
    "hometown smelled like."
),

"j8_quiet_118": (
    "The last night watchman in the small town was called Old Chen. In childhood memory "
    "he remains a half-lit, half-shadowed silhouette\u2014carrying a dim yellow paper "
    "lantern, tapping a bamboo clapper, walking slowly along the bluestone lane. \u2018The "
    "air is dry and things brittle\u2014mind your candles\u2014\u2019 His voice pitched just enough "
    "to penetrate thin window paper and drift into dreams. The profession was already "
    "nearly absurd by then. The town had electricity, every family an alarm clock. Yet "
    "Old Chen went out punctually every evening, undeterred by wind or rain, as if "
    "guarding not time but some older order. Mother told me he\u2019d been the town\u2019s primary "
    "school Chinese teacher; unable to sit idle after retirement, he took on the "
    "watchman\u2019s duties. He made the lantern himself\u2014bamboo-strip frame, peach-blossom "
    "paper, candle stub in the base. Its light was warm-toned, not sharp like electric "
    "light but soft, ringed with an orange-yellow halo, pushing back a small piece of "
    "darkness. Winter nights were hardest. He\u2019d wrap an oilcloth cloak over his padded "
    "jacket, hang the lantern on a curved bamboo pole. When snow fell heavily, he left "
    "shallow footprints, covered by fresh snow by dawn\u2014as if he\u2019d never been. The year "
    "Old Chen died, the town grew quieter. Never again did that drawn-out \u2018mind your "
    "candles\u2019 drift from the alley\u2019s depths. Only then did people realize the meaning "
    "of his rounds had never been telling time, but the reassurance his lantern gave "
    "countless late nights\u2014the feeling that someone was watching over things."
),

"j8_quiet_119": (
    "That Duan inkstone was passed down from my great-grandfather. Its stone is fine as "
    "an infant\u2019s skin, and at the center of the grinding surface a shallow depression "
    "has formed from over a hundred years of grinding\u2014arc-shaped traces of countless "
    "ink-stick rotations. Father said a good inkstone\u2019s value lies not in carving or "
    "stone quality, but in whether it has been earnestly used\u2014as a person\u2019s value lies "
    "not in appearance but in whether they\u2019ve been polished by the years. Grinding ink "
    "is a forgotten discipline. Most calligraphers today use bottled ink\u2014pour and "
    "write. But father insisted skipping the grinding was skipping calligraphy\u2019s most "
    "important ritual. He compared it to meditation\u2019s prelude: \u2018You\u2019ve begun writing "
    "before picking up the brush. That steady circular motion pulls you back from the "
    "chaotic outside world to this present moment, to the space between you and this "
    "stone.\u2019 I tried it. Grinding ink demands a special patience. Too fast and the ink "
    "is coarse; too slow and it won\u2019t reach the right density. Pressure matters\u2014too "
    "heavy damages the surface, too light produces no ink. It demands a state neither "
    "hurried nor sluggish, neither drifting nor pressing\u2014precisely the state hardest to "
    "maintain. Modern life teaches finishing faster; ink grinding teaches the opposite\u2014"
    "how to slow down, how to find an inner anchor in seemingly meaningless repetition. "
    "As father aged, his hands trembled slightly, yet his grinding remained steady. I "
    "asked why. \u2018Fifty years of this motion. It no longer passes through the brain. The "
    "hand knows how to turn on its own, just as you don\u2019t think about which foot to "
    "step with when you walk.\u2019"
),

"j8_quiet_120": (
    "The last ferry departed at six in the evening. By autumn, the sky had darkened\u2014"
    "only deep gray-blue on the river\u2019s surface, distant mountains reduced to ink "
    "silhouettes. The ferry was an old wooden boat, hull in mottled red lacquer, a "
    "hurricane lamp at the bow swaying and tracing circles of light. Old Zhou the "
    "boatman wore the same faded blue cotton jacket through all seasons, topped with a "
    "bamboo hat. He propelled the boat with a punt pole\u2014bamboo, about three meters, "
    "iron-tipped. He\u2019d plunge it into the riverbed mud, push with both arms, and the "
    "boat glided forward silently. This motion repeated in a steady, hypnotic rhythm. "
    "Passengers on the last ferry were mostly villagers returning from market\u2014empty "
    "baskets on shoulder poles, faces marked with a day\u2019s weariness. No one spoke; only "
    "water and punt pole alternated. Occasionally an egret started from the reeds, "
    "tracing a white arc through the dusk. At the far bank, Old Zhou pressed the bow "
    "against stone steps with his pole, waited until everyone disembarked, then carried "
    "the lamp to the stern, lit a cigarette, and sat on the deck alone. The glow was "
    "especially vivid against the river\u2019s dark tones\u2014the last punctuation mark of dusk. "
    "Years later I returned and learned the crossing had shut down. A bridge upstream; "
    "no one needed the ferry. Old Zhou was long gone. But every evening at dusk, I think "
    "of that boat moving through twilight, that lamp swaying in the river wind. That "
    "image holds a poetry no modern transport can replace\u2014it belongs to a slower era, "
    "when people were still willing to wait for a boat."
),

}


def main():
    with open(INPUT) as f:
        data = json.load(f)

    print(f"{'ID':<45} {'Before':>6} {'After':>6} {'Δ':>5}")
    print("-" * 66)

    modified = 0
    still_over = 0

    for passage in data:
        pid = passage["id"]
        if pid in COMPRESSED:
            old_text = passage["text_en"]
            new_text = COMPRESSED[pid]
            old_wc = len(old_text.split())
            new_wc = len(new_text.split())
            delta = new_wc - old_wc
            passage["text_en"] = new_text
            modified += 1
            marker = " ⚠" if new_wc > 280 else ""
            print(f"{pid:<45} {old_wc:>6} {new_wc:>6} {delta:>5}{marker}")
            if new_wc > 280:
                still_over += 1

    print("-" * 66)
    print(f"Modified: {modified} passages")
    print(f"Still over 280: {still_over}")

    with open(OUTPUT, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nSaved to {OUTPUT}")


if __name__ == "__main__":
    main()
