#!/usr/bin/env python3
"""Compress bloated text_en passages to within word limits.
HSK3: 130 words, HSK6: 230 words, HSK7: 250 words.
Only edits text_en. Prints before/after word counts."""

import json
import sys

# ── HSK3 replacements (limit 130) ──────────────────────────────────

hsk3_replacements = {

"j3_urban_001": "In the center of the city, there's a narrow alley. The bustling main street beside it is already busy at nine, but shops here haven't opened yet. Around ten, the first breakfast shop moves its tables outside. The owner wipes tables while chatting with the shop next door. People here never seem hurried. They say: 'The city runs too fast — our alley chooses to walk slowly.' Every time I walk in, I feel time has slowed down. The outside world is still running, but here you can stop for a bowl of porridge and look at the sky.",

"j3_identity_002": "I've written with my left hand since I was small. The teacher told me to switch to my right hand, saying that was more normal. I tried, but my right-hand writing was ugly and slow. Mom told the teacher: 'Besides using her left hand, she's the same as everyone else.' Growing up, I found a few other left-handed people. We chop vegetables, write, and hold chopsticks with our left hand — though sometimes it's inconvenient. Scissors are designed for right hands and never feel right when I use them. But this is simply who I am. I don't need to be changed.",

"j3_comedy_003": "The company needed a group photo. The photographer said: 'Tall ones in the back, short ones in front.' Xiao Zhang and Xiao Li were about the same height, and neither wanted to stand in front. Xiao Zhang said: 'I'm a little taller than you.' Xiao Li said: 'You're wearing heels — take them off and let's compare.' The photographer waited ten minutes. Finally the manager said: 'You two both stand in the middle — problem solved.' When the photo came out, Xiao Zhang had closed her eyes and asked to retake it. Xiao Li whispered: 'So serious about height, but not about the photo?'",

"j3_urban_008": "On our office building's rooftop there's a small garden, but few people know about it. I found it last summer — too hot, I wanted a quiet place for lunch. The roof had a few potted flowers, two old chairs, and a small table. Since then, I go up every noon. Later I found two others came regularly. The girl from the coffee shop downstairs reads here. The programmer from the 9th floor naps here. We never talk, but we've all made this place our secret garden. The city gets busier, but some places quietly wait for those who need them.",

"j3_urban_009": "Our complex has an orange cat nobody claims. Mornings it waits at Grandma Wang's door for food. At noon it sleeps on a garden chair. Evenings it goes to Uncle Li's to watch TV. Grandma Wang says: 'This is my cat.' Uncle Li says: 'It's obviously my cat.' The property manager says: 'This cat belongs to nobody — it's the complex's cat.' This cat treats everyone's home as its own. It knows whose fish tastes best, whose sofa is most comfortable, who turns off the lights last. It's loved by everyone because it's equally nice to everyone.",

"j3_inst_003": "On the hospital's first floor there's a tiny coffee shop. The owner, a woman in her thirties, used to be a nurse here. She says she knows how hard it is for people waiting for news. Her coffee costs half what it does outside. After ten at night, she gives unsold bread free to families waiting in corridors. Someone said: 'You won't make money this way.' She smiled: 'I worked here for eight years. Besides treating illness, the most important thing is making waiting people less afraid. A cup of hot coffee can't do anything big, but it's warm.'",

"j3_food_001": "Every Chinese New Year, our whole family makes dumplings together. Grandmother's are the prettiest — each one the same size. I learned from her, but mine always come out ugly. Grandmother says: 'How dumplings look doesn't matter — what matters is chatting while making them.' Dad kneads dough, Mom chops vegetables, my sister and I wrap. Grandmother watches, occasionally fixing our poorly wrapped ones. Last year Grandmother got sick. During New Year, I brought dumplings to her. She took a bite: 'Tastes just like mine.' I knew it wasn't the same, but I didn't say so. Those afternoons making dumplings together — that's what I most want to hold onto.",

"j3_observe_023": "On the third floor across from mine, a balcony light stays on every night. I noticed it when I moved here. Rain or wind, that light has never been off. I asked Auntie Wang downstairs. She said: 'That's Old Zhang's light. His daughter works in another city and comes back once or twice a year. He's afraid she won't find home, so he keeps the light on.' Since then, every time I come home at night and see that light, I feel I'm not the only one waiting for someone. That light isn't waste — it's a father's waiting.",

"j3_observe_026": "I took a taxi to the airport. After getting in, I noticed a pillow and blanket on the passenger seat. I asked: 'Do you often sleep in the car?' He said: 'I drive from five in the morning to midnight. When I'm tired, I nap for half an hour.' I asked why. He smiled: 'My daughter is taking the university entrance exam. Tuition is expensive. She has great grades — I don't want money to keep her from a good school.' At the airport, I said: 'Keep the change.' He shook his head: 'The fare is what it is. My daughter says: be honest.' That pillow was pressed flat, but clean.",

"j3_observe_027": "A stray dog comes to the bakery door every afternoon. It doesn't bark or go inside — just lies quietly at the entrance. Every day at three, the baker brings out an unsold bread roll. The dog sniffs it, eats slowly, then leaves. A neighbor asked: 'Do you feed it every day?' The baker said: 'It never comes in to bother me, never rummages through trash. It's more polite than many people. It deserves to be treated well.' One rainy day, the baker put a cardboard box at the door for shelter. After the dog went in, it turned back and looked at the baker.",

"j3_urban_012": "On the street corner there's a tiny bookstore. The sign says: 'Only used books.' The owner, a woman in her fifties, says every used book has been touched by someone — someone tucked in a photo, someone wrote a note in the margin. She finds this more interesting than new books. I once bought a used novel with a movie ticket inside. The date was fifteen years ago. I wondered: what is the person who read this fifteen years ago doing now? The store is dim, but every time you walk in, time seems to slow down. That shop sells other people's stories.",

"j3_mystery_005": "Every night around ten, I hear faint piano music from upstairs — always slow, quiet pieces. My building has poor soundproofing, but other neighbors say they don't hear it. One day I went to check. The sixth floor has only one household — a young person who just moved in. I knocked and asked if he was playing piano. He said: 'Yes, but I'm using headphones — you shouldn't hear it.' He took me to his piano — his headphone jack wasn't fully plugged in, so sound had been coming through the speakers all along. He was embarrassed, but I said: 'It sounds nice.'",

"j3_observe_031": "I took a long train ride from north to south. The scenery kept changing: grey cities, then yellow fields, then green mountains. Most people were on phones or sleeping — only I kept watching the window. An old grandmother across from me said: 'Young man, you're the first person who likes watching outside as much as I do.' She said: 'I take this train every year to see my daughter. The scenery is always a little different — last year that spot was a field, this year it's a building.' The train went farther, the view greener. This was more interesting than arriving.",

"j3_urban_013": "In an old district alley there's a barbershop with one chair, one mirror, and one old barber. A haircut costs fifteen yuan. But people don't come just for the price. The barber doesn't talk while cutting, his hands are steady, and afterward he wipes your face with a hot towel. The whole process takes twenty minutes, quiet. One young man has come since childhood. He says: 'Outside shops are expensive and noisy, always pushing extra treatments. Here they ask nothing — sit down and cut.' The barber overheard and smiled: 'I know your hair better than you do — no need to ask.'",

"j3_inst_006": "Every morning at eight, an old man in a yellow vest helps children cross the road at the kindergarten. He's not a traffic officer — he's a retired teacher. He says: 'This road has a lot of cars, and kids are short — drivers can't easily see them.' He raises his little flag to stop traffic. The kids call him 'Flag Grandpa.' One day it rained hard. He still came, drenched. The principal brought him an umbrella: 'It's raining so hard, you don't have to come.' He said: 'The harder it rains, the more dangerous the road. Who else would come?'",

"j3_food_005": "At one in the morning, most of the city is closed. But one noodle stall still has its light on. The owner sells only one kind — plain noodle soup. The simplest kind: noodles, scallion, soy sauce, a bit of lard. The customers are all late-night workers: taxi drivers, nurses, office workers pulling overtime. Nobody talks, everyone quietly finishes and leaves. But every person says 'thank you' or 'see you tomorrow' on the way out. Someone asked: 'Why not sell more kinds?' He said: 'People who come at night don't need choices. They need a bowl of something hot and simple.'",

"j3_identity_006": "I have a jacket I've worn for eight years. The color has faded, there's a small hole in the sleeve, and the zipper sometimes sticks. Friends tell me to throw it out. But I bought it the year I graduated college, with my first month's salary. I've worn it to interviews, moved houses in it, walked long winter streets in it. It doesn't look good anymore, but it's been through a lot with me. Some say clothes are just clothes. I patched the hole, fixed the zipper. It can last a few more years. Some things, when they get old, should be repaired, not thrown away.",

"j3_observe_033": "An umbrella stand appeared by our complex's main gate. A note reads: 'Take when it rains, return when it doesn't.' Nobody knows who put it there. At first there were three old umbrellas. One rainy day, two were taken. The next day, both came back — plus one new one. Someone thought the old ones weren't great, so they added their own. After a week, there were a dozen umbrellas. All colors, all sizes. The property manager said: 'We didn't arrange this, but it should stay.' That stand is old, but the umbrellas keep growing. This is trust — you give first, and others give back.",

"j3_inst_007": "Every morning at seven ten, my bus always has the same driver — a man in his fifties. He never rushes passengers and waits for people running to catch the bus. One morning he announced: 'Starting tomorrow I'm retiring. Thank you for riding my bus all these years.' The bus went silent. Then an old lady said 'thank you.' More and more people joined. The driver's eyes turned red. He said: 'After twenty years, some of you I don't know by name, but I know the expressions on your faces.' Doing the same thing at the same time every day is itself a kind of promise.",

"j3_observe_035": "While waiting for the bus, an old grandmother asked me the time. Then: 'How often does the 17 come?' About ten minutes. She smiled: 'Thank you. I'm not good with phones.' She told me she was going to the hospital to see her husband. She goes every week — forty minutes by bus. I asked why not have her son drive. She said: 'My son is busy. Riding the bus alone, I can still talk to people. At the hospital I'm always talking — on the bus I want to talk too.' After boarding, she turned back and smiled. Faint, but genuine.",

"j3_observe_037": "On my way home there's a stretch of dark road — the street light was broken. One evening I saw a man with a small truck and ladder fixing it. He climbed up, changed the bulb, and the light came on. The whole road got bright. He climbed down, looked at the light, and nodded. I thanked him. He smiled: 'No need — it's my job. Every night there are many broken lights in the city. I just drive around fixing them one by one.' I watched him drive off and felt that this city's nights are lit up by people like him, one lamp at a time.",

"j3_food_007": "My grandmother makes rice differently from everyone else. She doesn't use a rice cooker — she uses an old iron pot. She washes the rice three times, adds water to the first knuckle of her finger. Her mother taught her this. Iron-pot rice has a crispy bottom layer — crunchy and fragrant. As a child, that crust was my favorite. Grandmother always saved it for me. After growing up, I cook with a rice cooker — the taste is ordinary. Once I went home and Grandmother made iron-pot rice again. I took a bite of the crust and my eyes stung. That taste brought back the childhood kitchen, and Grandmother standing in it.",

"j3_mystery_007": "The morning it snowed, I found small footprints on my balcony. They went from the railing to the flower pot and back. I live on the fourth floor — who would climb up here? Uncle Wang downstairs said he'd seen them too, on the third-floor balcony. We checked the first floor — there too. And next to the flower pot, a small hole with peanuts inside. A squirrel. There's a big pine tree near the complex. The squirrel jumps from the tree to the balconies, burying peanuts in the soil for winter. This little mystery was simple, but when I saw the answer, I laughed.",

"j3_comedy_009": "My dad recently learned phone navigation. But he always argues with the GPS. It says 'turn right,' he says 'there's a wall on the right!' It says 'make a U-turn,' he says 'couldn't you have said that earlier!' The funniest time, the GPS said 'you have deviated from the route.' Dad said angrily: 'I didn't deviate — your route has a problem!' Mom was laughing: 'You're arguing with a machine that can't hear you.' Dad said: 'I know, but saying it makes me feel better.' Every ride in Dad's car, I hear the GPS and Dad's commentary at once — more entertaining than comedy shows.",

"j3_food_008": "Every morning at six, an old man on a tricycle stops at our complex gate to sell tofu. Handmade, traditional methods. He's been making tofu for forty years. I asked why he doesn't sell in supermarkets. He said: 'Supermarkets need packaging and preservatives. My tofu is made today, eaten today.' His tofu costs more than supermarket tofu, but the taste is completely different. He makes only two hundred pieces daily — sells out and goes home. Someone said he should make more. He shook his head: 'Make more, quality goes down. I'd rather sell less than let the taste get worse.'",

"j3_identity_009": "My Chinese name was chosen by my teacher: 'Wenjing' — quiet and gentle. But I'm not quiet at all — I speak loudly, and my laugh is louder than anyone's. For a while I felt the name didn't suit me and wanted to change it. After thinking a long time, I couldn't come up with anything better. Then a Chinese colleague said: 'You're becoming more like your name. Not the quiet type of wenjing, but your own kind — a quiet with strength. When you're not speaking, your eyes are full of thoughts.' A name doesn't have to match who you are — it can be who you're slowly becoming.",

"j3_travel_004": "The bullet train from Shanghai to Nanjing takes just over an hour, but I chose the slow train — four hours. My friend thought I was strange. I said: 'I'm not in a hurry. The slow train lets you see more.' It stops at many small stations. I saw rice paddies, small villages, farmers working in fields. One station had a big tree on the platform with elderly people chatting beneath it. That image made time feel slower. The bullet train is too fast to see what's outside clearly. The slow train lets you watch the world. My friend said: 'You're two hours late.' I said: 'But I saw two more hours of China.'",

"j3_travel_005": "In Chengdu, I stayed at a youth hostel. The room was tiny, but the shared kitchen was big. Every evening it was lively — people cooking, washing dishes, drinking beer. The night I arrived, a Korean girl was making kimchi soup. She noticed me watching and offered a taste. The soup was wonderful — spicy and warm. We ended up eating together. She'd been traveling alone for three months. I asked if she felt lonely. She said: 'At first, yes. But every place I go, I meet new friends in the kitchen. Today I met you.' That night, people from five countries chatted in the kitchen. My happiest evening in Chengdu.",

"j3_food_010": "My Chinese friend invited me to her grandmother's home for dumplings. Grandma lives in a small house in the old city. The table was set with flour and filling. She wrapped dumplings while chatting with me. She asked where I'm from, how many people in my family, whether I like spicy food. She wrapped incredibly fast — in the time I made one, she'd made five. She laughed: 'Forty years of practice.' During the meal, she kept putting dumplings in my bowl. I said enough. She said: 'Young people should eat more.' Those were the best dumplings I've had — every one filled with grandma's care.",

"j3_mystery_009": "I often go to the school library. One day I found a note in an old book: 'If you also like this book, write one character on the last page.' I turned to the last page — four characters: quiet, warm, light, wind. Each in different handwriting. I thought, then wrote 'yuan' — fate — because so many people reading the same book is itself destiny. Two weeks later, the last page had one more character: 'kind.' I don't know who wrote it, but they must be gentle. One book connecting strangers, each leaving a single character — like a quiet conversation.",

"j3_inst_011": "There's a 24-hour convenience store below my building. After eleven at night, it goes quiet. The night clerk is a young man who always wears earphones. Once at midnight I went to buy water. While he rang me up, I noticed an open book. He said: 'Exam prep. I go to class during the day and work here at night. When there are few customers, I study.' I said that must be tough. He smiled: 'The midnight store is quieter than the library. Sometimes no customer comes for a whole hour.' He later passed his exam and told me: 'Thanks for talking to me. The hardest thing about night shifts isn't being tired — it's being alone too long.'",
}


# ── HSK6 replacements (limit 230) ──────────────────────────────────

hsk6_replacements = {

"j6_mystery_001": "At the end of the hutong there's a watch repair shop whose sign has faded to near-illegibility. The owner, surnamed Shen, is seventy-eight — the last watchmaker on this street. When I brought my father's old pocket watch, he studied it and said reverently, 'this is a Shanghai brand movement from the seventies — they stopped making these.' He put on a magnifying loupe and began removing the back cover with a screwdriver thinner than a toothpick. His fingers were wrinkled and callused, but precise — each component placed gently on black velvet, arranged in disassembly order. He pointed to a tiny gear: 'this hairspring has broken. I have the last replacement; once it's used, there truly won't be any more.' The repair took two hours. He barely spoke — only the clinks of metal parts and his steady breathing. After finishing, he held the watch to his ear, then nodded. He charged eighty yuan. I said it was too little. He said, 'repairing watches isn't about money — it's about keeping time moving forward. This watch can still run, and that matters more than me hoarding a spare part.' Walking out I glanced back — he had already lowered his head to the next watch, window sunlight falling on his gray hair like a final gilding on a disappearing trade.",

"j6_food_002": "A good stock requires at least eight hours of slow simmering. My grandmother was a master — her kitchen always had a pot gently simmering. She said the secret isn't what you put in, but how long you're willing to wait. Her ingredients were ordinary: old hen, pork bones, ginger, scallion. But she handled them with ritualistic precision: the hen had to be over two years old, bones hard enough for full flavor. Pork bones were blanched first, then started again in cold water. Ginger was smashed, not sliced. The crucial step was heat control: after boiling, reduce to the lowest flame, keeping the surface barely moving — she called these 'shrimp-eye bubbles,' bubbles only as big as a shrimp's eye. The stock slowly becomes rich, golden, translucent. High heat produces white stock, cloudy and vigorous; low heat produces clear stock, gentle and profound. Like speaking: a loud person makes you hear volume; a soft-spoken person makes you hear content. Grandmother passed away five years ago. I've tried countless times to replicate her stock, but the taste always falls short. What's missing isn't the recipe but the willingness to wait eight hours — and the judgment of 'shrimp-eye bubbles' that only decades can cultivate.",

"j6_explain_001": "Some people feel immediate relaxation and safety upon entering a bookstore. This reaction has a scientific explanation. Paper during slow oxidation releases vanillin, whose scent resembles vanilla. Cellulose degradation in book pages produces trace furan compounds with a warm, caramel-like sweetness. These scents overlap with many people's childhood memories: cake baking in the kitchen, fireside wood, aged books in grandmother's study. Smell is the sense most closely linked to emotional memory — olfactory signals pass directly through the olfactory bulb into the limbic system's hippocampus and amygdala, bypassing rational analysis. Scent-triggered memories are more vivid and emotional than visual or auditory ones. This is why entering an old bookstore might make you think of your grandparents' living room — the association happens so fast your consciousness can't trace its source. You just feel 'safe.' E-books are erasing this experience. An e-book has no scent and cannot serve as a key to emotional memory. In gaining convenience we've lost a sensory dimension — one of the most irreplaceable parts of reading.",

"j6_observe_007": "The night shift security guard at our office building is surnamed Zhou, fifty-three, formerly a geography teacher laid off when his school merged. He never complains, but details reveal a rich inner life. His duty desk always has a leather notebook and a sharp pencil. Once past 2 AM I saw him writing in it. He opened it for me — densely filled with night-shift observations: 'November 7th, a spotlight in the northeast corner started flickering, probably a loose connection.' 'November 12th, more people working late on the 23rd floor, delivery riders came seven times between 9 and 10 PM.' 'November 15th, at 1 AM a cat slipped through the revolving door gap, slept on the sofa two hours, then left.' These records have no practical value — he reports none of it. He's recording this building's nighttime life in his own way. He said, 'when I was a teacher I observed students, now I observe this building. Every building has its own personality at night — this one is quiet but not desolate, like a room that keeps its light on waiting for you to come home.' This guard understands the building more deeply than anyone who works here during the day. He sees its true face after it's shed its daytime pretenses.",

"j6_observe_008": "Our compound's repairman, surnamed Chen, fixes pipes, circuits, air conditioners — everything. He has a habit residents find both strange and endearing: he talks to machines. Fixing an air conditioner, he crouches to listen, then murmurs, 'are you low on refrigerant? Let me check.' He encourages a rusty screw: 'stop being stubborn, brother, loosen up.' After finishing he pats the machine: 'no more acting up now.' I asked why. He said he's talking to himself. 'Fixing things requires concentration. Speaking aloud keeps focus. Once you say it, your hands know what to do — same logic as a doctor asking where it hurts.' He also said something striking: 'no machine breaks down suddenly. There are always signs. You listen to its sounds, feel its temperature, smell for burning — it's been telling you where it's uncomfortable, but most people don't bother to listen.' After he left I looked at the repaired air conditioner and felt, for the first time, as if it really was running contentedly — cared for by someone who understood it.",

"j6_observe_022": "There's an old street lamp downstairs that turns on at 6:23 every evening. I know this because I recorded it for two months — its activation is controlled by a photosensitive sensor, synchronized with sunset. It illuminates a circle roughly eight meters across, edges gradually transitioning into darkness like watercolor blending. Every evening this light is like a small theater's stage: around nine, an orange cat crosses through, always walking the boundary of light and shadow. At ten-thirty, Uncle Wang pauses with his dog, waiting for his elderly golden retriever to sniff around the utility pole. At one in the morning, occasionally a young person checks a map under the lamp, face lit simultaneously by the screen's blue and the lamp's warm light. The street lamp never rushes anyone, nor judges who passes at what hour. It turns on every day, keeping watch over its small territory of light.",

"j6_observe_029": "The office elevator has different personalities at different hours. Between eight and nine, it performs only 'ascending' tasks — lingering on the first floor, filling with workers, releasing a few at each stop. People stare at the floor display, the cab permeated with coffee and breakfast sandwich smell. Around noon, it enters chaotic bidirectional mode: some go down for lunch, others return, stopping at almost every floor. Conversations turn relaxed; someone discusses a nearby restaurant's special. After five-thirty, the elevator enters a slow, weary downward rhythm. Footsteps are no longer rushed; someone leans against the wall and closes their eyes, someone bows their head texting. At eleven at night, riding the empty elevator down alone, you discover its own voice: the trembling of cables, airflow between cab and shaft, the mechanical click of doors closing — sounds masked by human voices during the day, audible only now.",

"j6_city_036": "The bus stop where I wait daily is a small urban archaeological site. The cement ground has been worn into an arc — the trajectory of passengers pacing before the sign. The arc's center aligns with the route board, marking an optimal standing distance. The metal bench has been sat into depressions, armrest paint worn to bare metal by countless hands. The ground near the trash can is darker — a 'pollution halo' from years of beverage spills and gum. Most evocative is the low wall behind the stop: layers of remnant advertisement traces, new covering old, like geological sediment. You can make out phone number formats from over a decade ago on the deepest layers — when mobile numbers had area codes. On a rainy day, I found a 2008 coin wedged in a cement crack at the wall's base, half-covered by dirt. In a few years it'll be completely buried — a miniature fossil belonging to this bus stop.",

"j6_city_037": "Every neighborhood has invisible borders — not administrative lines on maps, but natural limits of activity formed through daily life. I spent months mapping these in my community. First, the 'grocery boundary': north-side residents go to the morning market outside the north gate, south-side residents go to the supermarket outside the south gate, divided roughly along the central road. Residents almost never cross this line, even if prices are better. Next, the 'dog-walking boundary': small-dog owners walk within the compound's garden; large-dog owners go to the riverside path outside. The two groups rarely cross, forming parallel networks. Most subtle is the 'greeting boundary': same-floor neighbors exchange nods, one-floor-apart neighbors occasionally chat, two-or-more floors apart usually ignore each other. Social intimacy drops roughly fifty percent per floor. Nobody deliberately sets these boundaries or is aware of them, but they cover the community like an invisible net, quietly organizing daily trajectories.",

"j6_city_043": "The street I pass to work has a scent calendar. At 6:30 AM, steam from bamboo steamers — flour and yeast mixed with the sweetness of boiling soy milk. At seven, the dry cleaner opens, adding chemical freshness of detergent and iron steam. Around eight, diesel bus exhaust hangs like a gray curtain masking all else. At ten, two restaurants prepare lunch: a Sichuan restaurant's chili spice pours from the exhaust fan; the neighboring Cantonese restaurant's stewed soup permeates slowly — ginseng and goji. Two in the afternoon is the faintest period, only the slight bitterness of plane tree leaves in sunlight. At six, kebab stalls appear; cumin and smoke announce night mode. If a fixed-time scent disappears for several days, that shop is usually renovating or has changed owners — scent is this street's most sensitive business barometer.",

"j6_system_063": "Our compound has an informal patrol team: six retired aunties. No uniforms, no positions, no authorization — yet their control over security exceeds most formal guards. The core figure, Auntie Zhang, has lived here twenty years and can name over eighty percent of residents. Every afternoon they split into two routes: one covering six east-side buildings and the garden, the other five west-side buildings and the garage entrance. The patrol appears casual — strolling, chatting, playing with cats. But they're continuously gathering intelligence. Unfamiliar faces are noted, suspicious plates memorized, unusual sounds trigger alertness. Once they noticed a household in Building 3 hadn't opened windows for three days. They knocked and found Grandma Wang, who lives alone, bedridden with a cold and fever. After this, the compound's attitude shifted from 'meddlesome busybodies' to silent gratitude. Their existence proves a truth: the most effective community security is often not technological, but rooted in human warmth.",

"j6_identity_067": "On my left wrist there is a three-centimeter scar from falling out of a tree at age eight. As a child it was my 'medal' — I'd embellish how high the tree was, how deep the wound. At fifteen the scar became a source of self-consciousness; in summer I'd cover it with my other hand. In college a classmate noticed and asked about it. For the first time I told the real story calmly: one summer afternoon, I climbed the jujube tree in the courtyard to pick dates and stepped on a rotting branch. The wound was bandaged in my grandmother's courtyard; three days passed before I got stitches at the township clinic, which is why the scar is visible. She quietly said: 'Everyone has marks like this — they're evidence that you've lived.' Now I view it as a miniature autobiography only I can read — within three centimeters, it records an eight-year-old's spirit of adventure, a jujube tree that no longer exists, a small town with limited medical facilities, and a grandmother whose hands trembled as she applied iodine.",

"j6_food_086": "Among all late-night foods, a bowl of clear-broth noodles holds the greatest healing power. Not the luxurious kind, but the simplest: noodles in water, a few drops of soy sauce, chopped scallions, and an egg if one's in the fridge. This bowl appears after working overtime, or at 2 AM when insomnia wins and you give up tossing. The minutes standing in the kitchen waiting for water to boil are peculiarly quiet — the entire world asleep, only you and the stove flame awake. The bubbling after noodles enter the pot is extraordinarily clear in the silence. I tried to analyze why this midnight bowl satisfies more than any daytime cuisine. A chef friend said: 'That bowl isn't meant to satisfy taste buds — it's meant to repair something invisible.' Midnight noodles are a ritual. They confirm you're still taking care of yourself, that even at your most exhausted you deserve a steaming bowl. The moment you set down the empty bowl, the day has truly ended.",

"j6_food_089": "My rice cooker has been in use for eleven years. The brand logo has worn beyond recognition, but it still faithfully works every day. It has cooked roughly four thousand pots of rice. It witnessed my transformation from a graduate who couldn't cook into someone who judges water levels by feel. Early on I followed the manual's ratios. Gradually I learned to adjust based on rice variety, age, and humidity — less water for new rice, more for aged, reduce when it's humid. After my mother stayed a week, she said: 'Your rice is better than mine now.' A subtle sense of achievement, like passing some adulthood test. Last year a friend gave me a smart rice cooker with phone control and automatic programs. After two weeks, I switched back. Not because the new one wasn't good, but because the old cooker and I have an understanding — I know its temperament, it knows my taste. Some relationships don't need upgrading; they need continuity.",

"j6_food_091": "Chinese people share an instinctive response when sick: make soup. Cold — mother cooks ginger soup with brown sugar. Stomach upset — grandmother makes congee with pickled radish. Sore throat — the auntie next door brings rock-sugar pear water. These soups may have limited medicinal efficacy, but their psychological healing is real. Last month I caught a cold, lying alone in my rental apartment, scrolling delivery apps without appetite. Finally I used the half white radish, few ginger slices, and handful of scallion whites left in my fridge to cook a pot of clear broth. A warm, familiar aroma filled the kitchen — pulling me back to childhood scenes of my mother at the stove when I was sick. I finished the bowl, broke into a sweat, and the heaviness seemed to lighten. I know this may be purely psychological, but when you're sick, the line between psychological and physiological is blurry. A hot bowl of soup's significance isn't its nutrients, but its message: you are taking care of yourself, or someone is taking care of you.",

"j6_food_096": "Every Sunday morning I make a pancake — not the hurried street-vendor jianbing of workdays, but a homemade version, slowly pan-fried over low heat. This began three years ago on a sleepless Saturday night. I got up at 5 AM, rummaged through the fridge, found flour and two eggs. The first pancake failed — too thick, raw in the middle, burnt at the edges. But between that quiet morning, the empty kitchen, and the imperfect pancake, a harmony formed. Since then, the Sunday pancake has become my most precious weekly ritual. The batter requires patience — flour-to-water ratio, eggs, a pinch of salt, stirring smooth but not over-mixing. During the two minutes waiting for the pan to preheat, I stand at the window watching the empty street. The pancake slowly taking shape in the pan is mesmerizing — liquid batter solidifying, changing color, puffing, becoming a circle. During breakfast I don't check my phone. I quietly savor this food I've made with my own hands. Monday through Saturday belongs to efficiency. These thirty minutes on Sunday belong to me.",

"j6_mystery_097": "My dark blue umbrella has vanished from the office umbrella stand again — the fourth time in three months. What puzzled me was that every disappearance occurred on a Wednesday. I decided to treat this as a deductive exercise. Wednesday is our department's regular meeting day, when outside colleagues enter our area. Only three dark blue umbrellas sit on the stand — mine, Sister Li's from finance, and intern Xiao Chen's. Sister Li's never goes missing because she stuck red tape on the handle. Xiao Chen's hasn't disappeared because his is five centimeters shorter. I suspected someone attending Wednesday meetings grabs an identical umbrella when leaving. The next Wednesday, I tied a yellow ribbon on the handle. At 5 PM my umbrella was intact. The following week I removed the ribbon — gone again. The truth: someone was taking the wrong umbrella, but they brought a new dark blue one every week — meaning they were also losing an umbrella on Wednesday. To me. We had been exchanging umbrellas without knowing it.",

"j6_mystery_101": "For three consecutive Fridays, a bouquet of fresh white daisies appeared in the reception vase, but nobody knew who sent them. Receptionist Xiao Zhou said the flowers were there before her 8 AM arrival — meaning the sender had early access. The first week everyone found it romantic, the second week curiosity grew, the third it became the company's main conversation. I noticed a detail others missed: the water was replaced fresh each time, but the vase hadn't moved — the water stain ring at its base stayed in position. The sender didn't merely place flowers but carefully changed the water and re-arranged the bouquet. This meticulousness suggested deliberate care, not impulsive romance. The fourth Friday, no flowers came. Xiao Zhou seemed disappointed. I later met the company's retired doorman Uncle Zhang in the parking lot, holding white daisies. He said bashfully: 'I just thought the reception desk looked too empty. I was hospitalized last week and couldn't make it.'",

"j6_mystery_105": "For the past month, every morning when I ride the elevator down, it stops on the fourteenth floor — the doors open, nobody enters, then close. This 'empty stop' occurs around 7:40 daily. Property management checked: no malfunction — someone had pressed the button. Who was pressing it, and why not get on? By adjusting my departure times, I finally saw the answer one Thursday. In the fourteenth-floor corridor, a girl of about four was on tiptoe pressing the elevator button. After pressing, she ran back to her half-open door. Seconds later, her mother came out carrying a smaller infant, saw the elevator had arrived, and sighed with relief. The little girl calls the elevator for her mom every morning, so when mom comes out carrying her brother, she doesn't have to wait. Since the girl doesn't leave with mom, the elevator is always empty at fourteen. A four-year-old caring for her mother the only way she could — the gentlest mystery solution I've encountered.",

"j6_mystery_107": "I bought a used copy of 'One Hundred Years of Solitude' at a secondhand bookstore. While reading, a folded letter slipped out from page 137. Written in blue fountain pen, elegant handwriting, unsigned and unaddressed. It read: 'I listened to the song you recommended seven times. On the third listen I cried on the subway, people staring. I didn't wipe my tears because you once said you shouldn't feel ashamed when crying. Returning the book to you; keeping the song.' This letter wasn't for me, but reached a stranger through a crack in time. I deduced: the writer and recipient shared this book — 'returning the book' indicates a loan. The recipient had recommended a song and spoken comforting words about crying, suggesting intimate trust. The letter was placed at page 137, possibly because a passage there moved the writer. I turned to page 137 and found a sentence underlined in pencil: 'Many years later, as he faced the firing squad, Colonel Aureliano Buendia was to remember that distant afternoon when his father took him to discover ice.' The writer may have found something in this sentence that resonated with the song — about time, memory, and inevitable farewell.",
}


# ── HSK7 replacements (limit 250) ──────────────────────────────────

hsk7_replacements = {

"j7_urban_002": "If you want to understand a city's true face, sit in a convenience store at 3 AM. Daytime convenience stores are functional — buy water, pay, leave, under ninety seconds. But a 3 AM convenience store is a different species. Fluorescent light harsh to distortion, the refrigerator hum the only ambient noise. People at this hour are often not here to shop, but to find a public space still lit that won't chase them away. I've seen young workers, pushed past breaking point by overtime, zoning out on window stools with long-cold oden before them. I've seen couples post-fight walk in one after the other, pretending to browse at opposite ends, both waiting for the other to speak first. I've seen elderly people living alone buy milk, then chat with the clerk about weather for twenty minutes. The clerks — mostly night school students — take all this in stride, maintaining calibrated professional indifference. This is the core value of a 3 AM convenience store: not merchandise, but a shelter of 'not being questioned.' In a world where everyone demands you explain yourself, a place that doesn't ask why you're sitting alone at 3 AM is itself a form of tenderness.",

"j7_urban_006": "Most surviving independent bookstores have learned to disguise themselves — becoming cafes or cultural spaces where books are decoration. But I know one that doesn't disguise itself. It's in the semi-basement of an old residential building: no sign, no social media. You must know the door number. The owner, surnamed Yan, formerly an editor, only sells books he's read, each with his handwritten review tucked into the title page. I asked why he doesn't sell online. He shook his head: 'Selling books isn't selling commodities — it's handing something one person has read to another. This act must be face to face; I need to see whether the book suits them.' He refuses certain sales — not snobbery, but genuine mismatch. Once I wanted an existentialist philosophy book. He glanced at me: 'Your current state isn't right for this. Take this essay collection first.' I was annoyed, but a month later realized he was right. The semi-basement is damp, dim, and cramped, but walking in feels like entering a private library with someone standing guard. In an era of algorithmic recommendations, a real person who selects books by intuition may be the last luxury.",

"j7_inst_005": "During my night vigil at the hospital, the 3 AM corridor was like another world. Half the fluorescent lights on, shadows stretched long, occasionally an IV stand's wheels sliding with a sharp sound. Night nurse Xiao Zhao makes rounds every two hours; her footsteps are deliberately light, even shoe-sole sounds suppressed. She said it took three years to master this walk — 'In hospital wards, sound has weight. At 3 AM any tiny sound is amplified tenfold. One door closing might wake a patient who just fell asleep.' She carries a notebook recording each patient's sleep patterns — who startles easily, who sleepwalks, who needs turning to prevent bedsores. This information isn't in medical charts but determines nighttime quality of life. I asked about the biggest challenge of night shift. She thought: 'Not sleepiness — loneliness. In the predawn hospital you're the only one awake, responsible for an entire floor of sleepers. That weight sometimes makes it hard to breathe.' As dawn approached, she stood at the corridor window watching the sky lighten, then said: 'Every time I see daylight I breathe relief — I've safely accompanied them through another night.'",

"j7_mystery_003": "For three months, every Wednesday at exactly 12:05 AM, my landline would ring. I'd pick up; the other end would go silent a few seconds, then hang up. Caller ID showed a local number, but calling back got a busy signal. Its precision was suspicious — every Wednesday, 12:05, ringing five times before auto-disconnecting; if I answered, three seconds of silence before hanging up. I tried unplugging the line before Wednesday; no call came, but the next Wednesday after reconnecting, it rang as usual. I changed my number. The third Wednesday, the new number rang at 12:05. This sent chills — I was certain no one knew my new number. I chose the least rational response: every Wednesday midnight I brewed tea, sat by the phone, picked up, and said 'good night' during the caller's silence before hanging up. In the fourth month, the calls stopped. I still don't know what those three months meant, but I think of those late-night 'good nights' — some things don't need explanation, only someone to respond.",

"j7_observe_048": "I used to be terrible at waiting. Anxious in queues, restless waiting for people, refreshing the delivery tracker every thirty seconds. Then I noticed my neighbor Old Zhao. Retired carpenter, only hobby: fishing. Once I watched him fish all afternoon without a single catch. I asked if he was anxious. Without turning: 'Anxious about what? The fish don't have a clock to punch.' He explained that as a carpenter, after varnishing you wait for it to dry, after gluing a mortise you wait for it to set — rushing is useless. I said I understood but couldn't do it. He asked: 'What do you do while waiting for delivery?' Scroll my phone. He said: 'Then you're not waiting — you're avoiding waiting. Real waiting is doing nothing.' I tried. At a red light, doing nothing. I lasted eleven seconds before pulling out my phone. Second attempt: eighteen seconds. Third time I held out until the green light. Later I told Old Zhao. He was packing up — still zero fish. He said: 'Not bad. Took me thirty years to learn what you picked up in a week.' I said: 'In thirty years, how many fish have you caught?' He thought: 'Enough for one hotpot.' He slung the empty bucket over his shoulder and walked away. Waiting itself was his catch. The fish were a pretext.",

"j7_observe_049": "Before every market trip, my mother writes a grocery list — not on her phone, but in ballpoint pen on old calendar paper. Tight handwriting with parentheses: 'if it's fresh,' 'check the price.' Once I studied a list and found its information density exceeds most corporate project plans. 'Ribs (weekend stew — buy from Butcher Li, not Zhang, last time too fatty)' — time planning, vendor evaluation, quality control. 'Eggs x2 dozen (bring one dozen for Grandma Zhang downstairs, she picked up my delivery last week)' — social-debt settlement. 'Tofu (soft — since Old Wang moved away, buy from east-end stall, not as good but acceptable)' — supply-chain contingency. What puzzles me most is the line at the bottom of every single list: 'The pastry Xiao Ming likes.' I'm thirty-five. I haven't lived at home in twelve years. The last time I ate that pastry was probably high school. But that line has never disappeared. Once I said: 'Mom, I don't eat pastries anymore.' She glanced at me and kept writing: 'I'll buy some, in case you come home.' I pressed a few used lists inside a book. Some items she can no longer find, some stalls no longer exist. But 'the pastry Xiao Ming likes' is still there — the only item that never gets a discount comparison, a substitute, or a price check.",

"j7_observe_054": "My wife and I have been in a laundry-folding dispute for nine years. Her method: sleeves folded, body folded, then once more — all identical, lined up like a MUJI display. My method: split between 'approximate fold' and 'crumple into a ball,' depending on mood. She considers my method a crime against fabric. I maintain nobody can tell whether a shirt was carefully folded or thrown in a dryer. One day I ran an experiment: folded three T-shirts carefully, crumpled three, wore each out. Six coworkers spotted no difference. I showed my wife the photos, thinking I'd won. She said: 'I don't fold laundry for other people to see.' Then she finished a stack and stood before the closet gazing at it. That look wasn't checking neatness. It was someone appraising their own work. Then I understood: her life is out of control in many ways — work, the kid getting sick, her mother — but this closet is the one territory she fully commands. Since then I occasionally fold carefully too. It still looks terrible. But she laughs every time. That laugh isn't because I fold well — it's because I've stopped trying to prove she's wrong.",

"j7_city_069": "Next door's renovation has been going on four months. Contract said two. I can now identify by sound what they're doing: crisp clinking is tile-chipping, muffled thuds wall-demolishing, sustained buzzing the circular saw. I can gauge the workers' moods — smooth work produces steady rhythm; problems produce a pause, a curse, then resumption. My communication with the neighbors has been entirely through the wall. I know they fought about tile color three times: she wanted gray, he thought white was classic. They settled on gray-white — deduced from a worker muttering, 'What color even is this.' I know they went forty percent over budget, because the husband called his mother from the balcony to borrow money. I know the foreman's surname is Liu, he has three workers, and the newest one gets yelled at constantly. The new guy is Xiao Ma — 'Xiao Ma come look at how you sanded this corner' is a sentence I've heard two hundred times. The renovation ended last week. Next door went quiet. The next morning at eight-thirty, I reflexively braced for the drill — waited five minutes before realizing it wasn't coming. Four months of noise had become part of my life's rhythm. I don't know where Xiao Ma ended up.",

"j7_city_071": "In the center of our compound stands a massive camphor tree, said to be sixty or seventy years old. Its trunk requires two adults to embrace, its canopy spreading like an opened umbrella, shading nearly half the courtyard. This tree is the compound's public living room. In spring, elders sit on benches sunbathing while children search for insects between roots. In summer, it provides the best shade — wind through its leaves cools naturally, fresher than any AC. In autumn, leaves carpet the ground in gold; the property management sweeps twice daily but can never finish. In winter, only stout branches remain, like an ink-wash painting. A few years ago, a developer wanted to build a car shelter, requiring the tree's removal. Every resident opposed it. Not from environmental awareness or feng shui, but because this tree existed in everyone's memories. Summers cooling under it, afternoons playing cards, evenings of proposals, weekends teaching children to ride bicycles. A tree is a community's shared memory storage. Cutting it would be like formatting the compound's hard drive. The car shelter wasn't built. The developer conceded — not because they understood, but because they couldn't withstand unanimous opposition. The tree remains.",

"j7_observe_020": "I rode a taxi whose driver was a quiet middle-aged man. Classical music was playing. I asked if he liked it. He said no, but classical music has no lyrics, so he won't sing along; singing means distraction, distraction means accidents, accidents mean fines — so classical music is an economic decision. I found this logic impeccable. Near the destination he said: 'I've driven twenty years, carried hundreds of thousands of people. Know who impressed me most?' I guessed celebrities, rich people, drunks. He shook his head. 'People who say: not in a hurry, taking the long way is fine.' Such passengers numbered under ten in twenty years. But every one would say something profound in the car. His theory: these people had abandoned efficiency, making time luxurious, and in luxurious time people open up more easily. 'Every passenger's first words are either hurry up or a destination. Destination and speed — that's all modern people are.' I asked: 'What if I said not in a hurry right now?' He glanced at the meter: 'You could, but you've arrived. Fourteen-fifty.' I paid and got out. After two steps I looked back — his car hadn't moved, window half open, classical music drifting out. Waiting for the next passenger. Almost certainly someone who'd say 'hurry up.'",

"j7_travel_002": "In an era when high-speed rail covers nearly every line, I chose a green-skin train from Chengdu to Kunming — over twenty hours. No WiFi, seats that couldn't recline, intermittent air conditioning. But precisely because of these inconveniences, the trip acquired a peculiar texture. The train stopped and started, passing small stations unmarked on any map. At each stop people boarded carrying woven bags or bamboo baskets, filling the carriage with mixed smells — instant noodles, tangerines, tobacco, earth. Across from me an old woman with her grandson pulled out homemade pickled radish and shared it around. I took a piece; the sourness made me squint. She laughed: 'That's how radish tastes where we're from.' Outside, the scenery kept shifting — rapeseed fields, rolling hills, gorges and tunnels alternating. When the train plunged into a tunnel, the window became a black mirror reflecting faces. A young man with a guitar dozed; a couple leaned together reading the same book. Time on the green-skin train is slow, thick, a rhythm nearly forgotten. By the time we reached Kunming it was dawn. Walking out, I felt I hadn't just arrived at a destination but passed through a stretch of time that is disappearing.",

"j7_quiet_111": "When I was little, living at my grandmother's house by the river, every morning I was woken by a peculiar silence — not an alarm, not a rooster, but the feeling of the world growing still when fog descended. Opening the window, the river surface was draped in milky-white mist; houses and trees on the opposite bank were blurred silhouettes, like an unfinished ink wash painting. Grandmother said the fog was the river breathing. At night the water was warmer than the air, and rising vapor condensed to form fog. In the plainest language, she had given me an accurate meteorological explanation. Sounds in the fog changed too. The roosters across the bank disappeared, replaced by finer nearby sounds — dewdrops falling from eaves, the neighbor's cat stepping on damp stone, river water lapping shore rocks. Fog acted like a filter, absorbing distant sounds and amplifying near ones. Around seven or eight, after the sun climbed higher, the fog dissipated rapidly. First the rooftops emerged, then treetops, then the entire river surface turned clear and luminous. After Grandmother passed, I never returned to that town. But every foggy morning, in any city, I think of that river and that tender silence within the fog.",

"j7_quiet_112": "I have worked at the city library for seventeen years. The quietest spot is not the reading room — that has pages turning, the AC hum, the occasional lowered phone call. The truly quietest place is the foreign periodicals section at the far end of the third floor's east wing. Outside the window stands an enormous ginkgo tree blocking nearly all light. The shelves display expired French and German journals nobody reads. But this corner has preserved a precious stillness — not the dead silence of emptiness, but quiet with depth, settled through countless afternoons. I sit there during lunch breaks. By the window is an old rattan chair left by some former director, its cushion pressed into human shape. In autumn, when the ginkgo leaves turn yellow, afternoon sunlight filters through golden leaves and spills inside, dyeing the corner amber. That light has a hypnotic power: it lets you relax without realizing it, thoughts becoming slow and transparent. A colleague asked why I didn't transfer to the new branch — newer facilities, more space. I said: 'The new branch doesn't have my rattan chair, or my ginkgo tree.' Some things cannot be moved. They belong only to that corner and the time spent there.",

"j7_quiet_113": "In my compound, there is an old gentleman who walks his dog. I don't know his surname, his building, or his Shiba Inu's name. But every morning around seven-thirty, on my way to the subway, I see him on the gravel path through the garden. Our communication is a mutual nod. No 'good morning,' no 'nice weather' — just a slight inclination of the head, then each going our way. This has continued for three years. This brief ritual gave me a stability difficult to put into words. As long as I could see him when I stepped out, today would be a normal, safe day. Once I returned from a two-week business trip. The first morning back, I saw him at the usual spot; he nodded as always. A warmth welled up — not ardent emotion, but a low-temperature, thermostat-like steadiness. Later he was absent for several consecutive days, and a faint worry crept in. On the fourth morning he reappeared, this time with a black Labrador beside him. When he nodded, his gaze had softened, carrying something I couldn't read. Perhaps the Shiba had gone. We still didn't speak. But that day's nod was half a beat slower, as if we had both lingered an extra instant within that tiny gesture.",

"j7_quiet_114": "Father had a fixed routine for brewing tea that never changed over decades. First scald the pot, pour it out, add leaves, fill to seven-tenths, lid on, wait. He said the most crucial thing isn't water temperature or leaf quality, but patience. Pour too hastily and the leaves haven't unfurled — the flavor is shallow, astringent. Wait too long and it turns bitter. That moment of just right requires experience and intuition alike. As a child I didn't understand why he spent so much time on tea. He didn't argue, just handed me a cup. I took a sip and it was different from instant — not simply tastes-good-or-not, but a difference in texture, like hand-woven versus machine-woven cloth. Later, when I started brewing myself, I understood his ritual. The process is the purpose. When you stand waiting for leaves to unfurl in hot water, you are forced to slow down. Attention pulls free from tangled thoughts and focuses on the small changes inside that pot. Curled leaves open, color shifting from dark brown to jade green, the water gradually deepening. The process is quiet, slow, irreversible — like some miniature turning of the seasons. Father passed away last year. Each morning I brew tea in the purple clay pot he left behind. Decades of tea stains line the walls; they say such a pot yields faint fragrance even with plain water. I choose to believe it.",

"j7_quiet_115": "Sorting through Mother's belongings, I found a letter at the back of her vanity table drawer. The envelope bore an address and stamp, but had never been mailed. The addressee was a name I'd never heard: Zhou Ruolan. The paper was yellowed, ink faded — written at least twenty years ago. I hesitated but opened it. The contents were ordinary: Mother telling Zhou Ruolan she'd been learning to bake, that her husband had been promoted, that her daughter had started elementary school. The letter ended: 'I often think of those nights we stayed up talking in the dormitory. The future seemed so far away then; looking back, those nights were the most precious. I hope all is well with you.' I tried the address — demolished. The name — no results. Why had Mother written but never sent it? Perhaps the address was uncertain. Perhaps she reread it, planned to revise, and let procrastination win. Perhaps she never intended to send it — writing was the purpose, like speaking to a distant shadow, needing no reply. I refolded the letter and placed it back.",

"j7_quiet_116": "Old Mr. Zhao downstairs practices calligraphy with water on the plaza every morning. He uses a sponge brush, dips it in clear water, and writes large characters on gray concrete. Within minutes the strokes disappear as the water evaporates. He has written for decades without leaving a single character behind. Once I watched for a full hour. His rhythm was distinctive — not uniform, but breathing. The opening stroke was slow, the brush tip pausing as if gathering force. Then it accelerated, gliding smoothly, like a river meeting a slope. At turning points it decelerated, even stopped, then turned at a precise angle. At the closing stroke, the tip rose slowly, tracing an invisible arc through air. Every character was one complete breath: inhale, hold, exhale. I asked why he didn't use ink on paper, so something would remain. He looked at the vanishing characters and said: 'The last stroke of this yong is about to vanish. Do you think it has disappeared?' I said if you can't see it, it should count as gone. He shook his head: 'You just saw it. You remember it. Then it hasn't disappeared. Calligraphy's meaning isn't where the character rests, but the moment of writing — the accord between heart, hand, breath, and character. That instant is eternal. It doesn't need paper to prove it.'",

"j7_quiet_117": "The Kyoto inn room had a shoji door — wooden frame covered in washi paper. During the day, sunlight passed through, filtered into soft, even diffused light. But what moved me was the night. I woke past two in the morning; the room was dark, but on the shoji appeared a wash of silver-white light. Moonlight. It had passed through courtyard maples, been cut into fragments by branches, then filtered through washi into hazy, flowing light and shadow. When the wind blew, maple branches swayed and the patterns shifted slowly, like a silent film projected on a white screen. I lay on the tatami watching for a long time. This light reminded me of yugen — the Japanese aesthetic of beauty that is suggestive, never fully revealed. Moonlight is already beautiful, but filtered through paper and carved by tree shadows, it becomes something else: diminished in brightness, deepened in layers. As in a poem, the finest image is not stated directly but wrapped in negative space. When I checked out, the elderly woman at the front desk asked how my stay was. I said: 'The moonlight was wonderful.' She smiled, as if to say: you saw it.",

"j7_quiet_118": "I have a habit: finishing a notebook's last page always brings a sense of ceremony. Not because the last page contains anything special — usually meeting notes or scattered thoughts. The ceremony comes from ending itself. A notebook fills in three to four months. Of what happened, some things were recorded, some not. Flipping back, the problem troubling you three months ago has been forgotten; key points from last month's meeting now read as unremarkable. Time is a marvelous editor — continually reshuffling priorities, pushing what felt important to the margins, elevating overlooked details. What I treasure most is not formal notes but margin doodles — squares drawn while zoning out in a meeting, curves scrawled while waiting for a call, a flower sketched when I was in a good mood. These traces are more honest than written words because they were left unconsciously, without editing. After the last page, I close the notebook and place it in a cardboard box on my bookcase's highest shelf. Over twenty are in there, in chronological order. I never go back through old ones, but knowing they're there brings peace. As if the past, though it can't return, has not completely dissipated — compressed between yellowing pages, quietly waiting.",

"j7_quiet_119": "In the courtyard of our old family home stands a parasol tree, planted by my grandfather's generation. Every autumn the leaves turn yellow, carpeting the courtyard in gold. When I was small, Father would sweep the fallen leaves each morning into a bamboo basket. I asked why he didn't wait until all leaves had fallen — a new layer would fall the next day. He said: 'Sweeping leaves isn't about keeping the courtyard clean. The courtyard will never be clean, because the tree is alive, still shedding. Sweeping is about greeting this tree — telling it: I see you, I know another day has come.' That answer baffled me then. But now I live in this courtyard, and each morning I pick up the broom and understand. Sweeping leaves is not cleaning but a ritual of time. Every leaf differs in shape, color, dryness. Fresh leaves carry a soft curve and lingering green; leaves down several days have curled crisp, crunching underfoot. You can feel the season's advance: September's leaves are faintly yellow at edges, October's fully golden, November's begin to brown. The swish of the broom across stone paving, joined by a new leaf spiraling down, composes a quiet autumn morning. Father never taught me aesthetics or philosophy, but he taught me to sweep fallen leaves. Looking back, perhaps those are the same thing.",

"j7_quiet_120": "While moving, I dug out an old key from a drawer. Not for my current place, nor the one before — the key to my first apartment after graduating college. The landlord gave me a spare; when I moved out I returned one, the other somehow stayed, following me through four moves. This key is slightly heavier than ordinary. Not from different material, but from use — edges worn smooth and round, sitting in the hand with a warm, polished texture like a river pebble. The teeth have grown shallow; it probably wouldn't open anything now. But I've never thrown it away. That apartment was in an old building in the south of the city. Twenty square meters: bed, desk, wardrobe, all crammed in. Shared kitchen at the corridor's end. Pipes leaked constantly; the landlord forever promising repairs next week. But it was the first space that was mine — not parents' home, not dormitory, but a room rented with money I earned, where I could lock the door and shut the world outside. Every evening, the instant I inserted the key and heard that 'click' was the most reassuring moment of the day. That sound meant: everything out there is temporarily none of your concern. The house I live in now is larger, with a fingerprint lock that opens silently. Convenient, but something is missing.",
}


def process_file(filename, replacements, limit):
    with open(filename) as f:
        data = json.load(f)

    changes = []
    for i, passage in enumerate(data):
        pid = passage["id"]
        if pid in replacements:
            old_text = passage["text_en"]
            new_text = replacements[pid]
            old_wc = len(old_text.split())
            new_wc = len(new_text.split())
            if new_wc > limit:
                print(f"  WARNING: {pid} still over limit: {new_wc} > {limit}")
            changes.append((pid, old_wc, new_wc))
            passage["text_en"] = new_text

    with open(filename, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    return changes


def main():
    configs = [
        ("passages_hsk3.json", hsk3_replacements, 130),
        ("passages_hsk6.json", hsk6_replacements, 230),
        ("passages_hsk7.json", hsk7_replacements, 250),
    ]

    for filename, replacements, limit in configs:
        print(f"\n{'='*60}")
        print(f"  {filename}  (limit: {limit} words)")
        print(f"{'='*60}")
        changes = process_file(filename, replacements, limit)
        total_before = 0
        total_after = 0
        for pid, old_wc, new_wc in changes:
            saved = old_wc - new_wc
            print(f"  {pid:30s}  {old_wc:3d} -> {new_wc:3d}  ({saved:+d})")
            total_before += old_wc
            total_after += new_wc
        total_saved = total_before - total_after
        print(f"  {'':30s}  ----    ----")
        print(f"  {'TOTAL':30s}  {total_before:4d} -> {total_after:4d}  ({-total_saved:+d})")
        print(f"  Passages edited: {len(changes)}")

    # Verify no passages remain over limit
    print(f"\n{'='*60}")
    print("  VERIFICATION")
    print(f"{'='*60}")
    all_clean = True
    for filename, _, limit in configs:
        with open(filename) as f:
            data = json.load(f)
        over = [(p["id"], len(p["text_en"].split()))
                for p in data if len(p["text_en"].split()) > limit]
        if over:
            all_clean = False
            print(f"  {filename}: {len(over)} STILL OVER LIMIT:")
            for pid, wc in over:
                print(f"    {pid}: {wc}")
        else:
            print(f"  {filename}: ALL UNDER {limit} words")
    if all_clean:
        print("\n  All passages within limits.")


if __name__ == "__main__":
    main()
