# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "/Users/jasongerson/mandarin/content_gen")
from gen_helpers import *

P = []

P.append(passage("j8_observe_013", "The Etiquette of Umbrella Sharing", "共伞的礼仪", 8,
    "下雨天，两个人共用一把伞时，伞的倾斜角度是一个精确的人际关系测量仪。情侣之间，伞自然地偏向更矮的那一方，高的那个人心甘情愿地让自己的半边肩膀淋湿。同事之间，伞保持严格的中线对称，两个人各淋一半，谁也不占便宜。最微妙的是刚认识的人之间：撑伞的人会把伞略微偏向对方，这是一种无声的善意表达；而对方如果把身体稍微靠近撑伞者，就是接受了这份善意。如果对方保持距离，宁可淋湿也不靠近，那就是一种礼貌的拒绝。我曾经在地铁站出口观察了一整个雨天，发现共伞行为中蕴含着一套完整的非语言沟通系统。最让我感动的场景是一位父亲送女儿上学，伞几乎完全罩在女儿头上，自己整个背部都被雨浸透了。女儿似乎完全没有注意到这一点。或许最深沉的爱就是这样：你把所有的庇护给了对方，而对方永远以为天没有在下雨。",
    "Xià yǔ tiān, liǎng gè rén gòng yòng yī bǎ sǎn shí, sǎn de qīngxié jiǎodù shì yī gè jīngquè de rénjì guānxì cèliángyí.",
    "On rainy days, when two people share an umbrella, its angle of tilt is a precise interpersonal-relationship gauge. Between couples, the umbrella naturally tilts toward the shorter one, the taller person willingly letting half their shoulder get wet. Between colleagues, the umbrella maintains strict centerline symmetry, each person equally dampened. Most subtle is between new acquaintances: the umbrella holder tilts slightly toward the other, a wordless expression of goodwill; if the other leans in slightly, they accept that goodwill; if they maintain distance, preferring to get wet rather than move closer, that's a polite refusal. I spent an entire rainy day observing at a subway exit and found umbrella-sharing contains a complete nonverbal communication system. The most moving scene was a father walking his daughter to school, umbrella almost entirely over her head, his entire back soaked. She seemed completely unaware. Perhaps the deepest love is like this: you give all the shelter to the other, and they forever believe it isn't raining.",
    mc("伞的倾斜角度在文中象征什么？", "What does the umbrella's tilt angle symbolize?",
       [o("天气的严重程度","tiānqì de yánzhòng chéngdù","Weather severity"),
        o("两个人之间关系的亲密程度和权力结构","liǎng gè rén zhījiān guānxì de qīnmì chéngdù hé quánlì jiégòu","The intimacy and power structure between two people",True),
        o("伞的质量好坏","sǎn de zhìliàng hǎo huài","Umbrella quality"),
        o("哪个人更高","nǎge rén gèng gāo","Who is taller")], 0.45),
    mc("父亲送女儿上学的场景，作者最感动的是什么？", "What moved the author most about the father walking his daughter to school?",
       [o("父亲的伞太小了","fùqīn de sǎn tài xiǎo le","The father's umbrella was too small"),
        o("父亲默默承受淋湿而女儿浑然不知","fùqīn mòmò chéngshòu lín shī ér nǚ'ér húnrán bù zhī","The father silently endured getting soaked while his daughter was completely unaware",True),
        o("女儿不关心父亲","nǚ'ér bù guānxīn fùqīn","The daughter doesn't care about her father"),
        o("应该买一把更大的伞","yīnggāi mǎi yī bǎ gèng dà de sǎn","They should buy a bigger umbrella")], 0.4),
    mc("文末「对方永远以为天没有在下雨」的含义是什么？", "What does 'they forever believe it isn't raining' mean?",
       [o("下雨天也可以出门","xià yǔ tiān yě kěyǐ chūmén","You can go out on rainy days too"),
        o("最深的爱是让被爱者感受不到任何牺牲的痕迹","zuì shēn de ài shì ràng bèi àizhě gǎnshòu bú dào rènhé xīshēng de hénjì","The deepest love makes the loved one feel no trace of sacrifice",True),
        o("孩子不懂天气","háizi bù dǒng tiānqì","Children don't understand weather"),
        o("伞的防雨效果很好","sǎn de fáng yǔ xiàoguǒ hěn hǎo","The umbrella's rain protection is excellent")], 0.5)))

P.append(passage("j8_identity_003", "The Language of Hands", "手的语言", 8,
    "我母亲的手告诉了我她的整个人生，尽管她自己从未主动提起。她的右手食指有一个硬茧，那是三十年缝纫留下的印记——她在服装厂做了一辈子车工。左手无名指的关节略微变形，那是类风湿的痕迹，每到阴雨天就会隐隐作痛。两只手的手背都布满了细密的皱纹和几处淡褐色的老年斑，但手掌心仍然温暖而柔软。每次我回家，她会用这双手端一碗热汤放在我面前，那个动作里有一种精准的温柔——碗不会太烫，汤不会洒出来，放下的位置刚好在我右手够得到的地方。我父亲的手完全不同：粗糙、厚实，指甲缝里永远有洗不净的机油痕迹。他是一名修理工，那双手拆装过上万个零件。但我记忆中最清晰的画面是他用那双油渍渍的手小心翼翼地帮我粘好一架摔断翅膀的纸飞机。手是一种不会说谎的传记：它记录了一个人做过的所有工作、承受过的所有磨损，以及在所有粗糙之下仍然保留的柔软。",
    "Wǒ mǔqīn de shǒu gàosu le wǒ tā de zhěnggè rénshēng, jǐnguǎn tā zìjǐ cóng wèi zhǔdòng tíqǐ.",
    "My mother's hands told me her entire life, though she herself never spoke of it. Her right index finger has a hard callus—the mark of thirty years of sewing, a lifetime as a garment factory seamstress. Her left ring finger's joint is slightly deformed from rheumatism, aching faintly on rainy days. Both hands' backs are covered with fine wrinkles and pale brown age spots, but her palms remain warm and soft. Each time I come home, she brings a bowl of hot soup with these hands, placing it before me with precise tenderness—the bowl not too hot, the soup not spilling, set exactly where my right hand can reach. My father's hands are entirely different: rough, thick, fingernail creases permanently stained with engine grease. He is a mechanic who has disassembled tens of thousands of parts. But my clearest memory is him using those greasy hands to carefully glue back the broken wing of my paper airplane. Hands are a biography that cannot lie: they record all the work a person has done, all the wear they've endured, and all the softness still preserved beneath the roughness.",
    mc("母亲端汤的动作为什么被描述为「精准的温柔」？", "Why is the mother's soup-serving gesture described as 'precise tenderness'?",
       [o("她曾接受过专业的服务培训","tā céng jiēshòu guò zhuānyè de fúwù péixùn","She received professional service training"),
        o("每个细节都经过无意识的关怀考量——温度、角度、位置都恰到好处","měi gè xìjié dōu jīngguò wúyìshi de guānhuái kǎoliáng——wēndù, jiǎodù, wèizhì dōu qiàdào hǎochù","Every detail is unconsciously calibrated with care—temperature, angle, position all just right",True),
        o("母亲在工厂养成了精确操作的习惯","mǔqīn zài gōngchǎng yǎngchéng le jīngquè cāozuò de xíguàn","The mother developed precise habits from factory work"),
        o("因为汤很贵不能浪费","yīnwèi tāng hěn guì bù néng làngfèi","Because the soup is expensive and shouldn't be wasted")], 0.45),
    mc("作者说「手是一种不会说谎的传记」，核心含义是什么？", "What is the core meaning of 'hands are a biography that cannot lie'?",
       [o("通过看手相可以预测命运","tōngguò kàn shǒuxiàng kěyǐ yùcè mìngyùn","Palm reading can predict fate"),
        o("手的物理状态忠实记录了一个人的劳动、经历和情感","shǒu de wùlǐ zhuàngtài zhōngshí jìlù le yī gè rén de láodòng, jīnglì hé qínggǎn","The physical state of hands faithfully records a person's labor, experience, and emotions",True),
        o("手比脸更能反映年龄","shǒu bǐ liǎn gèng néng fǎnyìng niánlíng","Hands reflect age better than faces"),
        o("手的保养很重要","shǒu de bǎoyǎng hěn zhòngyào","Hand care is important")], 0.45),
    mc("父亲用油渍渍的手修纸飞机这个画面的意义是什么？", "What is the significance of the father fixing the paper airplane with greasy hands?",
       [o("父亲的修理技术很好","fùqīn de xiūlǐ jìshù hěn hǎo","The father has good repair skills"),
        o("粗糙的劳动者之手依然保有对孩子的细腻温柔","cūcāo de láodòngzhě zhī shǒu yīrán bǎo yǒu duì háizi de xìnì wēnróu","Rough laborer's hands still retain delicate tenderness for their child",True),
        o("纸飞机对孩子很重要","zhǐ fēijī duì háizi hěn zhòngyào","The paper airplane was important to the child"),
        o("修理工可以修理任何东西","xiūlǐ gōng kěyǐ xiūlǐ rènhé dōngxi","Mechanics can fix anything")], 0.4)))

P.append(passage("j8_comedy_003", "The Science of Queue Jumping", "插队的科学", 8,
    "在任何需要排队的场景中，插队者都发展出了一套令人叹为观止的社会工程学技巧。我把这些技巧大致分为四个流派。第一流派是「无辜融入派」：他们先站在队伍旁边假装看手机或系鞋带，然后趁旁边的人注意力分散时自然地「融入」队列，表情平静到你会怀疑是自己记错了队伍的顺序。第二流派是「熟人寄生派」：他们找到队伍中任何一个可能认识的人，热情地打招呼，然后以「聊天」为名义站在那个人旁边，等前面的人走了就顺势补上空位。第三流派是「弱者特权派」：抱着孩子、拄着拐杖或表现出极度匆忙的样子，利用人们的同情心获取默许。第四流派最为高级，我称之为「规则重新定义派」：他们会指出队伍中某个不明显的分叉点，声称那里是另一条队伍的起点，然后在自己创造的「新队伍」中排在第一位。面对这些技巧，排队者的反应也很有趣：百分之八十的人选择沉默忍受，百分之十五的人用眼神表达不满，只有百分之五的人会真正出声制止。这个比例本身就是人性的缩影。",
    "Zài rènhé xūyào páiduì de chǎngjǐng zhōng, chāduìzhě dōu fāzhǎn chū le yī tào lìng rén tàn wéi guānzhǐ de shèhuì gōngchéngxué jìqiǎo.",
    "In any queuing scenario, queue-jumpers have developed a breathtaking set of social engineering techniques. I classify these into four schools. The first is the 'Innocent Merger': they stand beside the queue pretending to check their phone or tie a shoe, then when nearby people's attention lapses, naturally 'merge' into the line, expression so calm you doubt your own memory of the queue's order. The second is the 'Acquaintance Parasite': they find anyone remotely familiar in the queue, greet them enthusiastically, then stand beside them under the guise of 'chatting,' filling the gap when the person ahead moves on. The third is the 'Vulnerability Privilege': holding a child, using a cane, or displaying extreme urgency to leverage sympathy for tacit permission. The fourth and most advanced I call the 'Rule Redefiners': they identify an ambiguous fork in the queue, claim it's where another queue begins, then place themselves first in the 'new queue' they've created. Queuers' responses are equally interesting: eighty percent silently endure, fifteen percent express displeasure through eye contact alone, and only five percent actually speak up. That ratio itself is a microcosm of human nature.",
    mc("作者将插队者分为四个流派的目的是什么？", "What is the purpose of classifying queue-jumpers into four schools?",
       [o("教读者如何插队","jiāo dúzhě rúhé chāduì","Teaching readers how to cut in line"),
        o("用幽默的分类体系揭示人际行为中的策略性和表演性","yòng yōumò de fēnlèi tǐxì jiēshì rénjì xíngwéi zhōng de cèlüèxìng hé biǎoyǎnxìng","Using a humorous classification system to reveal the strategic and performative nature of interpersonal behavior",True),
        o("批评社会秩序的混乱","pīpíng shèhuì zhìxù de hùnluàn","Criticizing social disorder"),
        o("呼吁加强排队管理","hūyù jiāqiáng páiduì guǎnlǐ","Calling for better queue management")], 0.45),
    mc("文末的比例数据「80%沉默、15%眼神不满、5%出声」说明了什么？", "What does the ratio '80% silent, 15% eye contact, 5% speak up' illustrate?",
       [o("中国人特别能忍耐","zhōngguó rén tèbié néng rěnnài","Chinese people are especially patient"),
        o("大多数人在面对不公时倾向于沉默而非对抗","dàduōshù rén zài miànduì bùgōng shí qīngxiàng yú chénmò ér fēi duìkàng","Most people tend toward silence rather than confrontation when facing unfairness",True),
        o("插队行为其实不太严重","chāduì xíngwéi qíshí bú tài yánzhòng","Queue-jumping isn't actually very serious"),
        o("排队制度需要改革","páiduì zhìdù xūyào gǎigé","Queuing systems need reform")], 0.5),
    mc("第四流派「规则重新定义派」为什么被认为是最高级的？", "Why is the fourth school, 'Rule Redefiners,' considered the most advanced?",
       [o("因为他们的行为最大胆","yīnwèi tāmen de xíngwéi zuì dàdǎn","Because their behavior is the boldest"),
        o("他们不是违反规则而是重新定义规则，从根本上改变了游戏","tāmen bú shì wéifǎn guīzé ér shì chóngxīn dìngyì guīzé, cóng gēnběn shàng gǎibiàn le yóuxì","They don't violate rules but redefine them, fundamentally changing the game",True),
        o("他们的成功率最高","tāmen de chénggōnglǜ zuì gāo","They have the highest success rate"),
        o("他们人数最少","tāmen rénshù zuì shǎo","They are the fewest in number")], 0.45)))

P.append(passage("j8_observe_014", "The Philosophy of Leftovers", "剩菜的哲学", 8,
    "一顿饭结束后，桌上剩下的菜可以精确地反映出这顿饭的社交性质。朋友聚餐，剩菜最多——每个人都点了自己想吃的，但因为菜品太多而吃不完，桌上会留下一片色彩斑斓的残局。商务宴请，剩菜量也很大，但原因不同：客人不好意思吃太多以免显得贪婪，主人则宁可多点也不能让桌上出现空盘——空盘意味着「招待不周」。最整洁的是家庭日常饭菜，母亲会精确地计算每个人的食量，做出来的菜几乎恰好被吃完，最多剩下一个菜的量留到明天中午。我注意到一个有趣的代际差异：五六十岁以上的人会把所有剩菜打包回家，哪怕只是几片青菜叶子；三四十岁的人只打包那些他们认为第二天还能吃的；二十多岁的人几乎从不打包。这三种态度分别对应着「绝对不浪费」「理性不浪费」和「注意力不在这里」三种生活哲学。食物的命运，最终取决于吃它的人所经历过的时代。",
    "Yī dùn fàn jiéshù hòu, zhuō shàng shèng xià de cài kěyǐ jīngquè de fǎnyìng chū zhè dùn fàn de shèjiāo xìngzhì.",
    "After a meal ends, the food left on the table precisely reflects the meal's social nature. At friends' gatherings, leftovers are greatest—everyone ordered what they wanted, but with too many dishes to finish, the table shows a colorful aftermath. At business dinners, leftovers are also substantial, but for different reasons: guests don't eat much to avoid appearing greedy, while hosts would rather over-order than let an empty plate appear—empty plates mean 'poor hospitality.' The tidiest are family daily meals: mothers precisely calculate each person's appetite, making food that's almost exactly consumed, at most one dish left for tomorrow's lunch. I noticed an interesting generational divide: those over fifty or sixty take home all leftovers, even a few vegetable leaves; those in their thirties and forties only pack what they think is still edible tomorrow; those in their twenties almost never pack leftovers. These three attitudes correspond to three life philosophies: 'absolutely no waste,' 'rationally no waste,' and 'attention is elsewhere.' Food's fate is ultimately determined by the era its eater lived through.",
    mc("商务宴请剩菜多的原因与朋友聚餐有何不同？", "How does the reason for business dinner leftovers differ from friends' gatherings?",
       [o("商务宴请的菜更贵","shāngwù yànqǐng de cài gèng guì","Business dinner dishes are more expensive"),
        o("商务宴请中客人克制进食、主人怕空盘失礼，而朋友聚餐是因为点得太多","shāngwù yànqǐng zhōng kèrén kèzhì jìnshí, zhǔrén pà kōng pán shīlǐ, ér péngyǒu jùcān shì yīnwèi diǎn de tài duō","At business dinners guests restrain eating and hosts fear empty plates as rude, while friends simply order too much",True),
        o("商务宴请时间更短","shāngwù yànqǐng shíjiān gèng duǎn","Business dinners are shorter"),
        o("商务场合不允许打包","shāngwù chǎnghé bù yǔnxǔ dǎbāo","Packing leftovers isn't allowed at business occasions")], 0.5),
    mc("三个年龄段对打包的不同态度反映了什么？", "What do the three age groups' different attitudes toward packing leftovers reflect?",
       [o("年龄越大越节约","niánlíng yuè dà yuè jiéyuē","The older, the more frugal"),
        o("各代人经历的物质条件不同，形成了不同的食物价值观","gè dài rén jīnglì de wùzhì tiáojiàn bùtóng, xíngchéng le bùtóng de shíwù jiàzhíguān","Different material conditions experienced by each generation formed different food values",True),
        o("年轻人不喜欢剩菜的味道","niánqīng rén bù xǐhuān shèngcài de wèidào","Young people don't like the taste of leftovers"),
        o("餐厅的打包服务变差了","cāntīng de dǎbāo fúwù biàn chà le","Restaurants' takeout container service has worsened")], 0.45),
    mc("母亲「精确计算食量」在文中说明了什么？", "What does the mother's 'precise calculation of appetite' illustrate?",
       [o("母亲的厨艺很好","mǔqīn de chúyì hěn hǎo","The mother is a good cook"),
        o("家庭日常饭菜基于对家人的深度了解，不存在社交表演的成分","jiātíng rìcháng fàncài jīyú duì jiārén de shēndù liǎojiě, bù cúnzài shèjiāo biǎoyǎn de chéngfèn","Family daily meals are based on deep understanding of family members, without social performance",True),
        o("家庭经济比较紧张","jiātíng jīngjì bǐjiào jǐnzhāng","The family budget is tight"),
        o("母亲不喜欢做太多菜","mǔqīn bù xǐhuān zuò tài duō cài","The mother doesn't like cooking too many dishes")], 0.4)))

P.append(passage("j8_urban_005", "The Geometry of Construction Barriers", "施工围挡的几何学", 8,
    "城市里的施工围挡是一种临时性的空间重新定义。当一段人行道被围起来的时候，行人的行走路线会在二十四小时内自发形成一条新的「河道」——它绕过围挡，经过马路牙子，穿过一段非正式的泥地，然后在围挡的另一端重新汇入正规的人行道。这条新路线没有任何人规划过，也没有任何指示牌引导，但在第二天早上，你就能看到一条被无数脚步踩出来的清晰土路。更有趣的是，围挡本身很快就会成为一个新的社会空间：小贩会在围挡与建筑之间的夹角处摆摊，因为那里形成了一个天然的半封闭空间，既能遮风又能躲开城管的视线。围挡上贴满了小广告——搬家、开锁、疏通下水道——它们的出现速度永远比清理速度快。附近的居民会在围挡上挂衣服、靠自行车，甚至有人在围挡脚下种了一排小花。一个本来用于隔绝和限制的结构，被人们的日常需求改造成了一个充满功能性的微型社区。",
    "Chéngshì lǐ de shīgōng wéidǎng shì yī zhǒng línshíxìng de kōngjiān chóngxīn dìngyì.",
    "Construction barriers in a city are a temporary redefinition of space. When a stretch of sidewalk is fenced off, pedestrians' walking routes will within twenty-four hours spontaneously form a new 'riverbed'—bypassing the barrier, crossing the curb, traversing an informal patch of dirt, then rejoining the proper sidewalk at the barrier's other end. This new route was planned by no one, guided by no sign, but by the next morning you can see a clear dirt path trampled by countless feet. More interesting is that the barrier itself quickly becomes a new social space: vendors set up at the angle between barrier and building, where a natural semi-enclosed space forms—sheltered from wind and hidden from inspectors' sight. The barrier fills with small ads—moving services, locksmithing, drain unclogging—appearing faster than they can be removed. Nearby residents hang clothes on it, lean bicycles against it; someone even planted a row of flowers at its base. A structure meant for isolation and restriction has been repurposed by daily needs into a functional micro-community.",
    mc("行人绕过围挡自发形成新路线说明了什么？", "What does pedestrians spontaneously forming new routes around barriers illustrate?",
       [o("城市规划不合理","chéngshì guīhuà bù hélǐ","Urban planning is unreasonable"),
        o("人类行为具有自发的系统适应性","rénlèi xíngwéi jùyǒu zìfā de xìtǒng shìyìngxìng","Human behavior has spontaneous systemic adaptability",True),
        o("围挡的位置不对","wéidǎng de wèizhì bú duì","The barrier is poorly positioned"),
        o("行人不守交通规则","xíngrén bù shǒu jiāotōng guīzé","Pedestrians don't follow traffic rules")], 0.45),
    mc("围挡被改造成「微型社区」说明了什么更深层的道理？", "What deeper truth does the barrier's transformation into a 'micro-community' reveal?",
       [o("施工围挡应该设计得更美观","shīgōng wéidǎng yīnggāi shèjì de gèng měiguān","Construction barriers should be more aesthetically designed"),
        o("人们的日常需求会将任何空间重新定义为功能性场所","rénmen de rìcháng xūqiú huì jiāng rènhé kōngjiān chóngxīn dìngyì wéi gōngnéngxìng chǎngsuǒ","People's daily needs will redefine any space as a functional place",True),
        o("城市里的公共空间不够多","chéngshì lǐ de gōnggòng kōngjiān búgòu duō","There isn't enough public space in cities"),
        o("围挡应该尽快拆除","wéidǎng yīnggāi jǐnkuài chāichú","Barriers should be removed as soon as possible")], 0.5),
    mc("小贩在围挡夹角处摆摊的原因是什么？", "Why do vendors set up at the angle between barrier and building?",
       [o("那里人流量最大","nàlǐ rénliúliàng zuì dà","That spot has the most foot traffic"),
        o("那里形成了天然的半封闭空间，可以遮风且不易被发现","nàlǐ xíngchéng le tiānrán de bàn fēngbì kōngjiān, kěyǐ zhēfēng qiě bú yì bèi fāxiàn","It forms a natural semi-enclosed space, sheltered and harder to spot",True),
        o("围挡公司允许摆摊","wéidǎng gōngsī yǔnxǔ bǎitān","The barrier company allows vendors"),
        o("附近没有其他商店","fùjìn méiyǒu qítā shāngdiàn","There are no other shops nearby")], 0.4)))

P.append(passage("j8_inst_004", "The Invisible Hierarchy of Hospital Corridors", "医院走廊的隐形等级", 8,
    "医院走廊里的行走速度是一面人际关系的镜子。最快的是急诊科的护士和主治医生，他们几乎是在小跑，白大褂的下摆在身后飘动，走廊里的人自动为他们让路。其次是年轻的住院医生，他们走得也快，但脚步里带着一种不确定的紧张感——既要赶时间，又怕走错方向。然后是行政人员和清洁工，他们以中等速度移动，路线固定，神情平静，像是这个空间里最稳定的常量。最慢的是患者和家属，他们拖着点滴架或搀扶着彼此，每一步都带着小心翼翼的犹豫。但还有一个常被忽略的群体：在走廊角落里等待的人。他们坐在塑料椅上或者靠在墙边，目光空洞地看着前方。他们的等待与候诊室不同——候诊室里的等待有一个明确的终点，而走廊里的等待通常意味着手术正在进行，他们不知道终点在哪里。走廊是一个过渡空间，但对这些等待的人来说，它是全世界最难熬的地方——时间在这里变得比任何地方都更稠密。",
    "Yīyuàn zǒuláng lǐ de xíngzǒu sùdù shì yī miàn rénjì guānxì de jìngzi.",
    "Walking speed in hospital corridors is a mirror of interpersonal hierarchy. Fastest are ER nurses and attending physicians, nearly jogging, coat hems fluttering behind them, corridor occupants automatically clearing the way. Next are young residents, also quick but with uncertain nervousness in their steps—needing to hurry yet afraid of going the wrong way. Then administrative staff and cleaners, moving at moderate speed with fixed routes and calm expressions, like the most stable constants in this space. Slowest are patients and family members, dragging IV stands or supporting each other, each step carrying cautious hesitation. But there's an often-overlooked group: those waiting in corridor corners. They sit on plastic chairs or lean against walls, eyes vacant, staring ahead. Their waiting differs from the waiting room—waiting room waiting has a definite endpoint, while corridor waiting usually means surgery is underway, the endpoint unknown. A corridor is a transitional space, but for these waiting people it is the hardest place in the world to endure—time here becomes thicker than anywhere else.",
    mc("作者用行走速度来反映什么？", "What does the author use walking speed to reflect?",
       [o("医院的管理效率","yīyuàn de guǎnlǐ xiàolǜ","Hospital management efficiency"),
        o("医院中不同角色的权力地位和心理状态","yīyuàn zhōng bùtóng juésè de quánlì dìwèi hé xīnlǐ zhuàngtài","The power positions and psychological states of different roles in the hospital",True),
        o("医院走廊应该更宽","yīyuàn zǒuláng yīnggāi gèng kuān","Hospital corridors should be wider"),
        o("医生工作太忙","yīshēng gōngzuò tài máng","Doctors are too busy")], 0.4),
    mc("走廊等待与候诊室等待的根本区别是什么？", "What is the fundamental difference between corridor waiting and waiting room waiting?",
       [o("走廊里没有座位","zǒuláng lǐ méiyǒu zuòwèi","Corridors have no seats"),
        o("候诊室等待有明确终点，走廊等待没有","hòuzhěnshì děngdài yǒu míngquè zhōngdiǎn, zǒuláng děngdài méiyǒu","Waiting room waiting has a definite endpoint; corridor waiting doesn't",True),
        o("走廊里更安静","zǒuláng lǐ gèng ānjìng","Corridors are quieter"),
        o("候诊室等待时间更长","hòuzhěnshì děngdài shíjiān gèng cháng","Waiting room waits are longer")], 0.45),
    mc("文末说「时间在这里变得更稠密」是什么意思？", "What does 'time here becomes thicker' mean?",
       [o("走廊里的钟走得更慢","zǒuláng lǐ de zhōng zǒu de gèng màn","The corridor clocks run slower"),
        o("焦虑和不确定性让等待者感觉每一分钟都格外漫长","jiāolǜ hé bú quèdìngxìng ràng děngdàizhě gǎnjué měi yī fēnzhōng dōu géwài mànchang","Anxiety and uncertainty make each minute feel extraordinarily long for those waiting",True),
        o("走廊里的空气更潮湿","zǒuláng lǐ de kōngqì gèng cháoshī","The corridor air is more humid"),
        o("走廊里人太多了","zǒuláng lǐ rén tài duō le","There are too many people in the corridor")], 0.45)))

P.append(passage("j8_observe_015", "The Calendar of Street Trees", "行道树的日历", 8,
    "如果你每天走同一条路上班，行道树就是你最忠实的季节日历。我家门口的那排法国梧桐在三月底发出第一片嫩绿的新叶，那片叶子小得像婴儿的指甲。四月，叶片快速展开，从浅绿加深到翠绿，像有人每天在上面刷一层更浓的颜料。五月到八月，树冠达到最大体积，密得几乎透不过阳光，整条人行道变成一条绿色的隧道。九月下旬，最先变色的总是树冠顶部接受阳光最多的那些叶子——它们从绿变黄的过程像一场从上往下燃烧的慢火。到了十一月，落叶铺满人行道，环卫工人每天清扫两次，但每次扫完不到一小时地面又被覆盖了。十二月的某一天，你突然发现最后一片叶子也掉了，树枝完全裸露，可以看到从前被树叶遮挡的对面楼房的窗户。这种视野的突然开阔让人有一种被暴露的不安。整个冬天，那些光秃秃的树枝在灰色天空下构成一幅精细的线条画，等待着来年三月的又一次复活。",
    "Rúguǒ nǐ měi tiān zǒu tóngyī tiáo lù shàngbān, xíngdào shù jiù shì nǐ zuì zhōngshí de jìjié rìlì.",
    "If you walk the same route to work daily, street trees become your most faithful seasonal calendar. The row of plane trees outside my door pushes out its first tender green leaf in late March, tiny as a baby's fingernail. In April, leaves expand rapidly, deepening from pale to emerald green, as if someone paints a richer coat daily. From May through August, canopies reach maximum volume, so dense light barely penetrates, the entire sidewalk becoming a green tunnel. In late September, the first to change are always leaves atop the crown receiving the most sunlight—their green-to-yellow transition like a slow fire burning from top to bottom. By November, fallen leaves blanket the sidewalk, swept twice daily by sanitation workers, yet the ground re-covers within an hour. One December day, you suddenly notice the last leaf has dropped, branches completely bare, revealing previously hidden windows of the building opposite. This sudden openness of view creates an uneasy feeling of exposure. All winter, those bare branches form an intricate line drawing against grey sky, awaiting the next resurrection in March.",
    mc("作者为什么说落叶后「有一种被暴露的不安」？", "Why does the author describe 'an uneasy feeling of exposure' after leaves fall?",
       [o("光秃的树木不美观","guāngtū de shùmù bù měiguān","Bare trees are unattractive"),
        o("树叶提供的视觉遮挡消失后，原本隐藏的空间和视线突然暴露了","shùyè tígōng de shìjué zhēdǎng xiāoshī hòu, yuánběn yǐncáng de kōngjiān hé shìxiàn tūrán bàolù le","After the visual screen of leaves disappears, previously hidden spaces and sightlines are suddenly exposed",True),
        o("冬天太冷了让人不舒服","dōngtiān tài lěng le ràng rén bù shūfu","Winter cold makes people uncomfortable"),
        o("对面楼的居民会看过来","duìmiàn lóu de jūmín huì kàn guòlái","Residents opposite might look over")], 0.45),
    mc("作者描述行道树变化的叙述手法是什么？", "What narrative technique does the author use to describe tree changes?",
       [o("科学报告式的客观描述","kēxué bàogào shì de kèguān miáoshù","Objective scientific report style"),
        o("以时间线索展开的感官化叙事，融入了大量视觉比喻","yǐ shíjiān xiànsuǒ zhǎnkāi de gǎnguān huà xùshì, róngrù le dàliàng shìjué bǐyù","Sensory narrative unfolding along a timeline, incorporating many visual metaphors",True),
        o("对比今昔的怀旧手法","duìbǐ jīnxī de huáijiù shǒufǎ","Nostalgic contrast between past and present"),
        o("虚构故事中的象征手法","xūgòu gùshì zhōng de xiàngzhēng shǒufǎ","Symbolism in fictional narrative")], 0.4),
    mc("行道树被比作「日历」，核心原因是什么？", "Why are street trees compared to a 'calendar'?",
       [o("树上可以挂日历","shù shàng kěyǐ guà rìlì","You can hang a calendar on a tree"),
        o("树的四季变化精确地标记着时间的推移","shù de sìjì biànhuà jīngquè de biāojì zhe shíjiān de tuīyí","Trees' four-season changes precisely mark the passage of time",True),
        o("树的年轮可以计算年龄","shù de niánlún kěyǐ jìsuàn niánlíng","Tree rings can calculate age"),
        o("每棵树每年都一样","měi kē shù měi nián dōu yīyàng","Every tree is the same each year")], 0.35)))

P.append(passage("j8_explain_001", "Why We Remember Smells", "为什么我们记住了气味", 8,
    "在所有感官中，嗅觉是唯一与记忆直接相连的。视觉和听觉的信号要经过丘脑中转才能到达大脑皮层处理，但嗅觉信号直接连通海马体和杏仁核——前者负责记忆的形成，后者负责情感的处理。这就是为什么一种气味可以在没有任何思维准备的情况下，瞬间把你拉回二十年前的某个场景。我第一次理解这个现象是在异国的一个雨天。空气中突然飘来一股潮湿的泥土气息，混合着不知名的野草气味，我立刻被传送回了小时候外婆家后院的那个下午——连当时穿着什么衣服都想起来了。这种体验在科学上被称为「普鲁斯特效应」，因为法国作家普鲁斯特在小说里详细描写过一块玛德琳蛋糕的气味如何唤醒了他整个童年的记忆。嗅觉记忆的独特之处在于它的「全息性」：它不像视觉记忆那样提供一个画面，而是提供一个完整的场景——包括温度、情绪、声音和光线。气味是时光机器最精确的启动钥匙。",
    "Zài suǒyǒu gǎnguān zhōng, xiùjué shì wéiyī yǔ jìyì zhíjiē xiānglián de.",
    "Among all senses, smell is the only one directly connected to memory. Visual and auditory signals must pass through the thalamus before reaching the cerebral cortex for processing, but olfactory signals connect directly to the hippocampus and amygdala—the former responsible for memory formation, the latter for emotional processing. This is why a smell can, without any mental preparation, instantly pull you back to a scene twenty years ago. I first understood this on a rainy day abroad. A damp earth scent mixed with unknown wild grass suddenly wafted through the air, and I was instantly transported to an afternoon in my grandmother's backyard—I even remembered what I was wearing. This is scientifically called the 'Proust Effect,' after the French writer who described how a madeleine cake's smell awakened an entire childhood of memories. Olfactory memory is unique in its 'holographic' quality: unlike visual memory which provides a picture, it delivers a complete scene—including temperature, emotion, sound, and light. Smell is the most precise ignition key for the time machine.",
    mc("嗅觉记忆与视觉/听觉记忆的根本区别是什么？", "What is the fundamental difference between olfactory memory and visual/auditory memory?",
       [o("嗅觉比视觉更灵敏","xiùjué bǐ shìjué gèng língmǐn","Smell is more sensitive than sight"),
        o("嗅觉信号不经丘脑中转，直接连通记忆和情感中枢","xiùjué xìnhào bù jīng qiūnǎo zhōngzhuǎn, zhíjiē liántōng jìyì hé qínggǎn zhōngshū","Olfactory signals bypass the thalamus, directly connecting to memory and emotion centers",True),
        o("嗅觉不能被训练","xiùjué bù néng bèi xùnliàn","Smell cannot be trained"),
        o("视觉记忆比嗅觉记忆更持久","shìjué jìyì bǐ xiùjué jìyì gèng chíjiǔ","Visual memory lasts longer than olfactory memory")], 0.45),
    mc("嗅觉记忆的「全息性」指的是什么？", "What does the 'holographic quality' of olfactory memory refer to?",
       [o("气味可以被精确地复制","qìwèi kěyǐ bèi jīngquè de fùzhì","Smells can be precisely replicated"),
        o("它唤起的不是单一画面而是包含温度、情绪、声音的完整场景","tā huànqǐ de bú shì dānyī huàmiàn ér shì bāohán wēndù, qíngxù, shēngyīn de wánzhěng chǎngjǐng","It evokes not a single image but a complete scene including temperature, emotion, and sound",True),
        o("嗅觉记忆可以被全部回忆起来","xiùjué jìyì kěyǐ bèi quánbù huíyì qǐlái","All olfactory memories can be recalled"),
        o("气味是三维的","qìwèi shì sānwéi de","Smells are three-dimensional")], 0.4),
    mc("作者在雨天闻到泥土气息后的体验说明了什么？", "What does the author's experience of smelling damp earth on a rainy day illustrate?",
       [o("他想家了","tā xiǎng jiā le","He was homesick"),
        o("嗅觉可以不经思维准备瞬间触发完整的记忆场景","xiùjué kěyǐ bù jīng sīwéi zhǔnbèi shùnjiān chùfā wánzhěng de jìyì chǎngjǐng","Smell can trigger complete memory scenes instantly without mental preparation",True),
        o("泥土气味到处都一样","nítǔ qìwèi dàochù dōu yīyàng","Dirt smells the same everywhere"),
        o("雨天容易引起怀旧情绪","yǔ tiān róngyì yǐnqǐ huáijiù qíngxù","Rainy days easily trigger nostalgia")], 0.4)))

P.append(passage("j8_mystery_004", "The Map with No Legend", "没有图例的地图", 8,
    "我在祖父遗物中发现了一张手绘地图，画在一张发黄的牛皮纸上。地图上标注了一条河流、几座小山丘、一个湖泊和若干个用红色圆点标记的位置。没有图例，没有地名，也没有方位标记。我试图辨认这是哪里。河流的弯曲方式让我想起老家附近的那条河，但山丘的位置对不上。红色圆点有七个，分布不均匀，其中三个紧挨着河边，两个在山丘附近，一个在湖边，最后一个在地图边缘，旁边画了一个很小的十字。我把地图拿给父亲看，他沉默了很久说：「这可能是你祖父当年在部队时画的。」那个十字，父亲猜测可能标记的是一座坟墓。但他不确定，因为祖父生前从未提起过任何关于战争的细节。这张地图变成了一个无法解开的谜——它记录了一段我永远无法还原的经历，属于一个不再能开口的人。有时候最难受的不是没有答案，而是连问题都无法被准确地提出。地图还在，但能读懂它的人已经不在了。",
    "Wǒ zài zǔfù yíwù zhōng fāxiàn le yī zhāng shǒu huì dìtú, huà zài yī zhāng fā huáng de niúpí zhǐ shàng.",
    "Among my grandfather's belongings I found a hand-drawn map on yellowed vellum paper. It marked a river, several hills, a lake, and various positions indicated by red dots. No legend, no place names, no compass. I tried to identify the location. The river's curvature reminded me of the one near my hometown, but the hills didn't match. Seven red dots, unevenly distributed—three clustered by the river, two near the hills, one by the lake, and the last at the map's edge with a small cross drawn beside it. I showed it to my father. He was silent a long time, then said: 'This might be from when your grandfather was in the army.' The cross, he guessed, might mark a grave. But he wasn't sure, because grandfather never mentioned any details about the war while alive. This map became an unsolvable mystery—it records an experience I can never reconstruct, belonging to a person who can no longer speak. Sometimes what hurts most is not having no answers, but being unable to even formulate the questions accurately. The map remains, but the person who could read it is gone.",
    mc("作者发现地图后面对的根本困难是什么？", "What is the fundamental difficulty the author faces after finding the map?",
       [o("地图没有方位标记","dìtú méiyǒu fāngwèi biāojì","The map has no compass markings"),
        o("能解读这张地图的人已经去世，连正确的问题都无法提出","néng jiědú zhè zhāng dìtú de rén yǐjīng qùshì, lián zhèngquè de wèntí dōu wúfǎ tíchū","The person who could read the map has died, and even the right questions cannot be formulated",True),
        o("地图画得不够精确","dìtú huà de búgòu jīngquè","The map isn't drawn precisely enough"),
        o("父亲不愿意谈论祖父的事","fùqīn bú yuànyì tánlùn zǔfù de shì","The father is unwilling to discuss the grandfather")], 0.5),
    mc("地图边缘的小十字最可能代表什么？", "What does the small cross at the map's edge most likely represent?",
       [o("地图的起点","dìtú de qǐdiǎn","The map's starting point"),
        o("一座与战争有关的坟墓","yī zuò yǔ zhànzhēng yǒuguān de fénmù","A grave related to the war",True),
        o("一座教堂","yī zuò jiàotáng","A church"),
        o("一个军事目标","yī gè jūnshì mùbiāo","A military target")], 0.45),
    mc("「地图还在，但能读懂它的人已经不在了」这句话传达了什么情感？", "What emotion does 'the map remains, but the person who could read it is gone' convey?",
       [o("对旧物保管方式的遗憾","duì jiùwù bǎoguǎn fāngshì de yíhàn","Regret about how old items are stored"),
        o("对个人记忆和历史随生命消逝的深沉惋惜","duì gèrén jìyì hé lìshǐ suí shēngmìng xiāoshì de shēnchén wǎnxī","Deep wistfulness over personal memories and history vanishing with life",True),
        o("对祖父不分享故事的不满","duì zǔfù bù fēnxiǎng gùshì de bùmǎn","Dissatisfaction with the grandfather not sharing stories"),
        o("对地图学的兴趣","duì dìtúxué de xìngqù","Interest in cartography")], 0.5)))

P.append(passage("j8_observe_016", "The Rhythm of the Washing Machine", "洗衣机的节拍", 8,
    "深夜，当整栋楼都安静下来的时候，洗衣机的运转声会变成一种令人安心的白噪音。进水阶段是一串急促的冲刷声，像远处的瀑布；搅洗阶段是一种有节奏的来回摆动，像摇篮的律动；脱水阶段则是一个逐渐加速的旋转，频率越来越高，直到整台机器微微震颤，然后戛然而止。我发现自己会不自觉地用洗衣机的运行周期来丈量深夜的时间。一个完整的洗涤程序大约四十分钟，正好够我写完一封长邮件或读完一篇论文的引言。在没有闹钟提醒的深夜里，洗衣机的结束提示音成了最可靠的计时器。更有趣的是，我隔壁的邻居似乎也有深夜洗衣的习惯。有时两台洗衣机的声音会透过墙壁叠加在一起，形成一种不规则的复合节拍。那一刻我会想到：在这栋楼里，至少有另一个人也在深夜独自醒着，做着和我一样平凡的事情。这个念头本身就是一种微小的慰藉——城市的深夜并不像看起来那么孤独。",
    "Shēnyè, dāng zhěng dòng lóu dōu ānjìng xiàlái de shíhou, xǐyījī de yùnzhuǎn shēng huì biàn chéng yī zhǒng lìng rén ānxīn de bái zàoyīn.",
    "Late at night, when the entire building falls quiet, the washing machine becomes a reassuring white noise. The fill stage is a rush of sluicing, like a distant waterfall; the wash cycle is a rhythmic back-and-forth, like a cradle's rocking; the spin cycle is a gradually accelerating rotation, frequency climbing until the whole machine trembles slightly, then abruptly stops. I find myself unconsciously using the washing cycle to measure late-night time. A complete wash takes about forty minutes—just enough to finish a long email or read a paper's introduction. In the alarm-free late night, the machine's completion chime becomes the most reliable timer. More interesting, my next-door neighbor also seems to wash clothes at night. Sometimes two machines' sounds layer through the wall, forming an irregular compound beat. In that moment I think: somewhere in this building, at least one other person is also awake alone at night, doing the same mundane thing I am. That thought itself is a small consolation—the city's late night is not as lonely as it looks.",
    mc("作者用洗衣机的运行周期来做什么？", "What does the author use the washing cycle for?",
       [o("判断洗衣机是否正常工作","pànduàn xǐyījī shìfǒu zhèngcháng gōngzuò","Checking if the machine works properly"),
        o("在没有闹钟的深夜里丈量时间","zài méiyǒu nàozhōng de shēnyè lǐ zhàngliang shíjiān","Measuring time during alarm-free late nights",True),
        o("写音乐作品","xiě yīnyuè zuòpǐn","Composing music"),
        o("帮助自己入睡","bāngzhù zìjǐ rùshuì","Helping himself fall asleep")], 0.35),
    mc("两台洗衣机声音叠加让作者想到什么？", "What does the layering of two washing machines' sounds make the author think of?",
       [o("噪音太大应该投诉","zàoyīn tài dà yīnggāi tóusù","The noise is too loud and deserves a complaint"),
        o("在深夜的城市里至少还有另一个人也在醒着做平凡的事","zài shēnyè de chéngshì lǐ zhìshǎo hái yǒu lìng yī gè rén yě zài xǐng zhe zuò píngfán de shì","At least one other person in the city is also awake at night doing ordinary things",True),
        o("邻居应该白天洗衣服","línjū yīnggāi báitiān xǐ yīfu","The neighbor should wash clothes during the day"),
        o("他们应该买更安静的洗衣机","tāmen yīnggāi mǎi gèng ānjìng de xǐyījī","They should buy quieter machines")], 0.4),
    mc("作者说「城市的深夜并不像看起来那么孤独」，依据是什么？", "What is the basis for 'the city's late night is not as lonely as it looks'?",
       [o("深夜有很多营业的店铺","shēnyè yǒu hěn duō yíngyè de diànpù","Many shops operate late at night"),
        o("透过日常声音的叠加可以感知到其他人的存在","tòuguò rìcháng shēngyīn de diéjiā kěyǐ gǎnzhī dào qítā rén de cúnzài","Through the layering of everyday sounds one can perceive others' existence",True),
        o("夜班工作者很多","yèbān gōngzuòzhě hěn duō","There are many night-shift workers"),
        o("社交媒体让人时刻保持联系","shèjiāo méitǐ ràng rén shíkè bǎochí liánxì","Social media keeps people connected")], 0.45)))

P.append(passage("j8_food_002", "The Tea That Tastes Like Time", "尝起来像时间的茶", 8,
    "外婆泡茶有一套不可更改的仪式。首先，水必须是刚烧开的，壶嘴冒出的蒸汽要形成一条笔直的白线。其次，茶叶的量她用三根手指捏——不用茶匙，因为「手指知道多少是对的」。然后是注水的方式：壶嘴距离杯口大约一拳的高度，水流细而稳，绕着茶叶的边缘浇，不能直接冲在叶子上面。最后是等待——盖上杯盖，数到六十，不多不少。我小时候总觉得这些步骤多余，泡茶不就是把水倒进杯子里吗？长大后我逐渐明白，这套仪式的意义不在于让茶变得更好喝——也许确实更好喝了，但这不是重点。重点是在快速消费的时代里，有些东西值得你慢下来，用一分钟的等待来换取一个下午的安宁。外婆去世后，我继承了她的那套茶具：一把紫砂壶和四只白瓷杯。我试着按她的方式泡茶，每一个步骤都模仿得很像，但泡出来的茶总是差一点什么。后来我想明白了：差的那一点不是技术，而是几十年的肌肉记忆和与那把壶朝夕相处的默契。",
    "Wàipó pào chá yǒu yī tào bùkě gēnggǎi de yíshì.",
    "Grandmother had an unchangeable tea ceremony. First, the water must be just boiled, steam from the spout forming a straight white line. Second, she measured leaves with three fingers—no tea spoon, because 'fingers know the right amount.' Then the pouring: spout held about one fist above the cup, a thin, steady stream circling the leaves' edges, never directly onto them. Finally, waiting—cover on, count to sixty, no more, no less. As a child I thought these steps unnecessary—isn't tea just water poured into a cup? Growing up, I understood the ritual's meaning wasn't making tea taste better—though perhaps it did, but that wasn't the point. The point is that in an age of rapid consumption, some things are worth slowing down for, trading one minute of waiting for an afternoon's peace. After grandmother passed, I inherited her tea set: a purple clay pot and four white porcelain cups. I tried making tea her way, imitating every step closely, but the tea always missed something. Later I realized: what was missing wasn't technique, but decades of muscle memory and the unspoken rapport of living with that pot day after day.",
    mc("作者认为外婆泡茶仪式的真正意义是什么？", "What does the author believe is the true meaning of grandmother's tea ritual?",
       [o("让茶的味道更好","ràng chá de wèidào gèng hǎo","Making the tea taste better"),
        o("在快速消费的时代用慢的方式换取内心的安宁","zài kuàisù xiāofèi de shídài yòng màn de fāngshì huànqǔ nèixīn de ānníng","In an age of rapid consumption, using slowness to exchange for inner peace",True),
        o("保持传统文化","bǎochí chuántǒng wénhuà","Preserving traditional culture"),
        o("展示泡茶的技术","zhǎnshì pào chá de jìshù","Demonstrating tea-making technique")], 0.5),
    mc("作者模仿外婆泡茶但「总是差一点什么」，差的是什么？", "What was the 'something' the author's tea always lacked?",
       [o("正确的水温","zhèngquè de shuǐwēn","The correct water temperature"),
        o("几十年的肌肉记忆和与器具的默契","jǐ shí nián de jīròu jìyì hé yǔ qìjù de mòqì","Decades of muscle memory and rapport with the instrument",True),
        o("更好的茶叶","gèng hǎo de cháyè","Better tea leaves"),
        o("外婆的指导","wàipó de zhǐdǎo","Grandmother's guidance")], 0.45),
    mc("外婆说「手指知道多少是对的」，这反映了什么？", "What does grandmother's saying 'fingers know the right amount' reflect?",
       [o("她不识字所以不用量具","tā bú shízì suǒyǐ bú yòng liángjù","She was illiterate so didn't use measuring tools"),
        o("长期实践积累的身体知识超越了量化工具","chángqī shíjiàn jīlěi de shēntǐ zhīshi chāoyuè le liànghuà gōngjù","Bodily knowledge accumulated through long practice transcends quantitative tools",True),
        o("茶叶的量不重要","cháyè de liàng bú zhòngyào","The amount of tea doesn't matter"),
        o("她不喜欢厨房用具","tā bù xǐhuān chúfáng yòngjù","She disliked kitchen utensils")], 0.4)))

append_save("hsk8_batch3.json", P)
