# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "/Users/jasongerson/mandarin/content_gen")
from gen_helpers import *

P = []

# 16 - comedy
P.append(passage("j8_comedy_002",
    "The Art of Pretending to Work", "假装工作的艺术", 8,
    "在开放式办公室里，「假装工作」是一门精密的表演艺术。我曾在一家互联网公司观察过这种行为的全部变体。最基础的技巧是「忙碌打字法」：在完全没有输出的情况下保持击键的声音，键盘成了一种表演道具。更高级的是「会议室消失术」：在两个不相关的会议之间安排一段空白时间，然后告诉老板自己「一直在开会」。最具创造力的则是「文档伪装法」——在游戏或社交媒体的页面底部放一个Excel表格的窗口，只要有人走过来就快速切换。但最讽刺的发现是：那些花最多精力假装工作的人，如果把同等的精力用于真正的工作，效率可能会更高。这种矛盾揭示了一个关于现代办公文化的根本问题——许多工作岗位衡量的不是产出而是「在场感」。当一个组织开始计算你坐在椅子上的小时数而不是你实际完成的任务时，假装工作就从个人的懒惰变成了系统的必然产物。",
    "Zài kāifàngshì bàngōngshì lǐ, jiǎzhuāng gōngzuò shì yī mén jīngmì de biǎoyǎn yìshù. Wǒ céng zài yī jiā hùliánwǎng gōngsī guānchá guò zhè zhǒng xíngwéi de quánbù biàntǐ.",
    "In an open-plan office, 'pretending to work' is a precision performance art. I once observed every variant of this behavior at an internet company. The most basic technique is 'busy typing'—maintaining keystroke sounds with zero output, the keyboard becoming a prop. More advanced is the 'meeting room vanishing act'—scheduling blank time between unrelated meetings, then telling the boss you 'were in meetings all day.' Most creative is the 'document camouflage method'—placing an Excel window at the bottom of a game or social media page, quick-switching when someone approaches. But the most ironic finding: those spending the most energy pretending to work would likely be more efficient if they applied that energy to actual work. This paradox reveals a fundamental problem in modern office culture—many positions measure not output but 'presence.' When an organization starts counting hours you sit in a chair rather than tasks you complete, pretending to work transforms from individual laziness into a systemic inevitability.",
    mc("作者认为「假装工作」最根本的原因是什么？",
       "What does the author identify as the most fundamental cause of 'pretending to work'?",
       [o("员工天生懒惰","yuángōng tiānshēng lǎnduò","Employees are inherently lazy"),
        o("办公文化衡量的是在场感而非实际产出","bàngōng wénhuà héngliáng de shì zàichǎnggǎn ér fēi shíjì chǎnchū","Office culture measures presence rather than actual output",True),
        o("开放式办公室让人无法集中精力","kāifàngshì bàngōngshì ràng rén wúfǎ jízhōng jīnglì","Open offices prevent people from concentrating"),
        o("互联网公司管理松散","hùliánwǎng gōngsī guǎnlǐ sōngsǎn","Internet companies have loose management")], 0.45),
    mc("文中最具讽刺意味的发现是什么？",
       "What is the most ironic finding in the text?",
       [o("假装工作比真正工作更累","jiǎzhuāng gōngzuò bǐ zhēnzhèng gōngzuò gèng lèi","Pretending to work is more tiring than real work"),
        o("投入假装工作的精力如果用于真正工作，效率反而更高","tóurù jiǎzhuāng gōngzuò de jīnglì rúguǒ yòng yú zhēnzhèng gōngzuò, xiàolǜ fǎn'ér gèng gāo","The energy spent pretending, if applied to real work, would yield higher efficiency",True),
        o("老板也在假装工作","lǎobǎn yě zài jiǎzhuāng gōngzuò","Bosses also pretend to work"),
        o("所有人都知道别人在假装","suǒyǒu rén dōu zhīdào biérén zài jiǎzhuāng","Everyone knows others are pretending")], 0.4),
    mc("作者的结论将「假装工作」定义为什么？",
       "How does the author's conclusion define 'pretending to work'?",
       [o("个人道德的缺失","gèrén dàodé de quēshī","A personal moral failing"),
        o("系统性问题的必然产物","xìtǒngxìng wèntí de bìrán chǎnwù","An inevitable product of systemic problems",True),
        o("互联网时代的新现象","hùliánwǎng shídài de xīn xiànxiàng","A new phenomenon of the internet era"),
        o("年轻一代的工作态度","niánqīng yī dài de gōngzuò tàidù","The work attitude of the younger generation")], 0.45)))

# 17 - observe
P.append(passage("j8_observe_010",
    "The Weight of Plastic Bags", "塑料袋的重量", 8,
    "超市门口的塑料袋架上挂着两种袋子：小号三毛，大号五毛。这个定价策略背后隐藏着一个有趣的行为经济学现象。我观察了两个月，发现绝大多数顾客会选择大号袋子，即使他们只买了一瓶酱油和一包纸巾。理由很简单：五毛钱的差价太小，不值得为此纠结，但大袋子提供了一种心理上的安全感——万一还要装别的东西呢。更有趣的是那些自带购物袋的人。他们通常是五十岁以上的女性，袋子被折叠得整整齐齐放在随身的挎包里。她们对塑料袋的拒绝不是出于环保意识——至少在我询问过的十几位阿姨中，没有一位提到环保——而是源于一种根深蒂固的节俭本能。她们经历过物资匮乏的年代，对「花钱买一个用完就扔的东西」在感情上无法接受。这种节俭与年轻一代的环保叙事殊途同归，却基于完全不同的动机。我有时想，最持久的行为改变或许不来自宏大的理念教育，而来自骨子里的习惯记忆。",
    "Chāoshì ménkǒu de sùliào dài jià shàng guà zhe liǎng zhǒng dàizi: xiǎo hào sān máo, dà hào wǔ máo. Zhège dìngjià cèlüè bèihòu yǐncáng zhe yī gè yǒuqù de xíngwéi jīngjìxué xiànxiàng.",
    "At the supermarket entrance, the bag rack holds two sizes: small for three mao, large for five mao. Behind this pricing hides an interesting behavioral economics phenomenon. Over two months of observation, I found most customers choose the large bag even when buying only a bottle of soy sauce and a packet of tissues. The logic is simple: the two-mao difference is too small to agonize over, but the large bag provides psychological security—what if you need to fit something else? More interesting are those who bring their own bags. They're usually women over fifty, bags folded neatly inside a shoulder purse. Their rejection of plastic bags isn't from environmental awareness—among the dozen-plus aunties I asked, none mentioned the environment—but from a deep-rooted frugality instinct. They lived through eras of scarcity and emotionally cannot accept 'paying money for something you throw away after one use.' This frugality and younger generations' environmental narrative arrive at the same destination by different paths, driven by completely different motives. Sometimes I think the most lasting behavioral change comes not from grand ideological education, but from habits encoded in our bones.",
    mc("大多数顾客选择大号袋子的心理原因是什么？",
       "What is the psychological reason most customers choose the large bag?",
       [o("大号袋子质量更好","dà hào dàizi zhìliàng gèng hǎo","Large bags have better quality"),
        o("价差太小不值得纠结，大袋子提供心理安全感","jiàchā tài xiǎo bù zhíde jiūjié, dà dàizi tígōng xīnlǐ ānquángǎn","The price difference is too small to fuss over, and the large bag provides psychological security",True),
        o("大号袋子看起来更高档","dà hào dàizi kàn qǐlái gèng gāodàng","Large bags look more upscale"),
        o("超市推荐大号袋子","chāoshì tuījiàn dà hào dàizi","The supermarket recommends large bags")], 0.4),
    mc("自带购物袋的阿姨们拒绝塑料袋的真正动机是什么？",
       "What is the real motivation of the aunties who refuse plastic bags?",
       [o("响应政府的环保号召","xiǎngyìng zhèngfǔ de huánbǎo hàozhào","Responding to government environmental initiatives"),
        o("经历过物资匮乏年代形成的节俭本能","jīnglì guò wùzī kuìfá niándài xíngchéng de jiéjiǎn běnnéng","A frugality instinct formed by living through eras of scarcity",True),
        o("她们不喜欢塑料的手感","tāmen bù xǐhuān sùliào de shǒugǎn","They dislike how plastic feels"),
        o("自带袋子更方便","zìdài dàizi gèng fāngbiàn","Bringing your own bag is more convenient")], 0.45),
    mc("作者认为最持久的行为改变来自什么？",
       "What does the author believe produces the most lasting behavioral change?",
       [o("政府政策和法律法规","zhèngfǔ zhèngcè hé fǎlǜ fǎguī","Government policies and regulations"),
        o("骨子里的习惯记忆而非宏大的理念教育","gǔzi lǐ de xíguàn jìyì ér fēi hóngdà de lǐniàn jiàoyù","Habits encoded in our bones rather than grand ideological education",True),
        o("社交媒体上的宣传","shèjiāo méitǐ shàng de xuānchuán","Promotion on social media"),
        o("经济利益的驱动","jīngjì lìyì de qūdòng","Economic incentive")], 0.5)))

# 18 - urban
P.append(passage("j8_urban_003",
    "The Choreography of Crosswalks", "人行横道的编舞", 8,
    "如果你站在一个繁忙路口的天桥上往下看，行人过马路的轨迹会呈现出一种令人着迷的流体力学图案。绿灯亮起的瞬间，两侧人群同时启动，像两股相向而行的水流。最初的几秒钟，双方保持着整齐的队形，但很快，走在前面的人开始自动寻找缝隙，整个队形分解成无数条交叉的曲线。两股人流的交汇点通常在路中央偏左的位置——这是右侧通行惯例的自然结果。更有趣的是速度分层：最快的是赶时间的年轻上班族，他们像鱼一样灵活地穿过人群；中间速度层是普通行人；最慢的是老人和带小孩的家长，他们构成了一种移动的障碍物，其他人自动绕行。这套系统没有交通警察指挥，却极少发生碰撞。每个人都在进行着高速的微观计算——预判对方的速度、方向和可能的路径变化，然后实时调整自己的轨迹。这种无意识的集体协作，或许是人类社会性最优雅的证据。",
    "Rúguǒ nǐ zhàn zài yī gè fánmáng lùkǒu de tiānqiáo shàng wǎng xià kàn, xíngrén guò mǎlù de guǐjì huì chéngxiàn chū yī zhǒng lìng rén zháomí de liútǐ lìxué tú'àn.",
    "If you stand on a footbridge above a busy intersection and look down, pedestrian crossing patterns reveal a fascinating fluid dynamics tableau. The instant the light turns green, crowds from both sides launch simultaneously like two opposing water currents. For the first few seconds, both sides maintain orderly formation, but quickly the leaders start finding gaps and the formation dissolves into countless crossing curves. The confluence point is usually just left of center—a natural result of right-side walking conventions. More interesting is the speed stratification: fastest are young office workers rushing, weaving through crowds like fish; middle speed is ordinary pedestrians; slowest are the elderly and parents with children, forming moving obstacles that others automatically route around. This system has no traffic police directing it, yet collisions almost never occur. Everyone performs high-speed micro-calculations—predicting the other's speed, direction, and possible path changes, then adjusting their own trajectory in real time. This unconscious collective coordination may be the most elegant evidence of human sociality.",
    mc("作者用「流体力学」类比行人过马路，核心发现是什么？",
       "What core finding does the fluid dynamics analogy for pedestrian crossings reveal?",
       [o("行人过马路的方式与水流的物理规律相似","xíngrén guò mǎlù de fāngshì yǔ shuǐliú de wùlǐ guīlǜ xiāngsì","Pedestrian crossing patterns resemble the physics of water flow",True),
        o("城市交通需要更多天桥","chéngshì jiāotōng xūyào gèng duō tiānqiáo","Cities need more footbridges"),
        o("行人不遵守交通规则","xíngrén bù zūnshǒu jiāotōng guīzé","Pedestrians don't follow traffic rules"),
        o("绿灯时间太短","lǜdēng shíjiān tài duǎn","Green light duration is too short")], 0.45),
    mc("两股人流的交汇点偏左的原因是什么？",
       "Why is the confluence point slightly left of center?",
       [o("大多数人是右撇子","dàduōshù rén shì yòupiězi","Most people are right-handed"),
        o("右侧通行惯例的自然结果","yòucè tōngxíng guànlì de zìrán jiéguǒ","The natural result of right-side walking conventions",True),
        o("路口设计不对称","lùkǒu shèjì bú duìchèn","The intersection design is asymmetric"),
        o("人们习惯靠左走","rénmen xíguàn kào zuǒ zǒu","People habitually walk on the left")], 0.4),
    mc("作者认为行人的集体协作说明了什么？",
       "What does the collective coordination of pedestrians demonstrate according to the author?",
       [o("人类需要交通信号灯","rénlèi xūyào jiāotōng xìnhào dēng","Humans need traffic signals"),
        o("无意识的集体协调是人类社会性最优雅的证据","wúyìshi de jítǐ xiétiáo shì rénlèi shèhuìxìng zuì yōuyǎ de zhèngjù","Unconscious collective coordination is the most elegant evidence of human sociality",True),
        o("城市设计应该减少十字路口","chéngshì shèjì yīnggāi jiǎnshǎo shízì lùkǒu","Urban design should reduce intersections"),
        o("年轻人走路比老人快","niánqīng rén zǒulù bǐ lǎorén kuài","Young people walk faster than the elderly")], 0.5)))

# 19 - identity
P.append(passage("j8_identity_002",
    "The Dialect That Returns in Dreams", "在梦里回来的方言", 8,
    "我离开家乡已经二十年了，普通话说得比大多数人都标准。但有一件奇怪的事：每当我做梦时，梦里的对话全部是方言。父亲用方言叫我的小名，母亲用方言骂我不好好吃饭，甚至梦里的陌生人也说着同样的口音。醒来之后，那些方言词汇会在意识里停留几秒钟，然后像晨雾一样消散，被普通话重新覆盖。语言学家说，母语——准确地说是最初习得的语言——被存储在大脑更深层的区域，与情感记忆紧密连接。这解释了为什么方言总在最无防备的时刻回来：做梦时，喝醉时，极度悲伤或极度愤怒时。这些时刻，理性的控制力减弱，最原始的语言底层就浮现出来了。我有时会故意对着镜子说几句方言，那个声音听起来既熟悉又陌生——那是二十年前的我的声音，一个还没有被普通话和英语重新塑造过的人的声音。方言的消退不是遗忘，而是一种地层式的覆盖：新的语言铺在旧的上面，旧的并没有消失，只是沉到了更深的地方。",
    "Wǒ líkāi jiāxiāng yǐjīng èrshí nián le, pǔtōnghuà shuō de bǐ dàduōshù rén dōu biāozhǔn. Dàn yǒu yī jiàn qíguài de shì: měi dāng wǒ zuòmèng shí, mèng lǐ de duìhuà quánbù shì fāngyán.",
    "I left my hometown twenty years ago, and my Mandarin is more standard than most. But something strange: whenever I dream, all the dialogue is in dialect. My father calls my childhood name in dialect, my mother scolds me for not eating properly in dialect, even dream strangers speak the same accent. After waking, those dialect words linger for a few seconds, then dissipate like morning mist, re-covered by Mandarin. Linguists say the mother tongue—precisely, the first language acquired—is stored in deeper brain regions, tightly linked to emotional memory. This explains why dialect always returns at the most unguarded moments: dreaming, drunk, in extreme sadness or anger. In those moments, rational control weakens, and the most primitive linguistic layer surfaces. Sometimes I deliberately speak dialect to the mirror, and the voice sounds both familiar and strange—the voice of me twenty years ago, a person not yet reshaped by Mandarin and English. The fading of dialect is not forgetting, but a geological layering: new language laid over old, the old not vanished, just sunk to deeper ground.",
    mc("方言为什么总在「最无防备的时刻」回来？",
       "Why does dialect always return at 'the most unguarded moments'?",
       [o("因为方言比普通话更容易发音","yīnwèi fāngyán bǐ pǔtōnghuà gèng róngyì fāyīn","Because dialect is easier to pronounce than Mandarin"),
        o("理性控制力减弱时，与情感记忆连接的深层语言浮现","lǐxìng kòngzhì lì jiǎnruò shí, yǔ qínggǎn jìyì liánjiē de shēncéng yǔyán fúxiàn","When rational control weakens, the deep language connected to emotional memory surfaces",True),
        o("做梦时大脑会重置语言系统","zuòmèng shí dànǎo huì chóngzhì yǔyán xìtǒng","The brain resets its language system during dreams"),
        o("方言词汇比普通话词汇更生动","fāngyán cíhuì bǐ pǔtōnghuà cíhuì gèng shēngdòng","Dialect vocabulary is more vivid than Mandarin")], 0.5),
    mc("作者用「地层式的覆盖」来描述语言的变化，这意味着什么？",
       "What does the 'geological layering' metaphor for language change mean?",
       [o("旧语言被新语言完全替代","jiù yǔyán bèi xīn yǔyán wánquán tìdài","Old language is completely replaced by new"),
        o("新语言覆盖在旧语言上面，旧的沉到更深处但并未消失","xīn yǔyán fùgài zài jiù yǔyán shàngmiàn, jiù de chén dào gèng shēn chù dàn bìng wèi xiāoshī","New language layers over old, the old sinks deeper but doesn't disappear",True),
        o("学习多种语言会导致语言混乱","xuéxí duō zhǒng yǔyán huì dǎozhì yǔyán hùnluàn","Learning multiple languages causes linguistic confusion"),
        o("方言应该被保护和记录","fāngyán yīnggāi bèi bǎohù hé jìlù","Dialect should be protected and recorded")], 0.45),
    mc("作者对着镜子说方言时感到「既熟悉又陌生」，原因是什么？",
       "Why does the author feel 'both familiar and strange' when speaking dialect to the mirror?",
       [o("镜子里的倒影看起来不像自己","jìngzi lǐ de dàoyǐng kàn qǐlái bú xiàng zìjǐ","The reflection looks unfamiliar"),
        o("那个声音属于二十年前未被重塑的自己","nàge shēngyīn shǔyú èrshí nián qián wèi bèi chóng sù de zìjǐ","That voice belongs to the self from twenty years ago, not yet reshaped",True),
        o("他的方言已经说得不标准了","tā de fāngyán yǐjīng shuō de bú biāozhǔn le","His dialect is no longer standard"),
        o("方言让他想起不愉快的童年","fāngyán ràng tā xiǎngqǐ bú yúkuài de tóngnián","Dialect reminds him of an unpleasant childhood")], 0.45)))

# 20 - travel
P.append(passage("j8_travel_001",
    "The Airport as a System", "机场作为系统", 8,
    "机场是人类设计过的最复杂的流动系统之一，但大多数旅客只关注自己的那一小段路线——从值机柜台到登机口。如果你退后一步，把整个机场当作一个有机体来观察，你会看到一套令人惊叹的分流与汇流机制。出发层的旅客被安检口分成若干支流，然后在候机区重新汇合，最终通过登机口注入一架飞机。到达层则完全相反：一架飞机释放出几百个人，他们被行李转盘短暂聚拢，然后在出口处分散成出租车队列、地铁入口和接机人群。每一个分支都有自己的节奏和速度：免税店制造的停留效应会让一部分旅客减速，而赶飞机的旅客则像急流中的快鱼一样穿过人群。我曾在浦东机场的观景台上坐了一整个下午，看着下面的人流图案不断变化。从高处看，每个人都只是系统中的一个微粒，但每一个微粒都带着自己的目的地、自己的故事、自己即将到来或刚刚结束的旅程。这或许就是机场令人着迷的原因：它是一个所有故事短暂交汇又立即分离的地方。",
    "Jīchǎng shì rénlèi shèjì guò de zuì fùzá de liúdòng xìtǒng zhī yī, dàn dàduōshù lǚkè zhǐ guānzhù zìjǐ de nà yī xiǎo duàn lùxiàn——cóng zhíjī guìtái dào dēngjī kǒu.",
    "An airport is one of the most complex flow systems humans have designed, yet most travelers focus only on their own small segment—from check-in counter to boarding gate. If you step back and observe the entire airport as an organism, you see an astonishing system of divergence and convergence. Departing passengers are split by security into tributaries, reconverge in gate areas, then funnel through boarding gates into aircraft. Arrivals are reversed: a plane releases hundreds of people, briefly gathered by baggage carousels, then dispersed at exits into taxi queues, subway entrances, and greeting crowds. Each branch has its own rhythm: duty-free shops create drag that slows some travelers, while those rushing for flights dart through crowds like fast fish in a current. I once spent an entire afternoon on Pudong Airport's observation deck watching the flow patterns shift below. From above, each person is just a particle in the system, but every particle carries its own destination, story, and journey about to begin or just ended. Perhaps this is why airports fascinate: they are places where all stories briefly converge and immediately separate.",
    mc("作者把机场比作「有机体」，核心观点是什么？",
       "What is the core point of comparing an airport to an 'organism'?",
       [o("机场的建筑设计模仿了生物结构","jīchǎng de jiànzhù shèjì mófǎng le shēngwù jiégòu","Airport architecture mimics biological structures"),
        o("机场是一个由分流与汇流机制构成的复杂动态系统","jīchǎng shì yī gè yóu fēnliú yǔ huìliú jīzhì gòuchéng de fùzá dòngtài xìtǒng","An airport is a complex dynamic system of divergence and convergence mechanisms",True),
        o("机场里的人像细胞一样工作","jīchǎng lǐ de rén xiàng xìbāo yīyàng gōngzuò","People in airports work like cells"),
        o("机场需要更好的管理","jīchǎng xūyào gèng hǎo de guǎnlǐ","Airports need better management")], 0.45),
    mc("作者说免税店制造了「停留效应」，这在系统中的作用是什么？",
       "What role does the 'drag effect' of duty-free shops play in the system?",
       [o("增加机场的商业收入","zēngjiā jīchǎng de shāngyè shōurù","Increasing the airport's commercial revenue"),
        o("让一部分旅客减速，改变人流的速度分层","ràng yī bùfen lǚkè jiǎnsù, gǎibiàn rénliú de sùdù fēncéng","Slowing some travelers and changing the speed stratification of the flow",True),
        o("帮助旅客消磨等待时间","bāngzhù lǚkè xiāomó děngdài shíjiān","Helping travelers kill waiting time"),
        o("减少安检口的拥挤","jiǎnshǎo ānjiǎn kǒu de yōngjǐ","Reducing congestion at security checkpoints")], 0.5),
    mc("文末说机场「是一个所有故事短暂交汇又立即分离的地方」，表达了什么？",
       "What does the closing line about 'all stories briefly converging and immediately separating' express?",
       [o("机场的交通功能","jīchǎng de jiāotōng gōngnéng","The airport's transportation function"),
        o("机场是人类短暂共处又各奔前程的空间隐喻","jīchǎng shì rénlèi duǎnzàn gòngchù yòu gè bēn qiánchéng de kōngjiān yǐnyù","The airport is a spatial metaphor for humans briefly sharing space then going separate ways",True),
        o("旅行让人感到孤独","lǚxíng ràng rén gǎndào gūdú","Traveling makes people feel lonely"),
        o("航班经常延误","hángbān jīngcháng yánwù","Flights are often delayed")], 0.5)))

append_save("hsk8_batch2.json", P)
