# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "/Users/jasongerson/mandarin/content_gen")
from gen_helpers import *

P = []

# 1 - observe
P.append(passage("j8_observe_004",
    "The Geometry of Drying Laundry", "晾衣绳上的几何学", 8,
    "从我家阳台望出去，对面那栋老公寓的晾衣绳构成了一幅每天都不一样的抽象画。周一早晨，三楼的张阿姨会挂出一排白色的床单，它们在风中鼓胀成弧形，像一面面沉默的帆。四楼的年轻夫妇偏爱深色衣物，黑灰相间的T恤和牛仔裤垂直悬挂，形成一种工业感的节奏。五楼那位独居的老先生只晾两件东西：一件灰色的中山装和一条白毛巾，日复一日，从未改变。我曾试图从晾衣绳上解读每户人家的生活，就像考古学家从地层中推测文明的兴衰。床单的数量暗示家庭成员的多少，衣物的色彩透露审美倾向，晾晒的时间则反映作息规律。有一段时间，四楼突然只出现一个人的衣物，持续了大约三个月，然后又恢复了两个人的规模。我不知道那三个月里发生了什么，但晾衣绳忠实地记录了这段空白。在这个隐私被数据定义的时代，晾衣绳或许是最古老也最诚实的社交媒体——它从不美化，从不筛选，只是把生活最朴素的截面暴露在阳光下。",
    "Cóng wǒ jiā yángtái wàng chūqù, duìmiàn nà dòng lǎo gōngyù de liàngyīshéng gòuchéng le yī fú měi tiān dōu bù yīyàng de chōuxiàng huà. Zhōuyī zǎochén, sān lóu de Zhāng āyí huì guà chū yī pái báisè de chuángdān, tāmen zài fēng zhōng gǔzhàng chéng húxíng, xiàng yī miàn miàn chénmò de fān. Sì lóu de niánqīng fūfù piān'ài shēnsè yīwù, hēi huī xiāngjiàn de T xù hé niúzǎikù chuízhí xuánguà, xíngchéng yī zhǒng gōngyègǎn de jiézòu. Wǔ lóu nà wèi dújū de lǎo xiānshēng zhǐ liàng liǎng jiàn dōngxi: yī jiàn huīsè de zhōngshānzhuāng hé yī tiáo bái máojīn, rì fù yī rì, cóng wèi gǎibiàn. Wǒ céng shìtú cóng liàngyīshéng shàng jiědú měi hù rénjiā de shēnghuó, jiù xiàng kǎogǔ xuéjiā cóng dìcéng zhōng tuīcè wénmíng de xīngshuāi. Chuángdān de shùliàng ànshì jiātíng chéngyuán de duōshǎo, yīwù de sècǎi tòulù shěnměi qīngxiàng, liàngshài de shíjiān zé fǎnyìng zuòxī guīlǜ. Yǒu yī duàn shíjiān, sì lóu tūrán zhǐ chūxiàn yī gè rén de yīwù, chíxù le dàyuē sān gè yuè, ránhòu yòu huīfù le liǎng gè rén de guīmó. Wǒ bù zhīdào nà sān gè yuè lǐ fāshēng le shénme, dàn liàngyīshéng zhōngshí de jìlù le zhè duàn kòngbái. Zài zhège yǐnsī bèi shùjù dìngyì de shídài, liàngyīshéng huòxǔ shì zuì gǔlǎo yě zuì chéngshí de shèjiāo méitǐ——tā cóng bù měihuà, cóng bù shāixuǎn, zhǐshì bǎ shēnghuó zuì pǔsù de jiémiàn bàolù zài yángguāng xià.",
    "Looking out from my balcony, the clotheslines of the old apartment opposite form an abstract painting that changes every day. Monday mornings, Auntie Zhang on the third floor hangs white bedsheets that billow into arcs in the wind, like silent sails. The young couple on the fourth floor favors dark clothing—black and grey T-shirts and jeans hang vertically, creating an industrial rhythm. The elderly man living alone on the fifth floor dries only two things: a grey Mao suit and a white towel, day after day, never changing. I once tried to read each household's life from the clotheslines, the way an archaeologist infers the rise and fall of civilizations from strata. The number of bedsheets hints at family size, colors reveal aesthetic inclinations, and timing reflects daily routines. For a while, the fourth floor suddenly displayed only one person's clothing, lasting about three months, then returned to two. I don't know what happened during those three months, but the clothesline faithfully recorded the gap. In an age where privacy is defined by data, the clothesline is perhaps the oldest and most honest social media—it never embellishes, never filters, simply exposes the most unadorned cross-section of life to the sunlight.",
    mc("作者将晾衣绳比作「社交媒体」，核心观点是什么？",
       "What is the core point of comparing clotheslines to social media?",
       [o("晾衣绳展示的生活信息未经修饰，比网络社交更真实","liàngyīshéng zhǎnshì de shēnghuó xìnxī wèi jīng xiūshì, bǐ wǎngluò shèjiāo gèng zhēnshí","Clothesline information is unembellished, more authentic than online social media",True),
        o("晾衣绳是一种过时的通讯方式","liàngyīshéng shì yī zhǒng guòshí de tōngxùn fāngshì","Clotheslines are outdated communication"),
        o("人们应该减少使用社交媒体","rénmen yīnggāi jiǎnshǎo shǐyòng shèjiāo méitǐ","People should use social media less"),
        o("晾衣服会泄露个人隐私","liàng yīfu huì xièlù gèrén yǐnsī","Drying clothes leaks privacy")], 0.45),
    mc("四楼衣物数量变化的细节，在文中起到什么作用？",
       "What role does the fourth floor clothing change detail serve?",
       [o("说明晾衣绳能映射人际关系的变化","shuōmíng liàngyīshéng néng yìngshè rénjì guānxì de biànhuà","Shows clotheslines reflect relationship changes",True),
        o("批评年轻人的婚姻不稳定","pīpíng niánqīng rén de hūnyīn bù wěndìng","Criticizes unstable marriages"),
        o("表达作者对邻居的好奇心","biǎodá zuòzhě duì línjū de hàoqíxīn","Expresses curiosity about neighbors"),
        o("证明四楼夫妇经常出差","zhèngmíng sì lóu fūfù jīngcháng chūchāi","Proves the couple often travels for work")], 0.5),
    mc("作者用考古学家的类比，最主要想表达什么？",
       "What does the archaeologist analogy primarily convey?",
       [o("晾衣绳像地层一样保存着日常生活的痕迹","liàngyīshéng xiàng dìcéng yīyàng bǎocún zhe rìcháng shēnghuó de hénjì","Clotheslines preserve daily life traces like geological strata",True),
        o("考古学是一门有趣的学科","kǎogǔxué shì yī mén yǒuqù de xuékē","Archaeology is an interesting discipline"),
        o("老公寓应该被列为文化遗产","lǎo gōngyù yīnggāi bèi liè wéi wénhuà yíchǎn","Old apartments should be listed as heritage"),
        o("现代生活正在走向衰落","xiàndài shēnghuó zhèngzài zǒuxiàng shuāiluò","Modern life is in decline")], 0.45)))

# 2 - observe
P.append(passage("j8_observe_005",
    "The Temperature of Bookstores", "书店的温度", 8,
    "每座城市都有一种只能在独立书店里感受到的温度，它与空调无关，而是一种由纸张气味、木质书架和阅读者的呼吸共同构成的微气候。我走访过四十多家独立书店，发现它们都有一个共同特征：空气中弥漫着一种令人安心的迟缓感。在书店里，时间的流速似乎自动放慢了。人们翻书的动作是慢的，脚步是轻的，连交谈都压低了声音，仿佛每个人都自觉地遵守着一项从未被宣布的协议。我特别留意过书店里的声音层次：最底层是空调或暖气的低频嗡鸣，中间层是翻动纸页的沙沙声，最上层偶尔会出现收银台的轻声对话。这三层声音叠加在一起，构成了一种独特的声学环境，我称之为「书店白噪音」。它与咖啡馆的白噪音截然不同——咖啡馆的背景音是社交性的，而书店的背景音是内省性的。当一家独立书店关闭时，消失的不仅是一个售书的场所，而是一种特定的空间气质。连锁书店可以复制选品和装修，却无法复制那种由时间沉淀出来的温度。",
    "Měi zuò chéngshì dōu yǒu yī zhǒng zhǐ néng zài dúlì shūdiàn lǐ gǎnshòu dào de wēndù, tā yǔ kōngtiáo wúguān, ér shì yī zhǒng yóu zhǐzhāng qìwèi, mùzhì shūjià hé yuèdúzhě de hūxī gòngtóng gòuchéng de wēi qìhòu. Wǒ zǒufǎng guò sìshí duō jiā dúlì shūdiàn, fāxiàn tāmen dōu yǒu yī gè gòngtóng tèzhēng: kōngqì zhōng mímàn zhe yī zhǒng lìng rén ānxīn de chíhuǎn gǎn. Zài shūdiàn lǐ, shíjiān de liúsù sìhū zìdòng fàngmàn le. Rénmen fān shū de dòngzuò shì màn de, jiǎobù shì qīng de, lián jiāotán dōu yā dī le shēngyīn, fǎngfú měi gè rén dōu zìjué de zūnshǒu zhe yī xiàng cóng wèi bèi xuānbù de xiéyì. Wǒ tèbié liúyì guò shūdiàn lǐ de shēngyīn céngcì: zuì dǐcéng shì kōngtiáo huò nuǎnqì de dīpín wēngmíng, zhōngjiān céng shì fāndòng zhǐyè de shāshā shēng, zuì shàngcéng ǒu'ěr huì chūxiàn shōuyíntái de qīngshēng duìhuà. Zhè sān céng shēngyīn diéjiā zài yīqǐ, gòuchéng le yī zhǒng dútè de shēngxué huánjìng, wǒ chēng zhī wéi shūdiàn bái zàoyīn. Tā yǔ kāfēiguǎn de bái zàoyīn jiérán bùtóng——kāfēiguǎn de bèijǐngyīn shì shèjiāoxìng de, ér shūdiàn de bèijǐngyīn shì nèixǐngxìng de. Dāng yī jiā dúlì shūdiàn guānbì shí, xiāoshī de bùjǐn shì yī gè shòu shū de chǎngsuǒ, ér shì yī zhǒng tèdìng de kōngjiān qìzhì. Liánsuǒ shūdiàn kěyǐ fùzhì xuǎnpǐn hé zhuāngxiū, què wúfǎ fùzhì nà zhǒng yóu shíjiān chéndiàn chūlái de wēndù.",
    "Every city has a temperature that can only be felt inside an independent bookstore, one that has nothing to do with air conditioning but is a microclimate composed of the smell of paper, wooden shelves, and readers' breathing. I have visited over forty independent bookstores and found they share a common trait: the air is permeated with a reassuring sense of slowness. Inside a bookstore, time seems to decelerate automatically. People turn pages slowly, walk lightly, and even lower their voices when speaking, as though everyone voluntarily obeys an agreement never announced. I've paid attention to layers of sound in bookstores: the lowest layer is the low-frequency hum of air conditioning or heating, the middle layer is the rustle of turning pages, and the top layer occasionally includes quiet conversation at the register. These three layers combine to form a unique acoustic environment I call bookstore white noise. It differs fundamentally from cafe white noise—a cafe's background sound is social, while a bookstore's is introspective. When an independent bookstore closes, what disappears is not merely a place that sells books, but a specific spatial temperament. Chain bookstores can replicate selections and decor, but they cannot replicate the temperature that only time can sediment.",
    mc("作者所说的「温度」在文中指的是什么？",
       "What does the author's 'temperature' refer to in the text?",
       [o("书店内部的实际气温","shūdiàn nèibù de shíjì qìwēn","The actual air temperature inside the bookstore"),
        o("由时间和人文因素沉淀而成的空间气质","yóu shíjiān hé rénwén yīnsù chéndiàn ér chéng de kōngjiān qìzhì","A spatial temperament formed through sedimentation of time and human factors",True),
        o("读者对书店的好评程度","dúzhě duì shūdiàn de hǎopíng chéngdù","Readers' positive review ratings"),
        o("纸张发热产生的物理温度","zhǐzhāng fārè chǎnshēng de wùlǐ wēndù","Physical heat generated by paper")], 0.5),
    mc("作者区分「书店白噪音」和「咖啡馆白噪音」的标准是什么？",
       "What criterion distinguishes bookstore white noise from cafe white noise?",
       [o("音量的大小","yīnliàng de dàxiǎo","The volume level"),
        o("声音的性质是内省性的还是社交性的","shēngyīn de xìngzhì shì nèixǐngxìng de háishì shèjiāoxìng de","Whether the sound is introspective or social",True),
        o("是否包含音乐","shìfǒu bāohán yīnyuè","Whether music is included"),
        o("顾客人数的差异","gùkè rénshù de chāyì","Difference in customer numbers")], 0.45),
    mc("文末提到连锁书店「无法复制」独立书店的什么？",
       "What can chain bookstores 'not replicate' about independent bookstores?",
       [o("书籍种类和室内设计","shūjí zhǒnglèi hé shìnèi shèjì","Book selection and interior design"),
        o("低廉的价格和便利的位置","dīlián de jiàgé hé biànlì de wèizhì","Low prices and convenient location"),
        o("由时间积累形成的独特空间气质","yóu shíjiān jīlěi xíngchéng de dútè kōngjiān qìzhì","The unique spatial temperament formed through accumulation of time",True),
        o("店主的个人品味","diànzhǔ de gèrén pǐnwèi","The owner's personal taste")], 0.4)))

# 3 - urban
P.append(passage("j8_urban_001",
    "The Night Shift City", "夜班城市", 8,
    "凌晨三点的城市并不像人们想象的那样安静。它只是换了一套运行系统。便利店的灯光在空无一人的街道上投下方形的白色光斑，店员靠在柜台上翻看手机，关东煮的汤还在冒着细密的蒸汽。环卫工人推着橘色的手推车沿固定路线移动，他们的路线图与白天的交通网络完全重合，只是行驶在上面的不再是汽车而是扫帚。出租车司机在固定的路口停靠等客，车内的暖光从侧窗透出来，远远看去像一串低垂的灯笼。医院急诊室是这座夜间城市唯一灯火通明的公共空间，它二十四小时运转，对时间的划分方式与普通人截然不同。我在这个城市生活了十五年，却是在开始上夜班之后才真正认识了它。白天的城市属于效率、竞争和社交规则，而夜班城市属于另一群人——他们维持着城市运转的基本底线，却几乎不被看见。当你清晨醒来看到干净的街道时，那并不是自然的状态，而是有人在你睡着的时候替你完成的。",
    "Língchén sān diǎn de chéngshì bìng bú xiàng rénmen xiǎngxiàng de nàyàng ānjìng. Tā zhǐshì huàn le yī tào yùnxíng xìtǒng. Biànlìdiàn de dēngguāng zài kōng wú yī rén de jiēdào shàng tóu xià fāngxíng de báisè guāngbān, diànyuán kào zài guìtái shàng fānkàn shǒujī, guāndōngzhǔ de tāng hái zài mào zhe xìmì de zhēngqì. Huánwèi gōngrén tuī zhe júsè de shǒutuīchē yán gùdìng lùxiàn yídòng, tāmen de lùxiàntú yǔ báitiān de jiāotōng wǎngluò wánquán chónghé, zhǐshì xíngshǐ zài shàngmiàn de bú zài shì qìchē ér shì sàozhou. Chūzūchē sījī zài gùdìng de lùkǒu tíngkào děng kè, chē nèi de nuǎn guāng cóng cèchuāng tòu chūlái, yuǎnyuǎn kàn qù xiàng yī chuàn dī chuí de dēnglóng. Yīyuàn jízhěnshì shì zhè zuò yèjiān chéngshì wéiyī dēnghuǒ tōngmíng de gōnggòng kōngjiān, tā èrshísì xiǎoshí yùnzhuǎn, duì shíjiān de huàfēn fāngshì yǔ pǔtōng rén jiérán bùtóng. Wǒ zài zhège chéngshì shēnghuó le shíwǔ nián, què shì zài kāishǐ shàng yèbān zhīhòu cái zhēnzhèng rènshi le tā. Báitiān de chéngshì shǔyú xiàolǜ, jìngzhēng hé shèjiāo guīzé, ér yèbān chéngshì shǔyú lìng yī qún rén——tāmen wéichí zhe chéngshì yùnzhuǎn de jīběn dǐxiàn, què jīhū bú bèi kànjiàn. Dāng nǐ qīngchén xǐnglái kàn dào gānjìng de jiēdào shí, nà bìng bú shì zìrán de zhuàngtài, ér shì yǒu rén zài nǐ shuìzháo de shíhou tì nǐ wánchéng de.",
    "The city at three in the morning is not as quiet as people imagine. It has merely switched to a different operating system. Convenience store lights cast square white patches on deserted streets, the clerk leans against the counter scrolling a phone, and the oden soup still sends up fine wisps of steam. Sanitation workers push orange carts along fixed routes—their maps overlap perfectly with the daytime traffic network, only now what travels the roads is brooms, not cars. Taxi drivers park at designated intersections waiting for fares, warm light seeping through side windows, looking from afar like low-hanging lanterns. The hospital emergency room is the only brightly lit public space in this nocturnal city, running twenty-four hours with a way of dividing time entirely unlike ordinary people's. I lived in this city for fifteen years, yet truly came to know it only after starting night shifts. The daytime city belongs to efficiency, competition, and social rules, while the night-shift city belongs to another group—those who maintain the basic floor of urban functioning yet are almost never seen. When you wake to clean streets in the morning, that is not a natural state; someone completed it for you while you slept.",
    mc("作者说城市在凌晨「换了一套运行系统」，这意味着什么？",
       "What does 'switching to a different operating system' mean?",
       [o("城市的基础设施在夜间进行维修","chéngshì de jīchǔ shèshī zài yèjiān jìnxíng wéixiū","Infrastructure undergoes maintenance at night"),
        o("城市由不同的人群以不同的逻辑在维持运转","chéngshì yóu bùtóng de rénqún yǐ bùtóng de luójí zài wéichí yùnzhuǎn","The city is kept running by different people with different logic",True),
        o("夜间的电脑系统与白天不同","yèjiān de diànnǎo xìtǒng yǔ báitiān bùtóng","Nighttime computer systems differ from daytime"),
        o("城市在夜间完全停止运作","chéngshì zài yèjiān wánquán tíngzhǐ yùnzuò","The city completely stops at night")], 0.45),
    mc("作者对夜班工作者的态度可以概括为：",
       "The author's attitude toward night-shift workers is:",
       [o("同情他们的辛苦并呼吁改善待遇","tóngqíng tāmen de xīnkǔ bìng hūyù gǎishàn dàiyù","Sympathy and calling for better treatment"),
        o("敬意与反思——他们维持城市运转却不被看见","jìngyì yǔ fǎnsī——tāmen wéichí chéngshì yùnzhuǎn què bú bèi kànjiàn","Respect and reflection—they maintain the city yet go unseen",True),
        o("羡慕夜班生活的自由","xiànmù yèbān shēnghuó de zìyóu","Envying the freedom of night-shift life"),
        o("客观记录，不带任何情感","kèguān jìlù, bú dài rènhé qínggǎn","Objective recording without emotion")], 0.5),
    mc("文末「那并不是自然的状态」的深层含义是：",
       "The deeper meaning of 'that is not a natural state' is:",
       [o("城市清洁需要使用化学物质","chéngshì qīngjié xūyào shǐyòng huàxué wùzhì","City cleaning requires chemicals"),
        o("街道本来就不会脏","jiēdào běnlái jiù bú huì zāng","Streets wouldn't get dirty naturally"),
        o("我们习以为常的整洁背后有隐形劳动者的付出","wǒmen xí yǐ wéi cháng de zhěngjié bèihòu yǒu yǐnxíng láodòngzhě de fùchū","Behind the cleanliness we take for granted is invisible laborers' effort",True),
        o("自然界本身是混乱的","zìránjiè běnshēn shì hùnluàn de","Nature itself is chaotic")], 0.45)))

# 4 - observe
P.append(passage("j8_observe_006",
    "The Patience of Repair Shops", "修理铺的耐心", 8,
    "在我住的那条老街上，有一家修伞铺、一家修鞋铺和一家修钟表的小店。它们夹在奶茶店和快递驿站之间，显得格外突兀，像三个从另一个时代穿越来的幸存者。修伞的老周每天上午九点准时开门，在一张磨得发亮的木桌前坐下，戴上老花镜，等待顾客。他有时一整个上午都没有生意，就坐在那里磨伞骨上的锈迹，那种专注的神情像极了外科医生。我问他为什么不转行做更赚钱的生意，他想了想说：「这条街上已经没有人会修伞了，我要是也不修了，大家就只能扔掉再买新的。」这句话听起来平淡，却包含了一种朴素的伦理观：修复比替代更有尊严。修鞋的陈师傅说得更直接：「一双好鞋，修修补补能穿十年。现在的人买鞋跟买菜似的，穿一季就扔。」钟表铺的刘阿姨则几乎从不说话，她用一把小得不可思议的螺丝刀在表盘内部操作，偶尔会把某个零件举到灯下端详很久。这三家店的共同之处在于：它们都在对抗一种叫做「一次性文化」的潮流，用一种近乎固执的耐心。",
    "Zài wǒ zhù de nà tiáo lǎojiē shàng, yǒu yī jiā xiū sǎn pù, yī jiā xiū xié pù hé yī jiā xiū zhōngbiǎo de xiǎo diàn. Tāmen jiā zài nǎichá diàn hé kuàidì yìzhàn zhījiān, xiǎn de géwài tūwù, xiàng sān gè cóng lìng yī gè shídài chuānyuè lái de xìngcúnzhě. Xiū sǎn de lǎo Zhōu měi tiān shàngwǔ jiǔ diǎn zhǔnshí kāimén, zài yī zhāng mó de fāliàng de mùzhuō qián zuò xià, dài shàng lǎohuā jìng, děngdài gùkè. Tā yǒushí yī zhěnggè shàngwǔ dōu méiyǒu shēngyì, jiù zuò zài nàlǐ mó sǎngǔ shàng de xiùjì, nà zhǒng zhuānzhù de shénqíng xiàng jí le wàikē yīshēng. Wǒ wèn tā wèishéme bù zhuǎnháng zuò gèng zhuànqián de shēngyì, tā xiǎng le xiǎng shuō: zhè tiáo jiē shàng yǐjīng méiyǒu rén huì xiū sǎn le, wǒ yàoshi yě bù xiū le, dàjiā jiù zhǐ néng rēngdiào zài mǎi xīn de. Zhè jù huà tīng qǐlái píngdàn, què bāohán le yī zhǒng pǔsù de lúnlǐguān: xiūfù bǐ tìdài gèng yǒu zūnyán.",
    "On the old street where I live, there is an umbrella repair shop, a shoe repair shop, and a small watch repair store. Wedged between a milk tea shop and a courier station, they look strikingly out of place, like three survivors from another era. Old Zhou the umbrella mender opens at nine each morning, sits at a wooden table polished smooth by years of use, puts on reading glasses, and waits. Sometimes he has no business all morning, so he scrubs rust off umbrella ribs with the focus of a surgeon. I asked him why he doesn't switch to something more profitable. He thought and said: 'Nobody on this street can fix umbrellas anymore. If I stop too, people can only throw them away and buy new ones.' The words sound plain but contain a simple ethics: repair has more dignity than replacement. Cobbler Chen is more direct: 'A good pair of shoes, patched up, can last ten years. People nowadays buy shoes like vegetables—wear them one season and toss them.' Auntie Liu at the watch shop almost never speaks. She works inside watch faces with an impossibly small screwdriver, occasionally lifting a part to the lamplight to study it. What these three shops share: they all resist a trend called disposable culture, with a patience bordering on stubbornness.",
    mc("老周坚持修伞的核心理由是什么？",
       "What is Old Zhou's core reason for continuing to repair umbrellas?",
       [o("修伞利润比看起来高","xiū sǎn lìrùn bǐ kàn qǐlái gāo","Umbrella repair is more profitable than it looks"),
        o("如果他也停了，这项技能在街区就彻底消失了","rúguǒ tā yě tíng le, zhè xiàng jìnéng zài jiēqū jiù chèdǐ xiāoshī le","If he stops too, this skill will vanish from the neighborhood",True),
        o("他年纪大了无法学习新技能","tā niánjì dà le wúfǎ xuéxí xīn jìnéng","He's too old to learn new skills"),
        o("房东给他的租金很便宜","fángdōng gěi tā de zūjīn hěn piányí","His landlord charges low rent")], 0.4),
    mc("作者用「外科医生」来形容老周，最主要想表达什么？",
       "What does comparing Old Zhou to a 'surgeon' primarily express?",
       [o("修伞和外科手术一样复杂","xiū sǎn hé wàikē shǒushù yīyàng fùzá","Umbrella repair is as complex as surgery"),
        o("老周对修理工作投入了与医生同等级的专注和尊重","lǎo Zhōu duì xiūlǐ gōngzuò tóurù le yǔ yīshēng tóng děngjí de zhuānzhù hé zūnzhòng","Old Zhou brings a surgeon's level of focus and respect to his work",True),
        o("老周曾经是一名医生","lǎo Zhōu céngjīng shì yī míng yīshēng","Old Zhou was once a doctor"),
        o("修伞需要精密的工具","xiū sǎn xūyào jīngmì de gōngjù","Umbrella repair requires precision tools")], 0.45),
    mc("文章认为「修复比替代更有尊严」，这里的「尊严」指的是什么？",
       "What does 'dignity' mean when the article says 'repair has more dignity than replacement'?",
       [o("修理工人的社会地位","xiūlǐ gōngrén de shèhuì dìwèi","The social status of repair workers"),
        o("对物品价值和人类劳动的尊重","duì wùpǐn jiàzhí hé rénlèi láodòng de zūnzhòng","Respect for the value of objects and human labor",True),
        o("手工艺品比工业品更贵","shǒugōngyì pǐn bǐ gōngyè pǐn gèng guì","Handicrafts are more expensive"),
        o("旧东西比新东西更好用","jiù dōngxi bǐ xīn dōngxi gèng hǎo yòng","Old things work better than new ones")], 0.5)))

# 5 - inst
P.append(passage("j8_inst_001",
    "The Unwritten Rules of the Public Library", "公共图书馆的潜规则", 8,
    "公共图书馆是一个由无数不成文规则维持秩序的空间。没有任何一块告示牌会告诉你：自习室里最靠窗的那排座位属于考研的学生，他们从早上开馆就来占座，桌上堆满了颜色各异的参考书和保温杯；中间几排是退休老人的领地，他们看报纸，偶尔小声交谈，享受的不是阅读本身而是一种公共空间的陪伴感；最后两排靠近电源插座的位置则被自由职业者和远程工作者默默瓜分，他们的标志性配置是笔记本电脑加一副耳机。这套座位分配系统从未被明文规定，却运行得异常稳定。偶尔有不知情的新来者坐错位置，会收到周围人微妙的目光提示——不是敌意，而是一种温和的纠偏信号。我在这座图书馆观察了两年，发现这套系统的核心逻辑是：人们根据自己对时间的使用方式来选择座位。考研学生需要专注所以选择窗边的光线，老人需要社交所以选择中间区域，远程工作者需要电源所以选择后排。当一个空间允许人们自发地形成秩序，而不是用规章制度去规定秩序，这个空间就获得了一种有机的生命力。",
    "Gōnggòng túshūguǎn shì yī gè yóu wúshù bù chéngwén guīzé wéichí zhìxù de kōngjiān. Méiyǒu rènhé yī kuài gàoshìpái huì gàosu nǐ: zìxíshì lǐ zuì kào chuāng de nà pái zuòwèi shǔyú kǎoyán de xuéshēng, tāmen cóng zǎoshang kāiguǎn jiù lái zhàn zuò, zhuō shàng duī mǎn le yánsè gè yì de cānkǎoshū hé bǎowēnbēi; zhōngjiān jǐ pái shì tuìxiū lǎorén de lǐngdì, tāmen kàn bàozhǐ, ǒu'ěr xiǎoshēng jiāotán, xiǎngshòu de bú shì yuèdú běnshēn ér shì yī zhǒng gōnggòng kōngjiān de péibàngǎn; zuìhòu liǎng pái kàojìn diànyuán chāzuò de wèizhì zé bèi zìyóu zhíyèzhě hé yuǎnchéng gōngzuòzhě mòmò guāfēn, tāmen de biāozhìxìng pèizhì shì bǐjìběn diànnǎo jiā yī fù ěrjī. Zhè tào zuòwèi fēnpèi xìtǒng cóng wèi bèi míngwén guīdìng, què yùnxíng de yìcháng wěndìng.",
    "A public library is a space maintained by countless unwritten rules. No sign tells you that window-side seats in the study room belong to graduate exam students, who arrive at opening to claim spots with colorful reference books and thermos cups; the middle rows are retirees' territory, who read newspapers and occasionally chat softly, enjoying not reading itself but a sense of companionship in public space; the last two rows near outlets are silently divided among freelancers and remote workers, whose signature setup is a laptop plus headphones. This seating system has never been formally established yet runs remarkably stably. When a newcomer sits in the wrong spot, they receive subtle glances—not hostile, but a gentle corrective signal. I observed this library for two years and found the core logic: people choose seats based on how they use time. Exam students need focus and choose window light, retirees need social contact and choose the middle, remote workers need power and choose the back. When a space allows people to spontaneously form order rather than imposing it through regulations, that space acquires organic vitality.",
    mc("作者认为图书馆座位分配系统的核心逻辑是什么？",
       "What is the core logic of the library seating system?",
       [o("先到先得的竞争原则","xiān dào xiān dé de jìngzhēng yuánzé","First-come-first-served competition"),
        o("人们根据自己使用时间的方式选择座位","rénmen gēnjù zìjǐ shǐyòng shíjiān de fāngshì xuǎnzé zuòwèi","People choose seats based on how they use time",True),
        o("图书馆管理员的暗中安排","túshūguǎn guǎnlǐyuán de ànzhōng ānpái","Secret arrangements by the librarian"),
        o("年龄和社会地位的等级制度","niánlíng hé shèhuì dìwèi de děngjí zhìdù","A hierarchy of age and social status")], 0.4),
    mc("退休老人选择中间区域的根本原因是什么？",
       "Why do retirees fundamentally choose the middle area?",
       [o("中间区域光线最好","zhōngjiān qūyù guāngxiàn zuì hǎo","The middle has the best lighting"),
        o("他们来图书馆是为了享受公共陪伴感","tāmen lái túshūguǎn shì wèile xiǎngshòu gōnggòng péibàngǎn","They come for a sense of public companionship",True),
        o("中间座位最舒服","zhōngjiān zuòwèi zuì shūfu","Middle seats are most comfortable"),
        o("其他座位已经被占了","qítā zuòwèi yǐjīng bèi zhàn le","Other seats are already taken")], 0.4),
    mc("作者对这种自发形成的秩序持什么态度？",
       "What is the author's attitude toward this spontaneous order?",
       [o("认为它效率低下，应该用规章替代","rènwéi tā xiàolǜ dīxià, yīnggāi yòng guīzhāng tìdài","Considers it inefficient, should be replaced by regulations"),
        o("欣赏它赋予空间的有机生命力","xīnshǎng tā fùyǔ kōngjiān de yǒujī shēngmìnglì","Appreciates the organic vitality it gives the space",True),
        o("担忧它会导致冲突","dānyōu tā huì dǎozhì chōngtū","Worries it will lead to conflicts"),
        o("认为它只是巧合，没有深层含义","rènwéi tā zhǐshì qiǎohé, méiyǒu shēncéng hányì","Considers it mere coincidence")], 0.4)))

save("hsk8_batch2.json", P)
