# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "/Users/jasongerson/mandarin/content_gen")
from gen_helpers import *

P = []

# 1 - observe
P.append(passage("j8_observe_011",
    "The Archaeology of Desk Drawers", "书桌抽屉的考古学", 8,
    "搬家时整理书桌抽屉，我发现了一套完整的个人编年史。最上层是近期的杂物：几张快递单、一根断了的数据线、两颗已经没电的纽扣电池。往下是两三年前的痕迹：一张过期的健身卡——当时信誓旦旦要每周去三次，实际只去了两个月；几支笔帽丢失的圆珠笔；一本只写了三页的日记本。再往下，抽屉的底部是真正的「地层」：一封十年前朋友寄来的明信片，邮戳模糊但字迹依然清晰；一把钥匙，我已经记不清它属于哪扇门；一张泛黄的照片，背面用铅笔写着一个日期和一个地名。每一层都代表了一段被遗忘又被意外挖掘出来的时光。最让我感慨的不是那些物品本身，而是每一件物品所代表的、我曾经的某个打算：那张健身卡是想变得更健康的决心，那本日记是想记录生活的愿望，那把钥匙通向一个我已经遗忘的空间。抽屉就是这样一个地方：它收容了所有我们曾经在意但最终搁置的事物，直到搬家这种强制性的清理迫使我们与自己的过去重新相遇。",
    "Bānjiā shí zhěnglǐ shūzhuō chōutì, wǒ fāxiàn le yī tào wánzhěng de gèrén biānniánshǐ. Zuì shàngcéng shì jìnqī de záwù: jǐ zhāng kuàidì dān, yī gēn duàn le de shùjù xiàn, liǎng kē yǐjīng méi diàn de niǔkòu diànchí.",
    "While sorting desk drawers for a move, I discovered a complete personal chronicle. The top layer held recent clutter: delivery receipts, a broken data cable, two dead button batteries. Below were traces from two to three years ago: an expired gym card—I had sworn to go three times weekly, actually went two months; pens missing their caps; a diary with only three pages written. At the very bottom lay the true strata: a postcard from a friend ten years ago, postmark blurred but handwriting still clear; a key I can no longer remember which door it opens; a yellowed photo with a date and place name penciled on the back. Each layer represented a period forgotten then accidentally excavated. What moved me most was not the objects themselves but the intentions each represented: the gym card was a resolve to be healthier, the diary a wish to record life, the key led to a space I've forgotten. A drawer is a place that shelters everything we once cared about but ultimately set aside, until the forced clearing of moving compels us to re-encounter our own past.",
    mc("作者发现抽屉的分层结构与什么相似？",
       "What does the author find the drawer's layered structure resembles?",
       [o("图书馆的分类系统","túshūguǎn de fēnlèi xìtǒng","A library's classification system"),
        o("考古地层中时间的沉积","kǎogǔ dìcéng zhōng shíjiān de chénjī","The sedimentation of time in archaeological strata",True),
        o("搬家公司的打包方式","bānjiā gōngsī de dǎbāo fāngshì","A moving company's packing method"),
        o("电脑文件夹的层级结构","diànnǎo wénjiànjiā de céngjí jiégòu","The hierarchical structure of computer folders")], 0.4),
    mc("作者感慨的核心不是物品本身，而是什么？",
       "What moves the author is not the objects themselves but what?",
       [o("物品的经济价值","wùpǐn de jīngjì jiàzhí","The objects' economic value"),
        o("每件物品背后代表的、曾经在意但最终搁置的打算","měi jiàn wùpǐn bèihòu dàibiǎo de, céngjīng zàiyì dàn zuìzhōng gēzhì de dǎsuàn","The intentions behind each object—things once cared about but ultimately shelved",True),
        o("对过去生活的怀旧情感","duì guòqù shēnghuó de huáijiù qínggǎn","Nostalgia for past life"),
        o("自己的记忆力在变差","zìjǐ de jìyìlì zài biàn chà","His memory is getting worse")], 0.5),
    mc("作者说「搬家迫使我们与自己的过去重新相遇」，这意味着什么？",
       "What does 'moving forces us to re-encounter our own past' mean?",
       [o("搬家太累了","bānjiā tài lèi le","Moving is exhausting"),
        o("清理积存的物品时，我们被迫面对自己曾有但已放弃的生活计划","qīnglǐ jīcún de wùpǐn shí, wǒmen bèipò miànduì zìjǐ céng yǒu dàn yǐ fàngqì de shēnghuó jìhuà","While clearing accumulated items, we're forced to face life plans we once had but abandoned",True),
        o("旧东西应该及时扔掉","jiù dōngxi yīnggāi jíshí rēngdiào","Old things should be discarded promptly"),
        o("搬家让人回忆起过去的邻居","bānjiā ràng rén huíyì qǐ guòqù de línjū","Moving reminds people of past neighbors")], 0.45)))

# 2 - urban
P.append(passage("j8_urban_004",
    "The Grammar of Convenience Stores", "便利店的语法", 8,
    "便利店是城市的标点符号——它不构成主语或谓语，但没有它，城市的句子就会变得不可读。我住的小区周围一公里以内有七家便利店，每一家都有自己不同的「语法功能」。巷口那家是「逗号」，早晨上班的人在这里暂停两分钟，买一杯咖啡和一个饭团，然后继续赶路。公司楼下那家是「分号」，午休时承接上半天与下半天之间的过渡，人们在这里买一份便当和一瓶水。地铁站旁边那家是「连接词」，把地下交通系统和地面生活无缝衔接。而我家楼下那家深夜还亮着灯的小店，是「句号」——一天结束前最后一个文明的据点，你可以在这里买到明天早餐的牛奶和今晚失眠时可能需要的零食。便利店的本质不是零售，而是一种空间服务：它填充了城市肌理中那些微小的空隙——太晚了超市已关门，太早了餐厅还没开，太累了不想自己做饭。它永远在你需要的时候存在，却从不要求你的注意力。这是一种极其谦逊的商业形态。",
    "Biànlìdiàn shì chéngshì de biāodiǎn fúhào——tā bù gòuchéng zhǔyǔ huò wèiyǔ, dàn méiyǒu tā, chéngshì de jùzi jiù huì biàn de bùkě dú.",
    "Convenience stores are a city's punctuation marks—they don't form subject or predicate, but without them the city's sentences become unreadable. Within one kilometer of my neighborhood there are seven, each with its own 'grammatical function.' The one at the alley entrance is a 'comma,' where morning commuters pause two minutes for coffee and a rice ball before continuing. The one below the office is a 'semicolon,' bridging the transition between morning and afternoon during lunch break. The one by the subway station is a 'conjunction,' seamlessly linking underground transit and surface life. The one below my apartment still lit late at night is a 'period'—the last outpost of civilization before day's end, where you buy tomorrow's breakfast milk and snacks for tonight's potential insomnia. The essence of convenience stores is not retail but spatial service: they fill the tiny gaps in urban texture—too late for supermarkets, too early for restaurants, too tired to cook. They exist whenever you need them, yet never demand your attention. This is an extraordinarily humble form of commerce.",
    mc("作者将便利店比作「标点符号」，核心含义是什么？",
       "What is the core meaning of comparing convenience stores to punctuation marks?",
       [o("便利店很小，不起眼","biànlìdiàn hěn xiǎo, bù qǐyǎn","Convenience stores are small and inconspicuous"),
        o("便利店虽不是城市的核心功能，但没有它城市生活就无法流畅运转","biànlìdiàn suī bú shì chéngshì de héxīn gōngnéng, dàn méiyǒu tā chéngshì shēnghuó jiù wúfǎ liúchàng yùnzhuǎn","Though not a city's core function, without them urban life cannot run smoothly",True),
        o("便利店的数量太多了","biànlìdiàn de shùliàng tài duō le","There are too many convenience stores"),
        o("便利店应该在固定时间营业","biànlìdiàn yīnggāi zài gùdìng shíjiān yíngyè","Convenience stores should operate at fixed times")], 0.45),
    mc("作者为什么说便利店是「极其谦逊的商业形态」？",
       "Why does the author call convenience stores an 'extraordinarily humble form of commerce'?",
       [o("便利店的利润很低","biànlìdiàn de lìrùn hěn dī","Convenience store profits are low"),
        o("它在你需要时存在却从不要求你的注意力","tā zài nǐ xūyào shí cúnzài què cóng bù yāoqiú nǐ de zhùyìlì","It exists when you need it but never demands your attention",True),
        o("便利店的装修很简朴","biànlìdiàn de zhuāngxiū hěn jiǎnpǔ","Convenience store decor is simple"),
        o("便利店不做广告","biànlìdiàn bú zuò guǎnggào","Convenience stores don't advertise")], 0.45),
    mc("深夜便利店被比作「句号」的原因是什么？",
       "Why is the late-night convenience store compared to a 'period'?",
       [o("它是一天中最后一个可以获得服务的文明据点","tā shì yī tiān zhōng zuìhòu yī gè kěyǐ huòdé fúwù de wénmíng jùdiǎn","It is the last civilized outpost where you can get service before day's end",True),
        o("它每天在固定时间关门","tā měi tiān zài gùdìng shíjiān guānmén","It closes at a fixed time every day"),
        o("它的商品种类最少","tā de shāngpǐn zhǒnglèi zuì shǎo","It has the fewest product varieties"),
        o("它是最后一家还在营业的商店","tā shì zuìhòu yī jiā hái zài yíngyè de shāngdiàn","It's the last store still operating")], 0.4)))

# 3 - inst
P.append(passage("j8_inst_003",
    "The Post Office as Living Museum", "作为活体博物馆的邮局", 8,
    "我家附近有一间建于一九五二年的老邮局，至今仍在营业。走进去的第一感觉是时间在这里流速不同。柜台上方的电子叫号屏是唯一的现代元素，其余一切——水磨石地面、木质柜台、铁栏杆窗口——都保留着半个世纪前的样子。工作人员的操作方式也明显更慢：她们用手写体填单子，用橡皮图章逐一盖邮戳，把包裹放在一台老式台秤上称重。排队的人大多是五十岁以上的老人，他们来寄信、取汇款、交水电费——这些事情在手机上都能完成，但他们坚持亲自来。我问过一位每月都来交电费的陈大爷为什么不用手机。他说：「在手机上按几下就完了，太快了，感觉不像真的做了一件事。来这里，排个队，跟窗口的小姑娘说说话，拿到一张盖了章的收据，这才踏实。」邮局对这些老人来说不是一个办理业务的场所，而是一个仪式空间——他们用排队和盖章来确认自己仍然在这个社会系统中占有一个位置。当效率成为唯一的价值标准时，我们可能忘记了：对有些人来说，慢本身就是一种存在的证明。",
    "Wǒ jiā fùjìn yǒu yī jiān jiàn yú yī jiǔ wǔ èr nián de lǎo yóujú, zhìjīn réng zài yíngyè. Zǒu jìnqù de dì yī gǎnjué shì shíjiān zài zhèlǐ liúsù bùtóng.",
    "Near my home there's a post office built in 1952, still operating. Walking in, the first sensation is that time flows differently here. The electronic number display above the counter is the only modern element; everything else—terrazzo floor, wooden counter, iron-barred windows—remains as it was half a century ago. Staff operate noticeably slower: they fill forms by hand, stamp each postmark with rubber stamps, weigh parcels on an old-fashioned scale. Most people in line are over fifty, coming to mail letters, collect remittances, pay utility bills—all doable on a phone, yet they insist on coming in person. I asked Uncle Chen, who comes monthly to pay his electric bill, why not use his phone. He said: 'On the phone you tap a few times and it's done. Too fast. Doesn't feel like you've actually done something. Coming here, standing in line, chatting with the girl at the window, getting a stamped receipt—that feels real.' For these elderly people the post office is not a place to conduct business but a ritual space—they use queuing and stamps to confirm they still occupy a position in the social system. When efficiency becomes the only standard of value, we may forget: for some people, slowness itself is proof of existence.",
    mc("陈大爷坚持亲自去邮局交电费的根本原因是什么？",
       "What is Uncle Chen's fundamental reason for going to the post office in person?",
       [o("他不会用手机","tā bú huì yòng shǒujī","He doesn't know how to use a phone"),
        o("亲身参与的仪式感让他确认自己仍存在于社会系统中","qīnshēn cānyù de yíshìgǎn ràng tā quèrèn zìjǐ réng cúnzài yú shèhuì xìtǒng zhōng","The ritual of personal participation confirms he still exists within the social system",True),
        o("邮局的服务费更便宜","yóujú de fúwùfèi gèng piányí","Post office service fees are cheaper"),
        o("他不信任网上支付的安全性","tā bú xìnrèn wǎngshàng zhīfù de ānquánxìng","He doesn't trust online payment security")], 0.5),
    mc("作者说「慢本身就是一种存在的证明」，这句话的深层含义是什么？",
       "What is the deeper meaning of 'slowness itself is proof of existence'?",
       [o("效率不是唯一的价值标准，参与过程本身对人有确认存在的意义","xiàolǜ bú shì wéiyī de jiàzhí biāozhǔn, cānyù guòchéng běnshēn duì rén yǒu quèrèn cúnzài de yìyì","Efficiency is not the only value standard; the process of participation itself confirms one's existence",True),
        o("老年人动作慢是正常的","lǎonián rén dòngzuò màn shì zhèngcháng de","It's normal for elderly people to move slowly"),
        o("邮局应该保持传统做法","yóujú yīnggāi bǎochí chuántǒng zuòfǎ","Post offices should maintain traditional practices"),
        o("现代社会节奏太快","xiàndài shèhuì jiézòu tài kuài","Modern society's pace is too fast")], 0.55),
    mc("作者将邮局称为「活体博物馆」，最可能的原因是：",
       "Why does the author call the post office a 'living museum'?",
       [o("邮局的建筑有历史价值","yóujú de jiànzhù yǒu lìshǐ jiàzhí","The post office building has historical value"),
        o("它保留着过去的物质形态和运作方式，同时仍在服务于当下的人群","tā bǎoliú zhe guòqù de wùzhì xíngtài hé yùnzuò fāngshì, tóngshí réng zài fúwù yú dāngxià de rénqún","It preserves past material forms and operating methods while still serving present-day people",True),
        o("邮局里有很多旧物展示","yóujú lǐ yǒu hěn duō jiùwù zhǎnshì","The post office displays many old items"),
        o("很少有人再去邮局了","hěn shǎo yǒu rén zài qù yóujú le","Few people go to the post office anymore")], 0.45)))

# 4 - mystery
P.append(passage("j8_mystery_003",
    "The Notebook in the Used Bookstore", "旧书店里的笔记本", 8,
    "我在一家旧书店的角落里发现了一个皮面笔记本，夹在两本七十年代的工程手册之间。笔记本没有署名，也没有日期，但从纸张的泛黄程度和钢笔字迹的墨色来看，至少有三十年的历史。里面的内容让我困惑了好几天。前半部分是工整的植物学笔记：各种花卉的拉丁名、生长周期、适宜土壤，配有精确的手绘插图。后半部分突然变了——字迹变得潦草，内容变成了断断续续的句子，像是日记但又不完全是。「今天又下雨了，第三周了。」「她说得对，我确实不了解自己。」「栀子花开了，但不是去年那株。」「决定不再去那个地方了。」这些句子之间没有明确的因果关系，就像散落在地上的拼图碎片。我试图把它们拼成一个完整的故事：一个热爱植物学的人，经历了某种情感变故，笔记本从此成了一个无人对话的出口。但我知道这只是我的推测。旧书店老板说这本笔记本是从一位遗孀那里收来的废品堆中捡出来的。一个人的内心世界就这样变成了一件标价五元的二手商品。",
    "Wǒ zài yī jiā jiù shūdiàn de jiǎoluò lǐ fāxiàn le yī gè pí miàn bǐjìběn, jiā zài liǎng běn qīshí niándài de gōngchéng shǒucè zhījiān.",
    "I found a leather-bound notebook in the corner of a used bookstore, sandwiched between two 1970s engineering manuals. No name, no date, but the yellowing paper and pen ink color suggested at least thirty years. The contents puzzled me for days. The first half was meticulous botanical notes: Latin names of flowers, growth cycles, suitable soils, with precise hand-drawn illustrations. The second half changed abruptly—handwriting became scrawled, content shifted to fragmentary sentences, like a diary but not quite. 'Rained again today, third week.' 'She was right, I really don't understand myself.' 'The gardenia bloomed, but it's not last year's plant.' 'Decided not to go to that place anymore.' These sentences had no clear causal links, like puzzle pieces scattered on the floor. I tried assembling them into a complete story: a botany lover who experienced some emotional upheaval, the notebook becoming an outlet with no listener. But I know that's only my speculation. The bookstore owner said the notebook was salvaged from a pile of discards bought from a widow. A person's inner world had become a five-yuan secondhand item.",
    mc("笔记本前后两部分的变化暗示了什么？",
       "What does the change between the notebook's two halves suggest?",
       [o("写笔记的人换了一支笔","xiě bǐjì de rén huàn le yī zhī bǐ","The writer switched pens"),
        o("写作者经历了某种情感变故，从有序的学术记录转向了无序的内心表达","xiězuòzhě jīnglì le mǒu zhǒng qínggǎn biàngù, cóng yǒuxù de xuéshù jìlù zhuǎnxiàng le wúxù de nèixīn biǎodá","The writer experienced emotional upheaval, shifting from orderly academic notes to disordered inner expression",True),
        o("笔记本的后半部分是另一个人写的","bǐjìběn de hòu bànbùfen shì lìng yī gè rén xiě de","The second half was written by a different person"),
        o("植物学课程结束了","zhíwùxué kèchéng jiéshù le","The botany course ended")], 0.5),
    mc("作者说「一个人的内心世界变成了五元的二手商品」，表达了什么情感？",
       "What emotion does 'a person's inner world became a five-yuan secondhand item' express?",
       [o("对旧书店定价太低的不满","duì jiù shūdiàn dìngjià tài dī de bùmǎn","Dissatisfaction with the bookstore's low pricing"),
        o("对个人精神遗产被遗忘和贬值的惋惜","duì gèrén jīngshén yíchǎn bèi yíwàng hé biǎnzhí de wǎnxī","Wistfulness over personal spiritual legacy being forgotten and devalued",True),
        o("对收藏旧物的兴趣","duì shōucáng jiùwù de xìngqù","Interest in collecting old things"),
        o("对遗孀处理遗物方式的批评","duì yíshuǎng chǔlǐ yíwù fāngshì de pīpíng","Criticism of how the widow handled the belongings")], 0.55),
    mc("作者对笔记本中断续句子的处理方式反映了什么？",
       "What does the author's approach to the notebook's fragmentary sentences reflect?",
       [o("他是一个职业侦探","tā shì yī gè zhíyè zhēntàn","He is a professional detective"),
        o("人类倾向于从碎片中构建完整叙事，即使是推测","rénlèi qīngxiàng yú cóng suìpiàn zhōng gòujiàn wánzhěng xùshì, jíshǐ shì tuīcè","Humans tend to construct complete narratives from fragments, even speculatively",True),
        o("旧书店里经常能找到有价值的东西","jiù shūdiàn lǐ jīngcháng néng zhǎodào yǒu jiàzhí de dōngxi","Valuable things are often found in used bookstores"),
        o("他想把这个笔记本写成小说","tā xiǎng bǎ zhège bǐjìběn xiě chéng xiǎoshuō","He wants to turn the notebook into a novel")], 0.45)))

# 5 - observe
P.append(passage("j8_observe_012",
    "The Sound of Closing Shops", "打烊的声音", 8,
    "每座城市都有一首打烊的交响乐，只有习惯了晚归的人才听得见。九点左右是第一乐章：餐厅开始收桌，铁质桌椅在瓷砖地面上拖拽的刺耳声，混合着最后几桌客人的笑声。十点是第二乐章：卷帘门一家接一家地落下，金属轨道与地面接触时发出一声闷响，就像乐句末尾的休止符。这个声音沿着商业街以多米诺骨牌的节奏传播，从东到西，大约持续二十分钟。十一点是第三乐章：酒吧和KTV的低频音乐从墙壁后面渗出来，与夜宵摊位的油烟味构成一种感官上的混合体。午夜之后是终曲：最后一家便利店的店员把「营业中」的灯牌关掉，街道归于寂静，只剩下路灯发出的几不可闻的电流嗡嗡声。我发现，一条街的打烊顺序其实反映了它的商业生态系统：最先关门的是利润最薄的早餐店，最后关门的是利润最厚的酒吧。金钱决定了谁有权利在深夜的城市中占据一个光亮的位置。",
    "Měi zuò chéngshì dōu yǒu yī shǒu dǎyáng de jiāoxiǎngyuè, zhǐ yǒu xíguàn le wǎn guī de rén cái tīng de jiàn.",
    "Every city has a closing-time symphony, audible only to those accustomed to coming home late. Around nine is the first movement: restaurants clearing tables, the grating scrape of metal chairs on tile floors mixed with the last tables' laughter. Ten is the second movement: roller shutters descending one after another, the muffled thud of metal track meeting ground like a rest at the end of a musical phrase. This sound propagates along commercial streets in domino rhythm, east to west, lasting about twenty minutes. Eleven is the third: the low-frequency music of bars and KTVs seeping through walls, combining with the oily smoke of late-night snack stalls into a sensory hybrid. After midnight comes the finale: the last convenience store clerk switches off the 'Open' sign, the street falls silent, leaving only the barely audible hum of current from streetlights. I found that a street's closing order actually reflects its commercial ecosystem: the first to close are the thinnest-margin breakfast shops, the last are the highest-margin bars. Money determines who has the right to occupy a bright spot in the late-night city.",
    mc("作者用「交响乐」结构来描述打烊，这种写法的效果是什么？",
       "What is the effect of using 'symphony' structure to describe closing time?",
       [o("让读者觉得城市很吵","ràng dúzhě juéde chéngshì hěn chǎo","Making readers think the city is noisy"),
        o("将无序的城市声音组织成有层次、有节奏的叙事","jiāng wúxù de chéngshì shēngyīn zǔzhī chéng yǒu céngcì, yǒu jiézòu de xùshì","Organizing chaotic urban sounds into a layered, rhythmic narrative",True),
        o("暗示作者是音乐专业出身","ànshì zuòzhě shì yīnyuè zhuānyè chūshēn","Suggesting the author has a music background"),
        o("批评城市噪音污染","pīpíng chéngshì zàoyīn wūrǎn","Criticizing urban noise pollution")], 0.45),
    mc("作者发现打烊顺序与什么直接相关？",
       "What does the author find the closing order directly correlates with?",
       [o("营业时间的长短","yíngyè shíjiān de chángduǎn","Length of business hours"),
        o("商家的利润率高低","shāngjiā de lìrùnlǜ gāodī","The profit margin of businesses",True),
        o("商铺距离路口的远近","shāngpù jùlí lùkǒu de yuǎnjìn","Distance from the intersection"),
        o("店主的个人习惯","diànzhǔ de gèrén xíguàn","Shop owners' personal habits")], 0.4),
    mc("文末「金钱决定了谁有权利在深夜占据一个光亮的位置」表达了什么观点？",
       "What viewpoint does 'money determines who can occupy a bright spot at night' express?",
       [o("夜间经济需要政府补贴","yèjiān jīngjì xūyào zhèngfǔ bǔtiē","Nighttime economy needs government subsidies"),
        o("商业利润决定了城市空间的时间使用权","shāngyè lìrùn juédìng le chéngshì kōngjiān de shíjiān shǐyòngquán","Commercial profit determines temporal access rights to urban space",True),
        o("应该鼓励更多店铺延长营业时间","yīnggāi gǔlì gèng duō diànpù yáncháng yíngyè shíjiān","More shops should be encouraged to extend hours"),
        o("路灯应该整夜开着","lùdēng yīnggāi zhěng yè kāi zhe","Streetlights should stay on all night")], 0.55)))

save("hsk8_batch3.json", P)
