# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "/Users/jasongerson/mandarin/content_gen")
from gen_helpers import *

P = []

# 11 - observe
P.append(passage("j8_observe_008",
    "The Cartography of Cracks", "裂缝的地图学", 8,
    "我住的这栋楼有一面外墙正在缓慢地开裂。裂缝从三楼的窗角出发，以一种不可预测的路径向下延伸，经过四楼时拐了一个近乎直角的弯，到五楼又分叉成两条更细的支线。物业每年春天都会派人来填补，用白色的腻子把裂缝糊上。但到了秋天，裂缝总会在填补处的旁边重新出现，就好像它有自己的意志，拒绝被抹去。我开始用手机记录裂缝每个季度的变化，两年下来积累了八张照片。把它们排列在一起看，裂缝的扩展轨迹竟然呈现出一种类似河流水系的分形结构。我查了一些资料，发现建筑物的裂缝确实遵循与自然界类似的力学规律——应力沿最薄弱的路径释放，就像水沿地势最低的路线流淌。这面墙以它缓慢的崩解方式，无声地演示着一条物理学定律：一切结构都在寻找释放压力的出口。我忽然觉得，人也是如此——情绪的裂缝如果不被正视，也会沿着最脆弱的地方悄悄蔓延。",
    "Wǒ zhù de zhè dòng lóu yǒu yī miàn wàiqiáng zhèngzài huǎnmàn de kāiliè. Lièfèng cóng sān lóu de chuāngjiǎo chūfā, yǐ yī zhǒng bùkě yùcè de lùjìng xiàng xià yánshēn, jīngguò sì lóu shí guǎi le yī gè jìnhū zhíjiǎo de wān, dào wǔ lóu yòu fēnchā chéng liǎng tiáo gèng xì de zhīxiàn.",
    "The building I live in has an exterior wall slowly cracking. The crack starts from a third-floor window corner, extending downward along an unpredictable path, turning nearly ninety degrees at the fourth floor, then branching into two thinner lines at the fifth. Property management fills it with white putty every spring. But by autumn the crack always reappears beside the filled spot, as if it has its own will, refusing erasure. I began photographing it quarterly—eight photos over two years. Arranged together, the crack's expansion traces show a fractal structure resembling river systems. I found that building cracks indeed follow mechanics similar to nature—stress releases along the weakest path, like water flowing along the lowest terrain. This wall, through its slow disintegration, silently demonstrates a physics law: all structures seek an outlet for releasing pressure. I suddenly felt people are the same—emotional cracks, if not faced honestly, also spread quietly along the most vulnerable places.",
    mc("作者发现裂缝扩展轨迹的特征是什么？",
       "What characteristic did the author find in the crack's expansion pattern?",
       [o("完全随机，没有规律","wánquán suíjī, méiyǒu guīlǜ","Completely random, no pattern"),
        o("呈现类似河流水系的分形结构","chéngxiàn lèisì héliú shuǐxì de fēnxíng jiégòu","Shows a fractal structure resembling river systems",True),
        o("沿着建筑接缝直线延伸","yán zhe jiànzhù jiēfèng zhíxiàn yánshēn","Extends straight along building seams"),
        o("每年出现在完全相同的位置","měi nián chūxiàn zài wánquán xiāngtóng de wèizhì","Appears in exactly the same position each year")], 0.45),
    mc("文末将裂缝与人的情绪相类比，核心观点是什么？",
       "What is the core point of comparing cracks to human emotions at the end?",
       [o("人应该定期检查心理健康","rén yīnggāi dìngqī jiǎnchá xīnlǐ jiànkāng","People should regularly check mental health"),
        o("被压抑的情绪会沿最脆弱处蔓延，需要被正视","bèi yāyì de qínggǎn huì yán zuì cuìruò chù mányán, xūyào bèi zhèngshì","Suppressed emotions spread along vulnerable places and need to be faced",True),
        o("建筑维修和心理治疗原理相同","jiànzhù wéixiū hé xīnlǐ zhìliáo yuánlǐ xiāngtóng","Building repair and psychotherapy share the same principle"),
        o("物理学可以解释人类行为","wùlǐxué kěyǐ jiěshì rénlèi xíngwéi","Physics can explain human behavior")], 0.5),
    mc("物业每年填补裂缝但裂缝总会在旁边重新出现，作者暗示了什么？",
       "What does the author imply by the crack always reappearing beside the filled spot?",
       [o("物业使用的材料质量不好","wùyè shǐyòng de cáiliào zhìliàng bù hǎo","Property management uses poor quality materials"),
        o("表面的修补无法解决根本的结构问题","biǎomiàn de xiūbǔ wúfǎ jiějué gēnběn de jiégòu wèntí","Surface repairs cannot solve fundamental structural problems",True),
        o("建筑物应该被拆除重建","jiànzhùwù yīnggāi bèi chāichú chóngjiàn","The building should be demolished and rebuilt"),
        o("裂缝有自己的意识","lièfèng yǒu zìjǐ de yìshí","The crack has its own consciousness")], 0.45)))

# 12 - food
P.append(passage("j8_food_001",
    "The Taxonomy of Breakfast", "早餐的分类学", 8,
    "一个城市的性格可以从它的早餐摊位上读出来。在我长大的那座北方小城，早餐的选择遵循一种严格的季节逻辑：冬天是豆腐脑加油条，热气腾腾的碗端在手里可以暖和整个上午；夏天是凉皮加绿豆汤，酸辣的凉皮让人在闷热中恢复食欲。后来我搬到南方，发现这里的早餐是另一套完全不同的体系——肠粉、虾饺、叉烧包，每一种都精致到像是一件微型的手工艺品。我花了很长时间才适应这种转变，不是口味的适应，而是节奏的适应。北方早餐的核心是「快」：站在路边，三分钟吃完，赶公交上班。南方早茶的核心是「慢」：坐在茶楼里，一壶茶配四笼点心，可以聊一个上午。这两种早餐文化反映了截然不同的时间哲学。北方人把早餐当作一天的启动程序，功能性第一；南方人把早餐当作一天中最值得享受的时段，仪式感第一。如今两种文化都在被标准化的连锁早餐店侵蚀，那些千篇一律的三明治和美式咖啡，效率极高却毫无性格。",
    "Yī gè chéngshì de xìnggé kěyǐ cóng tā de zǎocān tānwèi shàng dú chūlái. Zài wǒ zhǎngdà de nà zuò běifāng xiǎo chéng, zǎocān de xuǎnzé zūnxún yī zhǒng yángé de jìjié luójí: dōngtiān shì dòufunǎo jiā yóutiáo, rèqì téngténg de wǎn duān zài shǒu lǐ kěyǐ nuǎnhuo zhěnggè shàngwǔ; xiàtiān shì liángpí jiā lǜdòu tāng, suānlà de liángpí ràng rén zài mēnrè zhōng huīfù shíyù.",
    "A city's character can be read from its breakfast stalls. In the northern town where I grew up, breakfast followed strict seasonal logic: winter meant tofu pudding with fried dough sticks, the steaming bowl warming your hands all morning; summer meant cold skin noodles with mung bean soup, the tangy spice restoring appetite in the heat. Later I moved south and found an entirely different system—rice rolls, shrimp dumplings, char siu buns, each refined like miniature handicraft. It took me a long time to adapt—not to the taste, but to the rhythm. Northern breakfast's core is 'fast': standing roadside, three minutes, catch the bus. Southern morning tea's core is 'slow': sitting in a tea house, a pot of tea with four baskets of dim sum, chatting all morning. These two breakfast cultures reflect radically different time philosophies. Northerners treat breakfast as a startup routine, function first; southerners treat it as the day's most enjoyable period, ritual first. Both cultures are now being eroded by standardized chain breakfast shops—those uniform sandwiches and American coffee, supremely efficient yet utterly without character.",
    mc("作者适应南方早餐，最难适应的不是口味而是什么？",
       "What was hardest for the author to adapt to about southern breakfast, if not taste?",
       [o("食物的种类太多","shíwù de zhǒnglèi tài duō","Too many food varieties"),
        o("用餐的节奏和时间哲学","yòngcān de jiézòu hé shíjiān zhéxué","The dining rhythm and time philosophy",True),
        o("价格比北方贵","jiàgé bǐ běifāng guì","Higher prices than the north"),
        o("找不到合适的早餐店","zhǎo bú dào héshì de zǎocān diàn","Couldn't find suitable breakfast shops")], 0.45),
    mc("作者认为北方和南方早餐文化的根本区别是什么？",
       "What does the author see as the fundamental difference between northern and southern breakfast cultures?",
       [o("食材的种类不同","shícái de zhǒnglèi bùtóng","Different types of ingredients"),
        o("对时间的态度不同——功能性优先还是仪式感优先","duì shíjiān de tàidù bùtóng——gōngnéngxìng yōuxiān háishì yíshìgǎn yōuxiān","Different attitudes toward time—function-first vs. ritual-first",True),
        o("烹饪技术的复杂程度不同","pēngrèn jìshù de fùzá chéngdù bùtóng","Different levels of cooking complexity"),
        o("气候决定了食物选择","qìhòu juédìng le shíwù xuǎnzé","Climate determines food choices")], 0.5),
    mc("作者对连锁早餐店的态度是什么？",
       "What is the author's attitude toward chain breakfast shops?",
       [o("支持它们带来的效率提升","zhīchí tāmen dài lái de xiàolǜ tíshēng","Supports the efficiency they bring"),
        o("认为它们效率高但缺乏地方文化个性","rènwéi tāmen xiàolǜ gāo dàn quēfá dìfāng wénhuà gèxìng","Considers them efficient but lacking local cultural character",True),
        o("完全反对，认为应该禁止","wánquán fǎnduì, rènwéi yīnggāi jìnzhǐ","Completely opposed, thinks they should be banned"),
        o("无所谓，认为早餐不重要","wúsuǒwèi, rènwéi zǎocān bú zhòngyào","Indifferent, considers breakfast unimportant")], 0.4)))

# 13 - mystery
P.append(passage("j8_mystery_002",
    "The Third-Floor Light", "三楼的灯", 8,
    "对面那栋楼的三楼，有一盏灯每天凌晨两点准时亮起，三点四十五分准时熄灭。我注意到这件事纯属偶然——某个失眠的夜晚，我站在窗前喝水，看到那盏灯孤零零地亮着，周围所有窗户都是暗的。此后我开始留意，发现它的时间表精确得不可思议，误差从未超过两分钟。最初我猜测是定时灯，但定时灯不会在窗帘后面投射出人影的移动。那是一个人的轮廓，有时坐着，有时站起来走动，偶尔会在窗前停留几秒钟。我无法判断那是男人还是女人，年轻还是年老。我知道自己不应该窥探，但这个谜题太过诱人。凌晨两点到三点四十五分，一小时四十五分钟，每天如此——这个人在做什么？写作？失眠？加班？照顾一个生病的家人？每一种猜测都引向一个完全不同的故事。我最终决定不去打听答案。有些谜，保持它们未解的状态本身就是一种尊重——对那扇窗户后面那个人的私密时光的尊重。",
    "Duìmiàn nà dòng lóu de sān lóu, yǒu yī zhǎn dēng měi tiān língchén liǎng diǎn zhǔnshí liàng qǐ, sān diǎn sìshíwǔ fēn zhǔnshí xīmiè. Wǒ zhùyì dào zhè jiàn shì chún shǔ ǒurán——mǒu gè shīmián de yèwǎn, wǒ zhàn zài chuāng qián hē shuǐ, kàn dào nà zhǎn dēng gūlínglíng de liàng zhe, zhōuwéi suǒyǒu chuānghù dōu shì àn de.",
    "On the third floor of the building opposite, a light turns on at exactly two AM and off at exactly three forty-five every night. I noticed purely by chance—one sleepless night, standing at my window drinking water, I saw it glowing alone, every surrounding window dark. After that I watched, finding its schedule impossibly precise, never varying more than two minutes. At first I guessed a timer, but timer lights don't project moving shadows behind curtains. It was a person's silhouette, sometimes sitting, sometimes standing and walking, occasionally pausing at the window for a few seconds. I couldn't tell man or woman, young or old. I knew I shouldn't spy, but the puzzle was too compelling. Two AM to three forty-five—one hour forty-five minutes, every day. What were they doing? Writing? Insomnia? Working overtime? Caring for a sick family member? Each guess led to an entirely different story. I ultimately decided not to investigate. Some mysteries, kept unsolved, are themselves a form of respect—respect for the private hours of the person behind that window.",
    mc("作者最终没有去打听答案，原因是什么？",
       "Why did the author ultimately not investigate the answer?",
       [o("他担心被当作偷窥者","tā dānxīn bèi dàng zuò tōukuīzhě","He worried about being seen as a voyeur"),
        o("保持谜题未解本身就是对他人私密时光的尊重","bǎochí mítí wèi jiě běnshēn jiù shì duì tārén sīmì shíguāng de zūnzhòng","Keeping the mystery unsolved is itself respect for someone's private hours",True),
        o("他搬走了，无法继续观察","tā bān zǒu le, wúfǎ jìxù guānchá","He moved away and couldn't continue observing"),
        o("答案太明显不值得追问","dá'àn tài míngxiǎn bù zhíde zhuīwèn","The answer was too obvious to pursue")], 0.5),
    mc("作者排除了「定时灯」的可能性，依据是什么？",
       "On what basis did the author rule out a timer light?",
       [o("定时灯不会每天都亮","dìngshí dēng bú huì měi tiān dōu liàng","Timer lights wouldn't turn on every day"),
        o("窗帘后面有人影在移动","chuānglián hòumiàn yǒu rényǐng zài yídòng","There was a moving silhouette behind the curtain",True),
        o("灯的亮度会变化","dēng de liàngdù huì biànhuà","The light's brightness varied"),
        o("定时灯不能持续一个多小时","dìngshí dēng bù néng chíxù yī gè duō xiǎoshí","Timer lights can't stay on for over an hour")], 0.4),
    mc("这篇文章的主题最接近以下哪项？",
       "Which of the following is closest to the article's theme?",
       [o("城市中的孤独","chéngshì zhōng de gūdú","Urban loneliness"),
        o("观察与尊重之间的边界","guānchá yǔ zūnzhòng zhījiān de biānjiè","The boundary between observation and respect",True),
        o("失眠的危害","shīmián de wēihài","The dangers of insomnia"),
        o("邻里关系的重要性","línlǐ guānxì de zhòngyàoxìng","The importance of neighborly relations")], 0.5)))

# 14 - inst
P.append(passage("j8_inst_002",
    "The Hospital Cafeteria at Midnight", "午夜的医院食堂", 8,
    "医院食堂是一个被低估的社会观察窗口，尤其是在午夜之后。白天的食堂与任何单位食堂无异——排队、刷卡、找座位、快速吃完走人。但午夜的食堂进入了一种完全不同的状态。灯光调暗了一半，只有靠近厨房的几排座位还亮着。顾客变成了三种人：值夜班的医生和护士，他们穿着手术服或白大褂，用一种机械的速度往嘴里塞食物，眼神疲惫但警觉，随时准备被呼叫回去；陪护病人的家属，他们通常独自坐着，面前的饭菜凉了也不动筷子，目光落在桌面的某个不确定的位置上；以及少数像我这样的深夜访客，因为家人住院而不得不在这个时间出现在这里。午夜的医院食堂有一种奇特的亲密感——所有人都被一种共同的疲惫和忧虑连接在一起，陌生人之间的戒备几乎完全消失了。我曾在凌晨一点与一位值班护士同桌吃饭，她用不到五分钟吃完一碗面条，临走时对我说了一句「加油」，那两个字在那个时间那个地点所携带的重量，远超它日常使用时的含义。",
    "Yīyuàn shítáng shì yī gè bèi dīgū de shèhuì guānchá chuāngkǒu, yóuqí shì zài wǔyè zhīhòu. Báitiān de shítáng yǔ rènhé dānwèi shítáng wú yì——páiduì, shuākǎ, zhǎo zuòwèi, kuàisù chī wán zǒu rén. Dàn wǔyè de shítáng jìnrù le yī zhǒng wánquán bùtóng de zhuàngtài.",
    "A hospital cafeteria is an underestimated window for social observation, especially after midnight. During the day it's like any workplace cafeteria—queue, swipe card, find a seat, eat quickly, leave. But the midnight cafeteria enters a completely different state. Lights are dimmed by half, only a few rows near the kitchen still lit. Customers become three types: night-shift doctors and nurses in scrubs or white coats, mechanically shoveling food, eyes exhausted but alert, ready to be called back any moment; family members attending patients, usually sitting alone, chopsticks untouched over cooling food, gaze falling on some uncertain point on the table; and a few late-night visitors like me, here because a family member is hospitalized. The midnight hospital cafeteria has a peculiar intimacy—everyone connected by shared fatigue and worry, guards between strangers almost completely dissolved. I once shared a table at one AM with an on-duty nurse who finished a bowl of noodles in under five minutes. As she left, she said 'jiāyóu'—those two syllables, at that hour in that place, carried a weight far beyond their everyday meaning.",
    mc("午夜医院食堂的三种顾客，他们的共同特点是什么？",
       "What do the three types of midnight cafeteria customers share in common?",
       [o("都是医院的工作人员","dōu shì yīyuàn de gōngzuò rényuán","All are hospital staff"),
        o("都被疲惫和忧虑所连接","dōu bèi píbèi hé yōulǜ suǒ liánjiē","All are connected by fatigue and worry",True),
        o("都在等待天亮","dōu zài děngdài tiān liàng","All are waiting for dawn"),
        o("都独自吃饭","dōu dúzì chīfàn","All eat alone")], 0.4),
    mc("护士临走时说的「加油」为什么重量特别大？",
       "Why did the nurse's parting 'jiāyóu' carry special weight?",
       [o("因为护士很少对陌生人说这种话","yīnwèi hùshi hěn shǎo duì mòshēngrén shuō zhè zhǒng huà","Nurses rarely say such things to strangers"),
        o("在深夜医院这个特殊场景下，共同的疲惫赋予了这两个字超越日常的意义","zài shēnyè yīyuàn zhège tèshū chǎngjǐng xià, gòngtóng de píbèi fùyǔ le zhè liǎng gè zì chāoyuè rìcháng de yìyì","The shared fatigue in this special late-night hospital context gave the words meaning beyond everyday use",True),
        o("因为她知道作者的家人病得很重","yīnwèi tā zhīdào zuòzhě de jiārén bìng de hěn zhòng","Because she knew the author's family member was seriously ill"),
        o("因为「加油」是医院的专用鼓励语","yīnwèi jiāyóu shì yīyuàn de zhuānyòng gǔlì yǔ","Because 'jiāyóu' is a specialized hospital encouragement phrase")], 0.55),
    mc("作者说午夜食堂有「奇特的亲密感」，根源是什么？",
       "What is the root of the midnight cafeteria's 'peculiar intimacy'?",
       [o("食堂灯光昏暗营造了温馨氛围","shítáng dēngguāng hūn'àn yíngzào le wēnxīn fēnwéi","Dim lighting creates a warm atmosphere"),
        o("共同的脆弱处境消解了人与人之间的社交壁垒","gòngtóng de cuìruò chǔjìng xiāojiě le rén yǔ rén zhījiān de shèjiāo bìlěi","Shared vulnerability dissolves social barriers between people",True),
        o("午夜没有管理人员监督","wǔyè méiyǒu guǎnlǐ rényuán jiāndū","No supervisors at midnight"),
        o("人们深夜更容易感到孤独","rénmen shēnyè gèng róngyì gǎndào gūdú","People feel lonelier late at night")], 0.5)))

# 15 - observe
P.append(passage("j8_observe_009",
    "The Migration Patterns of Park Benches", "公园长椅的迁徙规律", 8,
    "如果你连续一年每周去同一个公园，你会发现长椅上的人群有着与候鸟相似的季节性迁徙规律。春天，年轻母亲和婴儿车占领了朝南的长椅，她们需要温暖但不刺眼的阳光；同时，几位老人开始出现在银杏树下的椅子上，那里有刚好合适的斑驳树荫。夏天，所有朝南的座位都空了，人群迁移到北侧靠近喷泉的长椅，水雾带来几度的降温效果。秋天是最民主的季节——气温适宜，每张长椅都有人坐，从下棋的老人到看书的学生，从遛狗的中年人到发呆的上班族。冬天则最为极端：整个公园只有面朝南、背靠墙、有阳光直射的那三张椅子被使用，其余全部空置。这些迁徙模式没有人组织，没有人协调，却年复一年地精确重复。我有时觉得，人类在面对自然条件时的行为，远比我们以为的更加本能化。我们以为自己在做选择，其实只是在顺从光照和温度的指令。",
    "Rúguǒ nǐ liánxù yī nián měi zhōu qù tóngyī gè gōngyuán, nǐ huì fāxiàn chángyǐ shàng de rénqún yǒu zhe yǔ hòuniǎo xiāngsì de jìjiéxìng qiānxǐ guīlǜ.",
    "If you visit the same park weekly for a year, you'll find bench populations have seasonal migration patterns similar to migratory birds. In spring, young mothers with strollers claim south-facing benches for warm but not glaring sunlight; meanwhile, elderly residents appear on chairs under ginkgo trees with just the right dappled shade. In summer, all south-facing seats empty, crowds migrate to north-side benches near the fountain, where mist provides a few degrees of cooling. Autumn is the most democratic season—comfortable temperatures, every bench occupied, from chess-playing elders to reading students, dog-walking middle-aged people to daydreaming office workers. Winter is the most extreme: only three south-facing, wall-backed, sun-drenched chairs are used, all others abandoned. These migration patterns have no organizer, no coordinator, yet repeat precisely year after year. Sometimes I think human behavior in the face of natural conditions is far more instinctive than we believe. We think we're making choices, but we're simply obeying instructions from light and temperature.",
    mc("作者用「候鸟迁徙」来类比公园长椅人群的变化，核心发现是什么？",
       "What is the core finding in comparing park bench populations to bird migration?",
       [o("公园应该根据季节调整长椅位置","gōngyuán yīnggāi gēnjù jìjié tiáozhěng chángyǐ wèizhì","Parks should adjust bench positions by season"),
        o("人类对座位的选择遵循与动物迁徙相似的自然驱动模式","rénlèi duì zuòwèi de xuǎnzé zūnxún yǔ dòngwù qiānxǐ xiāngsì de zìrán qūdòng móshì","Human seat choices follow naturally-driven patterns similar to animal migration",True),
        o("老人比年轻人更喜欢户外活动","lǎorén bǐ niánqīng rén gèng xǐhuān hùwài huódòng","Elderly people enjoy outdoor activities more than young people"),
        o("公园在冬天应该关闭","gōngyuán zài dōngtiān yīnggāi guānbì","Parks should close in winter")], 0.45),
    mc("为什么作者说秋天是「最民主的季节」？",
       "Why does the author call autumn the 'most democratic season'?",
       [o("秋天的公园活动最多","qiūtiān de gōngyuán huódòng zuì duō","Autumn has the most park activities"),
        o("气温适宜使得每张长椅都有不同类型的人使用","qìwēn shìyí shǐ de měi zhāng chángyǐ dōu yǒu bùtóng lèixíng de rén shǐyòng","Comfortable temperatures let every bench be used by different types of people",True),
        o("秋天的公园对所有人免费开放","qiūtiān de gōngyuán duì suǒyǒu rén miǎnfèi kāifàng","The park is free for everyone in autumn"),
        o("秋天的景色最美丽","qiūtiān de jǐngsè zuì měilì","Autumn scenery is the most beautiful")], 0.4),
    mc("文末「我们以为自己在做选择，其实只是在顺从光照和温度的指令」表达了什么观点？",
       "What does the closing line about 'obeying instructions from light and temperature' express?",
       [o("人类的自由意志是一种幻觉","rénlèi de zìyóu yìzhì shì yī zhǒng huànjué","Human free will is an illusion"),
        o("人类行为受自然因素驱动的程度远超我们的自我认知","rénlèi xíngwéi shòu zìrán yīnsù qūdòng de chéngdù yuǎn chāo wǒmen de zìwǒ rènzhī","Human behavior is driven by natural factors far more than our self-awareness recognizes",True),
        o("气候变化正在改变人类行为","qìhòu biànhuà zhèngzài gǎibiàn rénlèi xíngwéi","Climate change is altering human behavior"),
        o("人们应该多做户外运动","rénmen yīnggāi duō zuò hùwài yùndòng","People should exercise outdoors more")], 0.5)))

append_save("hsk8_batch2.json", P)
