# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "/Users/jasongerson/mandarin/content_gen")
from gen_helpers import *

P = []

# 6 - mystery
P.append(passage("j8_mystery_001",
    "The Disappearing Bench", "消失的长椅", 8,
    "小区花园里有七张长椅，直到有一天变成了六张。我是唯一注意到这件事的人，至少在那一周里没有其他住户提起过。消失的是靠近东侧围墙的那张，它的位置有些偏僻，被两棵桂花树的树荫遮住，平时很少有人去坐。但我每天傍晚散步时都会经过，因为那条路线可以避开广场舞的音响。我向物业询问，得到的答复是「没有接到任何移除通知」。保安说他没注意到。花匠说她以为那里本来就没有椅子。这件事的奇怪之处不在于一张长椅消失了，而在于它消失后，整个空间的记忆似乎也跟着调整了。人们不是忘记了那张椅子，而是从未记得它存在过。我花了三天时间在小区的业主群里翻找，终于找到一张两年前的活动照片，背景里隐约可见那张长椅。我把照片发到群里询问，只有一个人回复说：「好像确实有过，可能是坏了被搬走了吧。」没有人追问。一张长椅就这样从物理世界和集体记忆中同时蒸发了。这让我意识到：一个事物的存在需要被注意力反复确认，否则它会在无人察觉的情况下退场，而且不会留下任何空缺的痕迹。",
    "Xiǎoqū huāyuán lǐ yǒu qī zhāng chángyǐ, zhídào yǒu yī tiān biàn chéng le liù zhāng. Wǒ shì wéiyī zhùyì dào zhè jiàn shì de rén, zhìshǎo zài nà yī zhōu lǐ méiyǒu qítā zhùhù tíqǐ guò. Xiāoshī de shì kàojìn dōngcè wéiqiáng de nà zhāng, tā de wèizhì yǒuxiē piānpì, bèi liǎng kē guìhuā shù de shùyīn zhēzhù, píngshí hěn shǎo yǒu rén qù zuò. Dàn wǒ měi tiān bàngwǎn sànbù shí dōu huì jīngguò, yīnwèi nà tiáo lùxiàn kěyǐ bìkāi guǎngchǎngwǔ de yīnxiǎng.",
    "There were seven benches in the residential garden, until one day there were six. I was the only person who noticed—at least no other resident mentioned it that week. The one that vanished was near the east wall, somewhat secluded under two osmanthus trees, rarely sat upon. But I passed it every evening because that route avoided the square-dancing speakers. Property management said they received no removal notice. The security guard hadn't noticed. The gardener assumed there had never been a bench there. The strange thing was not that a bench disappeared, but that afterward the space's collective memory adjusted. People didn't forget the bench—they had never remembered it. I spent three days searching the owners' group chat and found a photo from two years ago with the bench faintly visible. I posted it; one person replied: 'There does seem to have been one. Maybe it broke and was taken away.' Nobody asked further. A bench had evaporated from both the physical world and collective memory. This made me realize: an object's existence needs repeated confirmation by attention; otherwise it exits without anyone noticing, leaving no trace of its absence.",
    mc("作者认为这件事最奇怪的地方是什么？",
       "What does the author find strangest about this incident?",
       [o("物业没有任何记录","wùyè méiyǒu rènhé jìlù","Property management had no records"),
        o("长椅消失后，人们的记忆也跟着消失了","chángyǐ xiāoshī hòu, rénmen de jìyì yě gēnzhe xiāoshī le","After the bench disappeared, people's memory of it vanished too",True),
        o("没有人愿意帮忙寻找","méiyǒu rén yuànyì bāngmáng xúnzhǎo","Nobody was willing to help search"),
        o("长椅被偷走了","chángyǐ bèi tōu zǒu le","The bench was stolen")], 0.4),
    mc("文末的核心观点可以概括为：",
       "The core viewpoint at the end can be summarized as:",
       [o("物业管理需要更严格的监控","wùyè guǎnlǐ xūyào gèng yángé de jiānkòng","Property management needs stricter surveillance"),
        o("事物的存在依赖于持续的注意力确认","shìwù de cúnzài yīlài yú chíxù de zhùyìlì quèrèn","The existence of things depends on continuous confirmation by attention",True),
        o("小区应该安装更多监控摄像头","xiǎoqū yīnggāi ānzhuāng gèng duō jiānkòng shèxiàngtóu","Neighborhoods should install more cameras"),
        o("人们应该更关心公共设施","rénmen yīnggāi gèng guānxīn gōnggòng shèshī","People should care more about public facilities")], 0.5),
    mc("花匠说「以为那里本来就没有椅子」，这个细节说明了什么？",
       "What does the gardener saying she assumed there had never been a bench illustrate?",
       [o("花匠工作不认真","huājiang gōngzuò bú rènzhēn","The gardener is careless"),
        o("长椅的存在从未真正进入大多数人的注意范围","chángyǐ de cúnzài cóng wèi zhēnzhèng jìnrù dàduōshù rén de zhùyì fànwéi","The bench never truly entered most people's sphere of attention",True),
        o("花匠是新来的，不了解小区","huājiang shì xīn lái de, bù liǎojiě xiǎoqū","The gardener is new and unfamiliar"),
        o("长椅被植物完全遮挡了","chángyǐ bèi zhíwù wánquán zhēdǎng le","The bench was completely hidden by plants")], 0.45)))

# 7 - identity
P.append(passage("j8_identity_001",
    "The Name I Left Behind", "我留在身后的名字", 8,
    "我有两个名字。一个是户口本上的，三个字，父亲从《诗经》里选的，寓意「如松柏之茂」。另一个是移居海外后自己取的英文名，两个音节，简单利落，方便外国同事发音。起初我以为这只是一个实用的选择，就像出国时换一张电话卡。但十五年后我发现，这两个名字已经各自生长出了不同的人格。被叫中文名字的时候，我的声调会自动变低，用词变得含蓄，说话的节奏也会慢下来。被叫英文名字的时候，我的语速加快，表达更直接，笑容也更外放。我不确定哪个才是「真正的我」，或者说，我逐渐意识到这个问题本身就是错的。一个人可以同时拥有两种文化身份而不需要在它们之间做选择。真正让我不安的是第三种情况：当两个名字都不合适的时刻。比如和父母视频时突然切换成英文来解释一个没有中文对应词的概念，或者在海外的中餐馆里被问「您贵姓」时那一秒钟的犹豫。这些缝隙才是身份最真实的栖居地——不在任何一边，而在两边之间。",
    "Wǒ yǒu liǎng gè míngzì. Yī gè shì hùkǒuběn shàng de, sān gè zì, fùqīn cóng Shījīng lǐ xuǎn de, yùyì rú sōngbǎi zhī mào. Lìng yī gè shì yíjū hǎiwài hòu zìjǐ qǔ de yīngwén míng, liǎng gè yīnjié, jiǎndān lìluò, fāngbiàn wàiguó tóngshì fāyīn. Qǐchū wǒ yǐwéi zhè zhǐ shì yī gè shíyòng de xuǎnzé, jiù xiàng chūguó shí huàn yī zhāng diànhuà kǎ. Dàn shíwǔ nián hòu wǒ fāxiàn, zhè liǎng gè míngzì yǐjīng gèzì shēngzhǎng chū le bùtóng de réngé.",
    "I have two names. One is on my household registration, three characters, chosen by my father from the Book of Songs, meaning 'flourishing like pines and cypresses.' The other is an English name I gave myself after moving abroad, two syllables, clean and easy for foreign colleagues. At first I thought it was merely practical, like swapping a SIM card. But fifteen years later I found the two names had each grown distinct personalities. When called by my Chinese name, my tone lowers, my phrasing becomes reserved, my speech slows. When called by my English name, my pace quickens, expression becomes direct, smile opens wider. I'm not sure which is the real me—or rather, I've realized the question itself is wrong. A person can simultaneously hold two cultural identities without choosing between them. What truly unsettles me is a third situation: when neither name fits. Like switching to English mid-video-call with my parents to explain a concept with no Chinese equivalent, or the one-second hesitation when asked 'What's your surname?' at a Chinese restaurant overseas. These gaps are where identity truly resides—not on either side, but in the space between.",
    mc("作者认为「哪个才是真正的我」这个问题为什么是错的？",
       "Why does the author believe asking 'which is the real me' is wrong?",
       [o("因为两个名字都不代表真实自我","yīnwèi liǎng gè míngzì dōu bú dàibiǎo zhēnshí zìwǒ","Because neither name represents the true self"),
        o("因为一个人可以同时拥有多重文化身份","yīnwèi yī gè rén kěyǐ tóngshí yōngyǒu duōchóng wénhuà shēnfèn","Because a person can simultaneously hold multiple cultural identities",True),
        o("因为名字不重要","yīnwèi míngzì bú zhòngyào","Because names are not important"),
        o("因为他更喜欢英文名字","yīnwèi tā gèng xǐhuān yīngwén míngzì","Because he prefers his English name")], 0.45),
    mc("作者说「缝隙才是身份最真实的栖居地」，这里的「缝隙」指什么？",
       "What do the 'gaps' refer to as identity's truest dwelling place?",
       [o("两种语言之间无法翻译的概念","liǎng zhǒng yǔyán zhījiān wúfǎ fānyì de gàiniàn","Untranslatable concepts between two languages"),
        o("两种文化身份都不完全适用的模糊时刻","liǎng zhǒng wénhuà shēnfèn dōu bù wánquán shìyòng de móhú shíkè","Ambiguous moments when neither cultural identity fully applies",True),
        o("与父母之间的代沟","yǔ fùmǔ zhījiān de dàigōu","The generation gap with parents"),
        o("海外生活的孤独感","hǎiwài shēnghuó de gūdúgǎn","The loneliness of living abroad")], 0.55),
    mc("作者发现两个名字「生长出了不同的人格」，最能说明这一点的例子是：",
       "Which example best illustrates the two names growing distinct personalities?",
       [o("中文名来自《诗经》，英文名只有两个音节","zhōngwén míng láizì Shījīng, yīngwén míng zhǐ yǒu liǎng gè yīnjié","Chinese name from Book of Songs, English name has two syllables"),
        o("被叫不同名字时，说话方式、语速和表情都会改变","bèi jiào bùtóng míngzì shí, shuōhuà fāngshì, yǔsù hé biǎoqíng dōu huì gǎibiàn","When called by different names, speech style, pace, and expression all change",True),
        o("外国同事无法发音中文名","wàiguó tóngshì wúfǎ fāyīn zhōngwén míng","Foreign colleagues can't pronounce the Chinese name"),
        o("作者在海外生活了十五年","zuòzhě zài hǎiwài shēnghuó le shíwǔ nián","The author has lived abroad fifteen years")], 0.4)))

# 8 - comedy
P.append(passage("j8_comedy_001",
    "The Meeting That Could Have Been an Email", "本可以是一封邮件的会议", 8,
    "我粗略统计过，在过去五年的职业生涯中，我参加的会议里至少有百分之六十可以用一封三行的邮件替代。这不是抱怨，而是一个关于组织行为学的田野观察。典型的无效会议有一套固定的剧本：首先，组织者会提前十五分钟发一个模糊的议题，比如「讨论一下下季度的方向」，这种议题的信息量约等于「我们聊聊天吧」。其次，会议开始后的头五分钟用于等待迟到的人，这五分钟里已到场的人假装看手机，实则在计算这次迟到将浪费多少人的多少小时。然后进入正题——如果它存在的话。通常的情况是，说话时间的分配遵循一条隐形的权力曲线：职位最高的人说得最多，但信息密度最低；真正掌握关键数据的人往往在最后三分钟才被点名发言。会议结束时，组织者总结道：「那我们下次再详细讨论。」这句话翻译成人话就是：「这次会议什么结论也没达成。」最讽刺的是，会后最有效的信息交换往往发生在走廊里——两个人在散会后的三十秒对话里解决了会议上一小时没解决的问题。",
    "Wǒ cūlüè tǒngjì guò, zài guòqù wǔ nián de zhíyè shēngyá zhōng, wǒ cānjiā de huìyì lǐ zhìshǎo yǒu bǎifēnzhī liùshí kěyǐ yòng yī fēng sān háng de yóujiàn tìdài. Zhè bú shì bàoyuàn, ér shì yī gè guānyú zǔzhī xíngwéixué de tiányě guānchá.",
    "By rough count, at least sixty percent of meetings I've attended over five years could have been replaced by a three-line email. This is not a complaint but a field observation in organizational behavior. The typical ineffective meeting follows a fixed script: the organizer sends a vague agenda fifteen minutes ahead, like 'discuss next quarter's direction'—an agenda whose information content roughly equals 'let's chat.' The first five minutes are spent waiting for latecomers while attendees pretend to check phones while calculating wasted person-hours. Then comes the main topic—if it exists. Speaking time follows an invisible power curve: the highest-ranking person speaks most but with lowest information density; the person with key data typically isn't called until the last three minutes. The organizer concludes: 'Let's discuss in detail next time.' Translated: 'This meeting reached no conclusion.' Most ironically, the most effective information exchange happens in the hallway afterward—two people solve in thirty seconds what the meeting failed to solve in an hour.",
    mc("作者所说的「隐形的权力曲线」指的是什么？",
       "What does the 'invisible power curve' refer to?",
       [o("职位越高说话时间越多，但信息含量不一定高","zhíwèi yuè gāo shuōhuà shíjiān yuè duō, dàn xìnxī hánliàng bù yīdìng gāo","Higher position means more speaking time but not necessarily more information",True),
        o("会议中的座位安排反映权力等级","huìyì zhōng de zuòwèi ānpái fǎnyìng quánlì děngjí","Seating reflects power hierarchy"),
        o("迟到的人权力更大","chídào de rén quánlì gèng dà","Latecomers have more power"),
        o("组织者控制会议的所有决定","zǔzhīzhě kòngzhì huìyì de suǒyǒu juédìng","The organizer controls all decisions")], 0.45),
    mc("文末说会议室「是为了让人们感觉自己在做决策」，这属于什么修辞手法？",
       "What rhetorical technique is used in saying meeting rooms exist to make people feel like they're deciding?",
       [o("夸张","kuāzhāng","Hyperbole"),
        o("反讽","fǎnfěng","Irony",True),
        o("排比","páibǐ","Parallelism"),
        o("拟人","nǐrén","Personification")], 0.45),
    mc("作者认为最有效的信息交换发生在哪里？",
       "Where does the most effective information exchange occur?",
       [o("会议进行的最后三分钟","huìyì jìnxíng de zuìhòu sān fēnzhōng","The last three minutes of the meeting"),
        o("邮件里","yóujiàn lǐ","In emails"),
        o("会后走廊里的简短对话中","huì hòu zǒuláng lǐ de jiǎnduǎn duìhuà zhōng","In brief hallway conversations after the meeting",True),
        o("会议开始前的等待时间里","huìyì kāishǐ qián de děngdài shíjiān lǐ","During waiting time before the meeting")], 0.35)))

# 9 - observe
P.append(passage("j8_observe_007",
    "The Old Man and the Pigeons", "老人与鸽群", 8,
    "公园里有一个每天准时投喂鸽子的老人，无论刮风下雨，从不缺席。我观察他将近一年了。每天下午两点，他会出现在湖边的第三张长椅上，从一个旧布袋里取出玉米粒，均匀地撒在地上。鸽子们似乎有一套精确的生物钟，总是在他坐下的三到五分钟内从四面八方聚拢过来。有趣的是，鸽群的内部也有等级秩序：最先抵达的总是那几只羽毛最光亮的壮年鸽，它们占据中心位置，不紧不慢地啄食；随后是一群中等体型的，在外围快速争抢；最后才是那些年老体弱的，只能在最外缘拣食碎屑。老人似乎也注意到了这一点，他有时会故意把一小撮玉米粒扔到偏远的角落，那是给边缘鸽子的专属配给。我曾鼓起勇气问他为什么每天都来。他说：「它们认识我。如果我哪天不来，它们会等的。」这句话让我想了很久。他说的不是「我喜欢鸽子」，也不是「我退休了没事做」，而是一种被需要的责任感——一个七十多岁的老人，在被人类社会逐渐边缘化之后，在另一个物种那里找到了自己不可替代的位置。",
    "Gōngyuán lǐ yǒu yī gè měi tiān zhǔnshí tóuwèi gēzi de lǎorén, wúlùn guā fēng xià yǔ, cóng bù quēxí. Wǒ guānchá tā jiāngjìn yī nián le. Měi tiān xiàwǔ liǎng diǎn, tā huì chūxiàn zài hú biān de dì sān zhāng chángyǐ shàng, cóng yī gè jiù bùdài lǐ qǔ chū yùmǐ lì, jūnyún de sā zài dì shàng.",
    "In the park there is an old man who feeds pigeons at the same time every day, rain or shine, never missing. I've observed him for nearly a year. Every afternoon at two, he appears on the third bench by the lake, takes corn kernels from an old cloth bag, and scatters them evenly. The pigeons have a precise biological clock, gathering within three to five minutes. The flock has its own hierarchy: the first to arrive are prime-age pigeons with glossy feathers, claiming the center and pecking unhurriedly; next come medium-sized ones scrambling around the perimeter; last are the old and frail, picking crumbs on the outermost edge. The old man notices this too—sometimes he deliberately tosses corn to a distant corner, a ration for the marginal pigeons. I asked why he comes every day. He said: 'They know me. If I don't come one day, they'll wait.' That stayed with me. He didn't say 'I like pigeons' or 'I'm retired with nothing to do,' but expressed a responsibility born from being needed—a man in his seventies, gradually marginalized by human society, who found an irreplaceable position among another species.",
    mc("老人把玉米粒扔到角落里，这个行为反映了什么？",
       "What does tossing corn to distant corners reflect?",
       [o("他对鸽群内部弱势者的关照","tā duì gēqún nèibù ruòshìzhě de guānzhào","His care for the weaker members within the flock",True),
        o("他投喂技术不够熟练","tā tóuwèi jìshù búgòu shúliàn","His feeding technique isn't skilled"),
        o("他想把鸽子引到不同位置","tā xiǎng bǎ gēzi yǐn dào bùtóng wèizhì","He wants to lure pigeons to different spots"),
        o("角落的鸽子是他最喜欢的","jiǎoluò de gēzi shì tā zuì xǐhuān de","Corner pigeons are his favorites")], 0.4),
    mc("老人说「它们会等的」，作者认为这句话的深层含义是什么？",
       "What deeper meaning does the author find in 'they'll wait'?",
       [o("鸽子比人更忠诚","gēzi bǐ rén gèng zhōngchéng","Pigeons are more loyal than people"),
        o("老人通过被另一个物种需要而确认了自己的存在价值","lǎorén tōngguò bèi lìng yī gè wùzhǒng xūyào ér quèrèn le zìjǐ de cúnzài jiàzhí","The old man confirms his existential value through being needed by another species",True),
        o("动物有记忆能力","dòngwù yǒu jìyì nénglì","Animals have memory"),
        o("老人担心鸽子饿死","lǎorén dānxīn gēzi è sǐ","He worries pigeons will starve")], 0.5),
    mc("鸽群的等级秩序在文中有什么象征意义？",
       "What symbolic meaning does the flock's hierarchy carry?",
       [o("自然界比人类社会更公平","zìránjiè bǐ rénlèi shèhuì gèng gōngpíng","Nature is fairer than human society"),
        o("映射了人类社会中强者优先、弱者边缘化的结构","yìngshè le rénlèi shèhuì zhōng qiángzhě yōuxiān, ruòzhě biānyuánhuà de jiégòu","Mirrors human society's structure where the strong take priority and the weak are marginalized",True),
        o("说明动物行为学是精确的科学","shuōmíng dòngwù xíngwéixué shì jīngquè de kēxué","Shows animal behavior is a precise science"),
        o("鸽子需要人类的管理","gēzi xūyào rénlèi de guǎnlǐ","Pigeons need human management")], 0.55)))

# 10 - urban
P.append(passage("j8_urban_002",
    "The Elevator Sociology", "电梯社会学", 8,
    "电梯是现代城市里最小的公共空间，也是社交规则最密集的场所。我住的这栋三十二层的高楼里，电梯内的行为模式堪称一部微缩的社会学教材。首先是目光管理：当两个陌生人同处一部电梯时，他们的视线会精确地避开对方，转而投向楼层显示屏、手机或者自己的鞋尖。这种目光回避不是冷漠，而是一种默契的领地划分——在这么小的空间里，直视对方会被解读为侵犯。其次是位置选择：第一个进电梯的人通常站在最里面的角落，第二个人则站在对角线的位置，第三个人填补剩余的角落，如此直到空间被均匀分割。这套算法没有人教过，却全世界通用。最有趣的是电梯里的对话规则。邻居之间如果不熟，最常见的交流是关于天气的一句评论，它的功能不是传递信息，而是填充沉默——沉默在电梯里会被放大成一种令人不适的存在。然而一旦电梯门打开，这种短暂的社交契约立即解除，人们各奔东西，仿佛刚才那一分钟的共处从未发生过。",
    "Diàntī shì xiàndài chéngshì lǐ zuì xiǎo de gōnggòng kōngjiān, yě shì shèjiāo guīzé zuì mìjí de chǎngsuǒ. Wǒ zhù de zhè dòng sānshí'èr céng de gāolóu lǐ, diàntī nèi de xíngwéi móshì kānchēng yī bù wēisuō de shèhuìxué jiàocái.",
    "An elevator is the smallest public space in a modern city, and the most rule-dense social arena. In my thirty-two-story building, elevator behavior reads like a miniature sociology textbook. First, gaze management: two strangers' lines of sight precisely avoid each other, redirecting to the floor display, phone, or shoe tips. This isn't coldness but tacit territory partitioning—direct eye contact in such a small space reads as intrusion. Next, position selection: the first person takes the farthest corner, the second takes the diagonal, the third fills the remaining corner, until space is evenly divided. Nobody teaches this algorithm, yet it's universal. Most interesting are conversational rules. When neighbors aren't acquainted, the most common exchange is a weather remark, whose function is not information but filling silence—silence in an elevator amplifies into uncomfortable presence. Yet the moment doors open, this brief social contract dissolves, people scatter as though the one minute of coexistence never happened.",
    mc("作者认为电梯里「目光回避」的本质是什么？",
       "What is the essence of 'gaze avoidance' in elevators?",
       [o("城市人的冷漠和疏离","chéngshì rén de lěngmò hé shūlí","Urban coldness and alienation"),
        o("在极小空间内对个人领地的默契保护","zài jí xiǎo kōngjiān nèi duì gèrén lǐngdì de mòqì bǎohù","Tacit protection of personal territory in minimal space",True),
        o("人们在看手机所以没注意到别人","rénmen zài kàn shǒujī suǒyǐ méi zhùyì dào biérén","People are on phones and don't notice others"),
        o("电梯内光线太暗不方便看人","diàntī nèi guāngxiàn tài àn bù fāngbiàn kàn rén","Elevator lighting is too dim")], 0.45),
    mc("关于天气的评论在电梯对话中的功能是什么？",
       "What function does a weather remark serve in elevator conversation?",
       [o("分享有用的天气信息","fēnxiǎng yǒuyòng de tiānqì xìnxī","Sharing useful weather info"),
        o("填充沉默以缓解社交不适","tiánchōng chénmò yǐ huǎnjiě shèjiāo bú shì","Filling silence to ease social discomfort",True),
        o("表达对邻居的关心","biǎodá duì línjū de guānxīn","Expressing concern for neighbors"),
        o("建立长期友谊的开端","jiànlì chángqī yǒuyì de kāiduān","Beginning of long-term friendship")], 0.4),
    mc("电梯门打开后人们「各奔东西」说明了什么？",
       "What does people scattering when doors open illustrate?",
       [o("电梯内的社交是极度短暂且不留痕迹的","diàntī nèi de shèjiāo shì jídù duǎnzàn qiě bù liú hénjì de","Elevator socialization is extremely brief and leaves no trace",True),
        o("人们出电梯后都很着急","rénmen chū diàntī hòu dōu hěn zhāojí","People are in a hurry after exiting"),
        o("现代人不善于社交","xiàndài rén bú shànyú shèjiāo","Modern people are bad at socializing"),
        o("高楼层的居民更孤独","gāo lóucéng de jūmín gèng gūdú","Higher-floor residents are lonelier")], 0.45)))

append_save("hsk8_batch2.json", P)
