# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, "/Users/jasongerson/mandarin/content_gen")
from gen_helpers import *

P = []

P.append(passage("j8_observe_019", "The Archaeology of Refrigerator Magnets", "冰箱贴的考古学", 8,
    "冰箱门上的磁铁贴是一个家庭的非正式编年史。我妈妈的冰箱门分三个区域：最上面是各种磁性便签夹，夹着医院挂号单和水电缴费提醒——这是生活的行政区。中间是旅游纪念品磁铁：一个巴黎铁塔（二〇一五年的欧洲行）、一个富士山（二〇一七年的日本行）、一个兵马俑（去年的西安行）——这是记忆的展览区。最下面是已经泛黄的儿童画，用七八个不同颜色的卡通磁铁固定着——那是我五岁时的作品，但她从未取下来过。每个磁铁的位置都不是随意的：最常被看到的位置留给了最重要的内容，而那些被挤到角落或被新磁铁覆盖的，就是已经被时间淘汰但又舍不得完全扔掉的记忆。有一次我建议妈妈整理一下冰箱门——它实在太拥挤了——她说：「不行，每一个都有用处。」我后来明白，她说的「用处」不是功能性的，而是情感性的。这扇冰箱门就是她的记忆宫殿，每天做饭时扫一眼，就等于把过去二十年的人生复习了一遍。",
    "Bīngxiāng mén shàng de cítiě tiē shì yī gè jiātíng de fēi zhèngshì biānniánshǐ.",
    "Refrigerator magnets are a family's unofficial chronicle. My mother's fridge door has three zones: top holds magnetic clips with hospital appointment slips and utility reminders—life's administrative district. Middle holds travel souvenir magnets: an Eiffel Tower (2015 Europe trip), Mount Fuji (2017 Japan trip), Terracotta Warriors (last year's Xi'an trip)—memory's exhibition area. Bottom holds yellowed children's drawings, fixed by seven or eight cartoon magnets—my work from age five, never taken down. Each magnet's position is deliberate: the most visible spots are reserved for the most important content, while those squeezed to corners or covered by newer magnets are memories time has retired but which can't quite be thrown away. Once I suggested Mom tidy the fridge door—it was really too crowded. She said: 'No, each one has its use.' I later understood: the 'use' she meant wasn't functional but emotional. That fridge door is her memory palace—a daily glance while cooking equals reviewing twenty years of life.",
    mc("妈妈说「每一个都有用处」，这里的「用处」指什么？", "What does Mom's 'each has its use' refer to?",
       [o("磁铁用来固定纸张","cítiě yòng lái gùdìng zhǐzhāng","Magnets hold up papers"),
        o("每个磁铁承载着情感记忆的功能","měi gè cítiě chéngzài zhe qínggǎn jìyì de gōngnéng","Each magnet carries the function of emotional memory",True),
        o("冰箱门需要装饰","bīngxiāng mén xūyào zhuāngshì","The fridge door needs decoration"),
        o("扔东西是浪费","rēng dōngxi shì làngfèi","Throwing things away is wasteful")], 0.4),
    mc("冰箱门被比作「记忆宫殿」，核心含义是什么？", "What is the core meaning of comparing the fridge door to a 'memory palace'?",
       [o("冰箱很大","bīngxiāng hěn dà","The fridge is big"),
        o("它是日常生活中可以随时触发记忆回顾的实体空间","tā shì rìcháng shēnghuó zhōng kěyǐ suíshí chùfā jìyì huígù de shítǐ kōngjiān","It is a physical space in daily life that can trigger memory review at any time",True),
        o("妈妈的记忆力很好","māma de jìyìlì hěn hǎo","Mom has a good memory"),
        o("冰箱贴是一种收藏爱好","bīngxiāng tiē shì yī zhǒng shōucáng àihào","Fridge magnets are a collecting hobby")], 0.45),
    mc("磁铁位置的排列规律说明了什么？", "What does the arrangement pattern of magnets reveal?",
       [o("妈妈有强迫症","māma yǒu qiǎngpòzhèng","Mom has OCD"),
        o("记忆也有等级——最重要的占据最显眼位置，被淘汰的退居边缘","jìyì yě yǒu děngjí——zuì zhòngyào de zhànjù zuì xiǎnyǎn wèizhì, bèi táotài de tuìjū biānyuán","Memories also have hierarchies—the most important occupy the most visible spots, retired ones retreat to margins",True),
        o("冰箱门空间有限","bīngxiāng mén kōngjiān yǒuxiàn","Fridge door space is limited"),
        o("新磁铁比旧磁铁好看","xīn cítiě bǐ jiù cítiě hǎokàn","New magnets look better than old ones")], 0.45)))

P.append(passage("j8_inst_005", "The Democracy of the Vegetable Market", "菜市场的民主", 8,
    "菜市场是一个比任何正式民主场所都更真实地运行着供需博弈的空间。每天早上六点半，摊贩们就开始了一场关于定价权的无声战争。西红柿卖四块一斤的张大姐如果发现对面的李大哥标价三块八，她会在半小时内把价格调到三块五。但她不会挂出新的价格牌——那样太明显了。她会在顾客问价时口头报出新价格，同时眼角余光扫向李大哥那边，观察对方是否注意到了。这种定价策略比任何商学院的案例都更生动。顾客在这个博弈中也不是被动的。常来的阿姨们精通一种叫做「巡视定价」的策略：先走完整个市场一圈，记住每个摊位的价格，然后折回到性价比最高的摊位购买。更高阶的操作是在购买时随口提一句「那边才卖三块」，逼迫摊贩让利。菜市场的迷人之处在于：这里没有垄断，信息接近完全透明，进入门槛极低——任何一个背着编织袋来的农民都可以成为参与者。它是一个几乎完美的竞争市场，只是经济学教科书从来不用它做案例。",
    "Càishìchǎng shì yī gè bǐ rènhé zhèngshì mínzhǔ chǎngsuǒ dōu gèng zhēnshí de yùnxíng zhe gōngxū bóyì de kōngjiān.",
    "A vegetable market is a space where supply-demand dynamics run more authentically than any formal democratic venue. Every morning at six-thirty, vendors begin a silent war over pricing power. If Sister Zhang selling tomatoes at four yuan per jin sees Brother Li across the aisle pricing at three-eight, she'll adjust to three-five within half an hour. But she won't post a new sign—too obvious. She'll quote the new price verbally when customers ask, peripheral vision scanning Brother Li's side to check if he noticed. This pricing strategy is more vivid than any business school case study. Customers aren't passive either. Regular aunties master a strategy I call 'patrol pricing': walking the entire market first, memorizing every stall's prices, then doubling back to the best value-for-money stall. An advanced move is casually mentioning while buying: 'The other stall only charges three yuan,' forcing a concession. The market's charm is that there's no monopoly, information approaches full transparency, and entry barriers are minimal—any farmer arriving with a woven bag can become a participant. It's a nearly perfect competitive market, yet economics textbooks never use it as a case study.",
    mc("张大姐不挂新价格牌而口头报价，这种策略的原因是什么？", "Why does Sister Zhang quote new prices verbally rather than posting a sign?",
       [o("她不识字","tā bú shízì","She's illiterate"),
        o("避免公开的价格战，保持竞争的隐蔽性","bìmiǎn gōngkāi de jiàgé zhàn, bǎochí jìngzhēng de yǐnbìxìng","Avoiding open price wars and maintaining competitive stealth",True),
        o("口头报价更快","kǒutóu bàojià gèng kuài","Verbal pricing is faster"),
        o("价格变化太频繁","jiàgé biànhuà tài pínfán","Prices change too frequently")], 0.45),
    mc("作者为什么说菜市场比经济学教科书更生动？", "Why does the author say the market is more vivid than economics textbooks?",
       [o("菜市场更有趣","càishìchǎng gèng yǒuqù","Markets are more interesting"),
        o("它展示了完全竞争市场的所有特征——信息透明、低门槛、无垄断——但以人际互动的形式呈现","tā zhǎnshì le wánquán jìngzhēng shìchǎng de suǒyǒu tèzhēng——xìnxī tòumíng, dī ménkǎn, wú lǒngduàn——dàn yǐ rénjì hùdòng de xíngshì chéngxiàn","It demonstrates all features of perfect competition—transparent information, low barriers, no monopoly—but in the form of interpersonal interaction",True),
        o("教科书太枯燥","jiàokēshū tài kūzào","Textbooks are too dry"),
        o("菜市场的经济规模更大","càishìchǎng de jīngjì guīmó gèng dà","Markets have larger economic scale")], 0.5),
    mc("阿姨们的「巡视定价」策略体现了什么经济学原理？", "What economic principle does the aunties' 'patrol pricing' strategy embody?",
       [o("消费者是非理性的","xiāofèizhě shì fēi lǐxìng de","Consumers are irrational"),
        o("信息充分的消费者会通过比价来最大化自身利益","xìnxī chōngfèn de xiāofèizhě huì tōngguò bǐjià lái zuìdàhuà zìshēn lìyì","Well-informed consumers maximize their interests through price comparison",True),
        o("买菜需要花很多时间","mǎi cài xūyào huā hěn duō shíjiān","Grocery shopping takes a lot of time"),
        o("老年人更懂得节省","lǎonián rén gèng dǒngde jiéshěng","Elderly people are better at saving")], 0.4)))

P.append(passage("j8_observe_020", "The Neighbors I've Never Met", "从未见过的邻居", 8,
    "我住在这栋楼的第七层已经三年了，但除了隔壁那一户，我不认识同层任何一位邻居的面孔。我了解他们的方式完全是通过声音：七〇二的住户每天清晨六点的闹钟声透过墙壁传来，那是一首我叫不出名字的古典钢琴曲；七〇四好像养了一只猫，偶尔能听到柔软的喵喵声和猫爪在木地板上的细碎脚步；七〇六似乎住着一对年轻夫妇，他们偶尔争吵，声音模糊但情绪清晰。通过这些声音碎片，我在脑海中构建了一组邻居的「声学肖像」：七〇二是一个喜欢古典音乐的早起者，七〇四是一个独居的养猫人，七〇六是一对还在磨合期的新婚夫妇。这些画像当然可能完全是错的。有一天，七〇二门口出来一位穿嘻哈风格衣服的年轻人，与我想象中的古典音乐爱好者形象相差甚远。那一刻我意识到：我们对近在咫尺的人的了解，可能还不如对社交媒体上万里之外的博主的了解。城市创造了一种新型的亲近——我们共享墙壁、天花板和地板，共享水管和电路，却共享不了最基本的问候。",
    "Wǒ zhù zài zhè dòng lóu de dì qī céng yǐjīng sān nián le, dàn chúle gébì nà yī hù, wǒ bú rènshi tóng céng rènhé yī wèi línjū de miànkǒng.",
    "I've lived on the seventh floor for three years, but apart from one next-door neighbor, I don't know any same-floor neighbor's face. I know them entirely through sound: 702's alarm goes off daily at six AM, a classical piano piece I can't name, leaking through the wall; 704 seems to have a cat, occasionally I hear soft meowing and tiny paw steps on hardwood; 706 appears to house a young couple, they argue sometimes, words blurred but emotion clear. From these sound fragments, I've built 'acoustic portraits' of neighbors: 702 is a classical-music-loving early riser, 704 is a solitary cat owner, 706 is newlyweds still adjusting. These portraits are probably entirely wrong. One day a young person in hip-hop style clothing emerged from 702's door, vastly different from my imagined classical music lover. That moment I realized: our understanding of people inches away may be less than what we know about a blogger thousands of miles away on social media. Cities have created a new kind of proximity—we share walls, ceilings, and floors, share plumbing and wiring, yet can't share the most basic greeting.",
    mc("作者通过什么方式「了解」邻居？", "How does the author 'know' the neighbors?",
       [o("通过社交媒体","tōngguò shèjiāo méitǐ","Through social media"),
        o("完全通过穿透墙壁的声音碎片","wánquán tōngguò chuāntòu qiángbì de shēngyīn suìpiàn","Entirely through sound fragments penetrating the walls",True),
        o("通过物业管理的介绍","tōngguò wùyè guǎnlǐ de jièshào","Through property management introductions"),
        o("通过观察他们进出电梯","tōngguò guānchá tāmen jìnchū diàntī","By watching them enter and exit the elevator")], 0.35),
    mc("七〇二的年轻人与作者想象不符这个细节说明了什么？", "What does the mismatch between 702's actual resident and the author's imagination illustrate?",
       [o("年轻人也会喜欢古典音乐","niánqīng rén yě huì xǐhuān gǔdiǎn yīnyuè","Young people can like classical music too"),
        o("基于有限信息建立的认知可能完全偏离现实","jīyú yǒuxiàn xìnxī jiànlì de rènzhī kěnéng wánquán piānlí xiànshí","Perceptions built on limited information may completely deviate from reality",True),
        o("声音传播会产生误导","shēngyīn chuánbō huì chǎnshēng wùdǎo","Sound transmission can mislead"),
        o("人的外表和内在不一定一致","rén de wàibiǎo hé nèizài bù yīdìng yīzhì","People's appearance and inner selves may not match")], 0.45),
    mc("作者说「共享墙壁却共享不了最基本的问候」，表达了什么？", "What does 'sharing walls yet unable to share the most basic greeting' express?",
       [o("楼房的隔音太差","lóufáng de géyīn tài chà","Building soundproofing is too poor"),
        o("现代城市中物理上的紧密接近与人际上的疏离形成讽刺性对比","xiàndài chéngshì zhōng wùlǐ shàng de jǐnmì jiējìn yǔ rénjì shàng de shūlí xíngchéng fěngcìxìng duìbǐ","The ironic contrast between physical closeness and interpersonal distance in modern cities",True),
        o("应该组织更多社区活动","yīnggāi zǔzhī gèng duō shèqū huódòng","More community activities should be organized"),
        o("城市人太忙了","chéngshì rén tài máng le","City people are too busy")], 0.5)))

P.append(passage("j8_mystery_005", "The Numbers on the Bridge", "桥上的数字", 8,
    "我每天跑步都会经过的那座小桥的栏杆上，有人用记号笔写了一组数字：3-17-42-8-23。这组数字出现在大约三个月前，没有任何解释或署名。我最初以为是彩票号码或者某种游戏暗号，但仔细看会发现字迹非常端正，不像随手涂鸦。数字之间用短横线分隔，写在栏杆第三根竖杆的外侧，那个位置需要特意弯腰才能注意到。我开始留意这组数字的变化。第二周，42变成了43。第四周，8变成了9。到了第八周，整组数字变成了3-17-44-10-23。我终于看出了规律：第一个和最后一个数字不变，中间三个数字在缓慢递增，但递增的速度不一样。这是在计数什么？或者在追踪什么？我试过在不同时间去桥上蹲守，但从未见到任何人在修改数字。有一天，所有数字被人擦掉了，只留下一个淡淡的痕迹。一周后，同样的位置出现了新的一组数字，笔迹一样：1-1-1-1-1。重置了。我站在桥上，看着河水从桥下流过，突然觉得有些事物的意义也许就在于它们永远无法被理解。",
    "Wǒ měi tiān pǎobù dōu huì jīngguò de nà zuò xiǎo qiáo de lángān shàng, yǒu rén yòng jìhào bǐ xiě le yī zǔ shùzì: 3-17-42-8-23.",
    "On the railing of the small bridge I jog past daily, someone wrote a set of numbers in marker: 3-17-42-8-23. They appeared about three months ago with no explanation or signature. I first thought lottery numbers or a game code, but the handwriting was very neat, not like casual graffiti. Numbers were separated by hyphens, written on the third vertical bar's outer side—a position requiring deliberate bending to notice. I started tracking changes. Week two, 42 became 43. Week four, 8 became 9. By week eight, the set was 3-17-44-10-23. I finally spotted the pattern: first and last numbers stayed fixed, the middle three slowly incremented at different rates. What was being counted? Or tracked? I tried staking out the bridge at different times but never saw anyone modifying the numbers. One day, all numbers were erased, leaving faint traces. A week later, at the same spot, new numbers appeared in identical handwriting: 1-1-1-1-1. Reset. I stood on the bridge, watching the river flow beneath, suddenly feeling that some things' meaning lies precisely in their being forever incomprehensible.",
    mc("作者观察到数字变化的规律是什么？", "What pattern did the author observe in the number changes?",
       [o("所有数字都在增加","suǒyǒu shùzì dōu zài zēngjiā","All numbers were increasing"),
        o("首尾数字不变，中间三个数字以不同速度递增","shǒuwěi shùzì bú biàn, zhōngjiān sān gè shùzì yǐ bùtóng sùdù dìzēng","First and last stayed fixed, middle three incremented at different rates",True),
        o("数字每周翻倍","shùzì měi zhōu fānbèi","Numbers doubled weekly"),
        o("只有一个数字在变化","zhǐ yǒu yī gè shùzì zài biànhuà","Only one number was changing")], 0.4),
    mc("数字被擦除后重新出现「1-1-1-1-1」，这个细节的叙事作用是什么？", "What is the narrative function of '1-1-1-1-1' appearing after the numbers were erased?",
       [o("证明数字是某种计数系统","zhèngmíng shùzì shì mǒu zhǒng jìshù xìtǒng","Proves the numbers are some counting system"),
        o("制造更深的悬念——系统被重置但依然存在，谜题不但没解开反而加深了","zhìzào gèng shēn de xuánniàn——xìtǒng bèi chóngzhì dàn yīrán cúnzài, mítí bùdàn méi jiě kāi fǎn'ér jiāshēn le","Creates deeper suspense—the system was reset but persists, the mystery deepens rather than resolves",True),
        o("说明有人在破坏桥上的涂鸦","shuōmíng yǒu rén zài pòhuài qiáo shàng de túyā","Shows someone is vandalizing bridge graffiti"),
        o("暗示这是一个笑话","ànshì zhè shì yī gè xiàohua","Suggests this is a joke")], 0.5),
    mc("文末「有些事物的意义在于永远无法被理解」表达了什么态度？", "What attitude does 'some things' meaning lies in being forever incomprehensible' express?",
       [o("放弃思考","fàngqì sīkǎo","Giving up thinking"),
        o("接受并欣赏世界中不可解释之物的存在","jiēshòu bìng xīnshǎng shìjiè zhōng bùkě jiěshì zhī wù de cúnzài","Accepting and appreciating the existence of inexplicable things in the world",True),
        o("批评写数字的人不负责任","pīpíng xiě shùzì de rén bù fùzérèn","Criticizing the number-writer as irresponsible"),
        o("对自己的观察能力感到失望","duì zìjǐ de guānchá nénglì gǎndào shīwàng","Disappointed in his own observational ability")], 0.45)))

P.append(passage("j8_comedy_004", "The Taxonomy of Napping at Work", "午睡的分类学", 8,
    "办公室午睡是一门需要天赋和技术的隐蔽艺术。在我工作过的几家公司里，我总结出了五种经典的午睡姿势。第一种是「趴桌式」——双臂交叉在桌面上，头埋在臂弯里，这是最常见也最容易被识别的姿势。它的致命缺点是醒来后脸上会留下清晰的衣袖褶皱印记，持续大约四十分钟才会消退。第二种是「假装看文件式」——一手撑头，另一手放在打开的文件上，闭上眼睛，头微微下垂。从远处看，这个人像是在认真思考一个复杂的问题。第三种是「洗手间冥想式」——去洗手间的隔间里坐五到十分钟，这需要极强的平衡感以防止因为睡着而从马桶上滑落。第四种是「通勤午睡式」——利用午休时间在车里或者附近的咖啡馆小睡，这是最舒适但成本最高的方案。第五种是最高境界，我称之为「睁眼入定式」——这种人可以在看起来完全清醒的状态下进入某种浅睡眠，眼睛是睁开的，但如果你仔细看，瞳孔已经失去了焦距。",
    "Bàngōngshì wǔshuì shì yī mén xūyào tiānfù hé jìshù de yǐnbì yìshù.",
    "Office napping is a covert art requiring talent and technique. Across several companies I've worked at, I've catalogued five classic napping postures. First is the 'desk drape'—arms crossed on the desk, head buried in the crook. Most common and identifiable. Its fatal flaw: waking with clear sleeve-crease marks on the face, lasting about forty minutes. Second is the 'pretending to read'—one hand propping the head, the other on an open document, eyes closed, head slightly drooping. From afar, this person appears to be pondering a complex problem. Third is the 'restroom meditation'—sitting in a stall for five to ten minutes, requiring excellent balance to avoid sliding off the toilet if you fall asleep. Fourth is the 'commute nap'—using lunch break to sleep in the car or a nearby cafe, most comfortable but highest cost. Fifth is the ultimate level, which I call the 'open-eyed trance'—these individuals enter a light sleep while appearing fully awake, eyes open, but look carefully and the pupils have lost focus.",
    mc("作者将午睡分为五种姿势的写作手法是什么？", "What writing technique does the author use in classifying five napping postures?",
       [o("科学研究报告","kēxué yánjiū bàogào","Scientific research report"),
        o("以学术分类的框架来幽默地描述日常行为","yǐ xuéshù fēnlèi de kuàngjià lái yōumò de miáoshù rìcháng xíngwéi","Using an academic classification framework to humorously describe everyday behavior",True),
        o("抱怨办公室环境不好","bàoyuàn bàngōngshì huánjìng bù hǎo","Complaining about poor office conditions"),
        o("建议公司安排午休时间","jiànyì gōngsī ānpái wǔxiū shíjiān","Suggesting companies arrange nap times")], 0.4),
    mc("「趴桌式」的「致命缺点」是什么？", "What is the 'fatal flaw' of the 'desk drape'?",
       [o("对颈椎不好","duì jǐngzhuī bù hǎo","Bad for the cervical spine"),
        o("醒来后脸上留下衣袖褶皱的印记暴露了午睡事实","xǐnglái hòu liǎn shàng liú xià yīxiù zhězhòu de yìnjì bàolù le wǔshuì shìshí","Sleeve-crease marks on the face after waking expose the napping",True),
        o("容易被老板看到","róngyì bèi lǎobǎn kàn dào","Easy for the boss to see"),
        o("睡得不舒服","shuì de bù shūfu","Uncomfortable sleeping")], 0.35),
    mc("「睁眼入定式」被称为最高境界的原因是什么？", "Why is the 'open-eyed trance' called the ultimate level?",
       [o("因为它最舒适","yīnwèi tā zuì shūshì","Because it's most comfortable"),
        o("它实现了在看似清醒的状态下入睡，完全不会被发现","tā shíxiàn le zài kànsì qīngxǐng de zhuàngtài xià rùshuì, wánquán bú huì bèi fāxiàn","It achieves sleeping while appearing fully awake, completely undetectable",True),
        o("它对健康最好","tā duì jiànkāng zuì hǎo","It's healthiest"),
        o("只有老板才会这种姿势","zhǐ yǒu lǎobǎn cái huì zhè zhǒng zīshì","Only bosses know this posture")], 0.4)))

P.append(passage("j8_observe_021", "The Patience of Stoplights", "红绿灯的耐心", 8,
    "一个红绿灯能告诉你很多关于一个城市节奏的信息。在我住的城市，主干道的红灯时长是九十秒，这在全国范围内属于偏长的。九十秒的等待在步行者的体感中被无限拉长——我观察过，大约有百分之三十五的行人会在红灯亮了六十秒之后开始张望，判断是否可以闯红灯。到了七十秒，又有百分之二十的人会迈出试探性的一步。而那些坚持等到绿灯的人，往往不是因为更有耐心，而是因为他们在看手机——注意力被转移了，时间的压迫感也随之减轻。最有趣的是凌晨时分的红绿灯。马路上空无一人一车，灯还在机械地变换着红黄绿。那个场景有一种超现实的荒诞感：一个为人类设计的系统，在没有人使用的时候仍然忠实地运转着。它不知道现在是凌晨三点，不知道路上没有人，不知道自己的存在在此刻毫无意义。但正是这种不知疲倦的机械忠诚，让我莫名地感到安慰——世界上至少有些东西是不会因为无人注目而停止工作的。",
    "Yī gè hónglǜdēng néng gàosu nǐ hěn duō guānyú yī gè chéngshì jiézòu de xìnxī.",
    "A traffic light can tell you a lot about a city's rhythm. In my city, main road red lights last ninety seconds—long by national standards. Ninety seconds stretches infinitely in a pedestrian's perception—I observed that about thirty-five percent of pedestrians start looking around after sixty seconds of red, judging whether to jaywalk. At seventy seconds, another twenty percent take a tentative step. Those who wait for green are often not more patient but distracted by phones—diverted attention lightens time's pressure. Most interesting are traffic lights at dawn. Streets empty of people and cars, lights still mechanically cycling red-yellow-green. The scene has a surreal absurdity: a system designed for humans, faithfully operating when no one uses it. It doesn't know it's three AM, doesn't know the road is empty, doesn't know its existence is momentarily meaningless. But this tireless mechanical loyalty somehow comforts me—at least some things in this world won't stop working just because nobody is watching.",
    mc("百分之三十五的行人在六十秒后开始张望，这说明了什么？", "What does 35% of pedestrians looking around after 60 seconds indicate?",
       [o("红灯时间设计不合理","hónglǜdēng shíjiān shèjì bù hélǐ","Traffic light timing is poorly designed"),
        o("人类对等待的忍耐力有一个普遍的阈值","rénlèi duì děngdài de rěnnàilì yǒu yī gè pǔbiàn de yùzhí","Human patience for waiting has a universal threshold",True),
        o("这个城市的交通很差","zhège chéngshì de jiāotōng hěn chà","This city's traffic is poor"),
        o("行人安全意识不强","xíngrén ānquán yìshi bù qiáng","Pedestrians lack safety awareness")], 0.45),
    mc("凌晨空无一人时红绿灯仍在运转的场景为什么让作者感到安慰？", "Why does the empty-street traffic light still cycling comfort the author?",
       [o("说明电力系统很可靠","shuōmíng diànlì xìtǒng hěn kěkào","Shows the power system is reliable"),
        o("不知疲倦的机械忠诚代表了一种不依赖人类注意力而持续运转的秩序","bù zhī píjuàn de jīxiè zhōngchéng dàibiǎo le yī zhǒng bù yīlài rénlèi zhùyìlì ér chíxù yùnzhuǎn de zhìxù","The tireless mechanical loyalty represents an order that persists without depending on human attention",True),
        o("红绿灯的灯光在夜里很好看","hónglǜdēng de dēngguāng zài yè lǐ hěn hǎokàn","Traffic lights look nice at night"),
        o("他害怕完全黑暗的街道","tā hàipà wánquán hēi'àn de jiēdào","He fears completely dark streets")], 0.5),
    mc("看手机的行人能等更久的原因是什么？", "Why can phone-checking pedestrians wait longer?",
       [o("手机上有倒计时","shǒujī shàng yǒu dàojìshí","Their phones have a countdown"),
        o("注意力被转移，减轻了等待的时间压迫感","zhùyìlì bèi zhuǎnyí, jiǎnqīng le děngdài de shíjiān yāpògǎn","Diverted attention lightens the sense of time pressure while waiting",True),
        o("他们不赶时间","tāmen bù gǎn shíjiān","They're not in a hurry"),
        o("手机让他们看不到红灯","shǒujī ràng tāmen kàn bú dào hónglǜdēng","Phones prevent them from seeing the red light")], 0.4)))

# Continue: observe, urban, inst, identity, food
P.append(passage("j8_observe_022", "The Handwriting of Strangers", "陌生人的笔迹", 8,
    "在共享办公空间的白板上，你能看到至少五种截然不同的笔迹共存于同一块书写面上。有一种字迹极小而工整，像是用直尺辅助写出来的——这通常属于做数据分析的人，他们连写字都追求精确。有一种字迹龙飞凤舞，潦草到几乎无法辨认——这往往是创意部门的产物，思维速度远超书写速度。有一种字迹总是使用大写字母和方框来强调重点——这是管理者的习惯，每一个字都透着一种「我在做决定」的气场。偶尔会出现一种特别柔和的圆体字迹，所有的拐角都被磨圆了——我后来发现这属于实习生，她们的书写方式还带着学生时代的影子。白板上这些笔迹的重叠和覆盖构成了一种独特的集体记忆。每周五下午清洁白板时，一周的讨论、争论和灵感就这样被一块湿抹布擦去了。我有时觉得这个动作本身就是一个隐喻：在这个时代，我们创造的大多数东西都是可擦除的。",
    "Zài gòngxiǎng bàngōng kōngjiān de báibǎn shàng, nǐ néng kàn dào zhìshǎo wǔ zhǒng jiérán bùtóng de bǐjì gòngcún yú tóngyī kuài shūxiě miàn shàng.",
    "On a shared office whiteboard, you can see at least five distinctly different handwriting styles coexisting on the same surface. One is tiny and precise, as if written with a ruler—typically from data analysts, who pursue accuracy even in writing. One is wildly cursive, nearly illegible—often from the creative department, thinking faster than writing speed allows. One always uses block capitals and boxes for emphasis—a manager's habit, every letter radiating 'I am making decisions.' Occasionally there's a particularly soft, rounded script with all corners smoothed—I discovered this belongs to interns, whose writing still carries the shadow of student days. These overlapping handwriting styles on the board form a unique collective memory. When the whiteboard is cleaned Friday afternoon, a week of discussions, debates, and inspirations are erased by a damp cloth. I sometimes think this act is itself a metaphor: in this era, most things we create are erasable.",
    mc("不同笔迹与职业角色之间的对应关系说明了什么？", "What does the correspondence between handwriting and professional roles illustrate?",
       [o("应该统一办公室的书写规范","yīnggāi tǒngyī bàngōngshì de shūxiě guīfàn","Office writing standards should be unified"),
        o("书写方式无意识地反映了一个人的思维模式和职业身份","shūxiě fāngshì wúyìshi de fǎnyìng le yī gè rén de sīwéi móshì hé zhíyè shēnfèn","Writing style unconsciously reflects a person's thinking pattern and professional identity",True),
        o("白板不适合办公使用","báibǎn bú shìhé bàngōng shǐyòng","Whiteboards aren't suitable for office use"),
        o("每个人的教育背景不同","měi gè rén de jiàoyù bèijǐng bùtóng","Everyone's educational background differs")], 0.45),
    mc("擦白板被比作隐喻，这个隐喻指什么？", "What does the whiteboard-erasing metaphor refer to?",
       [o("清洁工作很重要","qīngjié gōngzuò hěn zhòngyào","Cleaning is important"),
        o("这个时代我们创造的大多数内容都是临时的、可被轻易抹去的","zhège shídài wǒmen chuàngzào de dàduōshù nèiróng dōu shì línshí de, kě bèi qīngyì mǒ qù de","Most content we create in this era is temporary and easily erasable",True),
        o("每周应该更换白板","měi zhōu yīnggāi gēnghuàn báibǎn","Whiteboards should be replaced weekly"),
        o("讨论的结果应该被记录下来","tǎolùn de jiéguǒ yīnggāi bèi jìlù xiàlái","Discussion results should be recorded")], 0.5),
    mc("实习生的圆体字迹「带着学生时代的影子」暗示了什么？", "What does interns' rounded script 'carrying the shadow of student days' suggest?",
       [o("实习生字写得好看","shíxíshēng zì xiě de hǎokàn","Interns have pretty handwriting"),
        o("书写习惯保留了一个人的成长痕迹，职场尚未将其重塑","shūxiě xíguàn bǎoliú le yī gè rén de chéngzhǎng hénjì, zhíchǎng shàng wèi jiāng qí chóng sù","Writing habits preserve traces of one's growth, not yet reshaped by the workplace",True),
        o("学校应该教更多书写技巧","xuéxiào yīnggāi jiāo gèng duō shūxiě jìqiǎo","Schools should teach more writing skills"),
        o("实习生还不够专业","shíxíshēng hái búgòu zhuānyè","Interns aren't professional enough")], 0.45)))

P.append(passage("j8_urban_007", "The Social Contract of Dog Walking", "遛狗的社会契约", 8,
    "遛狗是城市社交中一种独特的破冰机制。两个素不相识的人在街上擦肩而过时绝不会主动搭话，但如果双方都牵着狗，一次对话几乎是不可避免的。对话的开端总是关于狗的：「它几岁了？」「是什么品种？」「好乖啊！」这些问题本身毫无信息价值，但它们的功能是建立一个安全的社交缓冲区——通过谈论狗来避免直接面对人与人之间的陌生感。更有趣的是，狗之间的互动往往主导着人之间的互动。如果两只狗互相嗅闻并友好地摇尾巴，主人们也会松弛下来，对话可能延伸到天气、小区设施甚至个人生活。但如果两只狗互相吠叫或对峙，主人们会迅速拉开距离，对话戛然而止。我观察到，有些人甚至会选择性地在特定时间遛狗，以便遇到那些狗与自己的狗「合得来」的邻居。这套由动物偏好驱动的社交过滤系统，比任何社交软件的算法都更诚实——它不考虑你的职业、收入或教育背景，只看你的狗是否愿意和对方的狗玩。",
    "Liú gǒu shì chéngshì shèjiāo zhōng yī zhǒng dútè de pò bīng jīzhì.",
    "Dog walking is a unique ice-breaking mechanism in urban social life. Two strangers passing on the street would never initiate conversation, but if both are walking dogs, dialogue is almost inevitable. It always starts about the dogs: 'How old?' 'What breed?' 'So well-behaved!' These questions have zero information value, but their function is to create a safe social buffer zone—talking about dogs to avoid directly facing interpersonal strangeness. More interesting, dogs' interactions often drive humans' interactions. If two dogs sniff each other and wag tails, owners relax and conversation may extend to weather, community facilities, even personal lives. But if dogs bark or posture at each other, owners quickly create distance and conversation halts. I've observed some people selectively walking dogs at specific times to encounter neighbors whose dogs 'get along' with theirs. This social filtering system driven by animal preferences is more honest than any social app algorithm—it doesn't consider your career, income, or education, only whether your dog is willing to play with theirs.",
    mc("遛狗时关于狗的寒暄本身有什么社交功能？", "What social function do dog-related pleasantries serve?",
       [o("获取关于狗的实用信息","huòqǔ guānyú gǒu de shíyòng xìnxī","Obtaining practical information about dogs"),
        o("建立安全的社交缓冲区，避免直接面对人际陌生感","jiànlì ānquán de shèjiāo huǎnchōng qū, bìmiǎn zhíjiē miànduì rénjì mòshēnggǎn","Creating a safe social buffer zone to avoid directly facing interpersonal strangeness",True),
        o("表达对动物的喜爱","biǎodá duì dòngwù de xǐ'ài","Expressing love for animals"),
        o("判断对方是否是好人","pànduàn duìfāng shìfǒu shì hǎo rén","Judging whether the other person is good")], 0.45),
    mc("作者说这套系统「比社交软件的算法更诚实」，原因是什么？", "Why does the author call this system 'more honest than social app algorithms'?",
       [o("狗不会说谎","gǒu bú huì shuōhuǎng","Dogs don't lie"),
        o("它只基于动物本能的直接反应来筛选社交对象，不涉及人类社会的身份标签","tā zhǐ jīyú dòngwù běnnéng de zhíjiē fǎnyìng lái shāixuǎn shèjiāo duìxiàng, bú shèjí rénlèi shèhuì de shēnfèn biāoqiān","It filters social contacts based only on animals' instinctive direct reactions, not human social identity labels",True),
        o("社交软件的算法不准确","shèjiāo ruǎnjiàn de suànfǎ bù zhǔnquè","Social app algorithms are inaccurate"),
        o("养狗的人都很友善","yǎng gǒu de rén dōu hěn yǒushàn","Dog owners are all friendly")], 0.5),
    mc("人们选择特定时间遛狗这一现象说明了什么？", "What does people choosing specific times for dog walking indicate?",
       [o("他们的作息时间很固定","tāmen de zuòxī shíjiān hěn gùdìng","They have fixed schedules"),
        o("人类会利用动物的社交偏好来间接选择自己的人际圈","rénlèi huì lìyòng dòngwù de shèjiāo piānhǎo lái jiānjiē xuǎnzé zìjǐ de rénjìquān","Humans use animals' social preferences to indirectly select their own social circles",True),
        o("不同品种的狗需要不同的遛狗时间","bùtóng pǐnzhǒng de gǒu xūyào bùtóng de liú gǒu shíjiān","Different dog breeds need different walking times"),
        o("为了避开交通高峰","wèile bìkāi jiāotōng gāofēng","To avoid traffic peaks")], 0.45)))

save("hsk8_batch4.json", P)
