"""Context notes for vocabulary items.

Culturally rich, observational notes that make vocabulary feel personal
rather than generic flashcard material. Keyed by hanzi.
"""

CONTEXT_NOTES = {
    # === HSK 1 (150 items) ===
    "爱": "The bottom component is a friend (友) cradled by a roof and claws — love as something you grasp and shelter. The simplified form dropped the heart (心) that the traditional character has, which says something.",
    "八": "The two strokes split apart, visually representing division — which is why 八 is associated with splitting and separating in other characters. Also the luckiest number in Chinese culture because it sounds like 发 (get rich).",
    "爸爸": "父 (father) over 巴 for sound. The doubling makes it informal — single-syllable 父 is too stiff for talking to your actual dad.",
    "杯子": "木 (wood) plus 不, originally a wooden drinking vessel. The 子 suffix turns it into a noun — you'll see this pattern constantly (桌子, 椅子, 孩子).",
    "北京": "Literally 'northern capital,' paired with 南京 (Nanjing, 'southern capital'). China has moved its capital so many times that the names are basically compass directions plus 京.",
    "本": "A tree (木) with a horizontal stroke at the base marking the root — the original meaning is 'root' or 'origin,' which evolved into 'this' and the measure word for books (bound at the root, so to speak).",
    "不客气": "Literally 'don't be a guest about it' — 客气 means polite in a formal, guest-like way. The reply to 谢谢 is basically 'stop being so formal.'",
    "不": "Changes to second tone (bú) before a fourth-tone word, which happens constantly. One of the first tone sandhi rules you actually need to internalize rather than memorize.",
    "菜": "Grass radical on top because vegetables are plants — shocking. But 菜 also means 'dish' as in a prepared food item, so 点菜 (order food) literally means 'select dishes.'",
    "茶": "The character decomposes into grass, person, and tree — a person among plants, more or less. Chinese tea culture predates pretty much every other tea tradition; the word 'tea' in most world languages derives from Chinese dialect pronunciations.",
    "吃": "Mouth radical (口) plus 乞 (beg). The original meaning was closer to stammer or stutter; the eating sense took over. You'll use this one multiple times daily.",
    "出租车": "Literally 'out-rent-vehicle.' Brutally practical compound. In many cities people say 打车 (hit a car) or 打的 (dǎ dī) to mean 'hail a cab,' which sounds violent but isn't.",
    "打电话": "打 literally means 'hit' or 'strike' — the metaphor is from the physical act of striking telegraph keys. Chinese uses 打 for an absurd number of actions: play ball, type, fight, fetch water.",
    "大": "A person (人) with arms stretched wide. One of the most visually intuitive characters you'll encounter. 太 adds a dot to mean 'too much' — even bigger than big.",
    "的": "The single most common character in written Chinese. It's the possessive and attributive marker — 我的 (my), 红的 (the red one). Grammatically load-bearing; you'll write it in your sleep.",
    "点": "Originally meant a dot or spot, extended to 'o'clock' (a point in time) and 'a little' (点儿). When ordering food, 点菜 uses this character — you're pointing at what you want.",
    "电脑": "Electric brain. One of the more charming modern coinages. Taiwan uses 電腦 (same meaning, traditional characters) while avoiding the mainland neologism 计算机 (computing machine) used in formal contexts.",
    "电视": "Electric vision. The pattern 电 + sense organ or function generates a lot of modern technology words: 电话 (electric speech = phone), 电影 (electric shadow = movie).",
    "电影": "Electric shadow — referring to the projected flickering images. Arguably the most poetic name for cinema in any language.",
    "东西": "East-west, but means 'thing' or 'stuff.' One theory: markets in ancient Chang'an ran east-west, so shopping meant going 东西. Whether or not that's true, it's how everyone remembers it.",
    "都": "Means 'all' or 'both' and it goes BEFORE the verb, which will trip you up repeatedly. 我们都去 (we all go), not 我们去都.",
    "读": "The speech radical (讠) plus 卖 — language being traded, in a sense. Primarily means 'read aloud'; silent reading is more often 看书.",
    "对不起": "Literally 'cannot face' or 'unable to face' — 对 (face/toward) 不 (not) 起 (rise). An apology framed as shame about not being able to meet someone's eyes.",
    "多": "Two 夕 (evening) stacked — many evenings, many of anything. Functions as both 'many' and 'how' in questions (多大 = how old, 多远 = how far), which is a genuinely useful pattern.",
    "多少": "Literally 'how many how few' — a question word that covers any quantity. Unlike 几, which implies a small expected number, 多少 is open-ended.",
    "儿子": "儿 originally depicted a baby with an open fontanelle. The 子 suffix here is part of the word, not the noun-suffix pattern — 儿子 is 'son' as a unit.",
    "二": "Two horizontal strokes. Simple enough, but watch out: Chinese has two words for 'two' — 二 (the number) and 两 (used with measure words). Mixing them up marks you instantly.",
    "饭店": "Rice-shop, essentially. Can mean either restaurant or hotel depending on context and how fancy the establishment is — a 饭店 with stars is a hotel; the one on the corner is where you eat.",
    "飞机": "Flying machine. 飞 itself is a beautiful character — the traditional form 飛 looks like a crane with spreading wings. The simplified version lost some of that grace.",
    "分钟": "分 means divide (and also the currency unit 'fen,' 1/100 of a yuan). A minute is a divided portion of time. 钟 is bell/clock — minutes are bell-divisions.",
    "高兴": "Tall excitement, roughly. 兴 (excitement, interest) appears in a lot of emotion words. 高兴 is the default way to say happy — more common in daily speech than 快乐.",
    "个": "The most common measure word, used when you can't remember the right one or when no specific one exists. Native speakers also default to it casually, so you're in good company.",
    "工作": "Worker-action. 工 (work) is a pictograph of a carpenter's square or tool. This word covers both the noun 'job' and the verb 'to work.'",
    "汉语": "Han-language. 汉 refers to the Han ethnic group (about 92% of China's population) and the Han Dynasty, which cemented Chinese cultural identity. 中文 emphasizes the writing system; 汉语 emphasizes the spoken language.",
    "好": "Woman (女) plus child (子) — the traditional idea that a woman with a child is 'good.' Problematic by modern standards, but etymologically transparent. Also used as a greeting: 你好 is literally 'you good.'",
    "喝": "Mouth radical plus 曷 for sound. You drink with your mouth — the radical system being helpful for once. 喝水, 喝茶, 喝咖啡: the verb stays the same regardless of liquid.",
    "和": "Grain (禾) plus mouth (口) — harmony comes from having food to discuss over. Functions as 'and' for nouns but NOT for linking clauses — a common early mistake.",
    "很": "Technically means 'very,' but in practice it often functions as a filler that makes adjective predicates grammatical. 她很漂亮 can mean 'she's pretty' without much 'very' emphasis.",
    "后面": "后 originally depicted a foot trailing behind. 面 is face/surface/side. Positional words in Chinese work like nouns — 桌子的后面 (the table's behind-side).",
    "回": "A spiral or return path — the character literally looks like something going back to where it started. The doubled-box structure is visually satisfying and easy to remember.",
    "会": "Covers 'can' (learned ability), 'will' (future), and 'meeting.' Context does all the heavy lifting. 我会游泳 = I can swim; 我会去 = I will go; 开会 = hold a meeting.",
    "几": "Means 'how many' when you expect a small number (under ten, roughly) and also means 'several.' The ambiguity between question and statement is resolved by context and tone of delivery.",
    "家": "A pig (豕) under a roof (宀) — livestock under shelter was the ancient marker of a household. Still the word for home, family, and the suffix for specialists (科学家, 艺术家).",
    "叫": "Mouth (口) plus a phonetic component. Means 'call' or 'be called' — 你叫什么名字 is the standard 'what's your name,' literally 'you are called what name.'",
    "今天": "Today. 今 (now/present) plus 天 (day/sky). The 天 character is a person with a big head (or with emphasis on what's above) — the sky overhead, extended to mean 'day.'",
    "九": "Sounds like 久 (long-lasting), making it a lucky number for relationships and durability. Historically associated with the emperor — the Forbidden City has 9,999 rooms (allegedly).",
    "开": "Simplified from 開, which showed two hands lifting a door bar. Covers an enormous semantic range: open, start, drive, turn on, operate. One of those verbs that keeps showing up in new compounds.",
    "看": "Hand (手, compressed to 扌-like shape on top) over eye (目) — shading your eyes to look. Covers watching, reading, and visiting (看朋友). Context determines which.",
    "看见": "看 (look) plus 见 (perceive) — the difference between looking and actually seeing. Chinese often pairs an action verb with a result verb this way. If you looked but didn't spot it, you didn't 看见.",
    "块": "The measure word for yuan (the base unit of RMB) and also means 'piece' or 'chunk.' In spoken Chinese, 块 is far more common than the formal 元 — like saying 'bucks' instead of 'dollars.'",
    "来": "Originally depicted a wheat plant — wheat 'came' from the west to ancient China. The borrowing for 'come' completely overtook the grain meaning. Traditional form 來 still shows the plant shape.",
    "老师": "Old-master, but 老 here is respectful, not decrepit. Teachers in China are addressed as [Surname]老师 in virtually all contexts — it carries more social weight than 'teacher' does in English.",
    "了": "Two functions, one character, endless confusion. Sentence-final 了 indicates change of state; post-verb 了 indicates completion. Entire dissertations have been written about this particle.",
    "冷": "Ice radical (冫) on the left — those two dots represent ice in the radical system. Whenever you see 冫, expect something related to cold or freezing.",
    "里": "Inside. Also a unit of distance (about half a kilometer). The character shows a field (田) inside a boundary (土 below) — land contained within something. In addresses, 里面 means 'inside.'",
    "零": "Rain radical on top (雨) — originally described light, scattered rain, which extended to 'scattered' and then 'zero.' A surprisingly poetic origin for a number.",
    "六": "Considered lucky because it sounds like 流 (flow), suggesting smooth sailing. Repeating sixes (66, 666) in Chinese culture mean 'everything going smoothly' — the opposite of Western 666 associations.",
    "妈妈": "女 (woman) plus 马 (horse) for sound. The 马 is purely phonetic — no equine implications for your mother. Like 爸爸, the doubling makes it the informal, spoken form.",
    "吗": "The yes/no question particle. Tack it onto any statement and it becomes a question — one of the most elegant features of Chinese grammar. No word reordering, no auxiliary verbs, just 吗.",
    "买": "Simplified from 買, which had a net (罒) over shells (贝) — catching money, essentially. Shells were ancient currency, which is why so many money-related characters have 贝.",
    "没关系": "Literally 'no connection' or 'no relation.' Used to dismiss concern — 'it doesn't matter.' The response to 对不起, and one of the first phrases you'll use reflexively.",
    "没有": "没 negates 有 specifically (not 不). This is a non-negotiable distinction: 不 negates everything else, but possession and existence get 没有. Forgetting this sounds genuinely wrong to native ears.",
    "米饭": "Rice-rice, basically — 米 is uncooked grain, 饭 is cooked food/meal. 米饭 specifies steamed rice as distinct from, say, 炒饭 (fried rice) or 饭 in the general meal sense.",
    "明天": "Bright day — 明 combines sun (日) and moon (月), meaning 'bright' or 'clear.' Tomorrow is the bright day ahead. Yesterday (昨天) doesn't have nearly as optimistic an etymology.",
    "名字": "Name-character. In Chinese culture, personal names are chosen with enormous care — stroke count, element balance (五行), and meaning all factor in. It's not unusual for families to consult a naming specialist.",
    "哪": "Which/where. Mouth radical (口) plus 那 — literally 'that' made into a question by adding the mouth component. The relationship between 那 (that) and 哪 (which) is baked into the characters.",
    "哪儿": "Where. The 儿 suffix is a Beijing/northern feature (儿化). In southern China and Taiwan, people say 哪里 instead. Both are correct; your choice signals regional influence.",
    "那": "That/there. Used as a filler word in speech (like English 'so' or 'well') — you'll hear 那...那...那... in natural conversation constantly.",
    "呢": "A question particle that's softer than 吗. 你呢? (and you?) after answering a question is its most common use. Also marks ongoing states: 她在看书呢 (she's reading, you know).",
    "能": "Ability based on circumstances or permission — 'can' in the sense of 'am able to' or 'am allowed to.' Distinguished from 会 (learned skill) and 可以 (permission/possibility). The three-way split takes practice.",
    "你": "Person radical (亻) plus 尔 for sound. In digital Chinese, 你 has spawned 妳 (female you, mainly in Taiwan) and the playful 泥 substitution in internet slang.",
    "年": "Originally a pictograph of a person carrying grain — a harvest cycle, hence 'year.' 过年 (celebrate New Year) is arguably the most important event in the Chinese calendar.",
    "女儿": "Woman-child. 女 is one of the most recognizable radicals — a kneeling figure in the ancient forms. It appears in an uncomfortable number of characters with negative meanings, a relic of historical attitudes.",
    "朋友": "Two strings of cowrie shells (朋) plus a pair of right hands (友) — wealth shared between helping hands. The character 朋 originally meant a unit of currency; friendship is two such units together.",
    "漂亮": "The 漂 has the water radical — floating, drifting, elegant on the surface. Primarily used for visual beauty of people and things; for abstract beauty (a beautiful idea), you'd use 美.",
    "苹果": "Apple. Also the Chinese name for Apple Inc. (苹果公司). The fruit wasn't native to China — it came via the Silk Road, and the characters are phonetic borrowings rather than descriptive.",
    "七": "Considered neither lucky nor unlucky in daily life, unlike six or eight. The seventh month (七月) is ghost month in some traditions, giving seven a mildly spooky association.",
    "钱": "Metal radical (钅) plus 戋 — money was originally metal (coins). The radical system tells you: if it has 钅, it's related to metal or money. 有钱 (have money) is blunt but ubiquitous.",
    "前面": "前 originally depicted a foot moving forward under a boat — advancing. 面 again means side/surface. Chinese spatial terms are consistently structured: direction + 面 or direction + 边.",
    "请": "Speech radical (讠) plus 青 (green/blue, here for sound). Covers 'please,' 'invite,' and 'treat someone to a meal' (请客). 请 is your all-purpose politeness upgrade for any request.",
    "去": "Originally a pictograph of a person leaving a dwelling — departure. Combined with destinations, it's simply 'go to.' Word order is 去 + place, not place + 去.",
    "热": "The bottom is 灬, a variant of fire (火) — four little flames heating things up. Characters with 灬 at the bottom usually involve heat or cooking (煮, 烹, 熟).",
    "人": "A side-view of a person walking — two strokes, one of the simplest characters. As a radical (亻) it appears in hundreds of characters relating to people and their qualities.",
    "认识": "Speech/word radical (讠) plus a phonetic component. The combination means 'recognize' or 'get to know' — 认 is the cognitive act, 识 is the knowledge. 你认识他吗 is 'do you know him (personally)?'",
    "三": "Three horizontal strokes. In classical Chinese thought, three represents completeness — heaven, earth, and humanity. The character 王 (king) connects all three with a vertical stroke.",
    "商店": "Commerce-shop. 商 (commerce, business) is one of the oldest Chinese characters, dating back to the Shang Dynasty — which was named for its association with trade.",
    "上": "Upward. A line above a baseline — the marker pointing up. Used for 'last' in time expressions (上个月 = last month) and 'on' in spatial ones (桌子上 = on the table). Direction is contextual.",
    "上午": "Upper-noon, i.e., the part of the day before the noon marker. The morning. Chinese divides the day into neat segments: 早上, 上午, 中午, 下午, 晚上.",
    "少": "Few, not much. Also pronounced shào in 少年 (youth). The small-over-a-slash structure suggests something being cut down or reduced. Opposite of 多, and they pair up everywhere.",
    "谁": "Who. Speech radical plus 隹 (short-tailed bird) for sound. In some dialects pronounced 'shéi,' in others 'shuí.' Both are correct; don't let anyone tell you otherwise.",
    "什么": "The most all-purpose question word. 什 is ten (十) next to person (亻), 么 is a diminutive suffix. Together they've become so fused that you'll never encounter them separately in this sense.",
    "十": "A cross shape — one theory says it represents a needle (the original meaning) and the number was a borrowing. The number ten as a perfect cross is almost too clean to be accidental.",
    "时候": "Time, moment. 时 has the sun radical (日) — time measured by the sun. 什么时候 (when) is one of the first question phrases worth memorizing as a chunk.",
    "是": "The copula. Grammatically, it ONLY links nouns — 她是老师 (she is a teacher). For adjectives, you don't use 是: 她很漂亮, NOT 她是漂亮. This trips up English speakers for months.",
    "书": "Simplified from 書, which showed a hand holding a brush over a mouth (dictation). The simplified version barely hints at its origins. Measure word is 本 (copy/volume).",
    "水": "A central stream with splashes on either side — one of the more recognizable pictographs. As a radical (氵), it appears in an enormous number of characters: 河, 海, 洗, 汤, 酒.",
    "水果": "Water-fruit. The 水 suggests juiciness. A superordinate term — you'd specify 苹果, 西瓜, etc. in practice, but 水果 is what you say when you want 'some fruit, whatever's good.'",
    "睡觉": "Eye-droop plus perceive. 睡 has the eye radical (目) — eyes in the act of falling shut. 觉 also means 'feel' or 'sense' (as in 觉得), connecting sleep to a state of awareness (or loss of it).",
    "说": "Speech radical plus 兑 (exchange). Speaking is exchanging words. One of the most frequently used verbs — 说中文, 说话, 怎么说, 你说呢.",
    "四": "Enclosing strokes around 八-like internals. Homophone with 死 (death), making four deeply unlucky — buildings skip the 4th floor, phone numbers with four cost less, gifts should never come in sets of four.",
    "岁": "Year of age. Derived from the year-star (Jupiter's cycle). In Chinese age-reckoning, you're traditionally one 岁 at birth and gain a year at New Year, not your birthday — though Western-style counting is increasingly common.",
    "他": "Person radical plus 也 (also) for sound. The gendered 他/她/它 distinction is a modern invention (early 20th century, influenced by European languages) — in spoken Chinese, they're all pronounced 'tā.'",
    "她": "Woman radical plus 也. Created in the 1910s-1920s as Chinese intellectuals modernized the writing system. Before that, 他 covered everyone. In speech, the distinction is still invisible.",
    "太": "Big (大) with an extra dot — excessively big, too much. 太好了 (too good = great!) is positive; 太贵了 (too expensive) is not. The dot makes the difference between 'big' and 'too much.'",
    "天气": "Sky-breath. Weather is what the sky is exhaling. 气 (air, breath, energy) is one of the most philosophically loaded characters in Chinese — from weather to martial arts to traditional medicine.",
    "听": "Simplified from 聽, which was ear (耳) plus a complex of components meaning 'attend with virtue.' The simplified version (口 + 斤) is almost comically stripped down by comparison.",
    "同学": "Same-study — people who study together. Used as both 'classmate' and a general form of address among students. Teachers call students 同学们 the way a teacher might say 'class.'",
    "喂": "The phone greeting — answer the phone and your first word is 喂 (wèi, fourth tone). Also used to call someone's attention (wéi, second tone), roughly equivalent to 'hey.'",
    "我": "Originally depicted a weapon (a halberd-like instrument) — 'I' as the one who holds the weapon, the self that asserts. As a character, its strokes are deceptively hard to write well.",
    "我们": "我 plus the pluralizer 们. Only used with pronouns and a few human nouns (人们, 朋友们). You can't just slap 们 onto any noun — 猫们 sounds strange, unlike English '-s.'",
    "喜欢": "Joy-joy, more or less. 喜 by itself is the character you see doubled (囍) at Chinese weddings — double happiness. 喜欢 is the everyday 'like' for people, things, and activities.",
    "下": "Downward, below, next. Mirror of 上. 下课 (class dismissed), 下雨 (rain falls), 下个月 (next month). Chinese pairs these spatial terms (上/下, 前/后, 左/右) symmetrically throughout the language.",
    "下午": "Lower-noon — the afternoon. After 中午 (noon) and before 晚上 (evening). Chinese time-of-day words divide neatly and sequentially; the system is tidy.",
    "先生": "Born first — the elder, the teacher, the mister. 先生 once specifically meant 'teacher' (and still does in some contexts). Now it's the standard formal address for adult men: [Surname]先生.",
    "现在": "Appear-exist: what appears and exists right now. One of those words you use dozens of times a day without thinking about it. 现在几点 (what time is it now) is a survival phrase.",
    "小": "Three strokes suggesting something being divided into smaller pieces. Opposite of 大. 小 before a surname (小李, 小王) is a casual, friendly way to address someone younger or junior — common in workplaces.",
    "小姐": "Little-elder, which makes no sense literally. Historically a polite address for young women; in mainland China 小姐 can mean 'prostitute' depending on context and region, so 女士 (nǚshì) is the safer formal option. In Taiwan, 小姐 is still perfectly polite.",
    "些": "Some, a few. The character combines 此 (this) and 二 (two) — 'these two-ish,' a vague small quantity. 一些 (some) and 有些 (some, somewhat) are the most common combinations.",
    "写": "Simplified from 寫, which had a roof radical over components meaning 'pour out.' Writing as pouring out meaning under shelter. The simplified version barely hints at this.",
    "星期": "Star-period. The seven-day week wasn't traditional in China — it was adopted in the early 20th century. Days are numbered: 星期一 through 星期六, with Sunday as 星期天 or 星期日.",
    "学生": "Study-born, one who is born to learn. The relationship between 学生 and 老师 is fundamental in Chinese culture — the teacher-student bond carries Confucian weight that persists today.",
    "学习": "Study-practice. 学 has a child (子) under a roof being taught; 习 originally showed a bird practicing flying (羽, wings). 学 is the input; 习 is the repetition.",
    "学校": "Study-school. 校 has the wood radical (木), suggesting the wooden buildings of early schools. The compound is straightforward — a place for studying.",
    "一": "A single horizontal stroke — the most elemental character. Changes tone depending on what follows: yī in isolation, yí before fourth tone, yì before others. These tone changes are automatic for native speakers but maddening for learners.",
    "衣服": "Clothing. 衣 is a pictograph of a robe with collar and sleeves visible. As a radical (衤), it appears in 裤 (pants), 裙 (skirt), 被 (quilt). When you see 衤, think fabric.",
    "医院": "Medicine-courtyard. 医 was simplified from 醫, which contained a quiver of arrows (矢), a hand performing surgery (殳), and a wine vessel for anesthetic (酉). Ancient Chinese surgery was not for the faint-hearted.",
    "椅子": "Wood radical (木) — chairs were wooden. The character 奇 (strange, remarkable) provides the sound. Like 桌子, the 子 suffix nominalizes it.",
    "有": "Historically, a hand (又) holding meat (月, which here represents flesh, not moon) — to possess, to have. 有没有 (have or not have) is the yes/no question form. 没有 negates it; never 不有.",
    "月": "A crescent moon — one of the clearest pictographs. As a radical, 月 confusingly represents both 'moon/month' AND 'flesh/body' (the latter from a separate character 肉 that was simplified to look identical).",
    "再见": "Again-see. A farewell that's really a promise: we'll see each other again. More formal than 拜拜 (bye-bye, borrowed from English), which is what people actually say to friends.",
    "在": "At, in, or marks ongoing action (在 + verb = currently doing). 存在 means 'to exist.' The character shows earth (土) and a seedling — something planted, present, existing in a place.",
    "怎么": "How or why, depending on context. 怎么走 = how do I get there; 怎么了 = what happened / what's wrong. The ambiguity between 'how' and 'why' can be confusing, but context always clarifies.",
    "中国": "Middle Kingdom — the country at the center of civilization, from the Chinese perspective. Not arrogance so much as a geographic description that stuck: the central states among surrounding territories.",
    "中午": "Middle-noon. Noon itself. The midpoint of the day. 中 (middle) is one of the most structurally balanced characters — a line through the center of a rectangle.",
    "住": "Person radical (亻) plus 主 (master, host). A person who masters a place — to live there, to stay. 住在 + location is the pattern: 我住在北京.",
    "桌子": "Wood radical — desks and tables were wooden. The phonetic component 卓 (outstanding, tall) suggests a raised surface. Another 子-suffix noun in the furniture category.",
    "字": "A child (子) under a roof (宀) — a character born inside, i.e., writing created indoors. 汉字 (Chinese characters) is the formal term for the writing system itself.",
    "昨天": "Yesterday. 昨 has the sun radical (日) plus 乍 (suddenly) — the day that suddenly passed. Less poetic than 明天 (bright day = tomorrow) but still nicely constructed.",
    "坐": "Two people (人人) on earth (土) — originally depicted two people sitting on the ground facing each other. Also means 'travel by' (坐公交车 = take the bus), which is just 'sit in a vehicle.'",
    "做": "Person radical plus components suggesting creation. The general-purpose 'do' or 'make' — 做饭 (cook), 做工作 (do work), 做梦 (dream, literally 'make a dream').",

    # === HSK 2 (49 items) ===
    "介绍": "Between-carry-on: to bring something between people, i.e., introduce. 自我介绍 (self-introduction) is a near-daily occurrence in Chinese social and professional settings.",
    "号": "Mouth radical (口) with a component suggesting calling out — a number or designation shouted aloud. Used for dates (三号 = the 3rd) and sizes (大号 = large size). Very colloquial.",
    "说话": "Speak-words. Slightly different from standalone 说: 说话 is the general activity of speaking/talking, while 说 takes a direct object (说中文, 说谎 'lie'). Subtle but real distinction.",
    "五": "A cross-shape between two lines — allegedly representing the five elements (wood, fire, earth, metal, water) intersecting. Considered neutral to mildly positive numerologically.",
    "下雨": "Fall-rain. The rain 'descends' — Chinese weather verbs use directional complements. 下雪 (snow falls) uses the same structure. The sky drops things on you; you don't passively experience weather.",
    "想": "Heart/mind radical (心) at the bottom, with 相 (mutual, appearance) on top — what appears in your heart-mind. Covers 'think,' 'miss (someone),' and 'want to.' Context separates them.",
    "谢谢": "The doubled form for emphasis — a single 谢 exists but sounds clipped. 谢 contains 射 (shoot) and the speech radical, roughly 'words shot back in return.' A verbal volley of gratitude.",
    "一点儿": "One-dot-er. 'A little bit.' The 儿 is the northern/Beijing r-colored suffix. Southerners might say 一点 without it. Essential for softening requests: 能便宜一点儿吗 (could you make it a little cheaper?).",
    "医生": "Medicine-born, one born to medicine. Doctors in China are addressed as [Surname]医生 or sometimes [Surname]大夫 (dàifu). The prestige of medicine in Chinese culture is immense and longstanding.",
    "怎么样": "How-about-it. The go-to phrase for soliciting opinions: 这个怎么样? (how about this one?). Also used for 'how is/was it' — 北京怎么样? (how's Beijing?).",
    "这": "This/here. The demonstrative that, along with 那 (that), structures most of Chinese spatial reference. 这个, 这里, 这样 — you'll build dozens of phrases from it.",
    "吧": "The suggestion particle — softens a statement into a proposal or uncertain agreement. 走吧 (let's go), 好吧 (okay, fine). It takes the edge off commands and makes them collaborative.",
    "帮助": "Help. 帮 has the towel radical (巾), suggesting wrapping or binding together in support. More formal than just 帮, which works fine in casual speech: 帮我一下 (give me a hand).",
    "得": "Three distinct pronunciations, three functions. dé (obtain), de (complement marker), děi (must/have to). As the complement marker (跑得快 = run fast), it's grammatically crucial and initially baffling.",
    "懂": "Heart radical (忄) signaling a mental process. Means 'understand' in the deep, comprehension sense — not just hearing but grasping meaning. 听懂 (listen-and-understand) versus just 听 (hear).",
    "非常": "Not-ordinary, i.e., extraordinary — 'very' or 'extremely.' More emphatic than 很 but less dramatic than spoken delivery of 太...了. A safe intensifier for formal or written contexts.",
    "公交车": "Public-transport-vehicle. The full form of what locals often shorten to 公交. In first-tier cities the bus systems are vast and cheap — but navigating them without Chinese is an adventure.",
    "过": "Experiential aspect particle — marks that something has happened at least once before. 我去过中国 (I've been to China). Also means 'pass' or 'cross' literally: 过马路 (cross the road).",
    "黑": "The character has fire (灬) at the bottom with a structure suggesting soot and darkness above — what fire leaves behind. 黑 also means 'shady' or 'illegal' in slang: 黑车 (unlicensed taxi), 黑市 (black market).",
    "火车站": "Fire-vehicle-station. Trains were fire-vehicles (steam engines). The name stuck even after electrification. 站 means both 'station' and 'stand' — a place where you stand and wait.",
    "机场": "Machine-field. An airfield. 机 (machine) is the same character in 飞机 (airplane) and 手机 (phone). It's become the default morpheme for any sophisticated device.",
    "鸡蛋": "Chicken-egg. Chinese specifies the source animal: 鸡蛋 (chicken egg), 鸭蛋 (duck egg). Eggs are so central to Chinese cooking that 鸡蛋 is among the first food words you'll need.",
    "件": "Person radical plus 牛 (ox) — originally a portion of meat divided per person, hence 'piece, item.' Now the measure word for clothing, luggage, matters, and events. Versatile counter.",
    "教室": "Teach-room. 教 contains 孝 (filial piety) and a hand with a rod (攵) — teaching through discipline, the ancient way. The classroom is where this happens.",
    "姐姐": "Woman radical plus 且 for sound. Elder sister. Chinese kinship terms are extraordinarily specific — you can't just say 'sister' without indicating older or younger, paternal or maternal side.",
    "白": "A ray of light above a small shape — the sun beginning to appear, hence 'white' and 'bright.' Also means 'in vain' or 'free of charge': 白吃 (eat without paying), 白说 (say something for nothing).",
    "百": "One (一) over 白 (white/bright). A hundred is a bright milestone. Large round numbers have cultural weight: 百 (100), 千 (1000), 万 (10,000) each function as conceptual units.",
    "报纸": "Report-paper. 报 originally meant to repay or respond; its extension to 'report' news is logical. Physical newspapers are declining in China even faster than elsewhere, replaced by WeChat feeds.",
    "比": "Two people standing side by side for comparison — the character literally looks like two figures next to each other. 比 is the core comparison word: A 比 B [adjective]. No 'than' needed; the structure does the work.",
    "别": "Don't — the negative imperative. 别走 (don't go), 别说 (don't say). More conversational than 不要, which sounds more like a stern parent or a sign on a wall.",
    "长": "Two pronunciations: cháng (long in space or time) and zhǎng (grow, chief). The character depicts flowing hair — long and growing. 长城 (Great Wall) uses the 'long' reading.",
    "唱歌": "Sing-song. 唱 has the mouth radical (口) doubled with a phonetic component — two mouths making music. Karaoke (KTV) is a genuine social institution in China, not just a drunken afterthought.",
    "出": "A foot stepping out of an enclosure — exit, go out. Two mountain-like bumps pushing outward. Pairs with 进 (enter) as a directional opposite. 出去 = go out, 出来 = come out.",
    "穿": "Cave/hole radical (穴) on top with a tooth (牙) below — pushing through a gap, like putting on clothes. 穿 covers both 'wear' (穿衣服) and 'pass through' (穿过).",
    "次": "Ice radical (冫) plus 欠 (owe, lack). The measure word for number of times or occurrences. 一次 (once), 下次 (next time), 每次 (every time). Also means 'secondary' or 'inferior' in compounds.",
    "从": "Two people (人人) walking together, one following another — 'from' or 'since.' The traditional form 從 adds a foot component, making the following-walking imagery even clearer.",
    "错": "Metal radical (钅) plus 昔 (past). Wrong, mistaken. Originally related to grinding or interlocking metal — something that doesn't fit together properly. 不错 (not bad) is high Chinese praise.",
    "打篮球": "Hit-basket-ball. 打 again in its athletic sense — 打 plus a sport is the general pattern for ball games played with hands (打篮球, 打网球). Foot sports use 踢.",
    "大家": "Big-family, everyone. Used to address a group: 大家好 (hello everyone). Common in speeches, meetings, and any situation where you're talking to more than three people.",
    "到": "Arrive, reach. Knife radical (刂) on the right — cutting through to reach a destination. 到 is also a result complement meaning 'succeed in reaching': 找到 (found it), 看到 (spotted it).",
    "等": "Bamboo radical (⺮) over 寺 (temple). Waiting at the bamboo temple — the image of patience. 等一下 (wait a moment) and 等等 (and so on, et cetera) are both daily use.",
    "弟弟": "Younger brother. The character 弟 shows a spool of thread wound in order — the sequence of siblings. Chinese kinship precision means 弟弟 is always younger; 哥哥 is always older.",
    "第一": "Ordinal marker plus one — 'first.' 第 (bamboo radical plus 弟) creates ordinals: 第二 (second), 第三 (third). Without 第, numbers are just cardinal (一, 二, 三).",
    "对": "Right, correct, toward. The left side (又, hand) faces the right (寸, inch/measure) — a hand measuring accurately. 对不起 uses 对 in the 'face' sense; 对 as 'correct' is its own common usage.",
    "房间": "Room. 房 (house, building) plus 间 (between, space). 间 has a sun (日) or moon (月) visible through a gate (门) — light between doors. A room is a space between walls.",
    "服务员": "Service-person. The standard address for waitstaff, shop attendants, and service workers. Calling out 服务员！ in a restaurant is normal and expected, not rude — though tone of voice matters.",
    "高": "A tall building with a pointed roof — the character is architecturally suggestive. Means both physically tall and metaphorically high (高级 = high-level, 高兴 = high-spirited). The opposite is 矮 (short).",
    "告诉": "Tell, inform. 告 originally showed an ox (牛) above a mouth (口) — an ox bellowing, a loud announcement. Less gentle than 'tell' implies; more like delivering information directly.",
    "哥哥": "Elder brother. 哥 is 可 (possible) doubled and stacked — phonetic, not semantic. In Chinese social dynamics, 哥 is also used for close male friends slightly older than you, not just blood relatives.",
    "给": "Thread radical (纟) plus 合 (join) — threads woven together as a gift. Means 'give,' but also functions as a marker meaning 'for' or 'to': 给你买 (buy for you). Extremely high frequency.",
    "公司": "Public-manage. A company or firm. 公 (public, official) appears in many institutional words: 公园 (park), 公安 (public security), 公交 (public transport).",
    "狗": "Dog radical (犭) plus 句 for sound. Dogs have a complicated status in Chinese culture — pets in cities now, but historically more working animals than companions. 狗 features in many colorful insults.",
    "贵": "Shell radical (贝, ancient money) under a structure suggesting stored value — expensive. 贵 also means 'noble' or 'honored': 贵姓 (your honorable surname) is a polite way to ask someone's name.",
    "还": "Still, yet, additionally. Also pronounced huán (return, give back). The 'still' function is constant in conversation: 还好 (okay, not bad), 还有 (there's also), 还是 (or, still is).",
    "孩子": "Child. 孩 has the child radical (子) plus 亥 for sound. 孩子 is the most neutral, common word for 'child/children.' Unlike 儿子 and 女儿, it doesn't specify gender.",
    "好吃": "Good-eat — delicious. The result complement structure: adjective describes how the eating turns out. Similarly: 好看 (good-looking), 好听 (good-sounding), 好喝 (good to drink). Productive pattern.",
    "红": "Thread/silk radical (纟) plus 工 (work). Red is China's color — luck, celebration, weddings, the flag, cash-gift envelopes (红包). Wearing white to a wedding would be like wearing black; red is the only right choice.",
    "欢迎": "Joyfully-welcome. 欢 is joy, 迎 is to meet or greet. 欢迎光临 (welcome, honor us with your presence) is what every shop plays on a motion-sensor loop as you walk in.",
    "回答": "Return-answer. 回 (return) plus 答 (reply, answer). To answer is to return speech to the questioner. More formal than just 答, used in classrooms and interviews.",

    # === HSK 3 (100 items) ===
    "进": "The walking radical (辶) carrying 井 (well) — advancing toward the well, entering. Opposite of 出 (exit). 进来 (come in), 进去 (go in). Directional complements are everywhere.",
    "近": "Walking radical (辶) plus 斤 (axe/catty). Close, near. Paired with 远 (far) as a fundamental spatial opposition. 近 often appears in 最近 (recently, nearest), one of the most useful time expressions.",
    "就": "Right away, immediately, precisely, then — one of those small words that carries enormous grammatical and emotional nuance. 就 can express immediacy, concession, emphasis, or logical consequence depending on position.",
    "觉得": "Feel, think (subjective opinion). 觉 is the same character from 睡觉 (sleep) — awareness in both waking thought and its absence. 我觉得 is 'I feel that' or 'in my opinion,' softer than 我认为.",
    "咖啡": "Purely phonetic transliteration of 'coffee' — both characters exist only for their sound value here. China's coffee culture has exploded in the last decade; Luckin Coffee outnumbers Starbucks in many cities.",
    "开始": "Open-begin. 始 has the woman radical (女) — the ancient association of women with origins and beginnings. 开始 is the standard 'start' for activities, events, and processes.",
    "考试": "Test-try. 考 originally meant 'old' or 'examine the elderly' (checking on aged parents). The examination sense took over completely. China's exam culture runs deep — from imperial 科举 to today's 高考.",
    "可能": "Can-able. Maybe, possibly. More tentative than 会 (will), less committal than 一定 (definitely). 可能 is the Chinese 'might' — useful for hedging when you're not sure, which is often.",
    "可以": "Can, may — permission or possibility. Distinguished from 能 (physical ability) and 会 (learned skill), though in practice the boundaries blur. 可以 is the politest way to ask permission.",
    "课": "Speech radical (讠) plus 果 (fruit). A lesson as the fruit of discourse. 上课 (attend class), 下课 (end class). 课本 (textbook) is the fruit-of-discourse book.",
    "快": "Heart radical (忄) plus 夬 — originally about the heart being decisive, which became 'quick.' 快 covers both speed (开快车 = drive fast) and time proximity (快到了 = almost there). Also: 快乐 (happy, literally quick-joy).",
    "快乐": "Quick-joy. Happiness as joy that comes fast and feels light. Used for greetings: 生日快乐 (happy birthday), 新年快乐 (happy new year). More celebratory than the daily-use 高兴.",
    "累": "Field (田) over silk threads (糸) with additional strokes — the exhaustion of working the fields and weaving. Pronounced lèi for 'tired' and lěi for 'accumulate.' Same character, different lives.",
    "离": "Away from. Measures distance between two points: 学校离我家很近 (school is close to my home). The grammar is location A 离 location B + distance/description. The structure is clean once you internalize it.",
    "两": "Two, but specifically used with measure words: 两个人 (two people), not 二个人. Also means 'a couple of' in a casual sense. 二 is for math and sequences; 两 is for counting things you can hold.",
    "路": "Foot radical (足) plus 各 (each). Each foot on a road. 路 means road but also bus route: 55路 is bus route 55. Asking directions inevitably involves 路 — 请问这条路怎么走?",
    "旅游": "Travel for leisure. 旅 has a flag radical suggesting group movement (a traveling party under a banner). Distinct from 旅行 (trip/journey, more general): 旅游 specifically implies tourism and sightseeing.",
    "卖": "Simplified from 賣, which had a net on top and shells (money) below — putting goods out to be caught by buyers. The buyer (买) removes the top component — buying doesn't require display.",
    "慢": "Heart radical (忄) suggesting a mental state, plus 曼 for sound. Slow. The opposite of 快. 慢慢 (slowly, little by little) is reduplicated for emphasis: 慢慢来 (take your time) is deeply practical Chinese advice.",
    "忙": "Heart radical (忄) plus 亡 (death, loss). A heart so overwhelmed it's dying — busy. 很忙 is the default excuse in China, accepted as both genuinely sympathetic and socially face-saving.",
    "猫": "Dog radical (犭) — wait, yes, the CAT character uses the dog radical. The radical means 'animal' more broadly, but it's still funny. 猫 uses 苗 (seedling, sprout) for sound.",
    "每": "Every, each. Contains 母 (mother) — possibly because mothers attend to every child. 每天 (every day), 每次 (every time), 每个人 (everyone). Requires a measure word before the noun: 每个, not 每人 (usually).",
    "妹妹": "Younger sister. 妹 is woman radical (女) plus 未 (not yet) — the one who has 'not yet' reached the elder sister's status. The character literally encodes birth order.",
    "门": "A pictograph of a double-door — the simplified version straightened the traditional 門, which you can still see as two door panels. As a radical, 门 appears in 间, 问, 闪, 闭.",
    "男": "Field (田) on top, strength (力) below — the one who labors in the field. Gender roles baked into ancient characters. The female counterpart 女 shows a kneeling figure. Bronze Age sociology, preserved in ink.",
    "您": "你 (you) with 心 (heart) at the bottom — 'you, with heart,' the respectful form. Used for elders, strangers you want to show deference to, and customer service interactions. Not used for friends.",
    "牛奶": "Cow-milk. Straightforward compound. Dairy was historically not central to Chinese cuisine — lactose intolerance rates are high in East Asia. The modern dairy industry in China is relatively recent and rapidly growing.",
    "女": "A kneeling figure with crossed arms — one of the oldest characters, dating to oracle bones. As a radical (女), it appears in 妈, 姐, 妹, 好, 她. Its presence doesn't always relate to women (如, 奴, 妨).",
    "旁边": "Side, nearby. 旁 has a top component suggesting direction and 方 (direction/place) — beside a place. 旁边 is the go-to word for 'next to': 银行在学校旁边.",
    "跑步": "Run-steps. 跑 has the foot radical (足) — running with your feet, as one does. The compound is specifically jogging/running as exercise; for running in general (fleeing, hurrying), just 跑 suffices.",
    "便宜": "Convenient-suitable — cheap, inexpensive. The word literally suggests something conveniently priced. 便宜 is also the basis of 占便宜 (take advantage of someone), suggesting that cheapness and opportunism are linked concepts.",
    "票": "Ticket. 票 has 示 (show/display) at the bottom with 西-like components on top — something shown or presented. Covers all tickets: 电影票 (movie ticket), 飞机票 (plane ticket), 门票 (entry ticket).",
    "妻子": "Wife. 妻 shows a hand grabbing a woman's hair — the character literally depicts the ancient practice of marriage by capture. One of the more uncomfortable etymologies in the writing system.",
    "起床": "Rise-bed. Getting up from bed. 起 has the walking radical (走) plus 己 (self) — setting yourself in motion. The bed (床) has the wood radical (广 suggests a shelter) because beds were wooden frames.",
    "千": "Thousand. A person (人) with a horizontal line — a single individual standing for a vast number. 千万 (ten million, but also 'by all means / absolutely must') doubles the emphasis.",
    "铅笔": "Lead-brush. A pencil — literally a lead (铅) writing implement (笔). 笔 has the bamboo radical (⺮) on top because brushes were made of bamboo. Even for a modern pencil, the brush character persists.",
    "晴": "Sun radical (日) plus 青 (blue/green). A clear, sunny day — the sun out in a blue sky. Pairs with 阴 (cloudy/overcast) as the basic weather binary.",
    "去年": "Go-year, the year that went away. Last year. Chinese time words often use spatial metaphors: 去 (go) for the past, 来 (come) for the future. Next year is 明年 (bright year), not 来年 in daily speech.",
    "让": "Speech radical (讠) plus a phonetic component. Let, allow, make. Also means 'yield' (让座 = give up your seat). 让 as a causative ('make someone do something') is structurally important: 他让我去.",
    "日": "A rectangle with a line through it — the sun with a mark inside (originally circular in oracle bones). As a radical it relates to time and daylight. More formal than 天 for 'day': used on calendars and in dates.",
    "上班": "Go-up-to-shift. Go to work. 班 originally meant a jade-cutting session (dividing jade, 班 has two jade radicals 玨 split by a knife 刀). A work shift as a divided portion of time.",
    "身体": "Body. 身 is a pictograph of a pregnant woman's body in profile — body at its most undeniably physical. 身体好 (good health) is one of the most common well-wishes.",
    "生病": "Birth-sickness — to fall ill. 病 has the sickness radical (疒), which represents a person on a bed sweating. Any character with 疒 relates to illness: 疼, 痛, 瘦, 症.",
    "生日": "Birth-day. Birthday. Chinese traditionally celebrated the lunar birthday, not the solar one. Many people now track both. The big birthdays are different too — first month, first year, then decade milestones.",
    "时间": "Time-between. Time as the space between moments. More abstract than 时候 (which implies a specific moment or period). 没有时间 (don't have time) is the universal modern condition.",
    "事情": "Matter, affair. 事 alone works but 事情 is the two-syllable standard. Chinese strongly prefers two-syllable words in speech — monosyllabic words often sound clipped or ambiguous.",
    "手表": "Hand-watch. A wristwatch — the watch on your hand. 表 (surface, display) is the outward-facing part. Despite smartphones, 手表 persists as a status symbol in Chinese business culture.",
    "手机": "Hand-machine. A mobile phone. The compound didn't exist before the 1990s; now it's one of the most uttered words in Chinese daily life. China's mobile-first culture means 手机 is essentially an extension of the self.",
    "送": "Walking radical (辶) plus 关 — to send off, escort, deliver, or give as a gift. 送礼 (give a gift) is a social art form in China with rules about what to give, how much, and when.",
    "虽然……但是……": "Although...but — Chinese requires BOTH halves, unlike English which drops 'but' after 'although.' This paired-conjunction structure (虽然 A, 但是 B) is non-negotiable grammar.",
    "它": "The pronoun for animals and things. Created alongside 她 in the early 20th century to distinguish he/she/it in writing. All three — 他, 她, 它 — are pronounced identically: tā.",
    "踢足球": "Kick-foot-ball. Play soccer. 踢 has the foot radical (足) — kicking with the foot, naturally. Soccer verbs use 踢; hand-ball sports use 打. The verb tells you which body part is involved.",
    "题": "Page radical (页) plus 是 (to be). A topic, question, or problem displayed on a page. 问题 (question/problem) is the compound you'll use far more often than standalone 题.",
    "跳舞": "Jump-dance. 跳 has the foot radical — dancing is organized jumping. 舞 is one of the more beautiful characters to write, with its symmetrical structure suggesting a person with outstretched arms.",
    "外": "Evening (夕) with a divination mark (卜) — performing divination at night, outside the home. Extended to 'outer, outside, foreign': 外国 (foreign country), 外面 (outside).",
    "完": "Roof (宀) over 元 (origin, primary) — the fundamental thing under the roof is complete. Means 'finish' or 'be used up.' As a result complement: 吃完 (finished eating), 看完 (finished reading).",
    "玩": "Jade radical (王) plus 元 (origin). Originally meant to handle jade — to play with a precious object. Extended to 'play' and 'have fun' generally. 好玩 (fun) is literally 'good to play with.'",
    "晚上": "Late-upper, evening. 晚 has the sun radical (日) with 免 — the sun being excused from duty, setting. Chinese evening socializing tends to start later than Western norms; 9 PM dinner is unremarkable.",
    "为什么": "For-what-reason. Why. Literally 'for what.' 因为 (because) is its natural partner — 为什么...因为... is the question-answer pair burned into every student's brain.",
    "问": "Mouth (口) inside a door (门) — a mouth at the door asking questions. One of the most satisfying character compositions: you can see someone standing at a doorway, mouth open, inquiring.",
    "问题": "Ask-topic. A question or problem. Covers both meanings and context distinguishes them: 有问题吗 can be 'any questions?' or 'is there a problem?' depending on the situation.",
    "西瓜": "West-melon. Watermelon came to China from the west (Central Asia, via the Silk Road). Summer in China without 西瓜 is unthinkable — it's sold on every street corner, often pre-cut.",
    "希望": "Rare-gaze. Hope is gazing at something rare — wanting what's not easily seen or obtained. Usable as both noun and verb: 我希望 (I hope), 有希望 (there's hope).",
    "洗": "Water radical (氵) plus 先 (first) for sound. Wash. 洗澡 (bathe), 洗衣服 (wash clothes), 洗手 (wash hands). The water radical does exactly what you'd expect here.",
    "小时": "Small-time. An hour. This replaced the traditional 时辰 (shíchen), which was a two-hour period in the old 12-division system. 小时 is literally 'small shi' — half of the old time unit.",
    "笑": "Bamboo radical (⺮) over 夭 (young, tender). The connection may be the swaying of young bamboo in wind — or the bright, bending quality of laughter. 笑 covers both laughing and smiling; Chinese doesn't lexically distinguish them.",
    "新": "Standing tree (木) being cut by an axe (斤) on the right — freshly cut wood is new. 新年 (New Year), 新的 (new), 新闻 (news, literally 'new things heard').",
    "姓": "Woman radical (女) plus 生 (born) — the name you're born with through your mother's line. In ancient China, surnames were matrilineal. 您贵姓 (what is your honorable surname) is the formal way to ask.",
    "休息": "Person (亻) leaning against a tree (木) — resting in the shade. One of the most visually lovely character compositions. 休 alone means rest; 息 (breath, cease) reinforces it.",
    "雪": "Rain radical (雨) over a hand sweeping (彐) — frozen rain you can brush away. 下雪 (snow falls) follows the same pattern as 下雨 (rain falls). Beijing winters involve both.",
    "颜色": "Face-color. Color. 颜 originally referred to the space between eyebrows — the face's expression and complexion. Extended to color in general. 什么颜色 (what color) is the question form.",
    "眼睛": "Eye-eye, essentially. 眼 and 睛 both contain the eye radical (目). 睛 specifically means the pupil or eyeball; together they mean 'eyes' as a unit. Chinese anatomical terms often double up this way for two-syllable flow.",
    "羊肉": "Sheep-meat. Mutton or lamb. 羊 is a frontal view of a sheep's horned head — one of the most direct pictographs. 羊肉串 (lamb skewers) from Xinjiang is some of the best street food in China.",
    "药": "Grass radical (艹) over 乐 (joy/music) — the plants that bring relief and joy. Traditional Chinese medicine (中药) remains widely used alongside Western medicine (西药). Pharmacies sell both.",
    "要": "West (西) over woman (女) — the original meaning was 'waist,' later borrowed for 'want, need, will.' 要 is high frequency and multifunctional: desire (我要), necessity (要注意), and future (要下雨了).",
    "也": "Also, too. Placed BEFORE the verb: 我也喜欢 (I also like). One of the simplest and most frequently used adverbs. Its calligraphic form is graceful — a single flowing stroke with a hook.",
    "一下": "One-down. 'Once' or 'briefly' — attached after verbs to soften the action: 看一下 (take a look), 等一下 (wait a sec). Makes requests less demanding and actions feel casual.",
    "一起": "One-rise. Together. 一起去 (go together), 一起吃 (eat together). Socializing in Chinese culture tends toward group activities; 一起 is the word that makes solo plans communal.",
    "已经": "Already. Marks completed states: 已经到了 (already arrived), 已经知道了 (already know). The double 已 and 经 both individually suggest 'passed' or 'completed' — the compound is emphatic.",
    "意思": "Intention-thought. Meaning. But also 'interesting' (有意思), 'embarrassing' (不好意思), and 'small token/gift' (小意思). One of those words that shapeshifts depending on context — learn the compounds, not just the base meaning.",
    "因为……所以……": "Because...therefore — another paired conjunction where Chinese expects both halves stated. English says 'because A, B' dropping 'therefore'; Chinese demands the full 因为 A, 所以 B structure.",
    "阴": "The hill radical (阝) plus 月 (moon) — the shaded side of a hill, where the moon lives. Overcast, cloudy. The 阴/阳 (yin/yang) opposition originates from shaded versus sunny hillsides, not cosmic abstraction.",
    "游泳": "Travel-in-water plus swim. 游 has the water radical; 泳 also has the water radical. Double water emphasis — you are very much in the water. 游泳池 (swimming pool) adds 'pond' for good measure.",
    "右边": "Right-side. 右 shows a hand (又) below a mouth (口) — the eating hand, the right hand for most people. 左 (left) mirrors it with a different hand component. Together, 左边/右边 cover your directions.",
    "鱼": "A pictograph of a fish — head on top, body in the middle, tail at the bottom. The traditional form 魚 is even more clearly fish-shaped. Fish (especially carp) symbolizes abundance because 鱼 sounds like 余 (surplus).",
    "远": "Walking radical (辶) plus 元 (origin). Far. The yuan you travel from your origin. 远 and 近 (near) are the distance pair: 很远 (very far), 不远 (not far).",
    "运动": "Transport-move. Exercise, sports, or political movement — the same word covers a jog in the park and a historical revolution. Context is everything. 运动会 is a sports meet; 运动 by itself usually means exercise.",
    "再": "Again, more, then (for future actions). Distinguished from 又 (again, for past actions): 再见 (see you again, future) versus 又来了 (here again, it happened). The past/future split between 又 and 再 is a pattern worth internalizing.",
    "早上": "Early-upper. Morning, specifically the early part. 早 is the sun (日) rising above a horizon line — the earliest sunlight. 早上好 (good morning) is the standard morning greeting.",
    "丈夫": "Ten-feet-man — a man of full stature. Husband. Slightly more colloquial than 先生 (which can also mean husband). In modern urban usage, 老公 (old duke) is increasingly common as a casual, affectionate 'hubby.'",
    "找": "Hand radical (扌) plus 戈 (weapon/dagger-axe) — searching with a weapon in hand, sweeping an area. Means 'seek, look for' and also 'give change' (找钱). The two meanings seem unrelated but both involve retrieving something.",
    "着": "The continuous aspect particle — marks ongoing states. 穿着红衣服 (wearing red clothes), 开着门 (the door is open). Pronounced zhe as a particle, zháo as 'touch/reach,' zhuó as 'wear.' Three readings, one character.",
    "真": "Straight (直) on top with a base — originally a person standing upright, truthful. Really, indeed, truly. 真的吗 (really?) is probably the most common reaction in conversation.",
    "正在": "Right-now-at. In the process of — marks an action happening at this exact moment. 我正在吃饭 (I'm eating right now). More emphatic than 在 alone, which also marks ongoing actions.",
    "知道": "Know-way. To know or be aware of. 知 has an arrow (矢) and a mouth (口) — knowledge shot straight from speech. 知道 is knowing facts; 认识 is knowing people. The distinction matters.",
    "准备": "Standard-prepare. Get ready, prepare, plan to. 准备好了吗 (are you ready?) precedes everything from meals to meetings. The 准 (standard, accurate) suggests preparation as bringing things to proper condition.",
    "自行车": "Self-moving-vehicle. A bicycle. The name dates from when a human-powered vehicle that moved by itself (without horses) was remarkable. China was once called the Kingdom of Bicycles; the 自行车 is making a comeback via sharing apps.",
    "走": "Originally a running figure — the top is a person swinging their arms, the bottom is a foot. Means 'walk' in modern use (the running meaning shifted to 跑). 走吧 (let's go) is how you get any group moving.",
    "最": "Sun (日) plus 取 (take) under a roof — taking the utmost. The superlative marker: 最好 (best), 最大 (biggest), 最近 (nearest/most recently). One character turns any adjective into its extreme.",
    "左边": "Left-side. 左 shows a left hand (工) below a covering — the hand that holds the ruler or tool while the right hand works. Chinese driving is on the right side; the 左边 is the passenger side.",
}
