"""Extra HSK 1-3 grammar points to supplement grammar_seed.py."""

EXTRA_GRAMMAR_HSK1_3 = [
    # =========================================================================
    # HSK 1 — 18 new grammar points
    # =========================================================================

    {"name": "有 have/exist", "name_zh": "有", "hsk_level": 1, "category": "structure",
     "description": "Expressing possession or existence: 我有一本书、桌子上有一杯水", "difficulty": 0.2,
     "examples": [
         {"zh": "我有一本书。", "pinyin": "Wǒ yǒu yì běn shū.", "en": "I have a book."},
         {"zh": "桌子上有一杯水。", "pinyin": "Zhuōzi shàng yǒu yì bēi shuǐ.", "en": "There is a glass of water on the table."},
         {"zh": "你有没有时间？", "pinyin": "Nǐ yǒu méiyǒu shíjiān?", "en": "Do you have time?"},
     ]},
    {"name": "也 also", "name_zh": "也", "hsk_level": 1, "category": "particle",
     "description": "Adverb meaning 'also/too', placed before the verb: 我也是学生", "difficulty": 0.1,
     "examples": [
         {"zh": "我也是学生。", "pinyin": "Wǒ yě shì xuéshēng.", "en": "I am also a student."},
         {"zh": "她也喜欢吃中国菜。", "pinyin": "Tā yě xǐhuan chī Zhōngguó cài.", "en": "She also likes Chinese food."},
         {"zh": "我也不知道。", "pinyin": "Wǒ yě bù zhīdào.", "en": "I don't know either."},
     ]},
    {"name": "都 all/both", "name_zh": "都", "hsk_level": 1, "category": "particle",
     "description": "Adverb meaning 'all/both', placed before the verb: 我们都喜欢", "difficulty": 0.2,
     "examples": [
         {"zh": "我们都喜欢吃水果。", "pinyin": "Wǒmen dōu xǐhuan chī shuǐguǒ.", "en": "We all like eating fruit."},
         {"zh": "他们都是中国人。", "pinyin": "Tāmen dōu shì Zhōngguó rén.", "en": "They are all Chinese."},
         {"zh": "这些书我都看过了。", "pinyin": "Zhèxiē shū wǒ dōu kànguo le.", "en": "I have read all of these books."},
     ]},
    {"name": "Question words 谁/什么/哪/哪儿", "name_zh": "疑问代词", "hsk_level": 1, "category": "structure",
     "description": "Question words stay in the position of the answer: 你是谁？你去哪儿？", "difficulty": 0.2,
     "examples": [
         {"zh": "你是谁？", "pinyin": "Nǐ shì shéi?", "en": "Who are you?"},
         {"zh": "你去哪儿？", "pinyin": "Nǐ qù nǎr?", "en": "Where are you going?"},
         {"zh": "这是什么？", "pinyin": "Zhè shì shénme?", "en": "What is this?"},
     ]},
    {"name": "几/多少 how many", "name_zh": "几/多少", "hsk_level": 1, "category": "structure",
     "description": "几 for small numbers (with measure word), 多少 for larger/unknown quantities: 你有几个孩子？多少钱？", "difficulty": 0.2,
     "examples": [
         {"zh": "你有几个孩子？", "pinyin": "Nǐ yǒu jǐ gè háizi?", "en": "How many children do you have?"},
         {"zh": "这个多少钱？", "pinyin": "Zhège duōshao qián?", "en": "How much is this?"},
         {"zh": "你们班有多少学生？", "pinyin": "Nǐmen bān yǒu duōshao xuéshēng?", "en": "How many students are in your class?"},
     ]},
    {"name": "会 can/will", "name_zh": "会", "hsk_level": 1, "category": "structure",
     "description": "Learned ability or future likelihood: 我会说中文、明天会下雨", "difficulty": 0.2,
     "examples": [
         {"zh": "我会说中文。", "pinyin": "Wǒ huì shuō Zhōngwén.", "en": "I can speak Chinese."},
         {"zh": "明天会下雨。", "pinyin": "Míngtiān huì xiàyǔ.", "en": "It will rain tomorrow."},
         {"zh": "你会不会游泳？", "pinyin": "Nǐ huì bu huì yóuyǒng?", "en": "Can you swim?"},
     ]},
    {"name": "太...了 too...", "name_zh": "太…了", "hsk_level": 1, "category": "structure",
     "description": "Expressing excess or strong degree: 太贵了、太好了", "difficulty": 0.2,
     "examples": [
         {"zh": "这个太贵了。", "pinyin": "Zhège tài guì le.", "en": "This is too expensive."},
         {"zh": "太好了！", "pinyin": "Tài hǎo le!", "en": "Great! / That's wonderful!"},
         {"zh": "今天太热了。", "pinyin": "Jīntiān tài rè le.", "en": "It's too hot today."},
     ]},
    {"name": "这/那 demonstratives", "name_zh": "这/那", "hsk_level": 1, "category": "structure",
     "description": "Demonstrative pronouns 'this/that' used with measure words: 这个人、那本书", "difficulty": 0.1,
     "examples": [
         {"zh": "这个人是我的朋友。", "pinyin": "Zhège rén shì wǒ de péngyou.", "en": "This person is my friend."},
         {"zh": "那本书很有意思。", "pinyin": "Nà běn shū hěn yǒu yìsi.", "en": "That book is very interesting."},
         {"zh": "这是什么？那是什么？", "pinyin": "Zhè shì shénme? Nà shì shénme?", "en": "What is this? What is that?"},
     ]},
    {"name": "和 and", "name_zh": "和", "hsk_level": 1, "category": "connector",
     "description": "Connecting nouns or noun phrases: 我和他、苹果和香蕉", "difficulty": 0.1,
     "examples": [
         {"zh": "我和他是好朋友。", "pinyin": "Wǒ hé tā shì hǎo péngyou.", "en": "He and I are good friends."},
         {"zh": "我喜欢苹果和香蕉。", "pinyin": "Wǒ xǐhuan píngguǒ hé xiāngjiāo.", "en": "I like apples and bananas."},
         {"zh": "爸爸和妈妈都在家。", "pinyin": "Bàba hé māma dōu zài jiā.", "en": "Dad and Mom are both at home."},
     ]},
    {"name": "还是 or (choice question)", "name_zh": "还是", "hsk_level": 1, "category": "structure",
     "description": "Offering a choice between options in a question: 你喝茶还是咖啡？", "difficulty": 0.2,
     "examples": [
         {"zh": "你喝茶还是咖啡？", "pinyin": "Nǐ hē chá háishi kāfēi?", "en": "Do you drink tea or coffee?"},
         {"zh": "你坐公交车还是地铁？", "pinyin": "Nǐ zuò gōngjiāochē háishi dìtiě?", "en": "Do you take the bus or the subway?"},
         {"zh": "我们吃中餐还是西餐？", "pinyin": "Wǒmen chī zhōngcān háishi xīcān?", "en": "Shall we eat Chinese food or Western food?"},
     ]},
    {"name": "去/来+V purpose", "name_zh": "去/来+动词", "hsk_level": 1, "category": "structure",
     "description": "Using 去 or 来 before a verb to express purpose of going/coming: 我去买东西", "difficulty": 0.2,
     "examples": [
         {"zh": "我去买东西。", "pinyin": "Wǒ qù mǎi dōngxi.", "en": "I'm going to buy things."},
         {"zh": "你来吃饭吧。", "pinyin": "Nǐ lái chīfàn ba.", "en": "Come eat."},
         {"zh": "她去学校上课了。", "pinyin": "Tā qù xuéxiào shàngkè le.", "en": "She went to school to attend class."},
     ]},
    {"name": "Verb reduplication 看看", "name_zh": "动词重叠", "hsk_level": 1, "category": "structure",
     "description": "Repeating a verb to soften the action or suggest 'a little bit': 看看、试试", "difficulty": 0.3,
     "examples": [
         {"zh": "我看看。", "pinyin": "Wǒ kànkan.", "en": "Let me have a look."},
         {"zh": "你试试这个菜。", "pinyin": "Nǐ shìshi zhège cài.", "en": "Try this dish."},
         {"zh": "请等等我。", "pinyin": "Qǐng děngdeng wǒ.", "en": "Please wait for me a moment."},
     ]},
    {"name": "吧 suggestion", "name_zh": "吧", "hsk_level": 1, "category": "particle",
     "description": "Sentence-final particle for suggestions, agreement, or softening: 我们走吧", "difficulty": 0.2,
     "examples": [
         {"zh": "我们走吧。", "pinyin": "Wǒmen zǒu ba.", "en": "Let's go."},
         {"zh": "吃饭吧。", "pinyin": "Chīfàn ba.", "en": "Let's eat."},
         {"zh": "你先休息吧。", "pinyin": "Nǐ xiān xiūxi ba.", "en": "You should rest first."},
     ]},
    {"name": "喜欢+V like doing", "name_zh": "喜欢+动词", "hsk_level": 1, "category": "structure",
     "description": "Using 喜欢 followed by a verb to express liking an activity: 我喜欢游泳", "difficulty": 0.1,
     "examples": [
         {"zh": "我喜欢游泳。", "pinyin": "Wǒ xǐhuan yóuyǒng.", "en": "I like swimming."},
         {"zh": "她喜欢看电影。", "pinyin": "Tā xǐhuan kàn diànyǐng.", "en": "She likes watching movies."},
         {"zh": "他不喜欢跑步。", "pinyin": "Tā bù xǐhuan pǎobù.", "en": "He doesn't like running."},
     ]},
    {"name": "多+adj how (degree question)", "name_zh": "多+形容词", "hsk_level": 1, "category": "structure",
     "description": "Asking about the degree of an adjective: 你多大？多高？", "difficulty": 0.2,
     "examples": [
         {"zh": "你多大了？", "pinyin": "Nǐ duō dà le?", "en": "How old are you?"},
         {"zh": "你多高？", "pinyin": "Nǐ duō gāo?", "en": "How tall are you?"},
         {"zh": "从这儿到学校多远？", "pinyin": "Cóng zhèr dào xuéxiào duō yuǎn?", "en": "How far is it from here to school?"},
     ]},
    {"name": "Time word placement", "name_zh": "时间词语序", "hsk_level": 1, "category": "structure",
     "description": "Time words come before or after the subject, before the verb: 我明天去、他昨天来了", "difficulty": 0.2,
     "examples": [
         {"zh": "我明天去北京。", "pinyin": "Wǒ míngtiān qù Běijīng.", "en": "I'm going to Beijing tomorrow."},
         {"zh": "他昨天来了。", "pinyin": "Tā zuótiān lái le.", "en": "He came yesterday."},
         {"zh": "今天下午我们去看电影。", "pinyin": "Jīntiān xiàwǔ wǒmen qù kàn diànyǐng.", "en": "This afternoon we're going to see a movie."},
     ]},
    {"name": "还 still/in addition", "name_zh": "还", "hsk_level": 1, "category": "particle",
     "description": "Adverb meaning 'still' or 'in addition': 他还在吃饭、我还要一杯", "difficulty": 0.2,
     "examples": [
         {"zh": "他还在吃饭。", "pinyin": "Tā hái zài chīfàn.", "en": "He is still eating."},
         {"zh": "我还要一杯咖啡。", "pinyin": "Wǒ hái yào yì bēi kāfēi.", "en": "I want another cup of coffee."},
         {"zh": "你还有什么问题吗？", "pinyin": "Nǐ hái yǒu shénme wèntí ma?", "en": "Do you have any more questions?"},
     ]},
    {"name": "二 vs 两 two", "name_zh": "二/两", "hsk_level": 1, "category": "other",
     "description": "二 for ordinal/abstract numbers, 两 before measure words: 两个人 vs 第二", "difficulty": 0.3,
     "examples": [
         {"zh": "两个人。", "pinyin": "Liǎng gè rén.", "en": "Two people."},
         {"zh": "第二课。", "pinyin": "Dì èr kè.", "en": "Lesson two."},
         {"zh": "我有两本书，他是第二名。", "pinyin": "Wǒ yǒu liǎng běn shū, tā shì dì èr míng.", "en": "I have two books; he is second place."},
     ]},

    # =========================================================================
    # HSK 2 — 18 new grammar points
    # =========================================================================

    {"name": "就 then/immediately", "name_zh": "就", "hsk_level": 2, "category": "particle",
     "description": "Adverb indicating quick succession or emphasis on earliness: 他一来就走了", "difficulty": 0.4,
     "examples": [
         {"zh": "他一来就走了。", "pinyin": "Tā yì lái jiù zǒu le.", "en": "He left as soon as he arrived."},
         {"zh": "我吃完饭就去。", "pinyin": "Wǒ chīwán fàn jiù qù.", "en": "I'll go as soon as I finish eating."},
         {"zh": "他六点就起床了。", "pinyin": "Tā liù diǎn jiù qǐchuáng le.", "en": "He got up as early as six o'clock."},
     ]},
    {"name": "才 only then/only", "name_zh": "才", "hsk_level": 2, "category": "particle",
     "description": "Adverb indicating lateness, difficulty, or small quantity: 他五点才来", "difficulty": 0.4,
     "examples": [
         {"zh": "他五点才来。", "pinyin": "Tā wǔ diǎn cái lái.", "en": "He didn't come until five o'clock."},
         {"zh": "我学了三年才会说中文。", "pinyin": "Wǒ xuéle sān nián cái huì shuō Zhōngwén.", "en": "I studied for three years before I could speak Chinese."},
         {"zh": "他才二十岁。", "pinyin": "Tā cái èrshí suì.", "en": "He is only twenty years old."},
     ]},
    {"name": "已经...了 already", "name_zh": "已经…了", "hsk_level": 2, "category": "aspect",
     "description": "Indicating something has already happened: 我已经吃了", "difficulty": 0.3,
     "examples": [
         {"zh": "我已经吃了。", "pinyin": "Wǒ yǐjīng chī le.", "en": "I've already eaten."},
         {"zh": "他已经走了。", "pinyin": "Tā yǐjīng zǒu le.", "en": "He has already left."},
         {"zh": "电影已经开始了。", "pinyin": "Diànyǐng yǐjīng kāishǐ le.", "en": "The movie has already started."},
     ]},
    {"name": "一点儿 a little", "name_zh": "一点儿", "hsk_level": 2, "category": "structure",
     "description": "Expressing a small amount or slight degree, often positive/neutral: 好一点儿了", "difficulty": 0.3,
     "examples": [
         {"zh": "好一点儿了。", "pinyin": "Hǎo yìdiǎnr le.", "en": "A little better now."},
         {"zh": "请说慢一点儿。", "pinyin": "Qǐng shuō màn yìdiǎnr.", "en": "Please speak a little slower."},
         {"zh": "给我一点儿时间。", "pinyin": "Gěi wǒ yìdiǎnr shíjiān.", "en": "Give me a little time."},
     ]},
    {"name": "有点儿 somewhat (negative)", "name_zh": "有点儿", "hsk_level": 2, "category": "structure",
     "description": "Expressing slight negative degree before adjectives: 有点儿贵", "difficulty": 0.3,
     "examples": [
         {"zh": "有点儿贵。", "pinyin": "Yǒudiǎnr guì.", "en": "A bit expensive."},
         {"zh": "我有点儿累。", "pinyin": "Wǒ yǒudiǎnr lèi.", "en": "I'm a bit tired."},
         {"zh": "今天有点儿冷。", "pinyin": "Jīntiān yǒudiǎnr lěng.", "en": "It's a bit cold today."},
     ]},
    {"name": "最 superlative", "name_zh": "最", "hsk_level": 2, "category": "comparison",
     "description": "Superlative 'most' before adjectives or verbs: 他最高、我最喜欢", "difficulty": 0.3,
     "examples": [
         {"zh": "他最高。", "pinyin": "Tā zuì gāo.", "en": "He is the tallest."},
         {"zh": "我最喜欢吃饺子。", "pinyin": "Wǒ zuì xǐhuan chī jiǎozi.", "en": "I like eating dumplings the most."},
         {"zh": "这个最好。", "pinyin": "Zhège zuì hǎo.", "en": "This one is the best."},
     ]},
    {"name": "先...再 first...then", "name_zh": "先…再", "hsk_level": 2, "category": "structure",
     "description": "Sequencing actions: first do X, then do Y: 先吃饭再走", "difficulty": 0.3,
     "examples": [
         {"zh": "先吃饭再走。", "pinyin": "Xiān chīfàn zài zǒu.", "en": "Eat first, then leave."},
         {"zh": "先做作业，再看电视。", "pinyin": "Xiān zuò zuòyè, zài kàn diànshì.", "en": "Do homework first, then watch TV."},
         {"zh": "你先休息，再继续工作。", "pinyin": "Nǐ xiān xiūxi, zài jìxù gōngzuò.", "en": "Rest first, then continue working."},
     ]},
    {"name": "又 again (past)", "name_zh": "又", "hsk_level": 2, "category": "particle",
     "description": "Indicating repetition of a past action: 他又来了、又下雨了", "difficulty": 0.4,
     "examples": [
         {"zh": "他又来了。", "pinyin": "Tā yòu lái le.", "en": "He came again."},
         {"zh": "又下雨了。", "pinyin": "Yòu xiàyǔ le.", "en": "It's raining again."},
         {"zh": "我又忘了。", "pinyin": "Wǒ yòu wàng le.", "en": "I forgot again."},
     ]},
    {"name": "再 again (future)", "name_zh": "再", "hsk_level": 2, "category": "particle",
     "description": "Indicating future repetition or 'one more time': 明天再来、再说一遍", "difficulty": 0.4,
     "examples": [
         {"zh": "明天再来吧。", "pinyin": "Míngtiān zài lái ba.", "en": "Come again tomorrow."},
         {"zh": "请再说一遍。", "pinyin": "Qǐng zài shuō yí biàn.", "en": "Please say it one more time."},
         {"zh": "我不想再等了。", "pinyin": "Wǒ bù xiǎng zài děng le.", "en": "I don't want to wait anymore."},
     ]},
    {"name": "别 don't (imperative)", "name_zh": "别", "hsk_level": 2, "category": "structure",
     "description": "Negative imperative 'don't': 别走、别说了", "difficulty": 0.3,
     "examples": [
         {"zh": "别走！", "pinyin": "Bié zǒu!", "en": "Don't go!"},
         {"zh": "别说了。", "pinyin": "Bié shuō le.", "en": "Stop talking."},
         {"zh": "别担心，没问题的。", "pinyin": "Bié dānxīn, méi wèntí de.", "en": "Don't worry, no problem."},
     ]},
    {"name": "V+着 continuous state", "name_zh": "动词+着", "hsk_level": 2, "category": "aspect",
     "description": "Indicating an ongoing state or manner: 他站着、门开着", "difficulty": 0.4,
     "examples": [
         {"zh": "他站着。", "pinyin": "Tā zhànzhe.", "en": "He is standing."},
         {"zh": "门开着。", "pinyin": "Mén kāizhe.", "en": "The door is open."},
         {"zh": "她笑着说。", "pinyin": "Tā xiàozhe shuō.", "en": "She said with a smile."},
     ]},
    {"name": "地 adverbial particle", "name_zh": "地", "hsk_level": 2, "category": "particle",
     "description": "Linking an adverb or adjective to a verb: 高兴地说、慢慢地走", "difficulty": 0.4,
     "examples": [
         {"zh": "她高兴地说。", "pinyin": "Tā gāoxìng de shuō.", "en": "She said happily."},
         {"zh": "他慢慢地走。", "pinyin": "Tā mànmàn de zǒu.", "en": "He walked slowly."},
         {"zh": "孩子们快乐地玩。", "pinyin": "Háizimen kuàilè de wán.", "en": "The children played happily."},
     ]},
    {"name": "给 for/give", "name_zh": "给", "hsk_level": 2, "category": "structure",
     "description": "As a verb 'give' or preposition 'for/to': 给我看看、我给你打电话", "difficulty": 0.3,
     "examples": [
         {"zh": "给我看看。", "pinyin": "Gěi wǒ kànkan.", "en": "Let me have a look."},
         {"zh": "我给你打电话。", "pinyin": "Wǒ gěi nǐ dǎ diànhuà.", "en": "I'll call you."},
         {"zh": "请给我一杯水。", "pinyin": "Qǐng gěi wǒ yì bēi shuǐ.", "en": "Please give me a glass of water."},
     ]},
    {"name": "让/叫 causative", "name_zh": "让/叫", "hsk_level": 2, "category": "structure",
     "description": "Causative constructions meaning 'to make/let someone do something': 妈妈让我学习", "difficulty": 0.4,
     "examples": [
         {"zh": "妈妈让我学习。", "pinyin": "Māma ràng wǒ xuéxí.", "en": "Mom makes me study."},
         {"zh": "老师叫我们写作业。", "pinyin": "Lǎoshī jiào wǒmen xiě zuòyè.", "en": "The teacher told us to write homework."},
         {"zh": "别让他走。", "pinyin": "Bié ràng tā zǒu.", "en": "Don't let him leave."},
     ]},
    {"name": "向/往 towards", "name_zh": "向/往", "hsk_level": 2, "category": "structure",
     "description": "Prepositions indicating direction of movement: 向左走、往前看", "difficulty": 0.4,
     "examples": [
         {"zh": "向左走。", "pinyin": "Xiàng zuǒ zǒu.", "en": "Turn left. / Walk to the left."},
         {"zh": "往前看。", "pinyin": "Wǎng qián kàn.", "en": "Look ahead."},
         {"zh": "请往右拐。", "pinyin": "Qǐng wǎng yòu guǎi.", "en": "Please turn right."},
     ]},
    {"name": "...的话 if (colloquial)", "name_zh": "…的话", "hsk_level": 2, "category": "connector",
     "description": "Colloquial conditional 'if': 下雨的话就不去了", "difficulty": 0.3,
     "examples": [
         {"zh": "下雨的话就不去了。", "pinyin": "Xiàyǔ de huà jiù bú qù le.", "en": "If it rains, we won't go."},
         {"zh": "你不舒服的话，就在家休息吧。", "pinyin": "Nǐ bù shūfu de huà, jiù zài jiā xiūxi ba.", "en": "If you're not feeling well, just rest at home."},
         {"zh": "有时间的话，来我家玩。", "pinyin": "Yǒu shíjiān de huà, lái wǒ jiā wán.", "en": "If you have time, come visit my home."},
     ]},
    {"name": "一下 briefly", "name_zh": "一下", "hsk_level": 2, "category": "structure",
     "description": "After a verb to indicate a brief or casual action: 等一下、看一下", "difficulty": 0.3,
     "examples": [
         {"zh": "等一下。", "pinyin": "Děng yíxià.", "en": "Wait a moment."},
         {"zh": "请看一下这个。", "pinyin": "Qǐng kàn yíxià zhège.", "en": "Please take a look at this."},
         {"zh": "我想问一下。", "pinyin": "Wǒ xiǎng wèn yíxià.", "en": "I'd like to ask a quick question."},
     ]},
    {"name": "快要...了 about to", "name_zh": "快要…了", "hsk_level": 2, "category": "aspect",
     "description": "Indicating something is about to happen: 快要来了、快要开始了", "difficulty": 0.4,
     "examples": [
         {"zh": "他快要来了。", "pinyin": "Tā kuàiyào lái le.", "en": "He is about to arrive."},
         {"zh": "电影快要开始了。", "pinyin": "Diànyǐng kuàiyào kāishǐ le.", "en": "The movie is about to start."},
         {"zh": "我快要毕业了。", "pinyin": "Wǒ kuàiyào bìyè le.", "en": "I'm about to graduate."},
     ]},

    # =========================================================================
    # HSK 3 — 18 new grammar points
    # =========================================================================

    {"name": "只 only", "name_zh": "只", "hsk_level": 3, "category": "particle",
     "description": "Adverb meaning 'only/just': 我只有一个", "difficulty": 0.4,
     "examples": [
         {"zh": "我只有一个。", "pinyin": "Wǒ zhǐ yǒu yí gè.", "en": "I only have one."},
         {"zh": "他只会说中文。", "pinyin": "Tā zhǐ huì shuō Zhōngwén.", "en": "He can only speak Chinese."},
         {"zh": "我只是想帮忙。", "pinyin": "Wǒ zhǐshì xiǎng bāngmáng.", "en": "I just want to help."},
     ]},
    {"name": "极了 extremely", "name_zh": "极了", "hsk_level": 3, "category": "complement",
     "description": "Complement of degree meaning 'extremely': 高兴极了、热极了", "difficulty": 0.4,
     "examples": [
         {"zh": "我高兴极了！", "pinyin": "Wǒ gāoxìng jí le!", "en": "I'm extremely happy!"},
         {"zh": "今天热极了。", "pinyin": "Jīntiān rè jí le.", "en": "It's extremely hot today."},
         {"zh": "这个菜好吃极了。", "pinyin": "Zhège cài hǎochī jí le.", "en": "This dish is absolutely delicious."},
     ]},
    {"name": "跟...一样 same as", "name_zh": "跟…一样", "hsk_level": 3, "category": "comparison",
     "description": "Comparing two things as equal: 他跟我一样高", "difficulty": 0.4,
     "examples": [
         {"zh": "他跟我一样高。", "pinyin": "Tā gēn wǒ yíyàng gāo.", "en": "He is as tall as me."},
         {"zh": "这个跟那个一样。", "pinyin": "Zhège gēn nàge yíyàng.", "en": "This one is the same as that one."},
         {"zh": "今天跟昨天一样冷。", "pinyin": "Jīntiān gēn zuótiān yíyàng lěng.", "en": "Today is as cold as yesterday."},
     ]},
    {"name": "A不如B not as good as", "name_zh": "不如", "hsk_level": 3, "category": "comparison",
     "description": "A is not as good as B: 今天不如昨天暖和", "difficulty": 0.5,
     "examples": [
         {"zh": "今天不如昨天暖和。", "pinyin": "Jīntiān bùrú zuótiān nuǎnhuo.", "en": "Today is not as warm as yesterday."},
         {"zh": "坐公交不如坐地铁快。", "pinyin": "Zuò gōngjiāo bùrú zuò dìtiě kuài.", "en": "Taking the bus is not as fast as the subway."},
         {"zh": "说得好不如做得好。", "pinyin": "Shuō de hǎo bùrú zuò de hǎo.", "en": "Talking well is not as good as doing well."},
     ]},
    {"name": "一...就 as soon as", "name_zh": "一…就", "hsk_level": 3, "category": "structure",
     "description": "As soon as one action happens, another follows: 他一回家就看电视", "difficulty": 0.5,
     "examples": [
         {"zh": "他一回家就看电视。", "pinyin": "Tā yì huíjiā jiù kàn diànshì.", "en": "As soon as he gets home, he watches TV."},
         {"zh": "我一看到他就笑了。", "pinyin": "Wǒ yí kàndào tā jiù xiào le.", "en": "I laughed as soon as I saw him."},
         {"zh": "天一黑，街上就没人了。", "pinyin": "Tiān yì hēi, jiē shàng jiù méi rén le.", "en": "As soon as it gets dark, there's no one on the street."},
     ]},
    {"name": "Potential complement V得/不了", "name_zh": "可能补语", "hsk_level": 3, "category": "complement",
     "description": "V+得/不+complement to express ability to achieve a result: 吃得完、看不见", "difficulty": 0.5,
     "examples": [
         {"zh": "这么多菜，你吃得完吗？", "pinyin": "Zhème duō cài, nǐ chī de wán ma?", "en": "So much food, can you finish it?"},
         {"zh": "太远了，我看不见。", "pinyin": "Tài yuǎn le, wǒ kàn bu jiàn.", "en": "It's too far, I can't see it."},
         {"zh": "这个字我听得懂。", "pinyin": "Zhège zì wǒ tīng de dǒng.", "en": "I can understand this character (by listening)."},
     ]},
    {"name": "只要...就 as long as", "name_zh": "只要…就", "hsk_level": 3, "category": "connector",
     "description": "Conditional: as long as X, then Y: 只要努力就能成功", "difficulty": 0.5,
     "examples": [
         {"zh": "只要努力，就能成功。", "pinyin": "Zhǐyào nǔlì, jiù néng chénggōng.", "en": "As long as you work hard, you can succeed."},
         {"zh": "只要你来，我就高兴。", "pinyin": "Zhǐyào nǐ lái, wǒ jiù gāoxìng.", "en": "As long as you come, I'll be happy."},
         {"zh": "只要有时间，我就去锻炼。", "pinyin": "Zhǐyào yǒu shíjiān, wǒ jiù qù duànliàn.", "en": "As long as I have time, I go exercise."},
     ]},
    {"name": "只好 have no choice but", "name_zh": "只好", "hsk_level": 3, "category": "structure",
     "description": "Having no other option: 他只好自己去", "difficulty": 0.4,
     "examples": [
         {"zh": "他只好自己去。", "pinyin": "Tā zhǐhǎo zìjǐ qù.", "en": "He had no choice but to go by himself."},
         {"zh": "没有出租车，我只好走路。", "pinyin": "Méiyǒu chūzūchē, wǒ zhǐhǎo zǒulù.", "en": "There were no taxis, so I had to walk."},
         {"zh": "票卖完了，我们只好回家。", "pinyin": "Piào mài wán le, wǒmen zhǐhǎo huíjiā.", "en": "The tickets were sold out, so we had no choice but to go home."},
     ]},
    {"name": "看起来 looks like", "name_zh": "看起来", "hsk_level": 3, "category": "structure",
     "description": "Expressing how something appears: 她看起来很累", "difficulty": 0.4,
     "examples": [
         {"zh": "她看起来很累。", "pinyin": "Tā kàn qǐlái hěn lèi.", "en": "She looks very tired."},
         {"zh": "这个菜看起来很好吃。", "pinyin": "Zhège cài kàn qǐlái hěn hǎochī.", "en": "This dish looks delicious."},
         {"zh": "他看起来不太高兴。", "pinyin": "Tā kàn qǐlái bú tài gāoxìng.", "en": "He doesn't look too happy."},
     ]},
    {"name": "根据 according to", "name_zh": "根据", "hsk_level": 3, "category": "structure",
     "description": "Preposition meaning 'according to/based on': 根据天气预报", "difficulty": 0.5,
     "examples": [
         {"zh": "根据天气预报，明天会下雨。", "pinyin": "Gēnjù tiānqì yùbào, míngtiān huì xiàyǔ.", "en": "According to the weather forecast, it will rain tomorrow."},
         {"zh": "根据他说的，我们改了计划。", "pinyin": "Gēnjù tā shuō de, wǒmen gǎi le jìhuà.", "en": "Based on what he said, we changed the plan."},
         {"zh": "请根据实际情况回答。", "pinyin": "Qǐng gēnjù shíjì qíngkuàng huídá.", "en": "Please answer based on the actual situation."},
     ]},
    {"name": "关于 about/concerning", "name_zh": "关于", "hsk_level": 3, "category": "structure",
     "description": "Preposition meaning 'about/regarding': 关于这个问题", "difficulty": 0.5,
     "examples": [
         {"zh": "关于这个问题，我想说几句。", "pinyin": "Guānyú zhège wèntí, wǒ xiǎng shuō jǐ jù.", "en": "Regarding this question, I'd like to say a few words."},
         {"zh": "你知道关于他的事吗？", "pinyin": "Nǐ zhīdào guānyú tā de shì ma?", "en": "Do you know about his situation?"},
         {"zh": "我看了一本关于中国历史的书。", "pinyin": "Wǒ kànle yì běn guānyú Zhōngguó lìshǐ de shū.", "en": "I read a book about Chinese history."},
     ]},
    {"name": "原来 originally/turns out", "name_zh": "原来", "hsk_level": 3, "category": "other",
     "description": "Meaning 'originally' or expressing discovery/realization: 原来是你啊", "difficulty": 0.4,
     "examples": [
         {"zh": "原来是你啊！", "pinyin": "Yuánlái shì nǐ a!", "en": "Oh, it's you! / So it was you!"},
         {"zh": "我原来住在上海。", "pinyin": "Wǒ yuánlái zhù zài Shànghǎi.", "en": "I originally lived in Shanghai."},
         {"zh": "原来他已经结婚了。", "pinyin": "Yuánlái tā yǐjīng jiéhūn le.", "en": "So it turns out he's already married."},
     ]},
    {"name": "总是 always", "name_zh": "总是", "hsk_level": 3, "category": "particle",
     "description": "Adverb meaning 'always/invariably': 他总是迟到", "difficulty": 0.4,
     "examples": [
         {"zh": "他总是迟到。", "pinyin": "Tā zǒngshì chídào.", "en": "He is always late."},
         {"zh": "她总是很忙。", "pinyin": "Tā zǒngshì hěn máng.", "en": "She is always busy."},
         {"zh": "你为什么总是忘记？", "pinyin": "Nǐ wèishénme zǒngshì wàngjì?", "en": "Why do you always forget?"},
     ]},
    {"name": "差不多 almost/about the same", "name_zh": "差不多", "hsk_level": 3, "category": "other",
     "description": "Meaning 'almost/more or less/about the same': 差不多到了", "difficulty": 0.4,
     "examples": [
         {"zh": "差不多到了。", "pinyin": "Chàbuduō dào le.", "en": "We're almost there."},
         {"zh": "这两个差不多。", "pinyin": "Zhè liǎng gè chàbuduō.", "en": "These two are about the same."},
         {"zh": "我差不多每天都跑步。", "pinyin": "Wǒ chàbuduō měitiān dōu pǎobù.", "en": "I run almost every day."},
     ]},
    {"name": "为了 in order to", "name_zh": "为了", "hsk_level": 3, "category": "connector",
     "description": "Expressing purpose: 为了学好中文", "difficulty": 0.5,
     "examples": [
         {"zh": "为了学好中文，他每天练习。", "pinyin": "Wèile xué hǎo Zhōngwén, tā měitiān liànxí.", "en": "In order to learn Chinese well, he practices every day."},
         {"zh": "为了健康，我开始跑步了。", "pinyin": "Wèile jiànkāng, wǒ kāishǐ pǎobù le.", "en": "For the sake of health, I started running."},
         {"zh": "他为了省钱，每天自己做饭。", "pinyin": "Tā wèile shěng qián, měitiān zìjǐ zuòfàn.", "en": "In order to save money, he cooks for himself every day."},
     ]},
    {"name": "对...感兴趣 interested in", "name_zh": "对…感兴趣", "hsk_level": 3, "category": "structure",
     "description": "Expressing interest in something: 我对中国文化感兴趣", "difficulty": 0.5,
     "examples": [
         {"zh": "我对中国文化感兴趣。", "pinyin": "Wǒ duì Zhōngguó wénhuà gǎn xìngqù.", "en": "I'm interested in Chinese culture."},
         {"zh": "她对音乐很感兴趣。", "pinyin": "Tā duì yīnyuè hěn gǎn xìngqù.", "en": "She is very interested in music."},
         {"zh": "你对什么感兴趣？", "pinyin": "Nǐ duì shénme gǎn xìngqù?", "en": "What are you interested in?"},
     ]},
    {"name": "然后 then/afterwards", "name_zh": "然后", "hsk_level": 3, "category": "connector",
     "description": "Connecting sequential actions: 先吃饭，然后看电影", "difficulty": 0.4,
     "examples": [
         {"zh": "先吃饭，然后看电影。", "pinyin": "Xiān chīfàn, ránhòu kàn diànyǐng.", "en": "First eat, then watch a movie."},
         {"zh": "我先去超市，然后回家。", "pinyin": "Wǒ xiān qù chāoshì, ránhòu huíjiā.", "en": "I'll go to the supermarket first, then go home."},
         {"zh": "他下了课，然后去图书馆了。", "pinyin": "Tā xiàle kè, ránhòu qù túshūguǎn le.", "en": "After class, he went to the library."},
     ]},
    {"name": "虽然...但是 although (basic)", "name_zh": "虽然…但是(基础)", "hsk_level": 3, "category": "connector",
     "description": "Basic concessive pattern at HSK 3 level: 虽然累但很开心", "difficulty": 0.5,
     "examples": [
         {"zh": "虽然累，但是很开心。", "pinyin": "Suīrán lèi, dànshì hěn kāixīn.", "en": "Although tired, I'm very happy."},
         {"zh": "虽然很远，但是我想去。", "pinyin": "Suīrán hěn yuǎn, dànshì wǒ xiǎng qù.", "en": "Although it's far, I want to go."},
         {"zh": "虽然他不高，但是打篮球很好。", "pinyin": "Suīrán tā bù gāo, dànshì dǎ lánqiú hěn hǎo.", "en": "Although he's not tall, he plays basketball well."},
     ]},
]
