"""Additional HSK 7-9 grammar points for the Mandarin learning system."""

EXTRA_GRAMMAR_HSK7_9 = [
    # HSK 7 — advanced formal/literary (10 new)
    {"name": "归根到底 at the root", "name_zh": "归根到底", "hsk_level": 7, "category": "connector",
     "description": "Getting to the root cause: 归根到底是教育问题", "difficulty": 0.75,
     "examples": [
         {"zh": "归根到底，这是一个教育问题。", "pinyin": "Guīgēn dàodǐ, zhè shì yí gè jiàoyù wèntí.", "en": "At the root, this is an education problem."},
         {"zh": "归根到底，成功靠的是坚持。", "pinyin": "Guīgēn dàodǐ, chénggōng kào de shì jiānchí.", "en": "At the root, success depends on persistence."},
         {"zh": "问题归根到底还是出在管理上。", "pinyin": "Wèntí guīgēn dàodǐ háishì chū zài guǎnlǐ shàng.", "en": "The problem, at its root, still comes down to management."},
     ]},
    {"name": "可想而知 as one can imagine", "name_zh": "可想而知", "hsk_level": 7, "category": "connector",
     "description": "Predictable outcome: 结果可想而知", "difficulty": 0.75,
     "examples": [
         {"zh": "他没有准备，结果可想而知。", "pinyin": "Tā méiyǒu zhǔnbèi, jiéguǒ kěxiǎng ér zhī.", "en": "He didn't prepare, so the result was predictable."},
         {"zh": "在那种环境下长大，他的性格可想而知。", "pinyin": "Zài nà zhǒng huánjìng xià zhǎngdà, tā de xìnggé kěxiǎng ér zhī.", "en": "Growing up in that environment, his personality is as one can imagine."},
         {"zh": "连续加班一个月，他的身体状况可想而知。", "pinyin": "Liánxù jiābān yí gè yuè, tā de shēntǐ zhuàngkuàng kěxiǎng ér zhī.", "en": "Working overtime for a month straight, his health is as one can imagine."},
     ]},
    {"name": "由此 from this / thereby", "name_zh": "由此", "hsk_level": 7, "category": "connector",
     "description": "Drawing inference: 由此可以看出", "difficulty": 0.75,
     "examples": [
         {"zh": "由此可以看出，他非常重视这件事。", "pinyin": "Yóucǐ kěyǐ kànchū, tā fēicháng zhòngshì zhè jiàn shì.", "en": "From this we can see that he attaches great importance to this matter."},
         {"zh": "由此可见，教育改革势在必行。", "pinyin": "Yóucǐ kějiàn, jiàoyù gǎigé shì zài bì xíng.", "en": "From this it is evident that education reform is imperative."},
         {"zh": "由此引发了一场激烈的讨论。", "pinyin": "Yóucǐ yǐnfā le yì chǎng jīliè de tǎolùn.", "en": "This triggered a heated discussion."},
     ]},
    {"name": "与此同时 at the same time", "name_zh": "与此同时", "hsk_level": 7, "category": "connector",
     "description": "Simultaneous development: 与此同时经济也在增长", "difficulty": 0.8,
     "examples": [
         {"zh": "城市在扩大，与此同时经济也在快速增长。", "pinyin": "Chéngshì zài kuòdà, yǔcǐ tóngshí jīngjì yě zài kuàisù zēngzhǎng.", "en": "The city is expanding, and at the same time the economy is growing rapidly."},
         {"zh": "科技在进步，与此同时也带来了新的问题。", "pinyin": "Kējì zài jìnbù, yǔcǐ tóngshí yě dàilái le xīn de wèntí.", "en": "Technology is advancing, and at the same time it has brought new problems."},
         {"zh": "他在忙着工作，与此同时妻子在家照顾孩子。", "pinyin": "Tā zài mángzhe gōngzuò, yǔcǐ tóngshí qīzi zài jiā zhàogù háizi.", "en": "He is busy with work, and at the same time his wife is at home taking care of the children."},
     ]},
    {"name": "充其量 at most", "name_zh": "充其量", "hsk_level": 7, "category": "structure",
     "description": "Upper limit/dismissive: 他充其量是个初学者", "difficulty": 0.8,
     "examples": [
         {"zh": "他充其量是个初学者，还谈不上专家。", "pinyin": "Tā chōngqíliàng shì gè chūxuézhě, hái tán bù shàng zhuānjiā.", "en": "He is at most a beginner, far from an expert."},
         {"zh": "这个方案充其量只能解决表面问题。", "pinyin": "Zhège fāng'àn chōngqíliàng zhǐ néng jiějué biǎomiàn wèntí.", "en": "This plan can at most only solve surface-level problems."},
         {"zh": "这件事充其量算个小误会。", "pinyin": "Zhè jiàn shì chōngqíliàng suàn gè xiǎo wùhuì.", "en": "This matter is at most a minor misunderstanding."},
     ]},
    {"name": "基于 based on", "name_zh": "基于", "hsk_level": 7, "category": "connector",
     "description": "Formal basis: 基于以上分析", "difficulty": 0.75,
     "examples": [
         {"zh": "基于以上分析，我们得出了结论。", "pinyin": "Jīyú yǐshàng fēnxī, wǒmen déchū le jiélùn.", "en": "Based on the above analysis, we have reached a conclusion."},
         {"zh": "这个决定是基于事实做出的。", "pinyin": "Zhège juédìng shì jīyú shìshí zuòchū de.", "en": "This decision was made based on facts."},
         {"zh": "基于安全考虑，活动被取消了。", "pinyin": "Jīyú ānquán kǎolǜ, huódòng bèi qǔxiāo le.", "en": "Based on safety considerations, the event was cancelled."},
     ]},
    {"name": "何尝 when has...ever", "name_zh": "何尝", "hsk_level": 7, "category": "structure",
     "description": "Rhetorical negation: 我何尝不想去", "difficulty": 0.8,
     "examples": [
         {"zh": "我何尝不想去？只是没有时间。", "pinyin": "Wǒ hécháng bù xiǎng qù? Zhǐshì méiyǒu shíjiān.", "en": "When have I ever not wanted to go? I just don't have time."},
         {"zh": "他何尝不知道自己的问题？", "pinyin": "Tā hécháng bù zhīdào zìjǐ de wèntí?", "en": "When has he ever not known about his own problems?"},
         {"zh": "父母何尝不希望孩子过得好？", "pinyin": "Fùmǔ hécháng bù xīwàng háizi guò de hǎo?", "en": "When have parents ever not wished for their children to live well?"},
     ]},
    {"name": "难怪 no wonder", "name_zh": "难怪", "hsk_level": 7, "category": "connector",
     "description": "Realization: 难怪他不高兴", "difficulty": 0.7,
     "examples": [
         {"zh": "原来他生病了，难怪今天没来。", "pinyin": "Yuánlái tā shēngbìng le, nánguài jīntiān méi lái.", "en": "So he was sick — no wonder he didn't come today."},
         {"zh": "难怪他中文说得那么好，他在中国住了十年。", "pinyin": "Nánguài tā Zhōngwén shuō de nàme hǎo, tā zài Zhōngguó zhù le shí nián.", "en": "No wonder his Chinese is so good — he lived in China for ten years."},
         {"zh": "难怪大家都不高兴，原来计划又变了。", "pinyin": "Nánguài dàjiā dōu bù gāoxìng, yuánlái jìhuà yòu biàn le.", "en": "No wonder everyone is unhappy — turns out the plan changed again."},
     ]},
    {"name": "之际 at the time of", "name_zh": "之际", "hsk_level": 7, "category": "structure",
     "description": "Formal temporal marker: 毕业之际", "difficulty": 0.8,
     "examples": [
         {"zh": "毕业之际，老师送给我们一句话。", "pinyin": "Bìyè zhī jì, lǎoshī sòng gěi wǒmen yí jù huà.", "en": "At the time of graduation, the teacher gave us a piece of advice."},
         {"zh": "新年来临之际，祝大家万事如意。", "pinyin": "Xīnnián láilín zhī jì, zhù dàjiā wànshì rúyì.", "en": "At the arrival of the new year, I wish everyone all the best."},
         {"zh": "危难之际，他挺身而出。", "pinyin": "Wēinàn zhī jì, tā tǐngshēn ér chū.", "en": "At a time of crisis, he stepped forward."},
     ]},
    {"name": "趁 take advantage of", "name_zh": "趁", "hsk_level": 7, "category": "structure",
     "description": "Seizing opportunity: 趁年轻多学习", "difficulty": 0.7,
     "examples": [
         {"zh": "趁年轻多学点东西。", "pinyin": "Chèn niánqīng duō xué diǎn dōngxi.", "en": "Take advantage of your youth to learn more."},
         {"zh": "趁天还没黑，我们赶紧出发吧。", "pinyin": "Chèn tiān hái méi hēi, wǒmen gǎnjǐn chūfā ba.", "en": "Let's hurry and set off while it's still light."},
         {"zh": "趁热吃吧，凉了就不好吃了。", "pinyin": "Chèn rè chī ba, liáng le jiù bù hǎochī le.", "en": "Eat it while it's hot — it won't taste good once it cools down."},
     ]},

    # HSK 8 — classical/literary connectors (8 new)
    {"name": "所谓 so-called", "name_zh": "所谓", "hsk_level": 8, "category": "structure",
     "description": "Defining or questioning a term: 所谓的专家", "difficulty": 0.8,
     "examples": [
         {"zh": "所谓的专家，其实并不了解实际情况。", "pinyin": "Suǒwèi de zhuānjiā, qíshí bìng bù liǎojiě shíjì qíngkuàng.", "en": "The so-called experts don't actually understand the real situation."},
         {"zh": "所谓知己知彼，百战不殆。", "pinyin": "Suǒwèi zhījǐ zhībǐ, bǎizhàn bú dài.", "en": "As the saying goes, know yourself and your enemy, and you will never be defeated."},
         {"zh": "这就是所谓的双赢策略。", "pinyin": "Zhè jiùshì suǒwèi de shuāngyíng cèlüè.", "en": "This is what is called a win-win strategy."},
     ]},
    {"name": "无从 have no way to", "name_zh": "无从", "hsk_level": 8, "category": "structure",
     "description": "No means of doing: 无从得知真相", "difficulty": 0.85,
     "examples": [
         {"zh": "事情已经过去了，真相无从得知。", "pinyin": "Shìqing yǐjīng guòqù le, zhēnxiàng wúcóng dézhī.", "en": "The matter has passed, and the truth can no longer be known."},
         {"zh": "线索太少，警方无从下手。", "pinyin": "Xiànsuǒ tài shǎo, jǐngfāng wúcóng xiàshǒu.", "en": "With too few clues, the police had no way to proceed."},
         {"zh": "没有数据支撑，结论无从验证。", "pinyin": "Méiyǒu shùjù zhīchēng, jiélùn wúcóng yànzhèng.", "en": "Without data to support it, the conclusion cannot be verified."},
     ]},
    {"name": "归咎于 attribute blame to", "name_zh": "归咎于", "hsk_level": 8, "category": "structure",
     "description": "Assigning blame: 不能归咎于运气", "difficulty": 0.85,
     "examples": [
         {"zh": "失败不能简单地归咎于运气。", "pinyin": "Shībài bù néng jiǎndān de guījiù yú yùnqi.", "en": "Failure cannot simply be attributed to luck."},
         {"zh": "他把所有的问题都归咎于别人。", "pinyin": "Tā bǎ suǒyǒu de wèntí dōu guījiù yú biéren.", "en": "He attributes all problems to other people."},
         {"zh": "事故被归咎于管理不善。", "pinyin": "Shìgù bèi guījiù yú guǎnlǐ bú shàn.", "en": "The accident was attributed to poor management."},
     ]},
    {"name": "但凡 if only / whenever", "name_zh": "但凡", "hsk_level": 8, "category": "connector",
     "description": "Minimal condition: 但凡有一点办法也不会放弃", "difficulty": 0.85,
     "examples": [
         {"zh": "但凡有一点办法，他也不会放弃。", "pinyin": "Dànfán yǒu yìdiǎn bànfǎ, tā yě bú huì fàngqì.", "en": "If there were even the slightest way, he would not give up."},
         {"zh": "但凡你用心想一想，就不会犯这种错误。", "pinyin": "Dànfán nǐ yòngxīn xiǎng yì xiǎng, jiù bú huì fàn zhè zhǒng cuòwù.", "en": "If only you thought carefully, you wouldn't make this kind of mistake."},
         {"zh": "但凡了解历史的人，都知道这段往事。", "pinyin": "Dànfán liǎojiě lìshǐ de rén, dōu zhīdào zhè duàn wǎngshì.", "en": "Anyone who knows anything about history knows this episode."},
     ]},
    {"name": "势必 bound to / inevitably", "name_zh": "势必", "hsk_level": 8, "category": "connector",
     "description": "Inevitable outcome: 这势必会引起争议", "difficulty": 0.85,
     "examples": [
         {"zh": "这项政策势必会引起争议。", "pinyin": "Zhè xiàng zhèngcè shìbì huì yǐnqǐ zhēngyì.", "en": "This policy is bound to cause controversy."},
         {"zh": "不改革势必落后于时代。", "pinyin": "Bù gǎigé shìbì luòhòu yú shídài.", "en": "Without reform, one is bound to fall behind the times."},
         {"zh": "人口减少势必影响经济发展。", "pinyin": "Rénkǒu jiǎnshǎo shìbì yǐngxiǎng jīngjì fāzhǎn.", "en": "Population decline will inevitably affect economic development."},
     ]},
    {"name": "固有 inherent", "name_zh": "固有", "hsk_level": 8, "category": "structure",
     "description": "Intrinsic quality: 固有的观念需要改变", "difficulty": 0.8,
     "examples": [
         {"zh": "固有的观念需要改变，才能适应新环境。", "pinyin": "Gùyǒu de guānniàn xūyào gǎibiàn, cái néng shìyìng xīn huánjìng.", "en": "Inherent notions need to change in order to adapt to the new environment."},
         {"zh": "每种文化都有其固有的价值。", "pinyin": "Měi zhǒng wénhuà dōu yǒu qí gùyǒu de jiàzhí.", "en": "Every culture has its inherent value."},
         {"zh": "这个系统存在固有的缺陷。", "pinyin": "Zhège xìtǒng cúnzài gùyǒu de quēxiàn.", "en": "This system has inherent flaws."},
     ]},
    {"name": "无可厚非 understandable / beyond reproach", "name_zh": "无可厚非", "hsk_level": 8, "category": "structure",
     "description": "Acceptable behavior: 他的做法无可厚非", "difficulty": 0.85,
     "examples": [
         {"zh": "他的做法虽然不完美，但也无可厚非。", "pinyin": "Tā de zuòfǎ suīrán bù wánměi, dàn yě wúkě hòufēi.", "en": "His approach is not perfect, but it is understandable."},
         {"zh": "为了保护家人而撒谎，无可厚非。", "pinyin": "Wèile bǎohù jiārén ér sāhuǎng, wúkě hòufēi.", "en": "Lying to protect one's family is understandable."},
         {"zh": "追求更好的生活，这无可厚非。", "pinyin": "Zhuīqiú gèng hǎo de shēnghuó, zhè wúkě hòufēi.", "en": "Pursuing a better life — this is beyond reproach."},
     ]},
    {"name": "动辄 easily / at every turn", "name_zh": "动辄", "hsk_level": 8, "category": "structure",
     "description": "Frequent/excessive action: 他动辄发脾气", "difficulty": 0.85,
     "examples": [
         {"zh": "他动辄发脾气，同事们都怕他。", "pinyin": "Tā dòngzhé fā píqi, tóngshìmen dōu pà tā.", "en": "He loses his temper at every turn, and his colleagues are all afraid of him."},
         {"zh": "在大城市，房价动辄上百万。", "pinyin": "Zài dà chéngshì, fángjià dòngzhé shàng bǎi wàn.", "en": "In big cities, housing prices easily reach over a million."},
         {"zh": "这种机器动辄出故障，很不可靠。", "pinyin": "Zhè zhǒng jīqì dòngzhé chū gùzhàng, hěn bù kěkào.", "en": "This kind of machine breaks down at every turn — it's very unreliable."},
     ]},

    # HSK 9 — near-native/classical markers (6 new)
    {"name": "焉知 how would one know", "name_zh": "焉知", "hsk_level": 9, "category": "structure",
     "description": "Classical rhetorical: 焉知不是好事", "difficulty": 0.9,
     "examples": [
         {"zh": "塞翁失马，焉知非福。", "pinyin": "Sàiwēng shī mǎ, yān zhī fēi fú.", "en": "The old man lost his horse — how would one know it isn't a blessing?"},
         {"zh": "事情尚未结束，焉知最终结果？", "pinyin": "Shìqing shàngwèi jiéshù, yān zhī zuìzhōng jiéguǒ?", "en": "The matter is not yet over — how would one know the final result?"},
         {"zh": "今日之失败，焉知不是明日之成功的基石？", "pinyin": "Jīnrì zhī shībài, yān zhī bú shì míngrì zhī chénggōng de jīshí?", "en": "Today's failure — how would one know it isn't the foundation for tomorrow's success?"},
     ]},
    {"name": "岂料 who would have thought", "name_zh": "岂料", "hsk_level": 9, "category": "structure",
     "description": "Unexpected turn: 岂料事情如此复杂", "difficulty": 0.9,
     "examples": [
         {"zh": "本以为很简单，岂料事情如此复杂。", "pinyin": "Běn yǐwéi hěn jiǎndān, qǐliào shìqing rúcǐ fùzá.", "en": "I thought it would be simple — who would have thought the matter was so complicated."},
         {"zh": "他满怀信心出发，岂料中途遭遇暴风雨。", "pinyin": "Tā mǎnhuái xìnxīn chūfā, qǐliào zhōngtú zāoyù bàofēngyǔ.", "en": "He set out full of confidence, but who would have thought he'd encounter a storm midway."},
         {"zh": "大家都以为他会成功，岂料功亏一篑。", "pinyin": "Dàjiā dōu yǐwéi tā huì chénggōng, qǐliào gōngkuī yìkuì.", "en": "Everyone thought he would succeed, but who would have thought he'd fall at the last hurdle."},
     ]},
    {"name": "殊不知 little does one know", "name_zh": "殊不知", "hsk_level": 9, "category": "connector",
     "description": "Hidden truth: 殊不知后果严重", "difficulty": 0.9,
     "examples": [
         {"zh": "他以为万无一失，殊不知后果非常严重。", "pinyin": "Tā yǐwéi wànwú yīshī, shūbùzhī hòuguǒ fēicháng yánzhòng.", "en": "He thought it was foolproof, little knowing the consequences were very serious."},
         {"zh": "很多人追求速度，殊不知欲速则不达。", "pinyin": "Hěn duō rén zhuīqiú sùdù, shūbùzhī yùsù zé bù dá.", "en": "Many people pursue speed, little knowing that haste makes waste."},
         {"zh": "她一直瞒着父母，殊不知他们早已知情。", "pinyin": "Tā yìzhí mánzhe fùmǔ, shūbùzhī tāmen zǎoyǐ zhīqíng.", "en": "She kept it hidden from her parents, little knowing they already knew."},
     ]},
    {"name": "断然 absolutely / resolutely", "name_zh": "断然", "hsk_level": 9, "category": "structure",
     "description": "Decisive action: 他断然拒绝了", "difficulty": 0.85,
     "examples": [
         {"zh": "他断然拒绝了对方的无理要求。", "pinyin": "Tā duànrán jùjué le duìfāng de wúlǐ yāoqiú.", "en": "He resolutely refused the other party's unreasonable demand."},
         {"zh": "面对诱惑，她断然选择了坚持原则。", "pinyin": "Miànduì yòuhuò, tā duànrán xuǎnzé le jiānchí yuánzé.", "en": "Facing temptation, she resolutely chose to stick to her principles."},
         {"zh": "我们不能断然下结论，还需要更多证据。", "pinyin": "Wǒmen bù néng duànrán xià jiélùn, hái xūyào gèng duō zhèngjù.", "en": "We cannot jump to conclusions — we still need more evidence."},
     ]},
    {"name": "不啻 no less than", "name_zh": "不啻", "hsk_level": 9, "category": "structure",
     "description": "Literary equivalence: 这不啻是一场革命", "difficulty": 0.9,
     "examples": [
         {"zh": "这项发现不啻是科学界的一场革命。", "pinyin": "Zhè xiàng fāxiàn bùchì shì kēxuéjiè de yì chǎng gémìng.", "en": "This discovery is no less than a revolution in the scientific world."},
         {"zh": "对他来说，这不啻于晴天霹雳。", "pinyin": "Duì tā lái shuō, zhè bùchì yú qíngtiān pīlì.", "en": "For him, this was no less than a bolt from the blue."},
         {"zh": "这种行为不啻是对法律的公然挑战。", "pinyin": "Zhè zhǒng xíngwéi bùchì shì duì fǎlǜ de gōngrán tiǎozhàn.", "en": "This kind of behavior is no less than an open challenge to the law."},
     ]},
    {"name": "何以 how / why (classical)", "name_zh": "何以", "hsk_level": 9, "category": "structure",
     "description": "Classical interrogative: 何以见得", "difficulty": 0.9,
     "examples": [
         {"zh": "你说他不可信，何以见得？", "pinyin": "Nǐ shuō tā bù kěxìn, héyǐ jiàn dé?", "en": "You say he's not trustworthy — how can you tell?"},
         {"zh": "何以解忧？唯有读书。", "pinyin": "Héyǐ jiě yōu? Wéiyǒu dúshū.", "en": "How to relieve worries? Only through reading."},
         {"zh": "一个人连自己都管不好，何以管理他人？", "pinyin": "Yí gè rén lián zìjǐ dōu guǎn bù hǎo, héyǐ guǎnlǐ tārén?", "en": "If one cannot even manage oneself, how can one manage others?"},
     ]},
]
