"""Additional HSK 7-9 grammar points, round 2."""

EXTRA_GRAMMAR_HSK7_9_R2 = [
    # ── HSK 7 — advanced formal/literary (12 new) ──────────────────────

    {"name": "乃 is/indeed (literary)", "name_zh": "乃", "hsk_level": 7, "category": "structure",
     "description": "Literary copula or emphasis marker: 学习乃终身之事", "difficulty": 0.8,
     "examples": [
         {"zh": "学习乃终身之事。", "pinyin": "Xuéxí nǎi zhōngshēn zhī shì.", "en": "Learning is a lifelong endeavor."},
         {"zh": "失败乃成功之母。", "pinyin": "Shībài nǎi chénggōng zhī mǔ.", "en": "Failure is the mother of success."},
         {"zh": "此乃不争之事实。", "pinyin": "Cǐ nǎi bùzhēng zhī shìshí.", "en": "This is an indisputable fact."},
     ]},
    {"name": "未尝 have never", "name_zh": "未尝", "hsk_level": 7, "category": "structure",
     "description": "Literary negation of experience, often rhetorical: 我未尝不想过", "difficulty": 0.8,
     "examples": [
         {"zh": "我未尝不想过这个问题。", "pinyin": "Wǒ wèicháng bù xiǎngguo zhège wèntí.", "en": "It's not that I've never considered this question."},
         {"zh": "他未尝不努力，只是方法不对。", "pinyin": "Tā wèicháng bù nǔlì, zhǐshì fāngfǎ bú duì.", "en": "It's not that he hasn't tried hard — his approach was just wrong."},
         {"zh": "这种做法未尝不可。", "pinyin": "Zhè zhǒng zuòfǎ wèicháng bùkě.", "en": "This approach is not entirely out of the question."},
     ]},
    {"name": "不妨 might as well", "name_zh": "不妨", "hsk_level": 7, "category": "structure",
     "description": "Suggesting without pressure: 不妨试试看", "difficulty": 0.7,
     "examples": [
         {"zh": "不妨试试看，也许会有意想不到的效果。", "pinyin": "Bùfáng shìshi kàn, yěxǔ huì yǒu yìxiǎng bú dào de xiàoguǒ.", "en": "You might as well try — there may be unexpected results."},
         {"zh": "如果不确定，不妨多问几个人。", "pinyin": "Rúguǒ bú quèdìng, bùfáng duō wèn jǐ gè rén.", "en": "If you're unsure, you might as well ask a few more people."},
         {"zh": "时间还早，我们不妨在这里坐一会儿。", "pinyin": "Shíjiān hái zǎo, wǒmen bùfáng zài zhèlǐ zuò yíhuìr.", "en": "It's still early — we might as well sit here for a while."},
     ]},
    {"name": "非…不可 must", "name_zh": "非…不可", "hsk_level": 7, "category": "structure",
     "description": "Emphatic necessity: 这件事非解决不可", "difficulty": 0.8,
     "examples": [
         {"zh": "这件事非解决不可。", "pinyin": "Zhè jiàn shì fēi jiějué bùkě.", "en": "This matter absolutely must be resolved."},
         {"zh": "今天的作业非做完不可。", "pinyin": "Jīntiān de zuòyè fēi zuòwán bùkě.", "en": "Today's homework absolutely must be finished."},
         {"zh": "他非要亲自去不可。", "pinyin": "Tā fēi yào qīnzì qù bùkě.", "en": "He insists on going in person."},
     ]},
    {"name": "唯有 only", "name_zh": "唯有", "hsk_level": 7, "category": "structure",
     "description": "Exclusive condition (formal): 唯有坚持才能成功", "difficulty": 0.8,
     "examples": [
         {"zh": "唯有坚持，才能取得成功。", "pinyin": "Wéiyǒu jiānchí, cái néng qǔdé chénggōng.", "en": "Only through persistence can one achieve success."},
         {"zh": "唯有不断学习，才能跟上时代的步伐。", "pinyin": "Wéiyǒu búduàn xuéxí, cái néng gēnshàng shídài de bùfá.", "en": "Only through continuous learning can one keep up with the times."},
         {"zh": "唯有亲身经历，才能真正理解。", "pinyin": "Wéiyǒu qīnshēn jīnglì, cái néng zhēnzhèng lǐjiě.", "en": "Only through personal experience can one truly understand."},
     ]},
    {"name": "据此 based on this", "name_zh": "据此", "hsk_level": 7, "category": "connector",
     "description": "Drawing inference from evidence: 据此可以判断", "difficulty": 0.8,
     "examples": [
         {"zh": "据此可以判断，市场将会复苏。", "pinyin": "Jùcǐ kěyǐ pànduàn, shìchǎng jiāng huì fùsū.", "en": "Based on this, we can judge that the market will recover."},
         {"zh": "据此推算，项目将在下个月完成。", "pinyin": "Jùcǐ tuīsuàn, xiàngmù jiāng zài xià gè yuè wánchéng.", "en": "Based on this calculation, the project will be completed next month."},
         {"zh": "据此分析，问题出在第二个环节。", "pinyin": "Jùcǐ fēnxī, wèntí chū zài dì èr gè huánjié.", "en": "Based on this analysis, the problem lies in the second step."},
     ]},
    {"name": "尤为 especially (formal)", "name_zh": "尤为", "hsk_level": 7, "category": "structure",
     "description": "Formal emphasis on degree: 这一点尤为重要", "difficulty": 0.75,
     "examples": [
         {"zh": "这一点尤为重要。", "pinyin": "Zhè yì diǎn yóuwéi zhòngyào.", "en": "This point is especially important."},
         {"zh": "在当前形势下，合作尤为关键。", "pinyin": "Zài dāngqián xíngshì xià, hézuò yóuwéi guānjiàn.", "en": "Under the current circumstances, cooperation is especially crucial."},
         {"zh": "他的贡献尤为突出。", "pinyin": "Tā de gòngxiàn yóuwéi tūchū.", "en": "His contributions are especially outstanding."},
     ]},
    {"name": "一度 once / at one time", "name_zh": "一度", "hsk_level": 7, "category": "structure",
     "description": "Indicating a past phase or period: 他一度想放弃", "difficulty": 0.7,
     "examples": [
         {"zh": "他一度想放弃，但最终坚持了下来。", "pinyin": "Tā yídù xiǎng fàngqì, dàn zuìzhōng jiānchí le xiàlái.", "en": "He once thought about giving up, but ultimately persevered."},
         {"zh": "公司一度面临倒闭的危险。", "pinyin": "Gōngsī yídù miànlín dǎobì de wēixiǎn.", "en": "The company once faced the risk of bankruptcy."},
         {"zh": "这座城市一度是全国的经济中心。", "pinyin": "Zhè zuò chéngshì yídù shì quánguó de jīngjì zhōngxīn.", "en": "This city was once the economic center of the whole country."},
     ]},
    {"name": "不失为 can be considered", "name_zh": "不失为", "hsk_level": 7, "category": "structure",
     "description": "Moderate positive appraisal: 这不失为一个好办法", "difficulty": 0.75,
     "examples": [
         {"zh": "这不失为一个好办法。", "pinyin": "Zhè bùshīwéi yí gè hǎo bànfǎ.", "en": "This can be considered a good approach."},
         {"zh": "骑自行车上班不失为一种健康的生活方式。", "pinyin": "Qí zìxíngchē shàngbān bùshīwéi yì zhǒng jiànkāng de shēnghuó fāngshì.", "en": "Cycling to work can be considered a healthy lifestyle."},
         {"zh": "他的建议虽然保守，但不失为明智之举。", "pinyin": "Tā de jiànyì suīrán bǎoshǒu, dàn bùshīwéi míngzhì zhī jǔ.", "en": "His suggestion is conservative, but can be considered a wise move."},
     ]},
    {"name": "有待 remain to be", "name_zh": "有待", "hsk_level": 7, "category": "structure",
     "description": "Something yet to be done or verified: 这个问题有待解决", "difficulty": 0.75,
     "examples": [
         {"zh": "这个问题有待进一步研究。", "pinyin": "Zhège wèntí yǒudài jìnyíbù yánjiū.", "en": "This issue remains to be further studied."},
         {"zh": "他的能力有待考验。", "pinyin": "Tā de nénglì yǒudài kǎoyàn.", "en": "His abilities remain to be tested."},
         {"zh": "新政策的效果有待观察。", "pinyin": "Xīn zhèngcè de xiàoguǒ yǒudài guānchá.", "en": "The effect of the new policy remains to be observed."},
     ]},
    {"name": "无不 without exception", "name_zh": "无不", "hsk_level": 7, "category": "structure",
     "description": "Universal emphasis (literary): 大家无不感到震惊", "difficulty": 0.85,
     "examples": [
         {"zh": "听到这个消息，大家无不感到震惊。", "pinyin": "Tīngdào zhège xiāoxi, dàjiā wúbù gǎndào zhènjīng.", "en": "Upon hearing this news, everyone without exception was shocked."},
         {"zh": "看过这部电影的人无不为之感动。", "pinyin": "Kànguo zhè bù diànyǐng de rén wúbù wéi zhī gǎndòng.", "en": "Everyone who has seen this movie was moved by it without exception."},
         {"zh": "参加过那次活动的人无不赞不绝口。", "pinyin": "Cānjiāguo nà cì huódòng de rén wúbù zàn bù juékǒu.", "en": "Everyone who attended that event praised it endlessly."},
     ]},
    {"name": "以至于 to the extent that", "name_zh": "以至于(HSK7)", "hsk_level": 7, "category": "connector",
     "description": "Result of excessive degree (distinct from HSK 6 以至于 in more literary/formal contexts): 紧张以至于说不出话来", "difficulty": 0.8,
     "examples": [
         {"zh": "他紧张以至于完全忘了台词。", "pinyin": "Tā jǐnzhāng yǐzhìyú wánquán wàng le táicí.", "en": "He was nervous to the extent that he completely forgot his lines."},
         {"zh": "问题积累以至于无法收拾。", "pinyin": "Wèntí jīlěi yǐzhìyú wúfǎ shōushi.", "en": "Problems accumulated to the extent that they became unmanageable."},
         {"zh": "双方分歧以至于谈判破裂。", "pinyin": "Shuāngfāng fēnqí yǐzhìyú tánpàn pòliè.", "en": "The two sides diverged to the extent that negotiations broke down."},
     ]},

    # ── HSK 8 — classical/literary connectors (12 new) ─────────────────

    {"name": "诚如 just as (literary)", "name_zh": "诚如", "hsk_level": 8, "category": "connector",
     "description": "Literary agreement marker: 诚如所言", "difficulty": 0.85,
     "examples": [
         {"zh": "诚如您所言，这个问题确实很复杂。", "pinyin": "Chéngrú nín suǒ yán, zhège wèntí quèshí hěn fùzá.", "en": "Just as you said, this problem is indeed complex."},
         {"zh": "诚如专家所预测的那样，经济开始回暖。", "pinyin": "Chéngrú zhuānjiā suǒ yùcè de nàyàng, jīngjì kāishǐ huínuǎn.", "en": "Just as the experts predicted, the economy is starting to recover."},
         {"zh": "诚如古人所云，学无止境。", "pinyin": "Chéngrú gǔrén suǒ yún, xué wú zhǐjìng.", "en": "Just as the ancients said, learning knows no bounds."},
     ]},
    {"name": "不啻于 no less than", "name_zh": "不啻于", "hsk_level": 8, "category": "structure",
     "description": "Emphatic equivalence: 这不啻于一场灾难", "difficulty": 0.85,
     "examples": [
         {"zh": "这次失败不啻于一场灾难。", "pinyin": "Zhè cì shībài bùchìyú yì chǎng zāinàn.", "en": "This failure is no less than a disaster."},
         {"zh": "对他而言，这不啻于一个奇迹。", "pinyin": "Duì tā ér yán, zhè bùchìyú yí gè qíjì.", "en": "For him, this is no less than a miracle."},
         {"zh": "这样的指控不啻于诽谤。", "pinyin": "Zhèyàng de zhǐkòng bùchìyú fěibàng.", "en": "Such an accusation is no less than slander."},
     ]},
    {"name": "无可奈何 helpless / have no alternative", "name_zh": "无可奈何", "hsk_level": 8, "category": "structure",
     "description": "Expressing helplessness: 他无可奈何地叹了口气", "difficulty": 0.8,
     "examples": [
         {"zh": "他无可奈何地叹了口气。", "pinyin": "Tā wúkě nàihé de tàn le kǒu qì.", "en": "He sighed helplessly."},
         {"zh": "面对这种局面，我们实在无可奈何。", "pinyin": "Miànduì zhè zhǒng júmiàn, wǒmen shízài wúkě nàihé.", "en": "Facing this situation, we are truly helpless."},
         {"zh": "规定如此，大家也只好无可奈何地接受。", "pinyin": "Guīdìng rúcǐ, dàjiā yě zhǐhǎo wúkě nàihé de jiēshòu.", "en": "The rules are what they are, and everyone had no choice but to accept them."},
     ]},
    {"name": "不遗余力 spare no effort", "name_zh": "不遗余力", "hsk_level": 8, "category": "structure",
     "description": "Going all out: 他不遗余力地帮助我们", "difficulty": 0.85,
     "examples": [
         {"zh": "他不遗余力地帮助我们完成了项目。", "pinyin": "Tā bùyí yúlì de bāngzhù wǒmen wánchéng le xiàngmù.", "en": "He spared no effort in helping us complete the project."},
         {"zh": "政府不遗余力地推动经济改革。", "pinyin": "Zhèngfǔ bùyí yúlì de tuīdòng jīngjì gǎigé.", "en": "The government spares no effort in promoting economic reform."},
         {"zh": "她不遗余力地培养下一代人才。", "pinyin": "Tā bùyí yúlì de péiyǎng xià yí dài réncái.", "en": "She spares no effort in cultivating the next generation of talent."},
     ]},
    {"name": "与日俱增 increase day by day", "name_zh": "与日俱增", "hsk_level": 8, "category": "structure",
     "description": "Steadily growing: 压力与日俱增", "difficulty": 0.85,
     "examples": [
         {"zh": "随着工作量增加，压力与日俱增。", "pinyin": "Suízhe gōngzuòliàng zēngjiā, yālì yǔrì jùzēng.", "en": "As the workload increases, the pressure grows day by day."},
         {"zh": "人们对环境保护的意识与日俱增。", "pinyin": "Rénmen duì huánjìng bǎohù de yìshí yǔrì jùzēng.", "en": "People's awareness of environmental protection is increasing day by day."},
         {"zh": "这座城市的国际影响力与日俱增。", "pinyin": "Zhè zuò chéngshì de guójì yǐngxiǎnglì yǔrì jùzēng.", "en": "This city's international influence is growing day by day."},
     ]},
    {"name": "言之有理 what you said makes sense", "name_zh": "言之有理", "hsk_level": 8, "category": "structure",
     "description": "Acknowledging a well-reasoned point: 你说的言之有理", "difficulty": 0.8,
     "examples": [
         {"zh": "你说的言之有理，我同意你的看法。", "pinyin": "Nǐ shuō de yánzhī yǒulǐ, wǒ tóngyì nǐ de kànfǎ.", "en": "What you said makes sense — I agree with your view."},
         {"zh": "他的分析言之有理，值得参考。", "pinyin": "Tā de fēnxī yánzhī yǒulǐ, zhíde cānkǎo.", "en": "His analysis makes sense and is worth considering."},
         {"zh": "这番话虽然尖锐，但言之有理。", "pinyin": "Zhè fān huà suīrán jiānruì, dàn yánzhī yǒulǐ.", "en": "These words are sharp, but they make sense."},
     ]},
    {"name": "不言而喻 goes without saying", "name_zh": "不言而喻", "hsk_level": 8, "category": "structure",
     "description": "Self-evident truth: 其重要性不言而喻", "difficulty": 0.85,
     "examples": [
         {"zh": "教育的重要性不言而喻。", "pinyin": "Jiàoyù de zhòngyàoxìng bùyán ér yù.", "en": "The importance of education goes without saying."},
         {"zh": "健康对每个人来说都不言而喻地重要。", "pinyin": "Jiànkāng duì měi gè rén lái shuō dōu bùyán ér yù de zhòngyào.", "en": "Health is self-evidently important to everyone."},
         {"zh": "团队合作的价值不言而喻。", "pinyin": "Tuánduì hézuò de jiàzhí bùyán ér yù.", "en": "The value of teamwork goes without saying."},
     ]},
    {"name": "有目共睹 obvious to all", "name_zh": "有目共睹", "hsk_level": 8, "category": "structure",
     "description": "Widely recognized fact: 他的进步有目共睹", "difficulty": 0.85,
     "examples": [
         {"zh": "他的进步是有目共睹的。", "pinyin": "Tā de jìnbù shì yǒumù gòngdǔ de.", "en": "His progress is obvious to all."},
         {"zh": "这些年来中国的发展有目共睹。", "pinyin": "Zhèxiē nián lái Zhōngguó de fāzhǎn yǒumù gòngdǔ.", "en": "China's development over these years is obvious to all."},
         {"zh": "她的领导才能有目共睹，大家都很认可。", "pinyin": "Tā de lǐngdǎo cáinéng yǒumù gòngdǔ, dàjiā dōu hěn rènkě.", "en": "Her leadership ability is obvious to all, and everyone acknowledges it."},
     ]},
    {"name": "以身作则 lead by example", "name_zh": "以身作则", "hsk_level": 8, "category": "structure",
     "description": "Setting an example through one's own conduct: 领导应该以身作则", "difficulty": 0.85,
     "examples": [
         {"zh": "领导应该以身作则，带动团队。", "pinyin": "Lǐngdǎo yīnggāi yǐshēn zuòzé, dàidòng tuánduì.", "en": "Leaders should lead by example and motivate the team."},
         {"zh": "父母以身作则，是对孩子最好的教育。", "pinyin": "Fùmǔ yǐshēn zuòzé, shì duì háizi zuì hǎo de jiàoyù.", "en": "Parents leading by example is the best education for children."},
         {"zh": "他总是以身作则，从不要求别人做自己做不到的事。", "pinyin": "Tā zǒngshì yǐshēn zuòzé, cóng bù yāoqiú biéren zuò zìjǐ zuò bú dào de shì.", "en": "He always leads by example and never asks others to do what he cannot do himself."},
     ]},
    {"name": "无所不在 omnipresent", "name_zh": "无所不在", "hsk_level": 8, "category": "structure",
     "description": "Present everywhere: 科技的影响无所不在", "difficulty": 0.85,
     "examples": [
         {"zh": "在现代社会，科技的影响无所不在。", "pinyin": "Zài xiàndài shèhuì, kējì de yǐngxiǎng wúsuǒ bú zài.", "en": "In modern society, the influence of technology is omnipresent."},
         {"zh": "互联网的力量无所不在，改变了人们的生活方式。", "pinyin": "Hùliánwǎng de lìliàng wúsuǒ bú zài, gǎibiàn le rénmen de shēnghuó fāngshì.", "en": "The power of the internet is omnipresent, changing people's lifestyles."},
         {"zh": "文化的影响无所不在，渗透在日常生活的方方面面。", "pinyin": "Wénhuà de yǐngxiǎng wúsuǒ bú zài, shèntòu zài rìcháng shēnghuó de fāngfāng miànmiàn.", "en": "Cultural influence is omnipresent, permeating every aspect of daily life."},
     ]},
    {"name": "望文生义 take literally", "name_zh": "望文生义", "hsk_level": 8, "category": "structure",
     "description": "Misinterpreting by taking words at face value: 不要望文生义", "difficulty": 0.9,
     "examples": [
         {"zh": "学成语不能望文生义，要了解背后的故事。", "pinyin": "Xué chéngyǔ bù néng wàngwén shēngyì, yào liǎojiě bèihòu de gùshi.", "en": "When learning idioms, you can't take them literally — you must understand the story behind them."},
         {"zh": "他望文生义地理解了这个词，闹了笑话。", "pinyin": "Tā wàngwén shēngyì de lǐjiě le zhège cí, nào le xiàohua.", "en": "He interpreted this word literally and made a fool of himself."},
         {"zh": "很多外国学生容易望文生义，误解汉语表达。", "pinyin": "Hěn duō wàiguó xuéshēng róngyì wàngwén shēngyì, wùjiě Hànyǔ biǎodá.", "en": "Many foreign students tend to take things literally and misunderstand Chinese expressions."},
     ]},
    {"name": "顾名思义 as the name suggests", "name_zh": "顾名思义", "hsk_level": 8, "category": "structure",
     "description": "Inferring meaning from the name: 顾名思义，这是…", "difficulty": 0.85,
     "examples": [
         {"zh": "顾名思义，'自动驾驶'就是车辆自己驾驶。", "pinyin": "Gùmíng sīyì, 'zìdòng jiàshǐ' jiùshì chēliàng zìjǐ jiàshǐ.", "en": "As the name suggests, 'autonomous driving' means the vehicle drives itself."},
         {"zh": "顾名思义，'环保'就是保护环境。", "pinyin": "Gùmíng sīyì, 'huánbǎo' jiùshì bǎohù huánjìng.", "en": "As the name suggests, 'environmental protection' means protecting the environment."},
         {"zh": "顾名思义，'快餐'就是能快速准备好的食物。", "pinyin": "Gùmíng sīyì, 'kuàicān' jiùshì néng kuàisù zhǔnbèi hǎo de shíwù.", "en": "As the name suggests, 'fast food' is food that can be prepared quickly."},
     ]},

    # ── HSK 9 — near-native/classical markers (7 new) ─────────────────

    {"name": "于斯 at this / herein", "name_zh": "于斯", "hsk_level": 9, "category": "structure",
     "description": "Classical demonstrative locative: 于斯可见", "difficulty": 0.9,
     "examples": [
         {"zh": "于斯可见，教育之重要不可忽视。", "pinyin": "Yúsī kějiàn, jiàoyù zhī zhòngyào bùkě hūshì.", "en": "Herein we can see that the importance of education cannot be ignored."},
         {"zh": "文明之兴衰，于斯有据。", "pinyin": "Wénmíng zhī xīngshuāi, yúsī yǒu jù.", "en": "The rise and fall of civilization — herein lies the evidence."},
         {"zh": "于斯为盛，千古流传。", "pinyin": "Yúsī wéi shèng, qiāngǔ liúchuán.", "en": "Herein lies its greatness, passed down through the ages."},
     ]},
    {"name": "有过之而无不及 even surpass", "name_zh": "有过之而无不及", "hsk_level": 9, "category": "structure",
     "description": "Surpassing or exceeding: 他有过之而无不及", "difficulty": 0.95,
     "examples": [
         {"zh": "论勤奋，他比师父有过之而无不及。", "pinyin": "Lùn qínfèn, tā bǐ shīfu yǒuguòzhī ér wúbùjí.", "en": "In terms of diligence, he even surpasses his master."},
         {"zh": "这次危机的严重程度比上次有过之而无不及。", "pinyin": "Zhè cì wēijī de yánzhòng chéngdù bǐ shàng cì yǒuguòzhī ér wúbùjí.", "en": "The severity of this crisis surpasses the last one."},
         {"zh": "他的固执比他父亲有过之而无不及。", "pinyin": "Tā de gùzhí bǐ tā fùqīn yǒuguòzhī ér wúbùjí.", "en": "His stubbornness surpasses even that of his father."},
     ]},
    {"name": "当之无愧 deserve without a doubt", "name_zh": "当之无愧", "hsk_level": 9, "category": "structure",
     "description": "Fully deserving of a title or praise: 他当之无愧", "difficulty": 0.9,
     "examples": [
         {"zh": "她是当之无愧的冠军。", "pinyin": "Tā shì dāngzhī wúkuì de guànjūn.", "en": "She is the champion without a doubt."},
         {"zh": "他是这个领域当之无愧的权威。", "pinyin": "Tā shì zhège lǐngyù dāngzhī wúkuì de quánwēi.", "en": "He is the undisputed authority in this field."},
         {"zh": "这部作品当之无愧地获得了最高奖项。", "pinyin": "Zhè bù zuòpǐn dāngzhī wúkuì de huòdé le zuìgāo jiǎngxiàng.", "en": "This work deservedly won the highest award."},
     ]},
    {"name": "亦 also (literary)", "name_zh": "亦", "hsk_level": 9, "category": "structure",
     "description": "Classical equivalent of 也: 亦可如此", "difficulty": 0.85,
     "examples": [
         {"zh": "此法亦可用于其他场合。", "pinyin": "Cǐ fǎ yì kě yòng yú qítā chǎnghé.", "en": "This method can also be used in other situations."},
         {"zh": "人生亦如此，有起有落。", "pinyin": "Rénshēng yì rúcǐ, yǒu qǐ yǒu luò.", "en": "Life is also like this — there are ups and downs."},
         {"zh": "古人亦曾面对同样的困境。", "pinyin": "Gǔrén yì céng miànduì tóngyàng de kùnjìng.", "en": "The ancients also once faced the same predicament."},
     ]},
    {"name": "乃至于 and even", "name_zh": "乃至于", "hsk_level": 9, "category": "connector",
     "description": "Extending scope to an extreme: 影响了全国乃至于全世界", "difficulty": 0.9,
     "examples": [
         {"zh": "这场运动影响了全国乃至于全世界。", "pinyin": "Zhè chǎng yùndòng yǐngxiǎng le quánguó nǎizhìyú quán shìjiè.", "en": "This movement influenced the whole country and even the whole world."},
         {"zh": "这个决定将影响我们的部门乃至于整个公司。", "pinyin": "Zhège juédìng jiāng yǐngxiǎng wǒmen de bùmén nǎizhìyú zhěnggè gōngsī.", "en": "This decision will affect our department and even the entire company."},
         {"zh": "他的思想影响了一代人乃至于几代人。", "pinyin": "Tā de sīxiǎng yǐngxiǎng le yí dài rén nǎizhìyú jǐ dài rén.", "en": "His ideas influenced one generation and even several generations."},
     ]},
    {"name": "无以 have nothing to / unable to", "name_zh": "无以", "hsk_level": 9, "category": "structure",
     "description": "Classical expression of inability or lacking means: 无以复加", "difficulty": 0.95,
     "examples": [
         {"zh": "他的感激之情无以言表。", "pinyin": "Tā de gǎnjī zhī qíng wúyǐ yánbiǎo.", "en": "His gratitude is beyond words."},
         {"zh": "荒谬之极，无以复加。", "pinyin": "Huāngmiù zhī jí, wúyǐ fùjiā.", "en": "The absurdity has reached its peak — it cannot be surpassed."},
         {"zh": "若无知识，无以立身。", "pinyin": "Ruò wú zhīshi, wúyǐ lìshēn.", "en": "Without knowledge, one has no means to establish oneself."},
     ]},
    {"name": "不置可否 neither confirm nor deny", "name_zh": "不置可否", "hsk_level": 9, "category": "structure",
     "description": "Remaining noncommittal: 他对此不置可否", "difficulty": 0.9,
     "examples": [
         {"zh": "他对这个提议不置可否，没有明确表态。", "pinyin": "Tā duì zhège tíyì bùzhì kěfǒu, méiyǒu míngquè biǎotài.", "en": "He was noncommittal about this proposal and did not take a clear stance."},
         {"zh": "面对记者的追问，发言人不置可否。", "pinyin": "Miànduì jìzhě de zhuīwèn, fāyánrén bùzhì kěfǒu.", "en": "Facing the reporter's follow-up questions, the spokesperson neither confirmed nor denied."},
         {"zh": "她对这件事始终不置可否，让人摸不透。", "pinyin": "Tā duì zhè jiàn shì shǐzhōng bùzhì kěfǒu, ràng rén mō bú tòu.", "en": "She has always been noncommittal about this matter, leaving people unable to read her."},
     ]},
]
