"""Extra HSK 4-5 grammar points, round 3 — filling remaining gaps from official syllabus."""

EXTRA_GRAMMAR_HSK4_5_R3 = [
    # =========================================================================
    # HSK 4 — additional grammar points
    # =========================================================================
    {"name": "假如...就 supposing...then", "name_zh": "假如…就", "hsk_level": 4, "category": "connector",
     "description": "Formal conditional meaning 'supposing/if...then'. More literary than 如果...就, often used in hypothetical or written contexts.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "假如明天下雨，我们就不去了。", "pinyin": "Jiǎrú míngtiān xià yǔ, wǒmen jiù bú qù le.", "en": "Supposing it rains tomorrow, we won't go."},
         {"zh": "假如你是我，你就会理解了。", "pinyin": "Jiǎrú nǐ shì wǒ, nǐ jiù huì lǐjiě le.", "en": "If you were me, you would understand."},
         {"zh": "假如他不来，我们就自己开始吧。", "pinyin": "Jiǎrú tā bù lái, wǒmen jiù zìjǐ kāishǐ ba.", "en": "If he doesn't come, let's just start ourselves."},
     ]},
    {"name": "哪怕...也 even if (strong concessive)", "name_zh": "哪怕…也", "hsk_level": 4, "category": "connector",
     "description": "Strong concessive meaning 'even if/even though'. Emphasizes determination or willingness to accept an extreme condition.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "哪怕再难，我也不会放弃。", "pinyin": "Nǎpà zài nán, wǒ yě bú huì fàngqì.", "en": "Even if it's harder, I still won't give up."},
         {"zh": "哪怕只有一个人来，我们也要办这个活动。", "pinyin": "Nǎpà zhǐ yǒu yí ge rén lái, wǒmen yě yào bàn zhège huódòng.", "en": "Even if only one person comes, we'll still hold this event."},
         {"zh": "哪怕下大雪，他也每天去锻炼。", "pinyin": "Nǎpà xià dà xuě, tā yě měitiān qù duànliàn.", "en": "Even if it snows heavily, he still exercises every day."},
     ]},
    {"name": "要不是 if it weren't for", "name_zh": "要不是", "hsk_level": 4, "category": "connector",
     "description": "Counterfactual conditional meaning 'if it weren't for / if it hadn't been for'. Used to credit something or someone for an outcome.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "要不是你帮忙，我早就失败了。", "pinyin": "Yàobushì nǐ bāngmáng, wǒ zǎo jiù shībài le.", "en": "If it weren't for your help, I would have failed long ago."},
         {"zh": "要不是堵车，我们不会迟到。", "pinyin": "Yàobushì dǔchē, wǒmen bú huì chídào.", "en": "If it weren't for the traffic jam, we wouldn't have been late."},
         {"zh": "要不是他提醒我，我就忘了。", "pinyin": "Yàobushì tā tíxǐng wǒ, wǒ jiù wàng le.", "en": "If he hadn't reminded me, I would have forgotten."},
     ]},
    {"name": "以为 to mistakenly believe", "name_zh": "以为", "hsk_level": 4, "category": "structure",
     "description": "Means 'to think/believe mistakenly'. Implies the belief turned out to be wrong, unlike 认为 which is neutral.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "我以为他是中国人，其实他是日本人。", "pinyin": "Wǒ yǐwéi tā shì Zhōngguó rén, qíshí tā shì Rìběn rén.", "en": "I thought he was Chinese, but actually he's Japanese."},
         {"zh": "她以为我生气了，所以一直道歉。", "pinyin": "Tā yǐwéi wǒ shēngqì le, suǒyǐ yìzhí dàoqiàn.", "en": "She thought I was angry, so she kept apologizing."},
         {"zh": "大家都以为考试很简单，结果很难。", "pinyin": "Dàjiā dōu yǐwéi kǎoshì hěn jiǎndān, jiéguǒ hěn nán.", "en": "Everyone thought the exam was easy, but it turned out to be hard."},
     ]},
    {"name": "看来 it seems/apparently", "name_zh": "看来", "hsk_level": 4, "category": "structure",
     "description": "Sentence-initial adverb meaning 'it seems / apparently / it looks like'. Used to draw a conclusion from evidence or context.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "看来他今天不会来了。", "pinyin": "Kànlái tā jīntiān bú huì lái le.", "en": "It seems he won't come today."},
         {"zh": "看来这个问题没那么简单。", "pinyin": "Kànlái zhège wèntí méi nàme jiǎndān.", "en": "Apparently this problem isn't that simple."},
         {"zh": "看来我们得换一个计划了。", "pinyin": "Kànlái wǒmen děi huàn yí ge jìhuà le.", "en": "It looks like we need to change our plan."},
     ]},
    {"name": "各 each/every (individual)", "name_zh": "各", "hsk_level": 4, "category": "structure",
     "description": "Determiner meaning 'each/every', emphasizing individual members of a group. Often followed by a measure word or directly by a noun.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "各国代表都发了言。", "pinyin": "Gè guó dàibiǎo dōu fā le yán.", "en": "Representatives from each country gave speeches."},
         {"zh": "各位同学，请注意！", "pinyin": "Gèwèi tóngxué, qǐng zhùyì!", "en": "Every student, please pay attention!"},
         {"zh": "我们各有各的看法。", "pinyin": "Wǒmen gè yǒu gè de kànfǎ.", "en": "Each of us has our own views."},
     ]},
    {"name": "任何 any/whatever", "name_zh": "任何", "hsk_level": 4, "category": "structure",
     "description": "Determiner meaning 'any/whatever/whichever'. Often used in conditional, negative, or emphatic statements.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "任何人都不能迟到。", "pinyin": "Rènhé rén dōu bù néng chídào.", "en": "Nobody is allowed to be late."},
         {"zh": "她没有任何理由拒绝。", "pinyin": "Tā méiyǒu rènhé lǐyóu jùjué.", "en": "She has no reason whatsoever to refuse."},
         {"zh": "在任何情况下都要保持冷静。", "pinyin": "Zài rènhé qíngkuàng xià dōu yào bǎochí lěngjìng.", "en": "Under any circumstances, stay calm."},
     ]},
    {"name": "整个 entire/whole", "name_zh": "整个", "hsk_level": 4, "category": "structure",
     "description": "Determiner meaning 'entire/whole'. Emphasizes completeness or totality of something.",
     "difficulty": 0.35,
     "examples": [
         {"zh": "整个城市都在下雪。", "pinyin": "Zhěnggè chéngshì dōu zài xià xuě.", "en": "The entire city is snowing."},
         {"zh": "他花了整个下午写作业。", "pinyin": "Tā huā le zhěnggè xiàwǔ xiě zuòyè.", "en": "He spent the entire afternoon doing homework."},
         {"zh": "整个计划都需要重新考虑。", "pinyin": "Zhěnggè jìhuà dōu xūyào chóngxīn kǎolǜ.", "en": "The whole plan needs to be reconsidered."},
     ]},
    {"name": "所有 all (formal totality)", "name_zh": "所有", "hsk_level": 4, "category": "structure",
     "description": "Determiner meaning 'all/every'. More formal than 都 alone; often followed by 的 + noun.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "所有的学生都通过了考试。", "pinyin": "Suǒyǒu de xuéshēng dōu tōngguò le kǎoshì.", "en": "All the students passed the exam."},
         {"zh": "他把所有的钱都花光了。", "pinyin": "Tā bǎ suǒyǒu de qián dōu huāguāng le.", "en": "He spent all the money."},
         {"zh": "所有人都同意这个决定。", "pinyin": "Suǒyǒu rén dōu tóngyì zhège juédìng.", "en": "Everyone agreed with this decision."},
     ]},
    {"name": "其中 among them/of which", "name_zh": "其中", "hsk_level": 4, "category": "structure",
     "description": "Pronoun meaning 'among them / of which / within'. Used to single out part of a previously mentioned group.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "我们班有三十个人，其中十个是女生。", "pinyin": "Wǒmen bān yǒu sānshí ge rén, qízhōng shí ge shì nǚshēng.", "en": "Our class has thirty people, of which ten are girls."},
         {"zh": "这本书有很多故事，其中我最喜欢第三个。", "pinyin": "Zhè běn shū yǒu hěn duō gùshi, qízhōng wǒ zuì xǐhuān dì sān ge.", "en": "This book has many stories; among them, I like the third one most."},
         {"zh": "他去过很多国家，其中包括日本和法国。", "pinyin": "Tā qùguò hěn duō guójiā, qízhōng bāokuò Rìběn hé Fǎguó.", "en": "He's been to many countries, including Japan and France."},
     ]},
    {"name": "及时 timely/in time", "name_zh": "及时", "hsk_level": 4, "category": "structure",
     "description": "Adverb/adjective meaning 'timely / in time / promptly'. Can modify verbs or serve as a predicate.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "幸好医生及时赶到了。", "pinyin": "Xìnghǎo yīshēng jíshí gǎndào le.", "en": "Fortunately the doctor arrived in time."},
         {"zh": "请及时完成作业。", "pinyin": "Qǐng jíshí wánchéng zuòyè.", "en": "Please finish the homework promptly."},
         {"zh": "这个通知很及时。", "pinyin": "Zhège tōngzhī hěn jíshí.", "en": "This notice is very timely."},
     ]},
    {"name": "彼此 each other/mutually", "name_zh": "彼此", "hsk_level": 4, "category": "structure",
     "description": "Pronoun meaning 'each other / mutually / one another'. Slightly more formal than 互相.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "我们应该彼此尊重。", "pinyin": "Wǒmen yīnggāi bǐcǐ zūnzhòng.", "en": "We should respect each other."},
         {"zh": "彼此都是老朋友了，不用客气。", "pinyin": "Bǐcǐ dōu shì lǎo péngyou le, búyòng kèqi.", "en": "We're old friends, no need to be polite."},
         {"zh": "他们彼此了解得很深。", "pinyin": "Tāmen bǐcǐ liǎojiě de hěn shēn.", "en": "They understand each other very well."},
     ]},
    {"name": "不得了 extremely/terribly", "name_zh": "不得了", "hsk_level": 4, "category": "complement",
     "description": "Complement or exclamation meaning 'extremely / terribly / awful'. Used after adjectives as a degree complement, or standalone to express alarm.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "今天热得不得了。", "pinyin": "Jīntiān rè de bùdéliǎo.", "en": "It's unbearably hot today."},
         {"zh": "她高兴得不得了。", "pinyin": "Tā gāoxìng de bùdéliǎo.", "en": "She's extremely happy."},
         {"zh": "不得了！房子着火了！", "pinyin": "Bùdéliǎo! Fángzi zháohuǒ le!", "en": "Terrible! The house is on fire!"},
     ]},
    {"name": "好像 seems like/as if", "name_zh": "好像", "hsk_level": 4, "category": "structure",
     "description": "Adverb meaning 'seems like / as if / to look like'. Expresses uncertainty or resemblance.",
     "difficulty": 0.35,
     "examples": [
         {"zh": "他好像不太高兴。", "pinyin": "Tā hǎoxiàng bú tài gāoxìng.", "en": "He seems a bit unhappy."},
         {"zh": "外面好像下雨了。", "pinyin": "Wàimiàn hǎoxiàng xià yǔ le.", "en": "It seems like it's raining outside."},
         {"zh": "她的声音好像在哪儿听过。", "pinyin": "Tā de shēngyīn hǎoxiàng zài nǎr tīngguò.", "en": "Her voice sounds like I've heard it somewhere."},
     ]},
    {"name": "确实 indeed/truly", "name_zh": "确实", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'indeed / truly / really'. Used to affirm or confirm something as factual.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "这道菜确实很好吃。", "pinyin": "Zhè dào cài quèshí hěn hǎochī.", "en": "This dish is indeed delicious."},
         {"zh": "他确实说过这句话。", "pinyin": "Tā quèshí shuōguò zhè jù huà.", "en": "He truly did say this."},
         {"zh": "学中文确实不容易。", "pinyin": "Xué Zhōngwén quèshí bù róngyì.", "en": "Learning Chinese is indeed not easy."},
     ]},
    {"name": "显然 obviously (HSK4 intro)", "name_zh": "显然(HSK4)", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'obviously / clearly / evidently'. Introduces a conclusion the speaker considers self-evident.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "他显然没有准备好。", "pinyin": "Tā xiǎnrán méiyǒu zhǔnbèi hǎo.", "en": "He obviously wasn't prepared."},
         {"zh": "显然，这个方法行不通。", "pinyin": "Xiǎnrán, zhège fāngfǎ xíngbutōng.", "en": "Obviously, this method won't work."},
         {"zh": "她显然对这个话题很感兴趣。", "pinyin": "Tā xiǎnrán duì zhège huàtí hěn gǎn xìngqù.", "en": "She's obviously very interested in this topic."},
     ]},
    {"name": "不见得 not necessarily", "name_zh": "不见得", "hsk_level": 4, "category": "structure",
     "description": "Adverb meaning 'not necessarily / not likely'. Politely challenges an assumption or claim.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "贵的东西不见得好。", "pinyin": "Guì de dōngxi bújiàndé hǎo.", "en": "Expensive things are not necessarily good."},
         {"zh": "他不见得知道这件事。", "pinyin": "Tā bújiàndé zhīdào zhè jiàn shì.", "en": "He doesn't necessarily know about this."},
         {"zh": "努力不见得成功，但不努力一定不成功。", "pinyin": "Nǔlì bújiàndé chénggōng, dàn bù nǔlì yídìng bù chénggōng.", "en": "Hard work doesn't necessarily lead to success, but not working hard certainly won't."},
     ]},
    {"name": "一般 generally/usually", "name_zh": "一般", "hsk_level": 4, "category": "particle",
     "description": "Adverb/adjective meaning 'generally / usually / ordinary'. Describes typical situations or average quality.",
     "difficulty": 0.35,
     "examples": [
         {"zh": "我一般七点起床。", "pinyin": "Wǒ yìbān qī diǎn qǐchuáng.", "en": "I generally get up at seven."},
         {"zh": "一般来说，夏天比冬天热。", "pinyin": "Yìbān lái shuō, xiàtiān bǐ dōngtiān rè.", "en": "Generally speaking, summer is hotter than winter."},
         {"zh": "这家餐厅的菜一般般。", "pinyin": "Zhè jiā cāntīng de cài yìbānbān.", "en": "The food at this restaurant is so-so."},
     ]},
    {"name": "到底 after all/exactly (HSK4 full)", "name_zh": "到底(完整)", "hsk_level": 4, "category": "particle",
     "description": "Adverb used in questions meaning 'after all / exactly / on earth'. Conveys impatience or insistence on getting a clear answer.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "你到底想要什么？", "pinyin": "Nǐ dàodǐ xiǎng yào shénme?", "en": "What on earth do you want?"},
         {"zh": "到底发生了什么事？", "pinyin": "Dàodǐ fāshēng le shénme shì?", "en": "What exactly happened?"},
         {"zh": "你到底去不去？", "pinyin": "Nǐ dàodǐ qù bu qù?", "en": "Are you going or not, after all?"},
     ]},
    {"name": "究竟 after all/exactly (formal inquiry)", "name_zh": "究竟", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'after all / exactly /究竟'. More formal synonym of 到底, used in questions seeking a definitive answer.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "这件事究竟是怎么回事？", "pinyin": "Zhè jiàn shì jiūjìng shì zěnme huí shì?", "en": "What exactly is going on with this matter?"},
         {"zh": "他究竟去了哪里？", "pinyin": "Tā jiūjìng qù le nǎlǐ?", "en": "Where exactly did he go?"},
         {"zh": "究竟谁说的对？", "pinyin": "Jiūjìng shéi shuō de duì?", "en": "Who is right, after all?"},
     ]},
    {"name": "简直 simply/virtually (HSK4 intro)", "name_zh": "简直(HSK4)", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'simply / virtually / practically'. Expresses exaggeration or strong emphasis, often with surprise or disbelief.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "这简直太难了！", "pinyin": "Zhè jiǎnzhí tài nán le!", "en": "This is simply too hard!"},
         {"zh": "他简直是个天才。", "pinyin": "Tā jiǎnzhí shì ge tiāncái.", "en": "He's practically a genius."},
         {"zh": "这个消息简直让人不敢相信。", "pinyin": "Zhège xiāoxi jiǎnzhí ràng rén bù gǎn xiāngxìn.", "en": "This news is simply unbelievable."},
     ]},
    {"name": "陆续 one after another", "name_zh": "陆续", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'one after another / successively / in succession'. Describes actions happening in sequence over a period.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "客人们陆续到了。", "pinyin": "Kèrénmen lùxù dào le.", "en": "The guests arrived one after another."},
         {"zh": "学生们陆续交了作业。", "pinyin": "Xuéshēngmen lùxù jiāo le zuòyè.", "en": "The students turned in their homework one after another."},
         {"zh": "商店陆续开门了。", "pinyin": "Shāngdiàn lùxù kāimén le.", "en": "The shops opened one after another."},
     ]},
    {"name": "逐渐 gradually (HSK4 intro)", "name_zh": "逐渐(HSK4)", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'gradually / step by step'. Describes a slow, progressive change over time.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "天气逐渐变暖了。", "pinyin": "Tiānqì zhújiàn biàn nuǎn le.", "en": "The weather is gradually getting warmer."},
         {"zh": "他的中文逐渐进步了。", "pinyin": "Tā de Zhōngwén zhújiàn jìnbù le.", "en": "His Chinese has gradually improved."},
         {"zh": "城市逐渐发展起来了。", "pinyin": "Chéngshì zhújiàn fāzhǎn qǐlái le.", "en": "The city has gradually developed."},
     ]},
    {"name": "纷纷 one after another/in succession", "name_zh": "纷纷", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'one after another / in droves'. Implies many people or things doing something simultaneously or in rapid succession.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "听到消息，大家纷纷赶来。", "pinyin": "Tīngdào xiāoxi, dàjiā fēnfēn gǎnlái.", "en": "Hearing the news, everyone rushed over one after another."},
         {"zh": "树叶纷纷落下来。", "pinyin": "Shùyè fēnfēn luò xiàlái.", "en": "Leaves fell one after another."},
         {"zh": "网友们纷纷发表了意见。", "pinyin": "Wǎngyǒumen fēnfēn fābiǎo le yìjiàn.", "en": "Netizens expressed their opinions one after another."},
     ]},
    {"name": "不断 unceasingly/continuously", "name_zh": "不断", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'unceasingly / continuously / constantly'. Emphasizes that an action keeps happening without stopping.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "他不断地努力学习。", "pinyin": "Tā búduàn de nǔlì xuéxí.", "en": "He continuously studies hard."},
         {"zh": "科技在不断进步。", "pinyin": "Kējì zài búduàn jìnbù.", "en": "Technology is constantly advancing."},
         {"zh": "她不断问我同样的问题。", "pinyin": "Tā búduàn wèn wǒ tóngyàng de wèntí.", "en": "She keeps asking me the same question."},
     ]},
    {"name": "始终 from beginning to end", "name_zh": "始终", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'from beginning to end / all along / throughout'. Emphasizes consistency or persistence over time.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "他始终没有改变自己的想法。", "pinyin": "Tā shǐzhōng méiyǒu gǎibiàn zìjǐ de xiǎngfǎ.", "en": "He never changed his mind from start to finish."},
         {"zh": "她始终保持微笑。", "pinyin": "Tā shǐzhōng bǎochí wēixiào.", "en": "She maintained her smile throughout."},
         {"zh": "这个问题始终没有解决。", "pinyin": "Zhège wèntí shǐzhōng méiyǒu jiějué.", "en": "This problem has never been resolved."},
     ]},
    {"name": "即 namely/that is (formal)", "name_zh": "即", "hsk_level": 4, "category": "connector",
     "description": "Formal conjunction meaning 'namely / that is / i.e.'. Used in written language to clarify or restate.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "北京，即中国的首都。", "pinyin": "Běijīng, jí Zhōngguó de shǒudū.", "en": "Beijing, namely the capital of China."},
         {"zh": "下周一，即三月三号开始上课。", "pinyin": "Xià zhōuyī, jí sānyuè sān hào kāishǐ shàngkè.", "en": "Next Monday, that is March 3rd, classes begin."},
         {"zh": "此活动即日起开始报名。", "pinyin": "Cǐ huódòng jí rì qǐ kāishǐ bàomíng.", "en": "Registration for this event starts as of today."},
     ]},
    {"name": "将 will/shall (formal future)", "name_zh": "将", "hsk_level": 4, "category": "particle",
     "description": "Formal future marker meaning 'will / shall / be about to'. More literary than 会 or 要, common in news and formal writing.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "会议将在下周举行。", "pinyin": "Huìyì jiāng zài xià zhōu jǔxíng.", "en": "The meeting will be held next week."},
         {"zh": "他将成为一名医生。", "pinyin": "Tā jiāng chéngwéi yì míng yīshēng.", "en": "He will become a doctor."},
         {"zh": "这项政策将影响很多人。", "pinyin": "Zhè xiàng zhèngcè jiāng yǐngxiǎng hěn duō rén.", "en": "This policy will affect many people."},
     ]},
    {"name": "则 then/in that case (formal)", "name_zh": "则", "hsk_level": 4, "category": "connector",
     "description": "Formal conjunction meaning 'then / in that case / whereas'. Used in written language for contrast or conditional consequence.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "如果成功，则继续；如果失败，则重来。", "pinyin": "Rúguǒ chénggōng, zé jìxù; rúguǒ shībài, zé chónglái.", "en": "If successful, then continue; if failed, then start over."},
         {"zh": "城市热闹，乡村则安静。", "pinyin": "Chéngshì rènao, xiāngcūn zé ānjìng.", "en": "The city is lively, whereas the countryside is quiet."},
         {"zh": "学则不固。", "pinyin": "Xué zé bú gù.", "en": "If you learn, you won't be narrow-minded."},
     ]},
    {"name": "以 with/by means of (formal)", "name_zh": "以(介词)", "hsk_level": 4, "category": "structure",
     "description": "Formal preposition meaning 'with / by means of / in order to'. Classical-style function word still common in modern formal writing.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "以事实为依据。", "pinyin": "Yǐ shìshí wéi yījù.", "en": "Based on facts as evidence."},
         {"zh": "以质量取胜。", "pinyin": "Yǐ zhìliàng qǔshèng.", "en": "Win by means of quality."},
         {"zh": "他以优异的成绩毕业了。", "pinyin": "Tā yǐ yōuyì de chéngjì bìyè le.", "en": "He graduated with excellent grades."},
     ]},
    {"name": "为 for/in order to (formal purpose)", "name_zh": "为(目的)", "hsk_level": 4, "category": "structure",
     "description": "Formal preposition meaning 'for / in order to / for the sake of'. Used in written contexts to express purpose or beneficiary.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "为人民服务。", "pinyin": "Wèi rénmín fúwù.", "en": "Serve the people."},
         {"zh": "他为公司做出了很大贡献。", "pinyin": "Tā wèi gōngsī zuòchū le hěn dà gòngxiàn.", "en": "He made a great contribution to the company."},
         {"zh": "为了安全，请系好安全带。", "pinyin": "Wèile ānquán, qǐng jì hǎo ānquándài.", "en": "For safety, please fasten your seatbelt."},
     ]},
    {"name": "嘛 particle for obvious reasons", "name_zh": "嘛", "hsk_level": 4, "category": "particle",
     "description": "Sentence-final particle indicating that something should be obvious or self-evident. Conveys a 'well, of course' tone.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "孩子嘛，总是好动的。", "pinyin": "Háizi ma, zǒngshì hàodòng de.", "en": "Kids, well, they're always active."},
         {"zh": "学习嘛，当然要努力。", "pinyin": "Xuéxí ma, dāngrán yào nǔlì.", "en": "As for studying, of course you have to work hard."},
         {"zh": "大家都是朋友嘛，不用那么客气。", "pinyin": "Dàjiā dōu shì péngyou ma, búyòng nàme kèqi.", "en": "We're all friends, no need to be so polite."},
     ]},
    {"name": "来着 particle for recent past", "name_zh": "来着", "hsk_level": 4, "category": "particle",
     "description": "Sentence-final particle used to recall something from the recent past. Often used when trying to remember or confirm what just happened.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "他叫什么来着？", "pinyin": "Tā jiào shénme láizhe?", "en": "What was his name again?"},
         {"zh": "我刚才想说什么来着？", "pinyin": "Wǒ gāngcái xiǎng shuō shénme láizhe?", "en": "What was I going to say just now?"},
         {"zh": "那本书放在哪儿来着？", "pinyin": "Nà běn shū fàng zài nǎr láizhe?", "en": "Where did I put that book again?"},
     ]},
    {"name": "着呢 very much/quite (emphasis)", "name_zh": "着呢", "hsk_level": 4, "category": "particle",
     "description": "Sentence-final particle meaning 'very much / quite'. Adds emphasis, often with a colloquial or reassuring tone.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "他聪明着呢！", "pinyin": "Tā cōngming zhe ne!", "en": "He's quite clever!"},
         {"zh": "外面冷着呢，多穿点。", "pinyin": "Wàimiàn lěng zhe ne, duō chuān diǎn.", "en": "It's really cold outside, wear more."},
         {"zh": "时间早着呢，不急。", "pinyin": "Shíjiān zǎo zhe ne, bù jí.", "en": "It's still quite early, no rush."},
     ]},
    {"name": "似的 like/as if (suffix)", "name_zh": "似的", "hsk_level": 4, "category": "structure",
     "description": "Suffix meaning 'like / as if / as though'. Attached after nouns, verbs, or clauses to form similes.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "他跑得飞似的。", "pinyin": "Tā pǎo de fēi shìde.", "en": "He ran as if flying."},
         {"zh": "她高兴得什么似的。", "pinyin": "Tā gāoxìng de shénme shìde.", "en": "She was happy beyond words."},
         {"zh": "外面热得火炉似的。", "pinyin": "Wàimiàn rè de huǒlú shìde.", "en": "It's hot outside, like a furnace."},
     ]},
    {"name": "的确 indeed/truly (affirmation)", "name_zh": "的确", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'indeed / truly / really'. Used to emphatically confirm a fact. Slightly more formal than 确实.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "他的确很努力。", "pinyin": "Tā díquè hěn nǔlì.", "en": "He is indeed very hardworking."},
         {"zh": "这个地方的确很美。", "pinyin": "Zhège dìfang díquè hěn měi.", "en": "This place is truly beautiful."},
         {"zh": "这件事的确是我做错了。", "pinyin": "Zhè jiàn shì díquè shì wǒ zuò cuò le.", "en": "This matter — I indeed made a mistake."},
     ]},
    {"name": "不然 otherwise/or else", "name_zh": "不然", "hsk_level": 4, "category": "connector",
     "description": "Conjunction meaning 'otherwise / or else / if not'. Used to introduce the consequence of not doing something.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "快走吧，不然要迟到了。", "pinyin": "Kuài zǒu ba, bùrán yào chídào le.", "en": "Let's go quickly, otherwise we'll be late."},
         {"zh": "你得多练习，不然考试过不了。", "pinyin": "Nǐ děi duō liànxí, bùrán kǎoshì guòbuliǎo.", "en": "You need to practice more, or else you won't pass the exam."},
         {"zh": "带把伞吧，不然会淋雨的。", "pinyin": "Dài bǎ sǎn ba, bùrán huì lín yǔ de.", "en": "Bring an umbrella, otherwise you'll get rained on."},
     ]},
    {"name": "从来 always/all along (with negation)", "name_zh": "从来", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'always / never' (typically used with negation as 从来不/没). Emphasizes that something has never happened or always been the case.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "他从来不迟到。", "pinyin": "Tā cónglái bù chídào.", "en": "He never arrives late."},
         {"zh": "我从来没去过日本。", "pinyin": "Wǒ cónglái méi qùguò Rìběn.", "en": "I have never been to Japan."},
         {"zh": "她从来都是自己做饭。", "pinyin": "Tā cónglái dōu shì zìjǐ zuòfàn.", "en": "She has always cooked for herself."},
     ]},
    {"name": "V+成 result complement become", "name_zh": "动词+成", "hsk_level": 4, "category": "complement",
     "description": "Result complement where 成 after a verb indicates the result 'become / into / as'. Shows transformation or achievement of a goal.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "请把这篇文章翻译成英文。", "pinyin": "Qǐng bǎ zhè piān wénzhāng fānyì chéng Yīngwén.", "en": "Please translate this article into English."},
         {"zh": "他把房间改成了书房。", "pinyin": "Tā bǎ fángjiān gǎi chéng le shūfáng.", "en": "He converted the room into a study."},
         {"zh": "我把你当成了别人。", "pinyin": "Wǒ bǎ nǐ dàng chéng le biérén.", "en": "I mistook you for someone else."},
     ]},
    {"name": "V+掉 result complement off/away", "name_zh": "动词+掉", "hsk_level": 4, "category": "complement",
     "description": "Result complement where 掉 after a verb means 'off / away / gone'. Indicates removal, loss, or completion.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "把这些旧衣服扔掉吧。", "pinyin": "Bǎ zhèxiē jiù yīfu rēngdiào ba.", "en": "Throw away these old clothes."},
         {"zh": "他把密码忘掉了。", "pinyin": "Tā bǎ mìmǎ wàngdiào le.", "en": "He forgot the password."},
         {"zh": "请把灯关掉。", "pinyin": "Qǐng bǎ dēng guāndiào.", "en": "Please turn off the light."},
     ]},
    {"name": "被 passive without agent", "name_zh": "被(无施事)", "hsk_level": 4, "category": "structure",
     "description": "Passive construction using 被 without specifying the agent. Common in formal writing and news, focusing on the action received.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "他被录取了。", "pinyin": "Tā bèi lùqǔ le.", "en": "He was admitted."},
         {"zh": "这个计划被取消了。", "pinyin": "Zhège jìhuà bèi qǔxiāo le.", "en": "This plan was cancelled."},
         {"zh": "问题已经被解决了。", "pinyin": "Wèntí yǐjīng bèi jiějué le.", "en": "The problem has already been solved."},
     ]},
    {"name": "所+V(的)+N nominalization", "name_zh": "所+动词+的+名词", "hsk_level": 4, "category": "structure",
     "description": "Classical nominalization pattern where 所 before a verb turns the verb phrase into a noun modifier. Creates formal, literary expressions.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "这不是我所期望的结果。", "pinyin": "Zhè bú shì wǒ suǒ qīwàng de jiéguǒ.", "en": "This is not the result I expected."},
         {"zh": "他所说的话很有道理。", "pinyin": "Tā suǒ shuō de huà hěn yǒu dàolǐ.", "en": "What he said makes a lot of sense."},
         {"zh": "我所知道的就这些。", "pinyin": "Wǒ suǒ zhīdào de jiù zhèxiē.", "en": "This is all that I know."},
     ]},
    {"name": "V+过来/过去 compound directional", "name_zh": "动词+过来/过去", "hsk_level": 4, "category": "complement",
     "description": "Compound directional complement where 过来 (towards speaker) and 过去 (away from speaker) follow a verb. Also used figuratively for recovery or loss.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "他走过来跟我说话。", "pinyin": "Tā zǒu guòlái gēn wǒ shuōhuà.", "en": "He walked over and talked to me."},
         {"zh": "她终于醒过来了。", "pinyin": "Tā zhōngyú xǐng guòlái le.", "en": "She finally woke up."},
         {"zh": "把球踢过去！", "pinyin": "Bǎ qiú tī guòqù!", "en": "Kick the ball over there!"},
     ]},
    {"name": "之一 one of", "name_zh": "之一", "hsk_level": 4, "category": "structure",
     "description": "Phrase meaning 'one of'. Placed after the noun group to indicate membership in a set. Slightly formal.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "北京是世界上最大的城市之一。", "pinyin": "Běijīng shì shìjiè shang zuì dà de chéngshì zhī yī.", "en": "Beijing is one of the largest cities in the world."},
         {"zh": "他是我最好的朋友之一。", "pinyin": "Tā shì wǒ zuì hǎo de péngyou zhī yī.", "en": "He is one of my best friends."},
         {"zh": "这是中国最有名的景点之一。", "pinyin": "Zhè shì Zhōngguó zuì yǒumíng de jǐngdiǎn zhī yī.", "en": "This is one of China's most famous scenic spots."},
     ]},
    {"name": "以来 since (temporal)", "name_zh": "以来", "hsk_level": 4, "category": "structure",
     "description": "Temporal suffix meaning 'since / ever since'. Attached after a time expression to indicate a period from then until now.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "开学以来，他一直很用功。", "pinyin": "Kāixué yǐlái, tā yìzhí hěn yònggōng.", "en": "Since school started, he has been very diligent."},
         {"zh": "三年以来，这个城市变化很大。", "pinyin": "Sān nián yǐlái, zhège chéngshì biànhuà hěn dà.", "en": "In the past three years, this city has changed a lot."},
         {"zh": "自从他来以来，工作效率提高了。", "pinyin": "Zìcóng tā lái yǐlái, gōngzuò xiàolǜ tígāo le.", "en": "Since he arrived, work efficiency has improved."},
     ]},
    {"name": "多亏 thanks to/lucky that", "name_zh": "多亏", "hsk_level": 4, "category": "structure",
     "description": "Adverb meaning 'thanks to / fortunately / lucky that'. Attributes a positive outcome to someone or something.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "多亏你提醒我，我才没忘。", "pinyin": "Duōkuī nǐ tíxǐng wǒ, wǒ cái méi wàng.", "en": "Thanks to your reminder, I didn't forget."},
         {"zh": "多亏天气好，我们玩得很开心。", "pinyin": "Duōkuī tiānqì hǎo, wǒmen wán de hěn kāixīn.", "en": "Fortunately the weather was good, so we had a great time."},
         {"zh": "多亏有他的帮助，项目才能完成。", "pinyin": "Duōkuī yǒu tā de bāngzhù, xiàngmù cái néng wánchéng.", "en": "Thanks to his help, the project could be completed."},
     ]},
    {"name": "难道...吗 full rhetorical question", "name_zh": "难道…吗", "hsk_level": 4, "category": "structure",
     "description": "Full rhetorical question pattern using 难道 at the start and 吗 at the end. Expresses strong disbelief or challenges an assumption.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "难道你不知道吗？", "pinyin": "Nándào nǐ bù zhīdào ma?", "en": "Don't you know? (rhetorical)"},
         {"zh": "难道这是我的错吗？", "pinyin": "Nándào zhè shì wǒ de cuò ma?", "en": "Is this really my fault? (implying it isn't)"},
         {"zh": "难道他连这么简单的事都做不好吗？", "pinyin": "Nándào tā lián zhème jiǎndān de shì dōu zuò bù hǎo ma?", "en": "Can he really not even do something this simple?"},
     ]},
    {"name": "要是...就 if...then (HSK4 colloquial)", "name_zh": "要是…就", "hsk_level": 4, "category": "connector",
     "description": "Colloquial conditional meaning 'if...then'. More casual than 如果...就, common in everyday speech.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "要是你有空，就来我家吧。", "pinyin": "Yàoshi nǐ yǒu kòng, jiù lái wǒ jiā ba.", "en": "If you're free, come to my place."},
         {"zh": "要是下雨，我们就不出去了。", "pinyin": "Yàoshi xià yǔ, wǒmen jiù bù chūqù le.", "en": "If it rains, we won't go out."},
         {"zh": "要是早知道，我就不去了。", "pinyin": "Yàoshi zǎo zhīdào, wǒ jiù bú qù le.", "en": "If I had known earlier, I wouldn't have gone."},
     ]},
    {"name": "千万 by all means/definitely (HSK4 emphasis)", "name_zh": "千万", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'by all means / definitely / whatever you do'. Used for emphatic advice or warning, often with 别 or 要.",
     "difficulty": 0.4,
     "examples": [
         {"zh": "千万别忘了带护照。", "pinyin": "Qiānwàn bié wàng le dài hùzhào.", "en": "Whatever you do, don't forget to bring your passport."},
         {"zh": "千万要小心！", "pinyin": "Qiānwàn yào xiǎoxīn!", "en": "Be careful no matter what!"},
         {"zh": "这件事千万不能告诉他。", "pinyin": "Zhè jiàn shì qiānwàn bù néng gàosu tā.", "en": "You absolutely must not tell him about this."},
     ]},
    {"name": "往往 often/tend to (HSK4 pattern)", "name_zh": "往往", "hsk_level": 4, "category": "particle",
     "description": "Adverb meaning 'often / tend to / usually'. Describes a recurring pattern or tendency based on observation, not a specific instance.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "成功的人往往很自律。", "pinyin": "Chénggōng de rén wǎngwǎng hěn zìlǜ.", "en": "Successful people tend to be very self-disciplined."},
         {"zh": "好的开始往往是成功的一半。", "pinyin": "Hǎo de kāishǐ wǎngwǎng shì chénggōng de yí bàn.", "en": "A good start is often half the battle."},
         {"zh": "简单的事情往往被忽略。", "pinyin": "Jiǎndān de shìqing wǎngwǎng bèi hūlüè.", "en": "Simple things tend to be overlooked."},
     ]},

    # =========================================================================
    # HSK 5 — additional grammar points
    # =========================================================================
    {"name": "加以 to give/apply (formal action)", "name_zh": "加以", "hsk_level": 5, "category": "structure",
     "description": "Formal verb meaning 'to give / to apply / to carry out'. Used before disyllabic verbs to formalize the action, common in official writing.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "这个问题需要加以解决。", "pinyin": "Zhège wèntí xūyào jiāyǐ jiějué.", "en": "This problem needs to be resolved."},
         {"zh": "对不同情况要加以区分。", "pinyin": "Duì bùtóng qíngkuàng yào jiāyǐ qūfēn.", "en": "Different situations must be distinguished."},
         {"zh": "政府将对此加以改善。", "pinyin": "Zhèngfǔ jiāng duì cǐ jiāyǐ gǎishàn.", "en": "The government will improve this."},
     ]},
    {"name": "予以 to give/grant (formal)", "name_zh": "予以", "hsk_level": 5, "category": "structure",
     "description": "Formal verb meaning 'to give / to grant / to accord'. Used in official or written contexts before a disyllabic action noun.",
     "difficulty": 0.7,
     "examples": [
         {"zh": "对违规者将予以处罚。", "pinyin": "Duì wéiguī zhě jiāng yǔyǐ chǔfá.", "en": "Violators will be penalized."},
         {"zh": "请予以支持和配合。", "pinyin": "Qǐng yǔyǐ zhīchí hé pèihé.", "en": "Please give your support and cooperation."},
         {"zh": "学校对优秀学生予以奖励。", "pinyin": "Xuéxiào duì yōuxiù xuéshēng yǔyǐ jiǎnglì.", "en": "The school rewards outstanding students."},
     ]},
    {"name": "得以 to be able to (formal enablement)", "name_zh": "得以", "hsk_level": 5, "category": "structure",
     "description": "Formal verb meaning 'to be able to / to be enabled to'. Indicates that conditions have been met for something to happen.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "问题终于得以解决。", "pinyin": "Wèntí zhōngyú déyǐ jiějué.", "en": "The problem was finally able to be resolved."},
         {"zh": "他的才能得以充分发挥。", "pinyin": "Tā de cáinéng déyǐ chōngfèn fāhuī.", "en": "His talents were able to be fully utilized."},
         {"zh": "传统文化得以传承。", "pinyin": "Chuántǒng wénhuà déyǐ chuánchéng.", "en": "Traditional culture was able to be passed down."},
     ]},
    {"name": "善于 to be good at", "name_zh": "善于", "hsk_level": 5, "category": "structure",
     "description": "Verb meaning 'to be good at / to be skilled in'. More formal than 擅长, used to describe innate or developed abilities.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "她善于与人沟通。", "pinyin": "Tā shànyú yǔ rén gōutōng.", "en": "She is good at communicating with people."},
         {"zh": "他善于发现问题。", "pinyin": "Tā shànyú fāxiàn wèntí.", "en": "He is good at spotting problems."},
         {"zh": "善于学习的人进步快。", "pinyin": "Shànyú xuéxí de rén jìnbù kuài.", "en": "People who are good at learning progress quickly."},
     ]},
    {"name": "勇于 to have courage to", "name_zh": "勇于", "hsk_level": 5, "category": "structure",
     "description": "Verb meaning 'to have the courage to / to be brave enough to'. Praises willingness to face difficulty.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "他勇于承认自己的错误。", "pinyin": "Tā yǒngyú chéngrèn zìjǐ de cuòwù.", "en": "He has the courage to admit his mistakes."},
         {"zh": "我们要勇于尝试新事物。", "pinyin": "Wǒmen yào yǒngyú chángshì xīn shìwù.", "en": "We should be brave enough to try new things."},
         {"zh": "勇于面对困难才能成功。", "pinyin": "Yǒngyú miànduì kùnnan cái néng chénggōng.", "en": "Only by bravely facing difficulties can one succeed."},
     ]},
    {"name": "敢于 to dare to", "name_zh": "敢于", "hsk_level": 5, "category": "structure",
     "description": "Verb meaning 'to dare to / to have the guts to'. More formal than 敢, emphasizes boldness in the face of risk.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "他敢于说出真话。", "pinyin": "Tā gǎnyú shuōchū zhēnhuà.", "en": "He dares to speak the truth."},
         {"zh": "要敢于挑战自己。", "pinyin": "Yào gǎnyú tiǎozhàn zìjǐ.", "en": "You must dare to challenge yourself."},
         {"zh": "她敢于打破传统。", "pinyin": "Tā gǎnyú dǎpò chuántǒng.", "en": "She dares to break with tradition."},
     ]},
    {"name": "乐于 to be willing/happy to", "name_zh": "乐于", "hsk_level": 5, "category": "structure",
     "description": "Verb meaning 'to be willing to / to be happy to / to delight in'. Expresses cheerful willingness.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "她乐于助人。", "pinyin": "Tā lèyú zhùrén.", "en": "She is happy to help others."},
         {"zh": "他乐于接受新挑战。", "pinyin": "Tā lèyú jiēshòu xīn tiǎozhàn.", "en": "He is willing to take on new challenges."},
         {"zh": "年轻人应该乐于学习。", "pinyin": "Niánqīng rén yīnggāi lèyú xuéxí.", "en": "Young people should be eager to learn."},
     ]},
    {"name": "忙于 to be busy with", "name_zh": "忙于", "hsk_level": 5, "category": "structure",
     "description": "Verb meaning 'to be busy with / to be occupied with'. Formal way to express being engaged in an activity.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "他忙于工作，没时间休息。", "pinyin": "Tā mángyú gōngzuò, méi shíjiān xiūxi.", "en": "He is busy with work and has no time to rest."},
         {"zh": "大家都忙于准备考试。", "pinyin": "Dàjiā dōu mángyú zhǔnbèi kǎoshì.", "en": "Everyone is busy preparing for the exam."},
         {"zh": "她忙于照顾孩子。", "pinyin": "Tā mángyú zhàogù háizi.", "en": "She is busy taking care of the children."},
     ]},
    {"name": "致使 to cause/result in (formal)", "name_zh": "致使", "hsk_level": 5, "category": "connector",
     "description": "Formal verb meaning 'to cause / to result in'. Indicates that something led to a (usually negative) consequence.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "暴雨致使道路被淹。", "pinyin": "Bàoyǔ zhìshǐ dàolù bèi yān.", "en": "The heavy rain caused the roads to be flooded."},
         {"zh": "他的疏忽致使公司损失很大。", "pinyin": "Tā de shūhu zhìshǐ gōngsī sǔnshī hěn dà.", "en": "His negligence caused the company great losses."},
         {"zh": "交通事故致使三人受伤。", "pinyin": "Jiāotōng shìgù zhìshǐ sān rén shòushāng.", "en": "The traffic accident caused three people to be injured."},
     ]},
    {"name": "导致 to lead to/cause", "name_zh": "导致", "hsk_level": 5, "category": "connector",
     "description": "Verb meaning 'to lead to / to cause / to result in'. Common in both spoken and written language for cause-effect relationships.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "吸烟可能导致癌症。", "pinyin": "Xīyān kěnéng dǎozhì áizhèng.", "en": "Smoking may lead to cancer."},
         {"zh": "交通堵塞导致我迟到了。", "pinyin": "Jiāotōng dǔsè dǎozhì wǒ chídào le.", "en": "The traffic jam caused me to be late."},
         {"zh": "缺乏运动导致身体变差。", "pinyin": "Quēfá yùndòng dǎozhì shēntǐ biàn chà.", "en": "Lack of exercise leads to declining health."},
     ]},
    {"name": "促使 to urge/prompt", "name_zh": "促使", "hsk_level": 5, "category": "connector",
     "description": "Verb meaning 'to urge / to prompt / to impel'. Indicates a cause that pushes someone toward an action or decision.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "竞争促使他更加努力。", "pinyin": "Jìngzhēng cùshǐ tā gèngjiā nǔlì.", "en": "Competition prompted him to work even harder."},
         {"zh": "这件事促使我改变了想法。", "pinyin": "Zhè jiàn shì cùshǐ wǒ gǎibiàn le xiǎngfǎ.", "en": "This matter prompted me to change my mind."},
         {"zh": "经济发展促使城市快速扩张。", "pinyin": "Jīngjì fāzhǎn cùshǐ chéngshì kuàisù kuòzhāng.", "en": "Economic development has prompted rapid urban expansion."},
     ]},
    {"name": "迫使 to force/compel", "name_zh": "迫使", "hsk_level": 5, "category": "connector",
     "description": "Verb meaning 'to force / to compel / to coerce'. Stronger than 促使; implies the subject had no choice.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "恶劣的天气迫使航班取消。", "pinyin": "Èliè de tiānqì pòshǐ hángbān qǔxiāo.", "en": "Severe weather forced the flights to be cancelled."},
         {"zh": "经济压力迫使他换了工作。", "pinyin": "Jīngjì yālì pòshǐ tā huàn le gōngzuò.", "en": "Economic pressure forced him to change jobs."},
         {"zh": "伤病迫使她退出了比赛。", "pinyin": "Shāngbìng pòshǐ tā tuìchū le bǐsài.", "en": "Injury forced her to withdraw from the competition."},
     ]},
    {"name": "以...为主 primarily/mainly", "name_zh": "以…为主", "hsk_level": 5, "category": "structure",
     "description": "Pattern meaning 'primarily / mainly / with X as the main focus'. Used to indicate the dominant element.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "这个地区以农业为主。", "pinyin": "Zhège dìqū yǐ nóngyè wéi zhǔ.", "en": "This region is primarily agricultural."},
         {"zh": "我们的饮食以米饭为主。", "pinyin": "Wǒmen de yǐnshí yǐ mǐfàn wéi zhǔ.", "en": "Our diet is mainly rice-based."},
         {"zh": "这次考试以听力为主。", "pinyin": "Zhè cì kǎoshì yǐ tīnglì wéi zhǔ.", "en": "This exam focuses primarily on listening."},
     ]},
    {"name": "以...为基础 based on", "name_zh": "以…为基础", "hsk_level": 5, "category": "structure",
     "description": "Pattern meaning 'based on / with X as the foundation'. Used to identify the basis or foundation of something.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "这个理论以实验为基础。", "pinyin": "Zhège lǐlùn yǐ shíyàn wéi jīchǔ.", "en": "This theory is based on experiments."},
         {"zh": "以事实为基础做出判断。", "pinyin": "Yǐ shìshí wéi jīchǔ zuòchū pànduàn.", "en": "Make judgments based on facts."},
         {"zh": "我们的合作以互信为基础。", "pinyin": "Wǒmen de hézuò yǐ hùxìn wéi jīchǔ.", "en": "Our cooperation is based on mutual trust."},
     ]},
    {"name": "以...为目的 with the purpose of", "name_zh": "以…为目的", "hsk_level": 5, "category": "structure",
     "description": "Pattern meaning 'with the purpose of / aiming at'. Used to state the objective or goal explicitly.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "以提高效率为目的进行改革。", "pinyin": "Yǐ tígāo xiàolǜ wéi mùdì jìnxíng gǎigé.", "en": "Carry out reforms with the purpose of improving efficiency."},
         {"zh": "他以学习中文为目的来到中国。", "pinyin": "Tā yǐ xuéxí Zhōngwén wéi mùdì láidào Zhōngguó.", "en": "He came to China with the purpose of learning Chinese."},
         {"zh": "这个活动以促进交流为目的。", "pinyin": "Zhège huódòng yǐ cùjìn jiāoliú wéi mùdì.", "en": "This activity aims to promote exchange."},
     ]},
    {"name": "就是...也 even if...still (emphatic)", "name_zh": "就是…也", "hsk_level": 5, "category": "connector",
     "description": "Emphatic concessive meaning 'even if...still'. Stronger and more colloquial than 即使...也.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "就是再忙，也要吃饭。", "pinyin": "Jiùshì zài máng, yě yào chīfàn.", "en": "Even if you're busier, you still need to eat."},
         {"zh": "就是他不来，我们也要继续。", "pinyin": "Jiùshì tā bù lái, wǒmen yě yào jìxù.", "en": "Even if he doesn't come, we still need to continue."},
         {"zh": "就是下大雨，比赛也不会取消。", "pinyin": "Jiùshì xià dà yǔ, bǐsài yě bú huì qǔxiāo.", "en": "Even if it pours, the match won't be cancelled."},
     ]},
    {"name": "再...也 no matter how...still", "name_zh": "再…也", "hsk_level": 5, "category": "connector",
     "description": "Concessive pattern meaning 'no matter how much...still'. Emphasizes that an extreme degree doesn't change the outcome.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "再难也要坚持。", "pinyin": "Zài nán yě yào jiānchí.", "en": "No matter how hard, you must persist."},
         {"zh": "再贵我也要买。", "pinyin": "Zài guì wǒ yě yào mǎi.", "en": "No matter how expensive, I'll still buy it."},
         {"zh": "再怎么说，他也是你的父亲。", "pinyin": "Zài zěnme shuō, tā yě shì nǐ de fùqin.", "en": "No matter what you say, he is still your father."},
     ]},
    {"name": "别说...就是 let alone...even", "name_zh": "别说…就是", "hsk_level": 5, "category": "connector",
     "description": "Escalating pattern meaning 'let alone X, even Y'. States that if Y (the easier/lesser case) can't happen, X (the harder case) certainly can't.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "别说跑步了，就是走路他都走不动。", "pinyin": "Bié shuō pǎobù le, jiùshì zǒulù tā dōu zǒubudòng.", "en": "Let alone running, he can't even walk."},
         {"zh": "别说买房子了，就是租房子都很贵。", "pinyin": "Bié shuō mǎi fángzi le, jiùshì zū fángzi dōu hěn guì.", "en": "Let alone buying a house, even renting is expensive."},
         {"zh": "别说一百块，就是十块钱我也没有。", "pinyin": "Bié shuō yì bǎi kuài, jiùshì shí kuài qián wǒ yě méiyǒu.", "en": "Let alone a hundred yuan, I don't even have ten."},
     ]},
    {"name": "不免 inevitably (HSK5 intro)", "name_zh": "不免(HSK5)", "hsk_level": 5, "category": "particle",
     "description": "Adverb meaning 'inevitably / unavoidably'. Indicates a natural or expected consequence that cannot be helped.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "第一次做，不免会犯错。", "pinyin": "Dì yī cì zuò, bùmiǎn huì fàncuò.", "en": "Doing it for the first time, mistakes are inevitable."},
         {"zh": "一个人在国外，不免会想家。", "pinyin": "Yí ge rén zài guówài, bùmiǎn huì xiǎng jiā.", "en": "Being abroad alone, one inevitably feels homesick."},
         {"zh": "听到这个消息，不免有些失望。", "pinyin": "Tīngdào zhège xiāoxi, bùmiǎn yǒuxiē shīwàng.", "en": "Hearing this news, one can't help feeling somewhat disappointed."},
     ]},
    {"name": "可不 isn't that so", "name_zh": "可不", "hsk_level": 5, "category": "particle",
     "description": "Colloquial expression meaning 'isn't that so / you bet / exactly'. Used to strongly agree with what someone just said.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "今天真热啊。可不是嘛！", "pinyin": "Jīntiān zhēn rè a. Kěbushì ma!", "en": "It's really hot today. You bet it is!"},
         {"zh": "可不，我也是这么想的。", "pinyin": "Kěbù, wǒ yě shì zhème xiǎng de.", "en": "Exactly, I think so too."},
         {"zh": "这孩子真聪明。可不！", "pinyin": "Zhè háizi zhēn cōngming. Kěbù!", "en": "This kid is really smart. Isn't that the truth!"},
     ]},
    {"name": "所谓 so-called (HSK5 intro)", "name_zh": "所谓(HSK5)", "hsk_level": 5, "category": "structure",
     "description": "Adjective meaning 'so-called / what is known as'. Can be neutral (defining a term) or dismissive (questioning legitimacy).",
     "difficulty": 0.55,
     "examples": [
         {"zh": "所谓的专家其实什么都不懂。", "pinyin": "Suǒwèi de zhuānjiā qíshí shénme dōu bù dǒng.", "en": "The so-called experts actually know nothing."},
         {"zh": "所谓入乡随俗，就是要尊重当地文化。", "pinyin": "Suǒwèi rù xiāng suí sú, jiùshì yào zūnzhòng dāngdì wénhuà.", "en": "What's called 'when in Rome do as the Romans' means respecting local culture."},
         {"zh": "这就是所谓的幸福吧。", "pinyin": "Zhè jiùshì suǒwèi de xìngfú ba.", "en": "This is what they call happiness, I suppose."},
     ]},
    {"name": "不惜 not hesitate to (HSK5 intro)", "name_zh": "不惜(HSK5)", "hsk_level": 5, "category": "structure",
     "description": "Verb meaning 'not hesitate to / at the cost of / spare no'. Shows willingness to pay a high price for something.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "为了孩子，她不惜一切代价。", "pinyin": "Wèile háizi, tā bùxī yíqiè dàijià.", "en": "For her children, she spares no cost."},
         {"zh": "他不惜花大量时间来准备。", "pinyin": "Tā bùxī huā dàliàng shíjiān lái zhǔnbèi.", "en": "He didn't hesitate to spend a lot of time preparing."},
         {"zh": "公司不惜重金聘请了专家。", "pinyin": "Gōngsī bùxī zhòngjīn pìnqǐng le zhuānjiā.", "en": "The company spared no expense to hire experts."},
     ]},
    {"name": "不失为 can be considered (HSK5 intro)", "name_zh": "不失为(HSK5)", "hsk_level": 5, "category": "structure",
     "description": "Phrase meaning 'can be considered / is not a bad'. A moderate, measured way to recommend or evaluate something positively.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "这不失为一个好办法。", "pinyin": "Zhè bùshīwéi yí ge hǎo bànfǎ.", "en": "This can be considered a good approach."},
         {"zh": "坐火车旅行不失为一种享受。", "pinyin": "Zuò huǒchē lǚxíng bùshīwéi yì zhǒng xiǎngshòu.", "en": "Traveling by train can be considered a pleasure."},
         {"zh": "在家做饭不失为省钱的好方法。", "pinyin": "Zài jiā zuòfàn bùshīwéi shěng qián de hǎo fāngfǎ.", "en": "Cooking at home is a decent way to save money."},
     ]},
    {"name": "诸如 such as (formal enumeration)", "name_zh": "诸如", "hsk_level": 5, "category": "connector",
     "description": "Formal phrase meaning 'such as / for example'. Used to introduce examples in written or formal contexts.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "诸如此类的问题还有很多。", "pinyin": "Zhūrú cǐ lèi de wèntí hái yǒu hěn duō.", "en": "There are many more problems of this kind."},
         {"zh": "大城市诸如北京、上海发展很快。", "pinyin": "Dà chéngshì zhūrú Běijīng, Shànghǎi fāzhǎn hěn kuài.", "en": "Big cities such as Beijing and Shanghai are developing rapidly."},
         {"zh": "他学过很多语言，诸如英语、法语和德语。", "pinyin": "Tā xuéguò hěn duō yǔyán, zhūrú Yīngyǔ, Fǎyǔ hé Déyǔ.", "en": "He has studied many languages, such as English, French, and German."},
     ]},
    {"name": "凡是 every/all without exception", "name_zh": "凡是", "hsk_level": 5, "category": "structure",
     "description": "Determiner meaning 'every / all / whoever/whatever'. Emphasizes universality — no exceptions.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "凡是迟到的人都要罚款。", "pinyin": "Fánshì chídào de rén dōu yào fákuǎn.", "en": "Everyone who is late will be fined, without exception."},
         {"zh": "凡是他做的菜都很好吃。", "pinyin": "Fánshì tā zuò de cài dōu hěn hǎochī.", "en": "Every dish he makes is delicious."},
         {"zh": "凡是参加活动的人都能获得奖品。", "pinyin": "Fánshì cānjiā huódòng de rén dōu néng huòdé jiǎngpǐn.", "en": "Everyone who participates in the event can receive a prize."},
     ]},
    {"name": "以来 since (HSK5 temporal)", "name_zh": "以来(HSK5)", "hsk_level": 5, "category": "structure",
     "description": "Temporal suffix meaning 'since / ever since'. At HSK5 level, used in more complex and formal time expressions.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "改革开放以来，中国发生了巨大变化。", "pinyin": "Gǎigé kāifàng yǐlái, Zhōngguó fāshēng le jùdà biànhuà.", "en": "Since reform and opening up, China has undergone tremendous changes."},
         {"zh": "有史以来最大的一次地震。", "pinyin": "Yǒu shǐ yǐlái zuì dà de yí cì dìzhèn.", "en": "The largest earthquake in recorded history."},
         {"zh": "自古以来，人们就崇拜太阳。", "pinyin": "Zì gǔ yǐlái, rénmen jiù chóngbài tàiyáng.", "en": "Since ancient times, people have worshipped the sun."},
     ]},
    {"name": "之际 at the time of (formal)", "name_zh": "之际(HSK5)", "hsk_level": 5, "category": "structure",
     "description": "Formal temporal phrase meaning 'at the time of / on the occasion of'. Used in written or ceremonial contexts.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "在春节来临之际，祝大家新年快乐。", "pinyin": "Zài Chūnjié láilín zhī jì, zhù dàjiā xīnnián kuàilè.", "en": "On the occasion of Spring Festival, I wish everyone a happy new year."},
         {"zh": "毕业之际，我感慨万千。", "pinyin": "Bìyè zhī jì, wǒ gǎnkǎi wànqiān.", "en": "At the time of graduation, I'm filled with emotions."},
         {"zh": "在他离开之际，大家都来送行。", "pinyin": "Zài tā líkāi zhī jì, dàjiā dōu lái sòngxíng.", "en": "At the time of his departure, everyone came to see him off."},
     ]},
    {"name": "不时 from time to time", "name_zh": "不时", "hsk_level": 5, "category": "particle",
     "description": "Adverb meaning 'from time to time / now and then / occasionally'. Describes intermittent recurrence.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "她不时地看看手表。", "pinyin": "Tā bùshí de kànkan shǒubiǎo.", "en": "She glanced at her watch from time to time."},
         {"zh": "远处不时传来鸟叫声。", "pinyin": "Yuǎnchù bùshí chuánlái niǎo jiào shēng.", "en": "Birdsong could be heard from afar now and then."},
         {"zh": "他不时会想起小时候的事。", "pinyin": "Tā bùshí huì xiǎngqǐ xiǎoshíhou de shì.", "en": "He thinks of childhood events from time to time."},
     ]},
    {"name": "日益 increasingly/day by day", "name_zh": "日益", "hsk_level": 5, "category": "particle",
     "description": "Adverb meaning 'increasingly / day by day / more and more'. Formal alternative to 越来越, used in written language.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "环境污染问题日益严重。", "pinyin": "Huánjìng wūrǎn wèntí rìyì yánzhòng.", "en": "Environmental pollution is becoming increasingly serious."},
         {"zh": "两国关系日益密切。", "pinyin": "Liǎng guó guānxi rìyì mìqiè.", "en": "Relations between the two countries are growing closer day by day."},
         {"zh": "人们对健康日益重视。", "pinyin": "Rénmen duì jiànkāng rìyì zhòngshì.", "en": "People are paying increasing attention to health."},
     ]},
    {"name": "与其...不如 rather than...better to (HSK5 full)", "name_zh": "与其…不如(完整)", "hsk_level": 5, "category": "connector",
     "description": "Comparison pattern meaning 'rather than X, it's better to Y'. Used to express a preference between two options.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "与其抱怨，不如行动。", "pinyin": "Yǔqí bàoyuàn, bùrú xíngdòng.", "en": "Rather than complaining, it's better to take action."},
         {"zh": "与其等他，不如我们先走。", "pinyin": "Yǔqí děng tā, bùrú wǒmen xiān zǒu.", "en": "Rather than waiting for him, let's go first."},
         {"zh": "与其花钱买，不如自己做。", "pinyin": "Yǔqí huā qián mǎi, bùrú zìjǐ zuò.", "en": "Rather than spending money to buy it, it's better to make it yourself."},
     ]},
    {"name": "不论/无论...都 regardless of (HSK5 full)", "name_zh": "不论/无论…都(完整)", "hsk_level": 5, "category": "connector",
     "description": "Universal conditional meaning 'regardless of / no matter'. 不论 and 无论 are interchangeable; both are followed by 都 or 也.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "不论结果如何，我都不后悔。", "pinyin": "Búlùn jiéguǒ rúhé, wǒ dōu bú hòuhuǐ.", "en": "Regardless of the result, I have no regrets."},
         {"zh": "无论遇到什么困难，都不要放弃。", "pinyin": "Wúlùn yùdào shénme kùnnan, dōu búyào fàngqì.", "en": "No matter what difficulties you encounter, don't give up."},
         {"zh": "不论天气好坏，他都坚持跑步。", "pinyin": "Búlùn tiānqì hǎo huài, tā dōu jiānchí pǎobù.", "en": "Regardless of the weather, he insists on running."},
     ]},
    {"name": "非...不可 must/have to (HSK5 intro)", "name_zh": "非…不可(HSK5)", "hsk_level": 5, "category": "structure",
     "description": "Double-negative pattern meaning 'must / have to / absolutely need to'. Literally 'not X won't do', expressing strong necessity.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "这件事非做不可。", "pinyin": "Zhè jiàn shì fēi zuò bùkě.", "en": "This must be done."},
         {"zh": "他非要自己去不可。", "pinyin": "Tā fēi yào zìjǐ qù bùkě.", "en": "He absolutely insists on going himself."},
         {"zh": "这个问题非解决不可。", "pinyin": "Zhège wèntí fēi jiějué bùkě.", "en": "This problem absolutely must be resolved."},
     ]},
    {"name": "何必 why bother (HSK5 full)", "name_zh": "何必(完整)", "hsk_level": 5, "category": "particle",
     "description": "Rhetorical adverb meaning 'why bother / why must you / there's no need to'. Advises against unnecessary effort or worry.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "何必那么着急呢？", "pinyin": "Hébì nàme zháojí ne?", "en": "Why be in such a hurry?"},
         {"zh": "何必跟他计较？", "pinyin": "Hébì gēn tā jìjiào?", "en": "Why bother arguing with him?"},
         {"zh": "何必花那么多钱？", "pinyin": "Hébì huā nàme duō qián?", "en": "Why spend so much money?"},
     ]},
    {"name": "何况 let alone (reinforced, HSK5)", "name_zh": "何况(加强)", "hsk_level": 5, "category": "connector",
     "description": "Connector meaning 'let alone / much less / not to mention'. Introduces a stronger case after establishing a weaker one.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "大人都做不到，何况小孩子呢？", "pinyin": "Dàrén dōu zuòbudào, hékuàng xiǎo háizi ne?", "en": "Even adults can't do it, let alone children."},
         {"zh": "他连自己都照顾不好，何况别人？", "pinyin": "Tā lián zìjǐ dōu zhàogù bù hǎo, hékuàng biérén?", "en": "He can't even take care of himself, let alone others."},
         {"zh": "这么简单的题你都不会，何况难的？", "pinyin": "Zhème jiǎndān de tí nǐ dōu bú huì, hékuàng nán de?", "en": "You can't even do such a simple problem, let alone a hard one."},
     ]},
    {"name": "反正 anyway/in any case (HSK5 full)", "name_zh": "反正(完整)", "hsk_level": 5, "category": "particle",
     "description": "Adverb meaning 'anyway / in any case / regardless'. Indicates the conclusion holds no matter what the circumstances are.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "反正我已经决定了。", "pinyin": "Fǎnzhèng wǒ yǐjīng juédìng le.", "en": "Anyway, I've already decided."},
         {"zh": "反正时间还早，我们慢慢来。", "pinyin": "Fǎnzhèng shíjiān hái zǎo, wǒmen mànman lái.", "en": "In any case it's still early, let's take our time."},
         {"zh": "去不去都行，反正我无所谓。", "pinyin": "Qù bu qù dōu xíng, fǎnzhèng wǒ wúsuǒwèi.", "en": "Going or not is fine, I don't mind either way."},
     ]},
    {"name": "原来 it turns out/originally (HSK5 full)", "name_zh": "原来(完整)", "hsk_level": 5, "category": "particle",
     "description": "Adverb with dual meaning: (1) 'originally / formerly' referring to a past state, or (2) 'it turns out / so that's why' expressing sudden realization.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "原来是你啊！我没认出来。", "pinyin": "Yuánlái shì nǐ a! Wǒ méi rènchūlái.", "en": "Oh it's you! I didn't recognize you."},
         {"zh": "原来他早就知道了。", "pinyin": "Yuánlái tā zǎo jiù zhīdào le.", "en": "It turns out he already knew."},
         {"zh": "这里原来是一片农田。", "pinyin": "Zhèlǐ yuánlái shì yí piàn nóngtián.", "en": "This used to be farmland."},
     ]},
    {"name": "恐怕 I'm afraid/probably (HSK5 full)", "name_zh": "恐怕(HSK5)", "hsk_level": 5, "category": "particle",
     "description": "Adverb meaning 'I'm afraid / probably / I suspect'. Softens an unwelcome guess or prediction.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "恐怕这次来不及了。", "pinyin": "Kǒngpà zhè cì láibují le.", "en": "I'm afraid there's not enough time this time."},
         {"zh": "恐怕他不会同意的。", "pinyin": "Kǒngpà tā bú huì tóngyì de.", "en": "I'm afraid he won't agree."},
         {"zh": "明天恐怕要下雨。", "pinyin": "Míngtiān kǒngpà yào xià yǔ.", "en": "I'm afraid it's going to rain tomorrow."},
     ]},
    {"name": "未必 not necessarily (formal, HSK5)", "name_zh": "未必(HSK5)", "hsk_level": 5, "category": "particle",
     "description": "Adverb meaning 'not necessarily / may not'. Formal way to express doubt about a claim, more measured than 不一定.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "有钱未必幸福。", "pinyin": "Yǒu qián wèibì xìngfú.", "en": "Having money doesn't necessarily mean happiness."},
         {"zh": "他说的未必是真的。", "pinyin": "Tā shuō de wèibì shì zhēn de.", "en": "What he said may not be true."},
         {"zh": "这个方法未必有效。", "pinyin": "Zhège fāngfǎ wèibì yǒuxiào.", "en": "This method may not necessarily be effective."},
     ]},
    {"name": "势必 certainly/bound to (HSK5 intro)", "name_zh": "势必(HSK5)", "hsk_level": 5, "category": "particle",
     "description": "Adverb meaning 'certainly / bound to / inevitably'. Predicts a definite outcome based on the current situation.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "不改革势必落后。", "pinyin": "Bù gǎigé shìbì luòhòu.", "en": "Without reform, falling behind is inevitable."},
         {"zh": "这样做势必引起争议。", "pinyin": "Zhèyàng zuò shìbì yǐnqǐ zhēngyì.", "en": "Doing this is bound to cause controversy."},
         {"zh": "人口增长势必带来更多问题。", "pinyin": "Rénkǒu zēngzhǎng shìbì dàilái gèng duō wèntí.", "en": "Population growth will inevitably bring more problems."},
     ]},
    {"name": "仿佛 as if/seemingly", "name_zh": "仿佛", "hsk_level": 5, "category": "particle",
     "description": "Adverb meaning 'as if / as though / seemingly'. More literary than 好像, used for vivid description.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "她仿佛看到了自己的未来。", "pinyin": "Tā fǎngfú kàndào le zìjǐ de wèilái.", "en": "She seemed to see her own future."},
         {"zh": "一切仿佛都没有变。", "pinyin": "Yíqiè fǎngfú dōu méiyǒu biàn.", "en": "Everything seemed as though nothing had changed."},
         {"zh": "他的笑容仿佛阳光一样温暖。", "pinyin": "Tā de xiàoróng fǎngfú yángguāng yíyàng wēnnuǎn.", "en": "His smile was as warm as sunshine."},
     ]},
    {"name": "好比 just like/comparable to", "name_zh": "好比", "hsk_level": 5, "category": "comparison",
     "description": "Verb meaning 'just like / comparable to / can be likened to'. Used to draw analogies or comparisons.",
     "difficulty": 0.5,
     "examples": [
         {"zh": "学习好比逆水行舟。", "pinyin": "Xuéxí hǎobǐ nì shuǐ xíng zhōu.", "en": "Learning is like sailing against the current."},
         {"zh": "人生好比一场旅行。", "pinyin": "Rénshēng hǎobǐ yì chǎng lǚxíng.", "en": "Life is like a journey."},
         {"zh": "他们的关系好比鱼和水。", "pinyin": "Tāmen de guānxi hǎobǐ yú hé shuǐ.", "en": "Their relationship is like fish and water."},
     ]},
    {"name": "一旦 once/as soon as (HSK5 conditional)", "name_zh": "一旦(HSK5)", "hsk_level": 5, "category": "connector",
     "description": "Conjunction meaning 'once / as soon as / in the event that'. Introduces a condition with significant consequences.",
     "difficulty": 0.55,
     "examples": [
         {"zh": "一旦发现问题，要马上报告。", "pinyin": "Yídàn fāxiàn wèntí, yào mǎshàng bàogào.", "en": "Once a problem is found, report it immediately."},
         {"zh": "一旦失去信任，很难恢复。", "pinyin": "Yídàn shīqù xìnrèn, hěn nán huīfù.", "en": "Once trust is lost, it's hard to recover."},
         {"zh": "一旦做出决定，就不要后悔。", "pinyin": "Yídàn zuòchū juédìng, jiù búyào hòuhuǐ.", "en": "Once you make a decision, don't regret it."},
     ]},
    {"name": "总之 in short/in a word (HSK5 usage)", "name_zh": "总之(HSK5)", "hsk_level": 5, "category": "connector",
     "description": "Connector meaning 'in short / in a word / in summary'. Used to wrap up a discussion with a concluding statement.",
     "difficulty": 0.45,
     "examples": [
         {"zh": "总之，我们要更加努力。", "pinyin": "Zǒngzhī, wǒmen yào gèngjiā nǔlì.", "en": "In short, we need to work harder."},
         {"zh": "总之，这件事不能再拖了。", "pinyin": "Zǒngzhī, zhè jiàn shì bù néng zài tuō le.", "en": "In a word, this matter can't be delayed any further."},
         {"zh": "总之一句话，健康最重要。", "pinyin": "Zǒngzhī yí jù huà, jiànkāng zuì zhòngyào.", "en": "To sum it up in one sentence: health is most important."},
     ]},
    {"name": "归根结底 in the final analysis (HSK5 usage)", "name_zh": "归根结底(HSK5)", "hsk_level": 5, "category": "connector",
     "description": "Idiom meaning 'in the final analysis / at the root / ultimately'. Used to state the fundamental cause or conclusion.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "归根结底，问题在于沟通不够。", "pinyin": "Guīgēn jiédǐ, wèntí zàiyú gōutōng búgòu.", "en": "In the final analysis, the problem lies in insufficient communication."},
         {"zh": "归根结底，还是要靠自己。", "pinyin": "Guīgēn jiédǐ, háishi yào kào zìjǐ.", "en": "Ultimately, you have to rely on yourself."},
         {"zh": "归根结底，教育是最重要的。", "pinyin": "Guīgēn jiédǐ, jiàoyù shì zuì zhòngyào de.", "en": "In the final analysis, education is the most important thing."},
     ]},
    {"name": "从而 thereby/thus (HSK5 usage)", "name_zh": "从而(HSK5)", "hsk_level": 5, "category": "connector",
     "description": "Connector meaning 'thereby / thus / and as a result'. Links an action to its resulting consequence in formal contexts.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "他加强了锻炼，从而提高了体质。", "pinyin": "Tā jiāqiáng le duànliàn, cóng'ér tígāo le tǐzhì.", "en": "He strengthened his exercise, thereby improving his fitness."},
         {"zh": "改进了方法，从而提高了效率。", "pinyin": "Gǎijìn le fāngfǎ, cóng'ér tígāo le xiàolǜ.", "en": "By improving the method, efficiency was thus raised."},
         {"zh": "降低了成本，从而增加了利润。", "pinyin": "Jiàngdī le chéngběn, cóng'ér zēngjiā le lìrùn.", "en": "Costs were reduced, thereby increasing profits."},
     ]},
    {"name": "进而 furthermore/going further (HSK5 usage)", "name_zh": "进而(HSK5)", "hsk_level": 5, "category": "connector",
     "description": "Connector meaning 'furthermore / going a step further / and then'. Introduces a progression or escalation.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "先了解情况，进而提出解决方案。", "pinyin": "Xiān liǎojiě qíngkuàng, jìn'ér tíchū jiějué fāng'àn.", "en": "First understand the situation, then go further to propose solutions."},
         {"zh": "他先学会了拼音，进而开始学汉字。", "pinyin": "Tā xiān xuéhuì le pīnyīn, jìn'ér kāishǐ xué hànzì.", "en": "He first learned pinyin, and then progressed to learning characters."},
         {"zh": "环境恶化影响了生态，进而威胁到人类健康。", "pinyin": "Huánjìng èhuà yǐngxiǎng le shēngtài, jìn'ér wēixié dào rénlèi jiànkāng.", "en": "Environmental deterioration affects ecology, and further threatens human health."},
     ]},
    {"name": "何尝 when has it ever (rhetorical, HSK5)", "name_zh": "何尝(HSK5)", "hsk_level": 5, "category": "structure",
     "description": "Rhetorical adverb meaning 'when has it ever / it's not that...hasn't'. Used rhetorically to imply the opposite of the surface meaning.",
     "difficulty": 0.7,
     "examples": [
         {"zh": "我何尝不想去？只是没时间。", "pinyin": "Wǒ hécháng bù xiǎng qù? Zhǐshì méi shíjiān.", "en": "When have I not wanted to go? I just don't have time."},
         {"zh": "他何尝不知道这件事的重要性？", "pinyin": "Tā hécháng bù zhīdào zhè jiàn shì de zhòngyàoxìng?", "en": "When has he not known the importance of this?"},
         {"zh": "她何尝不努力？只是运气不好。", "pinyin": "Tā hécháng bù nǔlì? Zhǐshì yùnqi bù hǎo.", "en": "It's not that she hasn't tried hard; she's just been unlucky."},
     ]},
    {"name": "岂不 wouldn't it be (rhetorical)", "name_zh": "岂不", "hsk_level": 5, "category": "structure",
     "description": "Rhetorical adverb meaning 'wouldn't it be / isn't that'. Used in rhetorical questions to make a point seem obvious.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "这样做岂不更好？", "pinyin": "Zhèyàng zuò qǐ bú gèng hǎo?", "en": "Wouldn't it be even better to do it this way?"},
         {"zh": "放弃了岂不可惜？", "pinyin": "Fàngqì le qǐ bú kěxī?", "en": "Wouldn't it be a pity to give up?"},
         {"zh": "不学习岂不是浪费时间？", "pinyin": "Bù xuéxí qǐ bú shì làngfèi shíjiān?", "en": "Not studying — wouldn't that be a waste of time?"},
     ]},
    {"name": "总而言之 in summary (HSK5 usage)", "name_zh": "总而言之(HSK5)", "hsk_level": 5, "category": "connector",
     "description": "Formal idiom meaning 'in summary / to sum up / in a word'. More formal than 总之, used to conclude a discussion.",
     "difficulty": 0.6,
     "examples": [
         {"zh": "总而言之，我们需要更多时间。", "pinyin": "Zǒng'éryánzhī, wǒmen xūyào gèng duō shíjiān.", "en": "In summary, we need more time."},
         {"zh": "总而言之，安全第一。", "pinyin": "Zǒng'éryánzhī, ānquán dì yī.", "en": "To sum up, safety comes first."},
         {"zh": "总而言之，大家都做得很好。", "pinyin": "Zǒng'éryánzhī, dàjiā dōu zuò de hěn hǎo.", "en": "All in all, everyone did very well."},
     ]},
    {"name": "当务之急 the most urgent matter", "name_zh": "当务之急", "hsk_level": 5, "category": "structure",
     "description": "Idiom meaning 'the most urgent matter / top priority'. Used to identify what needs attention most urgently.",
     "difficulty": 0.65,
     "examples": [
         {"zh": "当务之急是解决资金问题。", "pinyin": "Dāngwù zhī jí shì jiějué zījīn wèntí.", "en": "The most urgent matter is to solve the funding problem."},
         {"zh": "当务之急是找到失踪的孩子。", "pinyin": "Dāngwù zhī jí shì zhǎodào shīzōng de háizi.", "en": "The top priority is to find the missing child."},
         {"zh": "现在的当务之急是控制疫情。", "pinyin": "Xiànzài de dāngwù zhī jí shì kòngzhì yìqíng.", "en": "The most urgent task now is to control the epidemic."},
     ]},
]
